CMakeLists.txt
```
Richard Jenkins:    I'm poking #5456
Michał Janiszewski: @rwjuk he always breaks stuff
Krutonium:          You can now enable paths up to the limit of the FS in
Windows now.
Michał Janiszewski: don't share your toys with him
Krutonium:          I kinda want to share my toys with him
Michał Janiszewski: he will put spaces and accented letters all over them
Richard Jenkins:    Haha :P
```
=> Fix building in paths with spaces or apostrophes

data/language/en-US.txt
Names are directly taken from OpenRCT2.
=> Convert en-US to UTF-8 and replace special characters (railway, road,  flag)

data/language/pt-BR.txt
All strings translated. Some testing will be required to make sure that gendered nouns and verb conjugations are correct.
=> pt-BR: Create initial Portuguese BR translation

src/openloco/things/vehicle.cpp
Issue caused by mistake in implementing. v was incorrectly being set to the wrong next car
=> Fix crash in vehicle breakdown code.

data/language/ko-KR.txt
But I need to check it if there exists typos or make them to more fluent
오탈자나 문맥을 부드럽게 수정할 필요가 있을 수 있습니다.
=> ko-KR: Fully translated

src/openloco/objects/objectmgr.cpp, src/openloco/objects/objectmgr.h, src/openloco/objects/vehicle_object.h, src/openloco/openloco.vcxproj, src/openloco/things/thing.cpp, src/openloco/things/thing.h, src/openloco/things/vehicle.cpp, src/openloco/things/vehicle.h, src/openloco/viewportmgr.cpp, src/openloco/viewportmgr.h, src/openloco/window.h
Label all object array addresses
=> Start implementing vehicle update.

src/openloco/gui.cpp, src/openloco/gui.h, src/openloco/interop/hooks.cpp, src/openloco/objects/interface_skin_object.h, src/openloco/objects/objectmgr.cpp, src/openloco/objects/objectmgr.h, src/openloco/openloco.vcxproj, src/openloco/viewportmgr.cpp, src/openloco/viewportmgr.h, src/openloco/window.h, src/openloco/windowmgr.cpp, src/openloco/windowmgr.h, src/openloco/windows/promptbrowsewnd.cpp, src/openloco/windows/promptokcancelwnd.cpp, src/openloco/windows/townwnd.cpp
Should be a match, but my code likely isn't what's expected.
=> Decompile gui initialisation

src/openloco/objects/vehicle_object.h, src/openloco/things/vehicle.cpp
Fix vehicle_object struct. Visual effects will now work
=> Fix vehicle_object struct

src/openloco/industry.cpp, src/openloco/map/tile.cpp, src/openloco/map/tile.h, src/openloco/objects/building_object.h, src/openloco/objects/industry_object.h, src/openloco/objects/objectmgr.cpp, src/openloco/objects/objectmgr.h, src/openloco/objects/road_station_object.h, src/openloco/openloco.vcxproj
=> Add more identified fields and improve tile engine

src/openloco/graphics/gfx.cpp, src/openloco/graphics/gfx.h, src/openloco/interop/hooks.cpp, src/openloco/objects/interface_skin_object.h, src/openloco/openloco.vcxproj, src/openloco/window.cpp, src/openloco/window.h, src/openloco/windowmgr.h, src/openloco/windows/stationwnd.cpp, src/openloco/windows/tooltip.cpp
Extracted Tooltip for #92. Includes flags from #94
=> Decompile tooltip

src/openloco/audio/audio.cpp, src/openloco/audio/audio.h, src/openloco/interop/hooks.cpp, src/openloco/map/tile.h, src/openloco/map/tilemgr.cpp, src/openloco/map/tilemgr.h, src/openloco/objects/objectmgr.cpp, src/openloco/objects/objectmgr.h, src/openloco/objects/steam_object.h, src/openloco/objects/vehicle_object.h, src/openloco/openloco.vcxproj, src/openloco/things/misc.cpp, src/openloco/things/misc.h, src/openloco/things/thing.cpp, src/openloco/things/thing.h, src/openloco/things/thingmgr.cpp, src/openloco/things/thingmgr.h, src/openloco/things/vehicle.cpp, src/openloco/things/vehicle.h
=> Continue Vehicle Update

src/openloco/interop/hooks.cpp, src/openloco/window.cpp, src/openloco/window.h, src/openloco/windowmgr.cpp, src/openloco/windowmgr.h, src/openloco/windows/title_version.cpp
For some reason this crashes when drawing a loaded park. Needs investigation into why this happens.
=> Decompile drawing

.github/ISSUE_TEMPLATE.md
This PR adds a basic template for new issues.
=> Add a basic issue template

src/openloco/config.h, src/openloco/interop/hooks.cpp, src/openloco/localisation/argswrapper.hpp, src/openloco/localisation/string_ids.h, src/openloco/localisation/stringmgr.cpp, src/openloco/localisation/stringmgr.h, src/openloco/objects/currency_object.h, src/openloco/objects/objectmgr.cpp, src/openloco/objects/objectmgr.h, src/openloco/windowmgr.h, src/openloco/windows/tooltip.cpp
This PR is to keep track of my progress implementing the string formatting functions. It's a bit of a mess still, but we'll clean up as we go along. Feedback welcome.
=> Implement string formatting

src/openloco/companymgr.cpp
I called it produce_companies as the function checks each 192 ticks if its able to create new ones given by the scenario settings and already active companies.
=> Implement sub_4306D1

src/openloco/gui.cpp, src/openloco/interop/hooks.cpp, src/openloco/openloco.vcxproj, src/openloco/ui/scrollview.cpp, src/openloco/ui/scrollview.h, src/openloco/window.cpp, src/openloco/window.h, src/openloco/windowmgr.cpp, src/openloco/windowmgr.h, src/openloco/windows/map.cpp, src/openloco/windows/promptbrowsewnd.cpp, src/openloco/windows/promptokcancelwnd.cpp, src/openloco/windows/tooltip.cpp
=> Decompile functions accessing window list

src/openloco/interop/hooks.cpp, src/openloco/map/tile.cpp, src/openloco/map/tile.h, src/openloco/window.cpp, src/openloco/window.h
I want to put `viewport_target_sprite`, `saved_view_y`, and `saved_view_x` into a sub struct, so we can just loop through viewports.
=> Start implementing viewports_update_position

CMakeLists.txt, src/openloco/graphics/image_ids.h, src/openloco/utility/collection.hpp, src/openloco/utility/string.hpp, src/openloco/window.h
Check if headers include everything they use
=> Headers check

data/language/pl-PL.txt
Completed pl-PL translation 100%
=> Add files via upload (Complete Polish Translation)

src/openloco/audio/audio.cpp, src/openloco/config.h, src/openloco/openloco.cpp, src/openloco/windows/options.cpp
=> Implement playing of background music

src/openloco/graphics/gfx.cpp, src/openloco/graphics/gfx.h, src/openloco/graphics/image_ids.h, src/openloco/gui.cpp, src/openloco/localisation/string_ids.h, src/openloco/openloco.cpp, src/openloco/platform/platform.h, src/openloco/platform/platform.posix.cpp, src/openloco/platform/platform.windows.cpp, src/openloco/ui/WindowManager.cpp, src/openloco/ui/WindowManager.h, src/openloco/window.cpp, src/openloco/window.h, src/openloco/windows/constructionwnd.cpp, src/openloco/windows/promptbrowsewnd.cpp
Implementing more of the window code as it currently crashes on Windows during the file enumeration. I couldn't work out why so just implemented it instead.
=> Implement more of window browse

.travis.yml
Analogous to https://github.com/OpenRCT2/OpenRCT2/pull/8621. I've left out "release" from the names, as we have no debug targets at the moment.
=> Name entries in Travis job matrix

data/language/en-GB.yml, src/openloco/config.h, src/openloco/input/mouse_input.cpp, src/openloco/localisation/string_ids.h, src/openloco/ui.cpp, src/openloco/ui.h, src/openloco/windows/options.cpp
This PR adds basic window scaling to OpenLoco.
To do:
=> Implement window scaling

src/openloco/game_commands.h, src/openloco/input.cpp, src/openloco/input.h, src/openloco/input/Shortcut.h, src/openloco/input/ShortcutManager.cpp, src/openloco/input/ShortcutManager.h, src/openloco/input/keyboard.cpp, src/openloco/input/mouse_input.cpp, src/openloco/interop/hooks.cpp, src/openloco/things/vehicle.h, src/openloco/ui.cpp, src/openloco/ui/WindowManager.cpp, src/openloco/ui/WindowManager.h, src/openloco/ui/WindowType.h, src/openloco/win32.h, src/openloco/windows/promptbrowsewnd.cpp, src/openloco/windows/promptokcancelwnd.cpp, src/openloco/windows/textinputwnd.cpp, src/openloco/windows/vehicle.cpp
Based on https://github.com/marijnvdwerf/wissel/pull/5 and https://github.com/marijnvdwerf/wissel/pull/14.
Fixes https://github.com/OpenRCT2/OpenLoco/issues/145.
=> Implement shortcut handling

CONTRIBUTORS.MD, appveyor.yml
This file credits developers, translators, graphic designers, and other contributors for their hard work.
=> Add contributors file

LICENSE
Update the license file to reflect that this is no longer a solo project. :-)
=> Update license to reflect project state

CHANGELOG.md, appveyor.yml, src/openloco/version.cpp
In preparation for the upcoming release.
=> Increase version number to 19.03

CHANGELOG.md, src/openloco/windows/promptbrowsewnd.cpp
=> Improve SV5 preview display

src/openloco/audio/audio.cpp, src/openloco/audio/vehicle_channel.cpp, src/openloco/things/misc.cpp, src/openloco/things/misc.h, src/openloco/things/thing.cpp, src/openloco/things/thing.h, src/openloco/things/thingmgr.cpp, src/openloco/things/vehicle.cpp, src/openloco/things/vehicle.h, src/openloco/viewportmgr.cpp, src/openloco/viewportmgr.h, src/openloco/window.cpp
=> Rework thing organisation

src/openloco/audio/audio.cpp, src/openloco/audio/audio.h, src/openloco/localisation/string_ids.h, src/openloco/types.hpp, src/openloco/ui/WindowManager.cpp, src/openloco/ui/WindowManager.h, src/openloco/window.cpp, src/openloco/window.h, src/openloco/windows/build_vehicle.cpp, src/openloco/windows/music_selection.cpp, src/openloco/windows/options.cpp, src/openloco/windows/promptbrowsewnd.cpp, src/openloco/windows/toolbar_top.cpp
This implements the music selection window, which is a relatively small one to implement.
NB: the first commit is a collection of useful bits from #271.
=> Implement the music selection window

src/openloco/objects/airport_object.h, src/openloco/objects/building_object.h, src/openloco/objects/cargo_object.h, src/openloco/objects/industry_object.h, src/openloco/objects/objectmgr.cpp, src/openloco/objects/objectmgr.h, src/openloco/objects/road_object.h, src/openloco/objects/road_station_object.h, src/openloco/objects/steam_object.h, src/openloco/objects/vehicle_object.h
Part of the splitting up of the vehicle update branch.
=> Add airport object file

src/openloco/input/keyboard.cpp, src/openloco/localisation/string_ids.h, src/openloco/objects/vehicle_object.h, src/openloco/things/vehicle.cpp, src/openloco/things/vehicle.h, src/openloco/windows/toolbar_top.cpp
Information from the vehicle update branch. Consider further rework on names
=> Update vehicle object struct

CONTRIBUTORS.MD, data/language/sk-SK.yml
This is a first version of Slovak transation. Later during the gameplay will make minor fixes.
=> Added initial version of Slovak translation

src/openloco/company.cpp, src/openloco/company.h, src/openloco/objects/competitor_object.h, src/openloco/objects/objectmgr.cpp, src/openloco/objects/objectmgr.h, src/openloco/openloco.cpp
Splitting off a few commits from #289; already used in #327 and some other local work.
=> Introduce competitor object

src/openloco/company.cpp, src/openloco/company.h, src/openloco/graphics/gfx.h, src/openloco/interop/hooks.cpp, src/openloco/localisation/string_ids.h, src/openloco/objects/cargo_object.h, src/openloco/objects/interface_skin_object.h, src/openloco/objects/objectmgr.cpp, src/openloco/objects/objectmgr.h, src/openloco/station.cpp, src/openloco/station.h, src/openloco/ui/WindowManager.h, src/openloco/ui/dropdown.cpp, src/openloco/ui/dropdown.h, src/openloco/widget.cpp, src/openloco/widget.h, src/openloco/window.cpp, src/openloco/window.h, src/openloco/windows/build_vehicle.cpp, src/openloco/windows/options.cpp, src/openloco/windows/station_list.cpp, src/openloco/windows/stationwnd.cpp, src/openloco/windows/title_menu.cpp
This PR is working towards implementing the station list window.
=> Implement the station list

src/openloco/town.h, src/openloco/townmgr.cpp, src/openloco/utility/numeric.cpp, src/openloco/utility/numeric.hpp
This still needs some cleanup, but I wanted to get some feedback wrt. variable naming / general feedback, since I am not too familiar with the code base yet.
=> Implement town::update_monthly

README.md
Removes reference to OpenRCT2's non-dev channel.
=> Change phrasing around the Gitter chat

src/openloco/interop/interop.cpp, src/openloco/interop/interop.hpp, src/openloco/windows/ScenarioOptions.cpp
See each commit's message for more details.
Ping @PoLoMoTo
=> Fixes for GCC9

src/openloco/audio/audio.cpp, src/openloco/date.cpp, src/openloco/date.h, src/openloco/game_commands.h, src/openloco/graphics/gfx.cpp, src/openloco/graphics/gfx.h, src/openloco/graphics/image_ids.h, src/openloco/input.h, src/openloco/input/keyboard.cpp, src/openloco/input/mouse_input.cpp, src/openloco/interop/hooks.cpp, src/openloco/localisation/string_ids.h, src/openloco/map/tile.h, src/openloco/objects/interface_skin_object.h, src/openloco/town.h, src/openloco/townmgr.cpp, src/openloco/ui/WindowManager.cpp, src/openloco/ui/WindowManager.h, src/openloco/ui/WindowType.h, src/openloco/viewport.cpp, src/openloco/viewport.hpp, src/openloco/widget.cpp, src/openloco/widget.h, src/openloco/window.cpp, src/openloco/window.h, src/openloco/windows/TimePanel.cpp, src/openloco/windows/textinputwnd.cpp, src/openloco/windows/townwnd.cpp
Not much to see here yet, just getting things ready.
=> Town window implementation

CHANGELOG.md, data/language/en-GB.yml, data/language/nl-NL.yml, data/language/sk-SK.yml, src/openloco/window.cpp
The underlying bug was addressed by @marijnvdwerf in #371. Big cheers!
=> Fix #226: Zooming to cursor is buggy on bigger maps

CMakeLists.txt, src/openloco/platform/platform.posix.cpp
* Fixed failed build with cmake for FreeBSD
* FIxed headers for BSD OS
=> Support bsd operating systems

src/openloco/interop/hooks.cpp
=> Fix #383: Crash in construction window

data/language/ja-JP.yml, data/language/ko-KR.yml
p.s. Which steps is remained to display non-latin texts?
=> Fix native language names of Korean and Japanese

CMakeLists.txt
And also for such that did not 'git pull --tags'.
=> Fix tag detection for shallow clones

.github/workflows/ci.yml, .travis.yml, CMakeLists.txt, dockerfiles/fedora-mingw32/Dockerfile, scripts/check-code-formatting.sh, src/openloco/audio/audio.cpp, src/openloco/audio/channel.cpp, src/openloco/audio/channel.h, src/openloco/audio/music_channel.cpp, src/openloco/audio/music_channel.h, src/openloco/config.cpp, src/openloco/core/FileSystem.hpp, src/openloco/environment.cpp, src/openloco/environment.h, src/openloco/graphics/gfx.cpp, src/openloco/interop/hooks.cpp, src/openloco/localisation/languages.cpp, src/openloco/platform/platform.h, src/openloco/thirdparty/filesystem.hpp, src/openloco/windows/promptbrowsewnd.cpp
Implements @chfast's suggestion from #381, ported from https://github.com/OpenRCT2/OpenRCT2/pull/10261
Presented as an alternative to #401.
=> Alternative implementation for std::filesystem

src/openloco/graphics/gfx.cpp, src/openloco/graphics/gfx.h, src/openloco/gui.cpp, src/openloco/map/SurfaceTile.cpp, src/openloco/map/tile.h, src/openloco/objects/cargo_object.h, src/openloco/things/thing.cpp, src/openloco/town.h, src/openloco/types.hpp, src/openloco/viewportmgr.cpp, src/openloco/viewportmgr.h, src/openloco/window.h, src/openloco/windows/townwnd.cpp
This PR extracts common elements from #359 in the hope that they may be useful to other PRs in the mean time.
=> Extract common elements from #359

src/openloco/town.cpp, src/openloco/town.h, src/openloco/widget.cpp, src/openloco/window.h, src/openloco/windows/townwnd.cpp
=> Refactor townwnd draw function

src/openloco/company.h, src/openloco/graphics/image_ids.h, src/openloco/gui.cpp, src/openloco/input/ShortcutManager.cpp, src/openloco/localisation/FormatArguments.hpp, src/openloco/localisation/string_ids.h, src/openloco/ui/WindowManager.h, src/openloco/ui/dropdown.cpp, src/openloco/ui/dropdown.h, src/openloco/window.h, src/openloco/windows/CompanyList.cpp, src/openloco/windows/CompanyWindow.cpp, src/openloco/windows/PlayerInfoPanel.cpp
Rescued from a forgotten branch.
=> Implement the player info panel

CONTRIBUTORS.MD, src/openloco/input.h, src/openloco/input/mouse_input.cpp, src/openloco/windows/vehicle.cpp
bool tool_set(ui::window* w, int16_t widgetIndex, uint8_t tool);
=> Implement 0x004CE367 tool_set function

src/openloco/input.h, src/openloco/input/mouse_input.cpp, src/openloco/map/tilemgr.cpp, src/openloco/map/tilemgr.h, src/openloco/ui/WindowManager.cpp, src/openloco/window.cpp, src/openloco/window.h
=> Implement 0x004CE3D6 cancel_tool function

src/openloco/gui.cpp, src/openloco/localisation/string_ids.h, src/openloco/ui/WindowManager.cpp, src/openloco/ui/WindowManager.h, src/openloco/windows/ToolbarBottomEditor.cpp, src/openloco/windows/title_menu.cpp, src/openloco/windows/toolbar_top.cpp, src/openloco/windows/toolbar_top_alt.cpp, src/openloco/windows/toolbar_top_common.cpp, src/openloco/windows/toolbar_top_common.h
Rescued from a forgotten branch.
=> Implement the editor toolbar

CHANGELOG.md, src/openloco/windows/townwnd.cpp
Also fixed bug causing population graph to show 0 population for Current Date.
=> Refactor townwnd  draw for tabs 2 and 3

CHANGELOG.md
Forgot to update the changelog about the extra error information that is broken in vanilla.
=> Update changelog for #428

src/openloco/input.h, src/openloco/input/mouse_input.cpp, src/openloco/map/tilemgr.cpp, src/openloco/map/tilemgr.h, src/openloco/ui/WindowManager.cpp
void map_invalidate_selection_rect();
=> Implement 0x004610F2 map_invalidate_selection_rect

CHANGELOG.md, src/openloco/company.cpp, src/openloco/company.h, src/openloco/companymgr.cpp, src/openloco/companymgr.h, src/openloco/game_commands.h, src/openloco/graphics/gfx.cpp, src/openloco/graphics/gfx.h, src/openloco/graphics/image_ids.h, src/openloco/localisation/string_ids.h, src/openloco/management/Expenditures.h, src/openloco/objects/interface_skin_object.h, src/openloco/openloco.cpp, src/openloco/things/thing.h, src/openloco/types.hpp, src/openloco/ui/WindowManager.cpp, src/openloco/ui/WindowManager.h, src/openloco/ui/dropdown.cpp, src/openloco/ui/dropdown.h, src/openloco/window.cpp, src/openloco/window.h, src/openloco/windows/CompanyFaceSelection.cpp, src/openloco/windows/CompanyWindow.cpp, src/openloco/windows/PlayerInfoPanel.cpp, src/openloco/windows/TimePanel.cpp, src/openloco/windows/station_list.cpp, src/openloco/windows/townwnd.cpp
This is my next project. I'm hoping that implementing this window will reveal most of the layout of how the company struct is laid out.
status
details
colour_scheme
finances
cargo_delivered
challenge
=> Company window implementation

src/openloco/map/tilemgr.cpp, src/openloco/viewportmgr.cpp
implementation of:
void map_invalidate_map_selection_tiles();
from assembly code
=> map_invalidate_map_selection_tiles

src/openloco/graphics/colours.h, src/openloco/windows/stationwnd.cpp
Apparently first needed in #441.
=> Introduce colour flags for outline and inset

src/openloco/input/ShortcutManager.cpp, src/openloco/ui/WindowManager.h, src/openloco/windows/CompanyList.cpp, src/openloco/windows/EditKeyboardShortcut.cpp, src/openloco/windows/PlayerInfoPanel.cpp, src/openloco/windows/about.cpp, src/openloco/windows/about_music.cpp, src/openloco/windows/constructionwnd.cpp, src/openloco/windows/toolbar_top.cpp, src/openloco/windows/toolbar_top_common.cpp
Couple little window refactors trying to move the windows to a more common layout.
=> Window refactors

src/openloco/station.cpp, src/openloco/station.h
Cherry picking out a standalone change refactor from https://github.com/OpenLoco/OpenLoco/pull/90
=> Refactor station::update

src/openloco/core/Optional.hpp, src/openloco/game_commands.h, src/openloco/localisation/string_ids.h, src/openloco/objects/objectmgr.h, src/openloco/openloco.cpp, src/openloco/openloco.h, src/openloco/window.h, src/openloco/windows/CompanyFaceSelection.cpp, src/openloco/windows/promptbrowsewnd.cpp
=> Company faceselection

src/openloco/interop/hooks.cpp, src/openloco/objects/interface_skin_object.h, src/openloco/things/vehicle.cpp, src/openloco/things/vehicle.h, src/openloco/windows/build_vehicle.cpp
This is one of the things I tried to roll into the massive vehicle_update branch. Here it is done cleanly.
=> Move vehicle body update to vehicle body struct

src/openloco/input.h, src/openloco/input/mouse_input.cpp, src/openloco/ui/WindowManager.h, src/openloco/windows/tooltip.cpp
=> Implement 0x004C87B5

src/openloco/localisation/FormatArguments.hpp, src/openloco/localisation/argswrapper.hpp, src/openloco/localisation/stringmgr.cpp, src/openloco/localisation/stringmgr.h, src/openloco/windows/build_vehicle.cpp
Just a little refactor to bring it more inline with the other windows. I was using this to test clang-tidy.
Also noticed a little bug while refactoring with the cargo quantities.
=> Initial refactor of build_vehicle window

src/openloco/windows/options.cpp
The options window was the first of the bigger windows that we implemented. Time to modernise it a little.
=> Options window refactor

src/openloco/window.cpp, src/openloco/window.h
- implement viewport_set_underground_flag(bool underground, ui::window* w, ui::viewport* vp)
- also implement directly the class version of function:
void window::viewportSetUndergroundFlag(bool underground, ui::viewport* vp)
=> implement 0x004C641F

src/openloco/window.cpp
- renamed to viewport_coord_to_map_coord(int16_t x, int16_t y, int16_t z, int32_t rotation, int16_t* outX, int16_t* outY, int16_t* outZ)
=> implement sub_45FD41

src/openloco/ui/WindowManager.h, src/openloco/windows/industry_list.cpp
Remove unused function from WindowManager.h and fix incorrect value in industry_list.cpp
=> Minor fixes to WindowManager.h and industry_list.cpp

src/openloco/localisation/FormatArguments.hpp, src/openloco/windows/build_vehicle.cpp
~~Also updated vcxproj file to use explicit files as MS are depretiating using the preferred wild cards approach~~
=> Fix incorrect uses of push format arguments

src/openloco/game_commands.h, src/openloco/graphics/image_ids.h, src/openloco/interop/hooks.cpp, src/openloco/localisation/string_ids.h, src/openloco/objects/land_object.h, src/openloco/objects/objectmgr.cpp, src/openloco/objects/objectmgr.h, src/openloco/objects/tree_object.h, src/openloco/objects/wall_object.h, src/openloco/objects/water_object.h, src/openloco/openloco.vcxproj, src/openloco/ui/WindowManager.h, src/openloco/ui/dropdown.cpp, src/openloco/ui/dropdown.h, src/openloco/window.h, src/openloco/windows/terraform.cpp
Started work on the Terraform Window
=> Terraform Window

src/openloco/ui/WindowManager.cpp, src/openloco/ui/WindowManager.h, src/openloco/viewport.hpp, src/openloco/window.cpp, src/openloco/window.h
- the function is defined as:
map::map_pos sub_45FCE6(int16_t x, int16_t y, int16_t z)
=> implement 0x0045FCE6

src/openloco/drawing/SoftwareDrawingEngine.cpp, src/openloco/drawing/SoftwareDrawingEngine.h, src/openloco/graphics/gfx.cpp, src/openloco/ui/WindowManager.cpp
=> Implement gfx::set_dirty_blocks

src/openloco/graphics/gfx.cpp
void clear(drawpixelinfo_t& dpi, uint32_t fill);
=> implement gfx::clear

src/openloco/GameCommands.cpp, src/openloco/graphics/gfx.cpp, src/openloco/graphics/gfx.h, src/openloco/interop/hooks.cpp, src/openloco/openloco.vcxproj, src/openloco/ui/WindowManager.cpp, src/openloco/ui/WindowManager.h, src/openloco/windows/error.cpp, src/openloco/windows/tooltip.cpp
Error window for Generic errors and Competitor related errors
=> Error window

src/openloco/graphics/gfx.cpp, src/openloco/graphics/gfx.h, src/openloco/ui/WindowManager.cpp, src/openloco/windows/textinputwnd.cpp
uint16_t get_string_width(const char* buffer);
=> Implement get_string_width function

src/openloco/GameCommands.cpp, src/openloco/company.cpp, src/openloco/company.h, src/openloco/game_commands.h, src/openloco/localisation/string_ids.h, src/openloco/objects/vehicle_object.h, src/openloco/openloco.vcxproj, src/openloco/things/CreateVehicle.cpp, src/openloco/things/thingmgr.cpp, src/openloco/things/thingmgr.h, src/openloco/things/vehicle.cpp, src/openloco/things/vehicle.h, src/openloco/types.hpp, src/openloco/windows/build_vehicle.cpp, src/openloco/windows/toolbar_top.cpp, src/openloco/windows/vehicle.cpp
Okay I promise not to abandon this one for two years...
Continues on from the other vehicle PR.
=> Vehicle create

CHANGELOG.md, src/openloco/config.h, src/openloco/environment.h, src/openloco/input.h, src/openloco/input/keyboard.cpp, src/openloco/input/mouse_input.cpp, src/openloco/interop/hooks.cpp, src/openloco/localisation/string_ids.h, src/openloco/openloco.cpp, src/openloco/scenario.cpp, src/openloco/scenario.h, src/openloco/tutorial.cpp, src/openloco/tutorial.h, src/openloco/ui.cpp, src/openloco/ui.h, src/openloco/windows/title_menu.cpp, src/openloco/windows/tooltip.cpp
This is working to getting tutorials working in forced 1024x768 windowed mode.
For the time being, these tutorials can help new players familiarise themselves with the game. When the windows start changing drastically, we'll need another solution, however.
=> Implement tutorial routines

data/language/ko-KR.yml
Update Korean even though OpenLoco cannot display Korean yet
=> ko-KR: Update translation

src/openloco/audio/audio.cpp, src/openloco/audio/audio.h, src/openloco/audio/vehicle_channel.cpp, src/openloco/company.cpp, src/openloco/interop/hooks.cpp, src/openloco/things/CreateVehicle.cpp, src/openloco/things/thingmgr.cpp, src/openloco/things/thingmgr.h, src/openloco/things/vehicle.cpp, src/openloco/things/vehicle.h, src/openloco/windows/CompanyWindow.cpp, src/openloco/windows/toolbar_top.cpp
=> Vehicle refactor

src/openloco/config.h, src/openloco/graphics/colours.h, src/openloco/graphics/image_ids.h, src/openloco/localisation/string_ids.h, src/openloco/message.h, src/openloco/messagemgr.cpp, src/openloco/messagemgr.h, src/openloco/openloco.cpp, src/openloco/openloco.h, src/openloco/openloco.vcxproj, src/openloco/station.cpp, src/openloco/ui/WindowManager.cpp, src/openloco/ui/WindowManager.h, src/openloco/windows/MessageWindow.cpp, src/openloco/windows/News/Common.cpp, src/openloco/windows/News/Common.h, src/openloco/windows/News/News.cpp, src/openloco/windows/News/News.h, src/openloco/windows/News/Ticker.cpp, src/openloco/windows/NewsWindow.cpp, src/openloco/windows/build_vehicle.cpp
=> News Window

src/openloco/graphics/colours.h, src/openloco/input/mouse_input.cpp, src/openloco/localisation/string_ids.h, src/openloco/ui/dropdown.cpp, src/openloco/ui/dropdown.h, src/openloco/windows/LandscapeGeneration.cpp, src/openloco/windows/MessageWindow.cpp, src/openloco/windows/PlayerInfoPanel.cpp, src/openloco/windows/ScenarioOptions.cpp, src/openloco/windows/TimePanel.cpp, src/openloco/windows/construction/ConstructionTab.cpp, src/openloco/windows/construction/OverheadTab.cpp, src/openloco/windows/construction/SignalTab.cpp, src/openloco/windows/construction/StationTab.cpp, src/openloco/windows/options.cpp, src/openloco/windows/terraform.cpp, src/openloco/windows/title_menu.cpp, src/openloco/windows/toolbar_top.cpp, src/openloco/windows/toolbar_top_alt.cpp, src/openloco/windows/toolbar_top_common.cpp, src/openloco/windows/town_list.cpp
Next window on the agenda. 
Also fixed the Message Window dropdowns not displaying the selected item.
=> Dropdown Window

src/openloco/input.h, src/openloco/input/mouse_input.cpp, src/openloco/window.h
- implement handling horizontal scrollbar button left press
=> Implement 0x4c894f

src/openloco/input.h, src/openloco/input/mouse_input.cpp, src/openloco/map/tile.h, src/openloco/objects/industry_object.h, src/openloco/station.cpp, src/openloco/things/vehicle.cpp, src/openloco/things/vehicle.h, src/openloco/ui.h, src/openloco/ui/WindowManager.h, src/openloco/ui/viewport_interaction.cpp, src/openloco/window.cpp, src/openloco/window.h, src/openloco/windows/construction/Common.cpp, src/openloco/windows/terraform.cpp, src/openloco/windows/vehicle.cpp
=> Implement viewport_left mouse input

src/openloco/input/mouse_input.cpp, src/openloco/window.h
- implement handling horizontal scrollbar button right press
=> Implement 0x4c89ae

src/openloco/input/mouse_input.cpp, src/openloco/window.h
- add assembly addresses to other cases in the switch branch
- use SCROLLBAR_BUTTON_CLICK_STEP constant instead of number 3
=> implement 0x4c8b85

src/openloco/input/mouse_input.cpp
- Implement hscrollbar_track_left handling
=> Implement 0x4c8a36

src/openloco/input/mouse_input.cpp
- Implement vscrollbar_track_top handling
=> Implement 0x4c8c0d

src/openloco/input/mouse_input.cpp
- Implement hscrollbar_track_right handling
=> Implement 0x4c8aa6

src/openloco/input.cpp, src/openloco/input.h, src/openloco/input/mouse_input.cpp, src/openloco/ui.cpp, src/openloco/ui/WindowManager.cpp, src/openloco/ui/scrollview.h, src/openloco/widget.cpp, src/openloco/window.cpp, src/openloco/window.h
PR #348 has gotten stale, and in the mean time other PRs have implemented some of the same functions. To make it easier to rebase or reconstruct #348, I intend to split it up.
=> Extracted bits from #348

src/openloco/input/mouse_input.cpp
I suggest to merge with regular merge (not squash) this one. So we can have a full implementation in the history if somebody will look up for the further calls.
=> Vscrollbar track bottom

src/openloco/ui/scrollview.cpp
static void verticalFollow(ui::window* const w, ui::widget_t* const widget, const widget_index widgetIndex, const size_t scrollIndex, const int16_t deltaY)
=> implement 0x004C8898

src/openloco/input/mouse_input.cpp, src/openloco/ui/scrollview.cpp, src/openloco/ui/scrollview.h
- implement stateScrollRight at 0x004C76A7
- implement horizontalDragFollow at 0x004C8CFD
- implement verticalDragFollow at 0x004C8E2E
=> implement stateScrollRight and sub functions

CMakeLists.txt, src/openloco/interop/hooks.cpp
=> Fixes for MinGW

src/openloco/TrackData.cpp, src/openloco/TrackData.h, src/openloco/openloco.vcxproj, src/openloco/windows/construction/Construction.h, src/openloco/windows/construction/ConstructionTab.cpp
I needed to get access to this on the vehicle window so thought might as well implement it sensibly.
I looked at a few ways to do this as I'd prefer not to use vector but I couldn't see any other way that would be sensible.
Everything is const so in theory it should be intelligent enough not to do any additional allocations.
=> Track data

src/OpenLoco/Company.h, src/OpenLoco/CompanyManager.cpp, src/OpenLoco/CompanyManager.h, src/OpenLoco/Localisation/StringIds.h, src/OpenLoco/Windows/CompanyWindow.cpp, src/OpenLoco/Windows/TimePanel.cpp
CompanyWindow::Challenge::draw(window * self, Gfx::drawpixelinfo_t * dpi)
=> Implement 0x00433DEB - CompanyWindow::Challenge::draw

CHANGELOG.md
Noticed several bugfixes since the last release had not been included in the changelog. Some entries could perhaps be a bit clearer. There may be more PRs that deserve an entry as well. Suggestions for either are welcome.
=> Update changelog to include several bugfixes

src/OpenLoco/Gui.cpp, src/OpenLoco/Ui/WindowManager.h, src/OpenLoco/Windows/Main.cpp, src/OpenLoco/Windows/TitleMenu.cpp, src/OpenLoco/openloco.vcxproj
=> Move Main window creation into separate file

src/OpenLoco/Localisation/StringIds.h, src/OpenLoco/Ui/WindowManager.h, src/OpenLoco/Windows/PromptBrowseWindow.cpp, src/OpenLoco/Windows/TextInputWindow.cpp
Just committing the work I started last week for now. Doesn't look to difficult, but help is welcome due to time constraints.
=> Implement scrollview interaction for load/save window

src/OpenLoco/Input/MouseInput.cpp, src/OpenLoco/Paint/Paint.cpp, src/OpenLoco/Paint/Paint.h, src/OpenLoco/Ui.h, src/OpenLoco/Ui/ViewportInteraction.cpp, src/OpenLoco/ViewportManager.cpp, src/OpenLoco/Window.cpp, src/OpenLoco/openloco.vcxproj
Been looking at this for reference as well.
https://github.com/OpenRCT2/OpenRCT2/commit/11b064617692b6a024571518166a9f5ed437d4ac
=> Start looking into getMapPos

.travis.yml, CMakeLists.txt, cmake/FindCCache.cmake
Ported from https://github.com/OpenRCT2/OpenRCT2/pull/12604
=> Add CMake option to build with CCache

src/OpenLoco/Input.h, src/OpenLoco/Input/MouseInput.cpp, src/OpenLoco/Input/ShortcutManager.cpp, src/OpenLoco/Ui/WindowManager.h, src/OpenLoco/Windows/Construction/Common.cpp, src/OpenLoco/Windows/TerraForm.cpp, src/OpenLoco/Windows/Vehicle.cpp
=> Implement construction rotate shortcut

src/OpenLoco/GameCommands.h, src/OpenLoco/Interop/Hooks.cpp, src/OpenLoco/Things/CreateVehicle.cpp, src/OpenLoco/Things/ThingManager.h, src/OpenLoco/Things/Vehicle.cpp, src/OpenLoco/Things/Vehicle.h, src/OpenLoco/Windows/BuildVehicle.cpp, src/OpenLoco/Windows/CompanyWindow.cpp
Continues from #682 simplifies the thing iterators.
=> Reorg thing2

src/OpenLoco/Graphics/Gfx.cpp, src/OpenLoco/Graphics/Gfx.h, src/OpenLoco/Paint/Paint.cpp, src/OpenLoco/Station.h, src/OpenLoco/Town.cpp, src/OpenLoco/Town.h, src/OpenLoco/Types.hpp, src/OpenLoco/Ui/ViewportInteraction.cpp, src/OpenLoco/ViewportManager.cpp
These two simple functions were just begging to be implemented.
=> Get map pos 2

src/OpenLoco/Things/Thing.h, src/OpenLoco/Things/ThingManager.cpp, src/OpenLoco/Things/ThingManager.h
Continues on from #683
Adds a ThingTileIterator so that you can iterate all things on a tile.
=> Reorg thing3

src/OpenLoco/Input/ShortcutManager.cpp, src/OpenLoco/Ui.cpp, src/OpenLoco/Ui/WindowManager.cpp
Remove redundant hook and integrate some basic shortcuts
=> Clean up shortcuts

src/OpenLoco/Interop/Hooks.cpp, src/OpenLoco/Map/Tile.h, src/OpenLoco/Paint/Paint.cpp, src/OpenLoco/Paint/Paint.h, src/OpenLoco/Window.cpp
Seems to work fine. Might add a hook so that can see how it handles the main drawing code as right now this is just used by viewport interaction.
=> Implement PaintSession::generate

src/OpenLoco/Paint/PaintEntity.cpp
Woops tiny mistake in last pr that caused draw mistakes on vehicles.
=> Fix display issue

src/OpenLoco/OpenLoco.cpp, src/OpenLoco/OpenLoco.h, src/OpenLoco/Windows/Construction/Common.cpp, src/OpenLoco/Windows/Construction/OverheadTab.cpp
Pretty sure this flag is set when the local machine is the host in network games.
=> Rename trackUpgrade to isNetworkHost

src/OpenLoco/Ui/ScrollView.cpp
OpenRCT2 ref https://github.com/OpenRCT2/OpenRCT2/blob/05622fd9bbb65c705a3926b04c977be1749bf91f/src/openrct2-ui/interface/Widget.cpp#L896-L1001
=> Implements ScrollView::getPart

src/OpenLoco/Localisation/FormatArguments.hpp, src/OpenLoco/Windows/CompanyWindow.cpp
Thought we could do with having a constructor that lets us add the items we need immediately rather than having to do lots of pushes. Also shows off a cpp fold expression as a test to see if all the ci's can handle it.
=> Formatter refactor

src/OpenLoco/Graphics/Colour.h, src/OpenLoco/Graphics/Gfx.cpp, src/OpenLoco/Graphics/Gfx.h, src/OpenLoco/Objects/VehicleObject.h, src/OpenLoco/Paint/Paint.cpp, src/OpenLoco/Paint/Paint.h, src/OpenLoco/Paint/PaintEntity.cpp, src/OpenLoco/Paint/PaintVehicle.cpp, src/OpenLoco/Paint/PaintVehicle.h, src/OpenLoco/Things/CreateVehicle.cpp, src/OpenLoco/Things/Thing.h, src/OpenLoco/Things/Vehicle.cpp, src/OpenLoco/Things/Vehicle.h, src/OpenLoco/Windows/ToolbarTop.cpp, src/OpenLoco/Windows/Vehicle.cpp, src/OpenLoco/openloco.vcxproj
=> Paintsetup 6: Vehicle Bogie

src/OpenLoco/Input.h, src/OpenLoco/Input/MouseInput.cpp, src/OpenLoco/Windows/CompanyList.cpp
Just a little function i saw. Might do the common one as well since it looks pretty similar.
=> Implement setKeyHover for cargo payment rates

src/OpenLoco/Input.h, src/OpenLoco/Input/MouseInput.cpp, src/OpenLoco/Localisation/FormatArguments.hpp, src/OpenLoco/Localisation/StringIds.h, src/OpenLoco/Map/Tile.cpp, src/OpenLoco/Map/Tile.h, src/OpenLoco/OpenLoco.cpp, src/OpenLoco/Station.cpp, src/OpenLoco/Station.h, src/OpenLoco/Things/Vehicle.cpp, src/OpenLoco/Things/Vehicle.h, src/OpenLoco/Ui/ViewportInteraction.cpp, src/OpenLoco/Ui/WindowManager.cpp, src/OpenLoco/Ui/WindowManager.h, src/OpenLoco/Windows/CompanyWindow.cpp, src/OpenLoco/Windows/MapToolTip.cpp, src/OpenLoco/Windows/StationList.cpp, src/OpenLoco/openloco.vcxproj
This is the final part of @marijnvdwerf interaction item_left that needed to be implemented. I needed more knowledge from get map position before being able to tackle it confidently.
=> Start implementing viewport interaction item_left

src/OpenLoco/Objects/VehicleObject.h, src/OpenLoco/Paint/Paint.cpp, src/OpenLoco/Paint/Paint.h, src/OpenLoco/Paint/PaintVehicle.cpp, src/OpenLoco/Things/CreateVehicle.cpp, src/OpenLoco/Things/Vehicle.cpp, src/OpenLoco/Things/Vehicle.h
=> Paintsetup 7: Vehicle Body

src/OpenLoco/openloco.vcxproj
This updates the OpenLoco Dependencies bundle version to v1.3.0 in the Visual Studio project. See https://github.com/OpenLoco/Dependencies/releases/v1.3.0 for details.
=> Update OpenLoco Dependencies bundle

src/OpenLoco/Vehicles/CreateVehicle.cpp, src/OpenLoco/Vehicles/Vehicle.h, src/OpenLoco/Vehicles/VehicleHead.cpp
Saw this nice simple function ripe for implementation.
Can't quite work out what the other flags it is looking for.
Possibly relates to when it broke down maybe something to do with if its just reached a station.
Should probably label the flags.
=> Implement applyBreakdownToTrain

src/OpenLoco/GameCommands.h, src/OpenLoco/Localisation/StringIds.h, src/OpenLoco/Windows/ToolbarTop.cpp
This fixes #715 through the cunning use of `std::filesystem`.
=> Implement ToolbarTop::Game::prepareSaveGame

src/OpenLoco/Vehicles/Vehicle.h, src/OpenLoco/Vehicles/VehicleBody.cpp
These functions are used in a number of locations and they should not be part of the vehicle body
I require the highest bit yaw function for a water update function so that was my thinking.
=> Make calculation of yaw from vectors a free function

src/OpenLoco/Interop/Hooks.cpp, src/OpenLoco/Station.h, src/OpenLoco/Vehicles/CreateVehicle.cpp, src/OpenLoco/Vehicles/Vehicle.cpp, src/OpenLoco/Vehicles/Vehicle.h, src/OpenLoco/Vehicles/VehicleBody.cpp, src/OpenLoco/Vehicles/VehicleHead.cpp, src/OpenLoco/Windows/Vehicle.cpp
Implements `VehicleHead::update()` up to the `waterUpdate()` function.
Based on #136.
=> Vehicle update2 Part 1: Water Update

src/OpenLoco/Station.h
=> Fix offset comment

src/OpenLoco/GameCommands.cpp, src/OpenLoco/Vehicles/CreateVehicle.cpp, src/OpenLoco/Vehicles/Vehicle.h
This will make it much easier for other developers to add new game commands and start work on implementing the game commands.
=> Add game commands table and remove vehicle create hook

CHANGELOG.md, data/language/en-GB.yml, src/OpenLoco/GameCommands.cpp, src/OpenLoco/GameCommands.h, src/OpenLoco/Localisation/StringIds.h, src/OpenLoco/Vehicles/CloneVehicle.cpp, src/OpenLoco/Vehicles/Vehicle.h, src/OpenLoco/Windows/BuildVehicle.cpp, src/OpenLoco/Windows/Vehicle.cpp, src/OpenLoco/openloco.vcxproj
For now I've overriden the button that opens the build vehicle window but obviously we need to create a new button for it.
Closes https://github.com/OpenLoco/OpenLoco/issues/122
=> Add ability to clone a vehicle

CHANGELOG.md, src/OpenLoco/Map/Tile.h, src/OpenLoco/Windows/Vehicle.cpp
=> Fix road waypoints from not being able to be set.

src/OpenLoco/Audio/VehicleChannel.cpp
The issue is because of #504
This just prevents CTD and does not fix the underlying issue.
=> Fix crash trying to play vehicle audio

src/OpenLoco/Objects/VehicleObject.h, src/OpenLoco/Speed.hpp, src/OpenLoco/Types.hpp, src/OpenLoco/Vehicles/Vehicle.h, src/OpenLoco/Vehicles/VehicleBody.cpp, src/OpenLoco/Vehicles/VehicleHead.cpp, src/OpenLoco/Windows/BuildVehicle.cpp, src/OpenLoco/Windows/Vehicle.cpp, src/OpenLoco/openloco.vcxproj
I'm not completely convinced on if this is a good idea. I've not implemented any arithmetic operators for these types as I've not made them signed. I think it kind of makes sense. Perhaps I should make them signed though?
=> Add types for speeds

src/OpenLoco/Audio/Audio.cpp, src/OpenLoco/Objects/VehicleObject.h, src/OpenLoco/Speed.hpp, src/OpenLoco/Vehicles/CreateVehicle.cpp, src/OpenLoco/Vehicles/Vehicle.h, src/OpenLoco/Vehicles/VehicleHead.cpp
=> Vehicle update2 Part 1d: Vehicle Driving Sounds Update

src/OpenLoco/CompanyManager.cpp, src/OpenLoco/CompanyManager.h, src/OpenLoco/Date.cpp, src/OpenLoco/Date.h, src/OpenLoco/Economy.cpp, src/OpenLoco/Economy.h, src/OpenLoco/OpenLoco.cpp, src/OpenLoco/Scenario.cpp, src/OpenLoco/Vehicles/VehicleManager.cpp, src/OpenLoco/Vehicles/VehicleManager.h, src/OpenLoco/openloco.vcxproj
Recent PRs made stubs for some of these routines. To prevent duplicated effort, I'm splitting these off from #362.
=> Implement Scenario::initialiseDate

src/OpenLoco/Objects/VehicleObject.h, src/OpenLoco/Vehicles/VehicleHead.cpp
=> Vehicle update2 Part 1c: Sound producing functions

src/OpenLoco/Map/SurfaceTile.cpp, src/OpenLoco/Map/Tile.h, src/OpenLoco/Things/Thing.h, src/OpenLoco/Vehicles/Orders.cpp, src/OpenLoco/Vehicles/Vehicle.h, src/OpenLoco/Vehicles/VehicleHead.cpp, src/OpenLoco/Windows/Vehicle.cpp
This function is sort of the pathfinding along with `sub_427FC9` which hasn't been implemented.
=> Vehicle update2 Part 1a: Water motion update

src/OpenLoco/Audio/Audio.h, src/OpenLoco/Audio/VehicleChannel.cpp
For when its a pair it should be a pair.
=> Use std::pair for pair in Audio code

src/OpenLoco/Vehicles/CreateVehicle.cpp, src/OpenLoco/Vehicles/Vehicle.h, src/OpenLoco/Vehicles/VehicleHead.cpp, src/OpenLoco/Windows/Vehicle.cpp
To make the airplane code as absolutely standalone as possible thought I'd do this bit of code separately since it can be done.
=> Move next position calc to function for airplane code

CHANGELOG.md, src/OpenLoco/Economy.cpp, src/OpenLoco/Economy.h, src/OpenLoco/OpenLoco.cpp, src/OpenLoco/Scenario.h
This is working towards implementing #361.
=> Implement inflation-related functions

src/OpenLoco/Vehicles/VehicleHead.cpp
=> Vehicle Update2 Part 2a: Implements removed parts from updateAir

src/OpenLoco/Vehicles/VehicleHead.cpp
Not much to report on this one. Pretty simple.
=> Vehicle Update2 Part 2f: Implements movePlaneTo

src/OpenLoco/Vehicles/Vehicle.h, src/OpenLoco/Vehicles/VehicleBody.cpp, src/OpenLoco/Vehicles/VehicleHead.cpp
This function is used to work out where to land the plane. I suspect there are a few variables and flags here that can be named.
=> Vehicle Update2 Part 2b: Implements sub_427122

src/OpenLoco/Vehicles/Vehicle.h, src/OpenLoco/Vehicles/VehicleHead.cpp
This has the majority of updateLand stubbed out much like the first bit of update air.
=> Vehicle Update 2 Part 3: Implement updateLand

src/OpenLoco/Vehicles/Vehicle.h, src/OpenLoco/Vehicles/VehicleHead.cpp
Very similar to leaving dock sound...
=> Vehicle Update2 Part 2c: Implements produceTouchdownAirportSound

src/OpenLoco/Objects/AirportObject.h, src/OpenLoco/Vehicles/VehicleHead.cpp
Might need to do further renaming after seeing how these apron areas work. 
This was a very useful reference https://www.tt-wiki.net/wiki/Aircraft_Movement_Graph
=> Vehicle Update2 Part 2d: Implement airportGetNextApronArea

src/OpenLoco/Windows/PromptBrowseWindow.cpp, src/OpenLoco/Windows/ToolbarTop.cpp
Minor cleanups I've had sitting in my working directory for too long.
=> Use fs::path::replace_extension

src/OpenLoco/Objects/AirportObject.h, src/OpenLoco/Station.h, src/OpenLoco/Vehicles/Vehicle.h, src/OpenLoco/Vehicles/VehicleHead.cpp
I'm going to do a bit of renaming on this
=> Vehicle Update 2 Part 2e: Implement airportGetApronTransitionTarget

src/OpenLoco/Vehicles/CreateVehicle.cpp, src/OpenLoco/Vehicles/Vehicle.cpp, src/OpenLoco/Vehicles/Vehicle.h, src/OpenLoco/Vehicles/VehicleHead.cpp
This exposes everyones favourite timeout at signals!
=> Vehicle Update 2 Part 3a: Start the regular movement code

src/OpenLoco/Vehicles/Vehicle.h, src/OpenLoco/Vehicles/VehicleHead.cpp
Extra care when checking required as this is only used for manual control.
=> Vehicle Update 2 Part 3d: Implements sub_4A8C81 part of manual vehicle control

CHANGELOG.md, data/language/en-GB.yml, src/OpenLoco/Config.cpp, src/OpenLoco/Config.h, src/OpenLoco/Drawing/FPSCounter.cpp, src/OpenLoco/Drawing/FPSCounter.h, src/OpenLoco/Localisation/StringIds.h, src/OpenLoco/Ui.cpp, src/OpenLoco/Windows/Options.cpp, src/OpenLoco/openloco.vcxproj
This adds an optional, basic FPS counter to the game.
=> Add simple FPS counter

nuget.config
This was suggested in https://github.com/actions/virtual-environments/issues/3038 to address Windows CI failures.
=> Add nuget.config

src/OpenLoco/Audio/Audio.cpp, src/OpenLoco/Audio/Audio.h, src/OpenLoco/Location.hpp, src/OpenLoco/Things/Misc.cpp, src/OpenLoco/Things/Misc.h, src/OpenLoco/Things/Thing.cpp, src/OpenLoco/Things/Thing.h, src/OpenLoco/Vehicles/VehicleBody.cpp, src/OpenLoco/Vehicles/VehicleHead.cpp, src/OpenLoco/Viewport.cpp, src/OpenLoco/Viewport.hpp, src/OpenLoco/Windows/BuildVehicle.cpp, src/OpenLoco/Windows/IndustryList.cpp, src/OpenLoco/Windows/IndustryWindow.cpp, src/OpenLoco/Windows/TerraForm.cpp, src/OpenLoco/Windows/TownList.cpp, src/OpenLoco/Windows/TownWindow.cpp
Based on #809. Needs rebasing once merged.
=> Use map_pos3 over Loc16

src/OpenLoco/CompanyManager.cpp, src/OpenLoco/CompanyManager.h, src/OpenLoco/Entities/EntityManager.cpp, src/OpenLoco/Entities/EntityManager.h, src/OpenLoco/Entities/Misc.cpp, src/OpenLoco/Entities/Misc.h, src/OpenLoco/GameCommands.cpp, src/OpenLoco/Viewport.cpp, src/OpenLoco/Viewport.hpp
~~Might still rejig where this is located I think I might make the first function part of something else.~~
=> Implement create money effect

src/OpenLoco/Math/Vector.cpp, src/OpenLoco/Math/Vector.hpp, src/OpenLoco/Vehicles/VehicleBody.cpp, src/OpenLoco/openloco.vcxproj
fastSquareRoot is used by a large amount of functions for calculating the distance between two locations.
=> Move fastSquareRoot to Math folder

src/OpenLoco/Map/TileManager.cpp
This also eliminates a bunch of branches in the getHeight function, when the surface is flat it can also bail early, all the conditions were basically identical and could be also expressed as ```slope != 0```.
=> Minor refactor work in TileManager.cpp

src/OpenLoco/CompanyManager.cpp
=> Fix rebase issue in spend money

src/OpenLoco/Math/Bound.hpp, src/OpenLoco/openloco.vcxproj
This will greatly simplify some users in the vehicle unload code.
=> Add bounded add/subtract to simplify some field updates

src/OpenLoco/Audio/Audio.cpp, src/OpenLoco/Audio/Audio.h, src/OpenLoco/CompanyManager.cpp, src/OpenLoco/CompanyManager.h, src/OpenLoco/Environment.cpp, src/OpenLoco/Environment.h, src/OpenLoco/GameCommands/GameCommands.cpp, src/OpenLoco/GameCommands/GameCommands.h, src/OpenLoco/GameCommands/LoadSaveQuit.cpp, src/OpenLoco/GameCommands/TogglePause.cpp, src/OpenLoco/GameException.hpp, src/OpenLoco/Localisation/StringIds.h, src/OpenLoco/OpenLoco.cpp, src/OpenLoco/OpenLoco.h, src/OpenLoco/Title.cpp, src/OpenLoco/Ui/WindowManager.h, src/OpenLoco/Windows/PromptSaveWindow.cpp, src/OpenLoco/openloco.vcxproj
The LoadSaveQuit game command is intertwined with the PromptSaveWindow. I am implementing both in this PR.
=> Implement PromptSaveWindow and LoadSaveQuit game command

src/OpenLoco/Ui/ViewportInteraction.cpp, src/OpenLoco/Vehicles/CreateVehicle.cpp, src/OpenLoco/Vehicles/RenameVehicle.cpp, src/OpenLoco/Vehicles/Vehicle.h, src/OpenLoco/Windows/BuildVehicle.cpp, src/OpenLoco/Windows/News/News.cpp, src/OpenLoco/Windows/Vehicle.cpp
Cherry picking from #878 to prevent conflicts
=> Name VehicleHead var_22 (name) and var_44 (ordinalNumber)

src/OpenLoco/Vehicles/CreateVehicle.cpp, src/OpenLoco/Vehicles/Vehicle.h, src/OpenLoco/Windows/Construction/ConstructionTab.cpp, src/OpenLoco/Windows/PlayerInfoPanel.cpp, src/OpenLoco/Windows/TimePanel.cpp, src/OpenLoco/Windows/Vehicle.cpp
Cherry picking from #878 to prevent conflicts
=> Name some Vehicle1 and Vehicle2 fields

src/OpenLoco/GameCommands/LoadSaveQuit.cpp, src/OpenLoco/GameCommands/TogglePause.cpp
=> Set regs.ebx for loadSaveQuit and togglePause game commands

src/OpenLoco/Vehicles/Vehicle.h, src/OpenLoco/Vehicles/VehicleHead.cpp, src/OpenLoco/Windows/Vehicle.cpp
=> Cleanup isPlaced instances; move generateCargoTotalString

src/OpenLoco/Input/MouseInput.cpp, src/OpenLoco/Input/ShortcutManager.cpp, src/OpenLoco/Localisation/StringIds.h, src/OpenLoco/Objects/InterfaceSkinObject.h, src/OpenLoco/Ui/WindowManager.h, src/OpenLoco/Vehicles/Vehicle.h, src/OpenLoco/Windows/ToolbarTop.cpp, src/OpenLoco/Windows/VehicleList.cpp
=> Implement the vehicle list window

src/OpenLoco/Localisation/StringIds.h, src/OpenLoco/Vehicles/Vehicle.h, src/OpenLoco/Vehicles/VehicleHead.cpp
=> VehicleHead::getStatus

src/OpenLoco/GameCommands/RenameTown.cpp, src/OpenLoco/Industry.h, src/OpenLoco/Station.h, src/OpenLoco/StationManager.cpp, src/OpenLoco/Town.cpp, src/OpenLoco/Town.h, src/OpenLoco/TownManager.cpp, src/OpenLoco/TownManager.h, src/OpenLoco/Types.hpp, src/OpenLoco/Ui/ViewportInteraction.cpp, src/OpenLoco/Windows/TownList.cpp
Just a little coding style enforcement
=> Town coding style

src/OpenLoco/Vehicles/Vehicle.h, src/OpenLoco/Vehicles/VehicleHead.cpp, src/OpenLoco/Windows/Vehicle.cpp
The get status PR confirmed the difference between 2 and 3.
=> Name Vehicle Status fields 2 and 3

src/OpenLoco/Windows/VehicleList.cpp
Every row was increasing the offset by 2px extra. That adds up. :)
=> Fix vehicle list drawScroll row offset

src/OpenLoco/Utility/String.cpp, src/OpenLoco/Utility/String.hpp, src/OpenLoco/Windows/VehicleList.cpp
=> Use logical string comparison for vehicle list order

src/OpenLoco/LabelFrame.h, src/OpenLoco/Paint/Paint.cpp, src/OpenLoco/Station.h, src/OpenLoco/Town.h, src/OpenLoco/ViewportManager.cpp, src/OpenLoco/openloco.vcxproj
Trying to reduce the include of town.h where it wasn't required.
=> Move label frame out into standalone file

CHANGELOG.md, src/OpenLoco/Vehicles/VehicleHead.cpp
Not sure if there is more issues with ships especially around the orders
=> Fix ships not marking stations as occupied

src/OpenLoco/CompanyManager.cpp, src/OpenLoco/Entities/Entity.h, src/OpenLoco/Entities/Misc.h, src/OpenLoco/Input/Keyboard.cpp, src/OpenLoco/Paint/PaintVehicle.cpp, src/OpenLoco/Vehicles/Vehicle.cpp, src/OpenLoco/Vehicles/Vehicle.h, src/OpenLoco/Windows/BuildVehicle.cpp
Follow on from #906
Reorg of some entity fields
=> Entity Reorg

src/OpenLoco/Entities/Entity.h, src/OpenLoco/Entities/EntityManager.cpp, src/OpenLoco/Entities/EntityManager.h, src/OpenLoco/Entities/Misc.cpp, src/OpenLoco/Entities/Misc.h, src/OpenLoco/Paint/PaintEntity.cpp, src/OpenLoco/S5/S5.cpp, src/OpenLoco/Vehicles/CreateVehicle.cpp
Follow on from #919 
Implements misc entity manager functions.
=> Entity2: Entity manager functions

src/OpenLoco/Entities/Entity.h, src/OpenLoco/Math/Triginometry.hpp, src/OpenLoco/Math/Trigonometry.hpp, src/OpenLoco/Vehicles/VehicleBody.cpp, src/OpenLoco/Vehicles/VehicleHead.cpp, src/OpenLoco/openloco.vcxproj
~~Wip.~~ Trying to simplify a bunch of body functions.
Will be further cleaned up in the base x, y, z PR.
=> Add base of trig class

src/OpenLoco/Windows/Vehicle.cpp
A surprisingly complex little bit of code for this.
=> Implement refresh displayed order labels

src/OpenLoco/Company.h, src/OpenLoco/CompanyManager.cpp, src/OpenLoco/CompanyManager.h, src/OpenLoco/Entities/Entity.h, src/OpenLoco/Industry.h, src/OpenLoco/Map/Tile.cpp, src/OpenLoco/Map/Tile.h, src/OpenLoco/Station.cpp, src/OpenLoco/Station.h, src/OpenLoco/Town.h, src/OpenLoco/Vehicles/CreateVehicle.cpp, src/OpenLoco/Vehicles/Vehicle.h, src/OpenLoco/Vehicles/VehicleBody.cpp, src/OpenLoco/Vehicles/VehicleHead.cpp, src/OpenLoco/Windows/CompanyList.cpp, src/OpenLoco/Windows/Vehicle.cpp
=> Vehicle Update: Cargo Unload

src/OpenLoco/Vehicles/CreateVehicle.cpp, src/OpenLoco/Vehicles/Vehicle.h, src/OpenLoco/Vehicles/VehicleHead.cpp, src/OpenLoco/Windows/Vehicle.cpp
=> Vehicle cargo2: sub_4BA7C7

src/OpenLoco/CompanyManager.cpp, src/OpenLoco/Entities/Entity.h, src/OpenLoco/Entities/EntityManager.cpp, src/OpenLoco/GameCommands/VehiclePickup.cpp, src/OpenLoco/Paint/PaintEntity.cpp, src/OpenLoco/Paint/PaintMiscEntity.cpp, src/OpenLoco/Paint/PaintVehicle.cpp, src/OpenLoco/Ui/ViewportInteraction.cpp, src/OpenLoco/Vehicles/CreateVehicle.cpp, src/OpenLoco/Vehicles/OrderSkip.cpp, src/OpenLoco/Vehicles/VehicleBody.cpp, src/OpenLoco/Vehicles/VehicleHead.cpp, src/OpenLoco/ViewportManager.cpp, src/OpenLoco/Window.cpp, src/OpenLoco/Windows/CompanyWindow.cpp, src/OpenLoco/Windows/Map.cpp
Should lead to some nice simplification of code.
=> Replace EntityBase::x,y,z with Map::Pos3

src/OpenLoco/Core/Variant.hpp, src/OpenLoco/Title.cpp, src/Thirdparty/variant.hpp
This re-enables compilation on macOS 10.13.
https://github.com/mpark/variant
=> Add polyfill for std::variant and std::visit

CHANGELOG.md, src/OpenLoco/Entities/EntityManager.cpp, src/OpenLoco/Entities/EntityTweener.cpp, src/OpenLoco/Entities/EntityTweener.h, src/OpenLoco/Interop/Hooks.cpp, src/OpenLoco/OpenLoco.cpp, src/OpenLoco/Ui.cpp, src/OpenLoco/Ui/WindowManager.cpp, src/OpenLoco/Ui/WindowManager.h, src/OpenLoco/openloco.vcxproj
This is based on #920 so it needs to wait.
=> Entity Tweening

src/OpenLoco/Graphics/Colour.h, src/OpenLoco/Objects/RoadStationObject.cpp, src/OpenLoco/Objects/RoadStationObject.h, src/OpenLoco/Objects/TrainStationObject.cpp, src/OpenLoco/Objects/TrainStationObject.h, src/OpenLoco/Windows/Construction/Common.cpp, src/OpenLoco/Windows/Construction/StationTab.cpp
=> Refactor construction window

src/OpenLoco/GameCommands/GameCommands.cpp, src/OpenLoco/GameCommands/GameCommands.h, src/OpenLoco/Industry.cpp, src/OpenLoco/Industry.h, src/OpenLoco/Input/MouseInput.cpp, src/OpenLoco/Interop/Hooks.cpp, src/OpenLoco/Map/MapGenerator.cpp, src/OpenLoco/Map/SurfaceTile.cpp, src/OpenLoco/Map/Tile.cpp, src/OpenLoco/Map/Tile.h, src/OpenLoco/Map/TileLoop.hpp, src/OpenLoco/Map/TileManager.cpp, src/OpenLoco/Map/TileManager.h, src/OpenLoco/Paint/Paint.h, src/OpenLoco/Station.cpp, src/OpenLoco/Ui/ViewportInteraction.cpp, src/OpenLoco/Ui/WindowManager.h, src/OpenLoco/Vehicles/CreateVehicle.cpp, src/OpenLoco/Vehicles/VehicleHead.cpp, src/OpenLoco/Windows/Construction/Common.cpp, src/OpenLoco/Windows/StationWindow.cpp, src/OpenLoco/Windows/TileInspector.cpp, src/OpenLoco/Windows/Vehicle.cpp
Little refactor as well. Noticed a very minor mistake with one of the viewport functions but it doesn't actually change anything as the values arent used.
=> Tile Coding Style Enforcement

src/OpenLoco/Drawing/SoftwareDrawingEngine.cpp, src/OpenLoco/Input/MouseInput.cpp, src/OpenLoco/Interop/Hooks.cpp, src/OpenLoco/Map/TileManager.cpp, src/OpenLoco/Paint/Paint.cpp, src/OpenLoco/Ui.cpp, src/OpenLoco/Ui.h, src/OpenLoco/Ui/ScrollView.cpp, src/OpenLoco/Ui/ScrollView.h, src/OpenLoco/Ui/ViewportInteraction.cpp, src/OpenLoco/Ui/WindowManager.cpp, src/OpenLoco/Ui/WindowManager.h, src/OpenLoco/ViewportManager.cpp, src/OpenLoco/Widget.cpp, src/OpenLoco/Window.cpp, src/OpenLoco/Window.h, src/OpenLoco/Windows/BuildVehicle.cpp, src/OpenLoco/Windows/CompanyList.cpp, src/OpenLoco/Windows/Construction/Common.cpp, src/OpenLoco/Windows/Construction/ConstructionTab.cpp, src/OpenLoco/Windows/DragVehiclePart.cpp, src/OpenLoco/Windows/IndustryList.cpp, src/OpenLoco/Windows/PlayerInfoPanel.cpp, src/OpenLoco/Windows/StationList.cpp, src/OpenLoco/Windows/TimePanel.cpp, src/OpenLoco/Windows/TitleMenu.cpp, src/OpenLoco/Windows/TownList.cpp, src/OpenLoco/Windows/Vehicle.cpp, src/OpenLoco/Windows/VehicleList.cpp
=> UI Coding Style

src/OpenLoco/Graphics/Colour.cpp, src/OpenLoco/Graphics/Colour.h, src/OpenLoco/Graphics/Gfx.cpp, src/OpenLoco/Graphics/Gfx.h, src/OpenLoco/Objects/BuildingObject.cpp, src/OpenLoco/Objects/BuildingObject.h, src/OpenLoco/Objects/TreeObject.cpp, src/OpenLoco/Ui/Dropdown.cpp, src/OpenLoco/Ui/Dropdown.h, src/OpenLoco/Windows/MapWindow.cpp, src/OpenLoco/Windows/StationWindow.cpp, src/OpenLoco/Windows/TerraForm.cpp, src/OpenLoco/Windows/TimePanel.cpp, src/OpenLoco/Windows/ToolbarBottomEditor.cpp, src/OpenLoco/Windows/TownList.cpp
I've purposely left out drawpixelinfo and point_t as there is discussions about renaming it.
=> Enforce coding style on gfx

CONTRIBUTORS.MD, data/language/zh-CN.yml
Some items are not translated yet.
According to issue #304 and #580, all characters will be displayed as question marks, which means I can't check whether all translated items are correct.
=> translation: simplified chinese

src/OpenLoco/Interop/Hooks.cpp, src/OpenLoco/Interop/Interop.hpp, src/OpenLoco/Paint/Paint.cpp, src/OpenLoco/Ui/WindowManager.cpp
=> Add force align attributes to all hooks

src/OpenLoco/TrackData.h
=> Add cstdlib include to TrackData.h for size_t

src/OpenLoco/Localisation/LanguageFiles.cpp, src/OpenLoco/Localisation/LanguageFiles.h, src/OpenLoco/OpenLoco.cpp
There was a difference how "Exit Game" button and closing the game window were handled
=> Exit cleanly in all conditions through common path

src/OpenLoco/openloco.vcxproj
This update adds Google's Test, Benchmark and Breakpad libraries
=> Update dependencies to v1.4.0

src/OpenLoco/Graphics/Gfx.cpp, src/OpenLoco/Graphics/Gfx.h, src/OpenLoco/Ui/WindowType.h, src/OpenLoco/Windows/MapToolTip.cpp
=> Start implementing the map tooltip window

src/OpenLoco/Company.h, src/OpenLoco/Message.h, src/OpenLoco/Vehicles/Vehicle.h, src/OpenLoco/Vehicles/VehicleHead.cpp
Starting to get paranoid on why I can't find the divergence so thought it best to split the PR up as much as possible.
=> Yank out refactors from cargo load pr

src/OpenLoco/Vehicles/VehicleHead.cpp
Forgot to do this after implementing all of the land update functions.
=> Remove TODO now that all functions implemented

src/OpenLoco/CompanyManager.cpp, src/OpenLoco/CompanyManager.h, src/OpenLoco/Graphics/ImageIds.h, src/OpenLoco/Ui/Dropdown.cpp, src/OpenLoco/Ui/Dropdown.h, src/OpenLoco/Widget.cpp, src/OpenLoco/Windows/CompanyWindow.cpp, src/OpenLoco/Windows/TerraForm.cpp, src/OpenLoco/Windows/TownList.cpp
Implemented the colour picker dropdown, as well -what should be- all its callers.
=> Implement colour picker dropdowns

src/OpenLoco/Company.cpp, src/OpenLoco/Company.h, src/OpenLoco/GameCommands/ChangeCompanyColour.cpp, src/OpenLoco/GameCommands/GameCommands.cpp, src/OpenLoco/GameCommands/GameCommands.h, src/OpenLoco/Map/Tile.h, src/OpenLoco/openloco.vcxproj
=> Implement ChangeCompanyColour game command

src/OpenLoco/Windows/CompanyWindow.cpp
Saw this while doing a little overview.
=> CompanyWindow Link up implemented function

src/OpenLoco/Graphics/Gfx.cpp, src/OpenLoco/Localisation/LanguageFiles.cpp, src/OpenLoco/Localisation/StringManager.h
Likely missed as nothing uses it. No harm readding it though.
=> Readd window_colour_4 control code

src/OpenLoco/Map/TileManager.cpp, src/OpenLoco/Map/TileManager.h, src/OpenLoco/Windows/TerraForm.cpp
Not completely convinced the functions should be in this file but it will do for now. Should probably make a MapRange variable to hold A and B.
=> Make accessor functions for mapselection points

src/OpenLoco/Audio/Audio.cpp, src/OpenLoco/Environment.cpp, src/OpenLoco/Game.cpp, src/OpenLoco/Localisation/LanguageFiles.cpp, src/OpenLoco/Localisation/Languages.cpp, src/OpenLoco/Objects/ObjectManager.cpp, src/OpenLoco/Platform/Platform.Macos.mm, src/OpenLoco/Platform/Platform.Posix.cpp, src/OpenLoco/Platform/Platform.Windows.cpp, src/OpenLoco/Platform/Platform.h, src/OpenLoco/Windows/PromptBrowseWindow.cpp
This fixes the issues on my end of loading wide paths and wide directories.
=> Fix #1048. Hopefully this fixes some of the issues

src/OpenLoco/Graphics/Gfx.cpp, src/OpenLoco/Graphics/Gfx.h, src/OpenLoco/Ui/Dropdown.cpp
very very similar to string width
=> Implement getMaxStringWidth

src/OpenLoco/Audio/Audio.cpp, src/OpenLoco/Map/SurfaceTile.cpp, src/OpenLoco/Map/Tile.cpp, src/OpenLoco/Map/Tile.h, src/OpenLoco/Viewport.cpp, src/OpenLoco/Viewport.hpp, src/OpenLoco/ViewportManager.cpp, src/OpenLoco/Window.cpp, src/OpenLoco/Windows/Construction/ConstructionTab.cpp, src/OpenLoco/Windows/Vehicle.cpp
Another day another duplicated function is found. Doh!
=> Remove duplicated function and rename

src/OpenLoco/Utility/Numeric.cpp
https://godbolt.org/z/dfvsG5PfG
=> Fix bitScanReverse for GCC

src/OpenLoco/Windows/CompanyWindow.cpp
Finishes last remaining tool function.
=> Company Window: Tool Update

CHANGELOG.md, src/OpenLoco/GameCommands/GameCommands.cpp, src/OpenLoco/GameCommands/GameCommands.h, src/OpenLoco/Objects/BuildingObject.h, src/OpenLoco/Windows/TownList.cpp
=> Townlist ToolUpdate/Down

src/OpenLoco/Vehicles/Vehicle.h, src/OpenLoco/Vehicles/VehicleHead.cpp
Ultimately very similar to the unload function. Not done much testing of this yet so may have some bugs.
=> VehicleHead::updateLoadCargo

src/OpenLoco/GameCommands/GameCommands.h, src/OpenLoco/Localisation/StringIds.h, src/OpenLoco/Windows/Vehicle.cpp
So it seems there are yet more arguments!
=> Vehicle Tool Down

src/OpenLoco/Drawing/FPSCounter.cpp, src/OpenLoco/Graphics/Gfx.cpp, src/OpenLoco/Graphics/Gfx.h, src/OpenLoco/Interop/Hooks.cpp, src/OpenLoco/Ui/Dropdown.cpp, src/OpenLoco/Widget.cpp, src/OpenLoco/Windows/CompanyFaceSelection.cpp, src/OpenLoco/Windows/CompanyWindow.cpp, src/OpenLoco/Windows/EditKeyboardShortcut.cpp, src/OpenLoco/Windows/LandscapeGenerationConfirm.cpp, src/OpenLoco/Windows/MapToolTip.cpp, src/OpenLoco/Windows/MapWindow.cpp, src/OpenLoco/Windows/News/News.cpp, src/OpenLoco/Windows/ObjectSelectionWindow.cpp, src/OpenLoco/Windows/PromptBrowseWindow.cpp, src/OpenLoco/Windows/PromptOkCancelWindow.cpp, src/OpenLoco/Windows/ScenarioSelect.cpp, src/OpenLoco/Windows/TextInputWindow.cpp, src/OpenLoco/Windows/TileInspector.cpp, src/OpenLoco/Windows/TitleExit.cpp, src/OpenLoco/Windows/TitleOptions.cpp, src/OpenLoco/Windows/TitleVersion.cpp, src/OpenLoco/Windows/Vehicle.cpp
Another pass by ref PR. This time from the other direction, the GFX functions.
=> Pass context by ref for all string functions

src/OpenLoco/Graphics/Gfx.cpp, src/OpenLoco/Graphics/Gfx.h, src/OpenLoco/Widget.cpp, src/OpenLoco/Windows/Construction/Common.cpp, src/OpenLoco/Windows/Construction/ConstructionTab.cpp, src/OpenLoco/Windows/Construction/OverheadTab.cpp, src/OpenLoco/Windows/DragVehiclePart.cpp, src/OpenLoco/Windows/IndustryList.cpp, src/OpenLoco/Windows/News/Ticker.cpp, src/OpenLoco/Windows/ObjectSelectionWindow.cpp, src/OpenLoco/Windows/ProgressBar.cpp, src/OpenLoco/Windows/PromptBrowseWindow.cpp, src/OpenLoco/Windows/TerraForm.cpp, src/OpenLoco/Windows/TextInputWindow.cpp, src/OpenLoco/Windows/TownList.cpp, src/OpenLoco/Windows/TownWindow.cpp
I didn't like how the old version basically used a global var so refactored that out. I also implemented it in two different ways. One way is as per the assembly the second way does it using the  intersect helper function that we have.
=> Clip context

src/OpenLoco/Input/MouseInput.cpp, src/OpenLoco/TrackData.cpp, src/OpenLoco/TrackData.h, src/OpenLoco/Ui/WindowManager.h, src/OpenLoco/Windows/Construction/Common.cpp, src/OpenLoco/Windows/Construction/Construction.h, src/OpenLoco/Windows/Construction/ConstructionTab.cpp, src/OpenLoco/Windows/TerraForm.cpp, src/OpenLoco/Windows/Vehicle.cpp
Some refactoring required before the tool functions can be implemented.
Will be trying to massage this code so that it is similar to the other windows.
=> Construct Refactor

src/OpenLoco/Windows/CompanyWindow.cpp
I hummed and harred for a while on the name. I'm open for suggestions.
=> Implement the last company window function

CHANGELOG.md, src/OpenLoco/Map/Tile.h, src/OpenLoco/Windows/Construction/Common.cpp, src/OpenLoco/Windows/Construction/Construction.h, src/OpenLoco/Windows/Construction/ConstructionTab.cpp, src/OpenLoco/Windows/Construction/SignalTab.cpp
Heavily based on the signal code.
=> Implement construction open At functions

src/OpenLoco/Map/TileManager.cpp, src/OpenLoco/Map/TileManager.h, src/OpenLoco/OpenLoco.cpp
Taking some of the code out of #367.
=> Implement base of TileManager::update

src/OpenLoco/Map/BuildingTile.cpp, src/OpenLoco/Map/Tile.h, src/OpenLoco/Map/TileManager.cpp, src/OpenLoco/Objects/BuildingObject.h, src/OpenLoco/Station.cpp, src/OpenLoco/StationManager.cpp, src/OpenLoco/StationManager.h, src/OpenLoco/Town.h, src/OpenLoco/TownManager.cpp, src/OpenLoco/TownManager.h, src/OpenLoco/Ui/ViewportInteraction.cpp, src/OpenLoco/openloco.vcxproj
This is the same function as #367 but I've done different parts of it. I'll cherry pick that pr into this one.
=> Further work on the building element update

src/OpenLoco/GameCommands/GameCommands.cpp, src/OpenLoco/GameCommands/GameCommands.h, src/OpenLoco/Map/Tile.h, src/OpenLoco/Objects/RoadObject.h, src/OpenLoco/Windows/Construction/Common.cpp, src/OpenLoco/Windows/Construction/ConstructionTab.cpp
=> Remove track Construction Window

src/OpenLoco/Vehicles/CreateVehicle.cpp, src/OpenLoco/Vehicles/Vehicle.h, src/OpenLoco/Vehicles/VehicleBody.cpp, src/OpenLoco/Vehicles/VehicleHead.cpp
I'm not entirely sure I have enough information to make this struct correctly but i think it works.
=> TrackAndDirection

src/OpenLoco/Audio/Audio.cpp, src/OpenLoco/Math/Vector.hpp, src/OpenLoco/Ui/ViewportInteraction.cpp, src/OpenLoco/Viewport.cpp, src/OpenLoco/Viewport.hpp, src/OpenLoco/Window.cpp, src/OpenLoco/Windows/Construction/Common.cpp, src/OpenLoco/Windows/Vehicle.cpp
This brings in the name changes I've used in https://github.com/OpenLoco/OpenLoco/wiki/Coordinate-Systems
=> Further Point refactoring

src/OpenLoco/Graphics/Gfx.cpp, src/OpenLoco/Graphics/Gfx.h, src/OpenLoco/Map/Tile.h, src/OpenLoco/Objects/TreeObject.cpp, src/OpenLoco/Objects/TreeObject.h, src/OpenLoco/Paint/Paint.cpp, src/OpenLoco/Paint/Paint.h, src/OpenLoco/Paint/PaintTile.cpp, src/OpenLoco/Paint/PaintTree.cpp, src/OpenLoco/Paint/PaintTree.h, src/OpenLoco/Paint/PaintVehicle.cpp, src/OpenLoco/Windows/TerraForm.cpp, src/OpenLoco/openloco.vcxproj
Based on the work by @marijnvdwerf a few years back.
=> Implement Tree Paint

src/OpenLoco/Game.cpp, src/OpenLoco/Interop/Hooks.cpp, src/OpenLoco/Platform/Platform.Windows.cpp, src/OpenLoco/Ui/WindowManager.h, src/OpenLoco/Windows/PromptBrowseWindow.cpp, src/OpenLoco/Windows/PromptOkCancelWindow.cpp
Currently, this only gets rid of a few string buffers, but I'd like to get more of the interop legacy out.
=> Further cleanup of the browse window

src/OpenLoco/Config.cpp
=> Load config files from non ASCII paths

src/OpenLoco/Environment.cpp, src/OpenLoco/Interop/Hooks.cpp, src/OpenLoco/OpenLoco.cpp, src/OpenLoco/Platform/Crash.cpp, src/OpenLoco/Platform/Platform.Macos.mm, src/OpenLoco/Platform/Platform.Posix.cpp, src/OpenLoco/Platform/Platform.Windows.cpp, src/OpenLoco/Platform/Platform.h, src/OpenLoco/Ui/Screenshot.cpp, src/OpenLoco/Windows/PromptBrowseWindow.cpp
Noticed this when we were correcting bugs.
=> Apply coding style to platform

src/OpenLoco/Entities/Misc.cpp, src/OpenLoco/Map/Map.hpp, src/OpenLoco/Paint/PaintTile.cpp, src/OpenLoco/Window.cpp
=> Map::validCoords refactor

src/OpenLoco/Paint/Paint.cpp, src/OpenLoco/Paint/Paint.h, src/OpenLoco/Paint/PaintTile.cpp
Made a small mistake in the tile element 1 code. This function is pretty much a copy paste of the other function. Looks like its for large images to get drawn correctly.
=> Paint tile2

src/OpenLoco/GameCommands/GameCommands.h, src/OpenLoco/GameCommands/RenameStation.cpp, src/OpenLoco/Input/MouseInput.cpp, src/OpenLoco/Map/Tile.h, src/OpenLoco/Paint/Paint.cpp, src/OpenLoco/Station.cpp, src/OpenLoco/Station.h, src/OpenLoco/StationManager.cpp, src/OpenLoco/StationManager.h, src/OpenLoco/Types.hpp, src/OpenLoco/Ui/ViewportInteraction.cpp, src/OpenLoco/Ui/WindowManager.cpp, src/OpenLoco/Ui/WindowManager.h, src/OpenLoco/Vehicles/Orders.h, src/OpenLoco/Vehicles/Vehicle.h, src/OpenLoco/Vehicles/VehicleHead.cpp, src/OpenLoco/Windows/Construction/ConstructionTab.cpp, src/OpenLoco/Windows/Construction/StationTab.cpp, src/OpenLoco/Windows/News/News.cpp, src/OpenLoco/Windows/StationList.cpp, src/OpenLoco/Windows/StationWindow.cpp, src/OpenLoco/Windows/Vehicle.cpp, src/OpenLoco/Windows/VehicleList.cpp
This should help prevent using the wrong types for certain things and in the distant future will be helpful if we ever want to increase limits.
=> Change StationId to be strong

CHANGELOG.md, src/OpenLoco/Windows/Construction/ConstructionTab.cpp
=> Fix tram turnaround piece activating wrong button

CHANGELOG.md, src/OpenLoco/Windows/Construction/Common.cpp, src/OpenLoco/Windows/Construction/ConstructionTab.cpp
Was incorrectly calling track functions from a road function.
=> Fix #1167. Incorrect right click interact with some road pieces.

src/OpenLoco/GameState.h, src/OpenLoco/S5/S5.h
Came across these two whilst looking at something else they are both used in lots of locations but hooking them up is for a latter date.
=> Label further gamestate

src/OpenLoco/Map/Tile.h, src/OpenLoco/Vehicles/VehicleTail.cpp
Not too confident on this one. Needs some testing. Code is a bit unknown.
=> Implement sub_48963F

src/OpenLoco/CommandLine.cpp, src/OpenLoco/OpenLoco.cpp, src/OpenLoco/S5/S5.cpp, src/OpenLoco/ViewportManager.cpp
It was missing the object header that is before the chunk.
=> Fix uncompress command with packed objects

CHANGELOG.md, data/language/en-GB.yml, src/OpenLoco/Company.cpp, src/OpenLoco/Company.h, src/OpenLoco/Economy/Currency.h, src/OpenLoco/GameCommands/GameCommands.cpp, src/OpenLoco/GameCommands/GameCommands.h, src/OpenLoco/GameState.cpp, src/OpenLoco/GameState.h, src/OpenLoco/Localisation/StringIds.h, src/OpenLoco/OpenLoco.cpp, src/OpenLoco/Windows/CompanyWindow.cpp
Automatic loan repayment #1284
=> Implement automatic loan repayment (#1284)

src/OpenLoco/Vehicles/CreateVehicle.cpp, src/OpenLoco/Vehicles/Orders.cpp, src/OpenLoco/Vehicles/Orders.h, src/OpenLoco/Vehicles/Vehicle.h, src/OpenLoco/Vehicles/VehicleBody.cpp, src/OpenLoco/Vehicles/VehicleHead.cpp, src/OpenLoco/Vehicles/VehicleManager.cpp
This further brings things in alignment with the coding style.
=> Vehicle Constants

src/OpenLoco/Map/Track/TrackData.cpp, src/OpenLoco/Map/Track/TrackData.h
This track data seems to be related to working out if a track can connect. Don't know much about it really.
=> Add connectFlags TrackData

CHANGELOG.md, src/OpenLoco/Vehicles/Vehicle.h, src/OpenLoco/Vehicles/VehicleHead.cpp, src/OpenLoco/Windows/Vehicle.cpp
Implements the feature requested in #1271.
I've added screenshots of my implementation in that issue.
=> adds cargo capacity to cargo window for vehicles

src/OpenLoco/GameCommands/Cheat.cpp, src/OpenLoco/GameCommands/RemoveWall.cpp, src/OpenLoco/Input/MouseInput.cpp, src/OpenLoco/Interop/Hooks.cpp, src/OpenLoco/OpenLoco.cpp, src/OpenLoco/Paint/PaintTile.cpp, src/OpenLoco/Station.h, src/OpenLoco/StationManager.cpp, src/OpenLoco/Town.cpp, src/OpenLoco/Town.h, src/OpenLoco/Ui/ViewportInteraction.cpp, src/OpenLoco/Vehicles/VehicleHead.cpp, src/OpenLoco/Vehicles/VehicleTail.cpp, src/OpenLoco/Windows/CompanyWindow.cpp, src/OpenLoco/Windows/IndustryWindow.cpp, src/OpenLoco/Windows/MapWindow.cpp, src/OpenLoco/Windows/News/News.cpp, src/OpenLoco/Windows/TownWindow.cpp, src/OpenLoco/Windows/Vehicle.cpp
Station.h had a using namespace that was bringing in all of Map into lots of files.
Also changed two constants to k
=> Remove using namespace from header

src/OpenLoco/CompanyManager.cpp, src/OpenLoco/Scenario.cpp, src/OpenLoco/Scenario.h, src/OpenLoco/Windows/CompanyWindow.cpp, src/OpenLoco/Windows/LandscapeGeneration.cpp, src/OpenLoco/Windows/PromptBrowseWindow.cpp, src/OpenLoco/Windows/ScenarioOptions.cpp
=> Apply coding style to scenario.h

CHANGELOG.md, CONTRIBUTORS.md, data/language/en-GB.yml, src/OpenLoco/GameCommands/GameCommands.cpp, src/OpenLoco/GameCommands/GameCommands.h, src/OpenLoco/GameCommands/SetGameSpeed.cpp, src/OpenLoco/Input/ShortcutManager.cpp, src/OpenLoco/Input/ShortcutManager.h, src/OpenLoco/Localisation/StringIds.h, src/OpenLoco/OpenLoco.cpp, src/OpenLoco/OpenLoco.h, src/OpenLoco/Title.cpp, src/OpenLoco/Windows/News/Common.cpp, src/OpenLoco/Windows/TimePanel.cpp, src/OpenLoco/openloco.vcxproj
PR for #43
* adds keyboard shortcuts for game speed
* adds game commands to set game speed
* refactors existing code to use the game speed command
=> adds game command for setting game speed, and adds keyboard shortcuts

CHANGELOG.md, src/OpenLoco/CommandLine.cpp, src/OpenLoco/CommandLine.h, src/OpenLoco/Input/Keyboard.cpp, src/OpenLoco/Intro.cpp, src/OpenLoco/OpenLoco.cpp
now that we have command line switches can readd intro outside of compile time flag.
=> Readd ability to run Intro

src/OpenLoco/Audio/Audio.cpp, src/OpenLoco/Audio/Audio.h, src/OpenLoco/Config.cpp, src/OpenLoco/Environment.cpp, src/OpenLoco/Environment.h, src/OpenLoco/Game.cpp, src/OpenLoco/Graphics/Gfx.cpp, src/OpenLoco/Interop/Hooks.cpp, src/OpenLoco/Localisation/LanguageFiles.cpp, src/OpenLoco/Localisation/Languages.cpp, src/OpenLoco/Objects/ObjectManager.cpp, src/OpenLoco/OpenLoco.cpp, src/OpenLoco/Scenario.cpp, src/OpenLoco/Title.cpp, src/OpenLoco/Tutorial.cpp
=> Apply coding style to environment.

src/OpenLoco/Input.h, src/OpenLoco/Input/MouseInput.cpp, src/OpenLoco/Ui.cpp
I started doing this using the exact same code as vanilla then thought there is no point can just use a queue and simplify this.
=> Implement enqueue/dequeue mouse button and refactor

src/OpenLoco/Entities/Misc.cpp
=> Fix minor divergence due to off by 1 in misc update

src/OpenLoco/Map/BuildingTile.cpp
This function updates a city's  population and company rating, amongst some unknown stuff.
I tested it and I think it works, more testing is probably needed.
Comments on improvements and changes are welcome.
=> Implement sub_497DC1

CHANGELOG.md, data/language/en-GB.yml, src/OpenLoco/Localisation/StringIds.h, src/OpenLoco/Windows/BuildVehicle.cpp
=> add vehicle obsolete date to build vehicles window

src/OpenLoco/Vehicles/Vehicle.cpp, src/OpenLoco/Vehicles/Vehicle.h, src/OpenLoco/Vehicles/Vehicle1.cpp, src/OpenLoco/Vehicles/Vehicle2.cpp, src/OpenLoco/Vehicles/VehicleBogie.cpp, src/OpenLoco/openloco.vcxproj
This is just to make things easier for implementing these last few updates.
=> Add stub functions for vehicle updates

src/OpenLoco/Company.h, src/OpenLoco/CompanyManager.cpp, src/OpenLoco/GameCommands/GameCommands.cpp, src/OpenLoco/GameCommands/GameCommands.h, src/OpenLoco/GameCommands/UpdateOwnerStatus.cpp, src/OpenLoco/openloco.vcxproj
This is my first PR in OpenLoco, and the first time I'm trying to reverse engineer a function here.
Any feedback and help making it better is appreciated.
Here are the things I noticed:
1. Do we need to check that the company returned from` CompanyManager` exists? It's not doing that in the original code, and it is happening in the calling function in `CompanyManager.cpp`.
2. I called the parameters to the function `param1` and `param2` because they can be either `position.x` and` position.y` or `-2` and `EntityId`. Is this OK?
=> Implement updateOwnerStatus game command

src/OpenLoco/Map/MapGenerator.cpp, src/OpenLoco/Map/MapGenerator.h, src/OpenLoco/Map/Tile.h, src/OpenLoco/Map/TileLoop.hpp, src/OpenLoco/Objects/LandObject.h, src/OpenLoco/S5/S5.h, src/OpenLoco/Windows/LandscapeGeneration.cpp
Works okay. I wanted to do this function as the basis for a simple game command that uses the randomStyleVariation function.
=> Map Gen Surface Styleing

src/OpenLoco/Audio/Audio.cpp, src/OpenLoco/Input/MouseInput.cpp, src/OpenLoco/Objects/VehicleObject.h, src/OpenLoco/Ui/ScrollView.cpp, src/OpenLoco/Vehicles/Orders.cpp, src/OpenLoco/Vehicles/VehicleHead.cpp, src/OpenLoco/Window.h, src/OpenLoco/Windows/BuildVehicle.cpp, src/OpenLoco/Windows/MusicSelection.cpp, src/OpenLoco/Windows/News/Common.cpp, src/OpenLoco/Windows/Options.cpp, src/OpenLoco/Windows/Vehicle.cpp, src/OpenLoco/Windows/VehicleList.cpp
I ran the default static-analysis tools in visual studio 2022 and fixed a few of the obvious bugs/implemented a few of the simple fixes.
=> Misc fixes from static analysis

src/OpenLoco/Graphics/Gfx.cpp, src/OpenLoco/Graphics/Gfx.h, src/OpenLoco/Objects/Object.h, src/OpenLoco/Objects/ObjectManager.cpp
=> Object load

src/OpenLoco/Ui/ScrollView.cpp
=> Fix scroll index crash

src/OpenLoco/Map/BuildingTile.cpp, src/OpenLoco/Map/SurfaceTile.cpp, src/OpenLoco/Map/Tile.h, src/OpenLoco/Map/TileManager.cpp, src/OpenLoco/Map/TileManager.h, src/OpenLoco/TownManager.cpp, src/OpenLoco/TownManager.h
This is a first draft for this function. I'm not sure what it does and if it should return something or not.
Here are a few remarks:
1. I'm not sure how to hook it into the original code. I added a `registerHooks()` function but I don't know how to call it from `registerHooks()` in `Hook.cpp`.
2. I don't know if this is the right place for it, although I guess it doesn't really matter until we figure out what it does.
3. I don't know how to test it because I'm not sure what it does.
I opened this PR as a draft so that I can get help in implementing and testing it correctly.
Help will be appreciated!
=> Implement sub_46902E

src/OpenLoco/Windows/Construction/ConstructionTab.cpp
There was tons of dead code in the vanilla versions of these functions making them really quite simple in the end.
=> Implement two construct functions

src/OpenLoco/Drawing/SoftwareDrawingEngine.cpp, src/OpenLoco/Drawing/SoftwareDrawingEngine.h, src/OpenLoco/Graphics/Gfx.cpp, src/OpenLoco/Graphics/ImageIds.h
Need to reorg the software drawing engine before this can be done nicely.
=> Implement updatePalette

src/OpenLoco/Audio/Channel.cpp, src/OpenLoco/Audio/Channel.h, src/OpenLoco/Audio/VehicleChannel.cpp, src/OpenLoco/Audio/VehicleChannel.h
=> Move sound attributes to base channel

CHANGELOG.md, src/OpenLoco/Ui/TextInput.cpp
=> Fix delete key not working in text input

CHANGELOG.md, src/OpenLoco/Localisation/StringManager.cpp
=> Fixes signed/unsigned formatting bug on total vehicle power

src/OpenLoco/Map/TileManager.cpp, src/OpenLoco/Map/TileManager.h, src/OpenLoco/Objects/BuildingObject.h
This is a sub function for the removeBuilding game command.
I'll probably implement the game command itself as well and then remove the hook I added here.
I tested this code by removing buildings in towns with the clear area tool.
=> Implement sub_42D8FF

src/OpenLoco/Company.cpp, src/OpenLoco/Company.h
These look to be part of a loop for placing down ai bought vehicles. tryPlaceVehicles is the actual function that does useful work looks to loop though looking for all vehicles of the company that are not placed and places them but only 1 at a time.
=> Implement companyThinkFunc2 functions

src/OpenLoco/Industry.cpp
Ummm not sure how i missed all this code...
#1332
=> Fix divergence from previous PR

src/OpenLoco/Company.cpp, src/OpenLoco/Company.h
Lots of unknowns here unfortunatly.
=> Implement a company think 1 function

CHANGELOG.md, src/OpenLoco/Windows/BuildVehicle.cpp
=> Sort vehicles correctly in build vehicle window

CHANGELOG.md, src/OpenLoco/Game.cpp, src/OpenLoco/Game.h, src/OpenLoco/Windows/ToolbarTopAlt.cpp
=> fixes landscapes not saving in scenario editor

src/OpenLoco/Audio/Audio.cpp
This needs a few little tweaks to the audio code before being ready. Interestingly it this function has a mistake in vanilla although im sure no one will have noticed but the volume code is a bit broken.
=> Ambient sound update

src/OpenLoco/Objects/CargoObject.cpp, src/OpenLoco/Objects/CargoObject.h, src/OpenLoco/Objects/CurrencyObject.cpp, src/OpenLoco/Objects/CurrencyObject.h, src/OpenLoco/Objects/InterfaceSkinObject.cpp, src/OpenLoco/Objects/InterfaceSkinObject.h, src/OpenLoco/Objects/LandObject.cpp, src/OpenLoco/Objects/LandObject.h, src/OpenLoco/Objects/LevelCrossingObject.cpp, src/OpenLoco/Objects/LevelCrossingObject.h, src/OpenLoco/Objects/Object.h, src/OpenLoco/Objects/ObjectManager.cpp, src/OpenLoco/Objects/ObjectManager.h, src/OpenLoco/Objects/RockObject.cpp, src/OpenLoco/Objects/RockObject.h, src/OpenLoco/Objects/SoundObject.cpp, src/OpenLoco/Objects/SoundObject.h, src/OpenLoco/Objects/SteamObject.cpp, src/OpenLoco/Objects/SteamObject.h, src/OpenLoco/Objects/TownNamesObject.cpp, src/OpenLoco/Objects/TownNamesObject.h, src/OpenLoco/Objects/TrainSignalObject.cpp, src/OpenLoco/Objects/TrainSignalObject.h, src/OpenLoco/Objects/WallObject.cpp, src/OpenLoco/Objects/WallObject.h, src/OpenLoco/Objects/WaterObject.cpp, src/OpenLoco/Objects/WaterObject.h, src/OpenLoco/openloco.vcxproj
~~Requires #1329 to really test.~~
=> Split up object functions

src/OpenLoco/Audio/Audio.cpp, src/OpenLoco/Audio/Audio.h, src/OpenLoco/Audio/VehicleChannel.cpp
This one is probably for after the OpenAL PR as its hard to verify without being able to hear the changes correctly.
=> Implement getVehicleSoundParameters

src/OpenLoco/Game.cpp, src/OpenLoco/OpenLoco.cpp, src/OpenLoco/S5/S5.cpp, src/OpenLoco/S5/S5.h, src/OpenLoco/Windows/ToolbarTop.cpp
=> Use constexpr for saveflags

src/OpenLoco/Map/Track/TrackData.cpp, src/OpenLoco/Map/Track/TrackData.h, src/OpenLoco/Windows/Construction/ConstructionTab.cpp
This removes the need to allocate the vectors on start as suggested by @ZehMatt
=> Switch to std::array's and stdx::span for trackData

src/OpenLoco/Intro.h, src/OpenLoco/Objects/TrainSignalObject.cpp
Fixes mistake from #1333 causing all sorts of issues.
=> Fix validate failing and entering loop. Fix invalid memory access

src/OpenLoco/Audio/VehicleChannel.cpp
https://github.com/OpenLoco/OpenLoco/pull/1352 made a mistake whilst doing refactoring...
=> Fix vehicle sound being -100dB

CHANGELOG.md, src/OpenLoco/S5/Limits.h, src/OpenLoco/Windows/LandscapeGeneration.cpp
=> Fix underflow in number of towns in scenario editor

src/OpenLoco/Graphics/Colour.cpp, src/OpenLoco/Graphics/Colour.h, src/OpenLoco/Ui/Dropdown.cpp, src/OpenLoco/Windows/Construction/Common.cpp, src/OpenLoco/Windows/Construction/Construction.h, src/OpenLoco/Windows/Construction/StationTab.cpp
Needed to use this for the paintStation code so thought it best to do this properly.
=> Extract out the translucent map

src/OpenLoco/Economy/Economy.cpp, src/OpenLoco/Map/Tile.cpp, src/OpenLoco/Objects/ObjectManager.cpp, src/OpenLoco/Objects/ObjectManager.h, src/OpenLoco/Windows/Options.cpp, src/OpenLoco/Windows/ScenarioSelect.cpp
Implemented this slightly differently to how it is in vanilla as it works out the id prior to trying to load anything.
=> Implement ObjectManager::load from header

CHANGELOG.md, src/OpenLoco/GameCommands/Cheat.cpp
=> Fix #1229 Reliability Cheat

src/OpenLoco/Map/TileManager.cpp
Double doh. Tried to free the wrong pointer... #1441
=> Actually fix removeElement

CHANGELOG.md, src/OpenLoco/Localisation/StringIds.h
Wrote a quick tool to verify StringIds.h and en-GB.yml, and it found these (now-fixed) issues
=> fix misc stringids

CHANGELOG.md, src/OpenLoco/Audio/Audio.cpp, src/OpenLoco/Company.cpp, src/OpenLoco/CompanyManager.cpp, src/OpenLoco/Entities/Entity.h, src/OpenLoco/Entities/EntityManager.h, src/OpenLoco/Entities/EntityTweener.cpp, src/OpenLoco/Entities/Misc.h, src/OpenLoco/GameCommands/Cheat.cpp, src/OpenLoco/Input/Keyboard.cpp, src/OpenLoco/Input/MouseInput.cpp, src/OpenLoco/MessageManager.cpp, src/OpenLoco/Paint/PaintEntity.cpp, src/OpenLoco/Ui/ViewportInteraction.cpp, src/OpenLoco/Vehicles/CreateVehicle.cpp, src/OpenLoco/Vehicles/RenameVehicle.cpp, src/OpenLoco/Vehicles/Routing.cpp, src/OpenLoco/Vehicles/Vehicle.cpp, src/OpenLoco/Vehicles/Vehicle.h, src/OpenLoco/Vehicles/VehicleHead.cpp, src/OpenLoco/Windows/BuildVehicle.cpp, src/OpenLoco/Windows/CompanyWindow.cpp, src/OpenLoco/Windows/MapWindow.cpp, src/OpenLoco/Windows/News/News.cpp, src/OpenLoco/Windows/Vehicle.cpp, src/OpenLoco/Windows/VehicleList.cpp
This will fix https://github.com/OpenLoco/OpenLoco/issues/1279 but id still like to make it that audio is correctly destroyed in a vehicle sell.
=> Change entitymanager to check types more

src/OpenLoco/Vehicles/VehicleBogie.cpp
URgh made too many mistakes in #1368
=> Fix bogies being back to front

src/OpenLoco/Map/TileManager.cpp
This has been wrong for a while. Looks like i copy pasted a broken bit of code from OpenRCT2 that has since been fixed. I originally put this change in #1461 but its not really related to create tree and as it is so extensively used would like some dedicated testing.
=> Fix height calc

src/OpenLoco/Graphics/Colour.h, src/OpenLoco/Widget.cpp, src/OpenLoco/Widget.h, src/OpenLoco/Windows/CompanyWindow.cpp, src/OpenLoco/Windows/TerraForm.cpp, src/OpenLoco/Windows/TownList.cpp, src/OpenLoco/Windows/Vehicle.cpp
=> Label reused imageId flag

src/OpenLoco/Graphics/Colour.h, src/OpenLoco/Objects/CargoObject.h, src/OpenLoco/Objects/TrainStationObject.cpp, src/OpenLoco/Objects/TrainStationObject.h, src/OpenLoco/Paint/Paint.cpp, src/OpenLoco/Paint/Paint.h, src/OpenLoco/Paint/PaintStation.cpp, src/OpenLoco/Paint/PaintStation.h, src/OpenLoco/Paint/PaintTile.cpp, src/OpenLoco/Station.cpp, src/OpenLoco/Station.h, src/OpenLoco/openloco.vcxproj
=> Paint Station

src/OpenLoco/Graphics/Gfx.cpp, src/OpenLoco/Graphics/Gfx.h, src/OpenLoco/Input/MouseInput.cpp, src/OpenLoco/Paint/Paint.cpp, src/OpenLoco/Paint/Paint.h, src/OpenLoco/Paint/PaintMiscEntity.cpp, src/OpenLoco/Paint/PaintSignal.cpp, src/OpenLoco/Paint/PaintStation.cpp, src/OpenLoco/Paint/PaintTree.cpp, src/OpenLoco/Ui.h, src/OpenLoco/Ui/ViewportInteraction.cpp, src/OpenLoco/ViewportManager.cpp
This is basically copying over work from OpenRCT2. 
https://github.com/OpenRCT2/OpenRCT2/blob/2cd075f6e701669bb399350016be1d5c090164e2/src/openrct2/paint/Paint.cpp#L936
=> Implement various addToPlotList functions

src/OpenLoco/Audio/Audio.cpp, src/OpenLoco/Audio/Audio.h, src/OpenLoco/Audio/VehicleChannel.h, src/OpenLoco/Ui/WindowManager.h, src/OpenLoco/Vehicles/CreateVehicle.cpp, src/OpenLoco/Vehicles/Vehicle.h, src/OpenLoco/Vehicles/VehicleHead.cpp, src/OpenLoco/Vehicles/VehicleManager.cpp, src/OpenLoco/Vehicles/VehicleManager.h, src/OpenLoco/Windows/VehicleList.cpp
This is part of the overall game command for vehicle sell and will replace the vehicleHead::removeDanglingTrain stub function.
=> Implement deleteTrain

CHANGELOG.md, data/language/en-GB.yml, src/OpenLoco/Config.cpp, src/OpenLoco/Config.h, src/OpenLoco/Input/MouseInput.cpp, src/OpenLoco/Localisation/StringIds.h, src/OpenLoco/Windows/Options.cpp
=> Add option to invert right-mouse view panning

src/OpenLoco/GameCommands/GameCommands.cpp, src/OpenLoco/GameCommands/GameCommands.h, src/OpenLoco/GameCommands/RemoveBuilding.cpp, src/OpenLoco/Localisation/StringIds.h, src/OpenLoco/Map/Tile.h, src/OpenLoco/Map/TileManager.cpp, src/OpenLoco/Objects/BuildingObject.h, src/OpenLoco/openloco.vcxproj
This is a first draft of the removeBuilding game command.
It doesn't seem to work correctly right now.
The original code used a lot of globals that are only being used in this function, so I removed them in this implementation.
=> Implement removeBuilding game command

src/OpenLoco/GameCommands/CreateTree.cpp, src/OpenLoco/GameCommands/GameCommands.cpp, src/OpenLoco/GameCommands/GameCommands.h, src/OpenLoco/Localisation/StringIds.h, src/OpenLoco/Map/QuarterTile.h, src/OpenLoco/Map/Tile.h, src/OpenLoco/Map/TileManager.cpp, src/OpenLoco/Map/TileManager.h, src/OpenLoco/Objects/TreeObject.h, src/OpenLoco/Scenario.cpp, src/OpenLoco/Scenario.h, src/OpenLoco/Ui/WindowManager.h, src/OpenLoco/Windows/TerraForm.cpp, src/OpenLoco/openloco.vcxproj
This is the first create game command so quite a bit of unrelated work required to get the mechanisms ready from TileManager.
=> GameCommand::createTree

src/OpenLoco/CompanyManager.cpp, src/OpenLoco/CompanyManager.h, src/OpenLoco/GameCommands/ChangeLoan.cpp, src/OpenLoco/Windows/ScenarioOptions.cpp
remove globals for 
* max loan
* starting loan
* competing companies,
* competitor delay
=> remove globals for more company things

src/OpenLoco/Vehicles/Routing.cpp, src/OpenLoco/Vehicles/Vehicle.h, src/OpenLoco/Vehicles/VehicleHead.cpp
Reverts OpenLoco/OpenLoco#1311
I merged this in but it fails to build, the branch needs to be rebased
=> Revert "Routing2: Finding clear signals"

src/OpenLoco/OpenLoco.cpp, src/OpenLoco/S5/S5.cpp, src/OpenLoco/Scenario.cpp, src/OpenLoco/Scenario.h, src/OpenLoco/ScenarioManager.cpp, src/OpenLoco/ScenarioManager.h
* `scenarioTicks2`
* also remove references I missed in #1428 to `scenarioTicks`
=> reduce-locoglobals - scenarioTicks2

src/OpenLoco/Vehicles/Routing.cpp, src/OpenLoco/Vehicles/Vehicle.h, src/OpenLoco/Vehicles/VehicleHead.cpp
#1311 had a rebase issue this resolves that.
=> Routing2: Finding clear signals (fixed)

src/OpenLoco/Graphics/Gfx.cpp, src/OpenLoco/Graphics/Gfx.h, src/OpenLoco/Interop/Hooks.cpp, src/OpenLoco/OpenLoco.cpp
Deleting some dead code. Implementing some simple setup funcs.
=> Cleanup OpenLoco.cpp

src/OpenLoco/Objects/RoadObject.h, src/OpenLoco/Objects/TrackObject.h, src/OpenLoco/Speed.hpp, src/OpenLoco/Vehicles/Vehicle.h, src/OpenLoco/Vehicles/Vehicle2.cpp, src/OpenLoco/Vehicles/VehicleBogie.cpp
Complete. Doesn't desync on lets play save but since it has a good bit of rack rail and manual control code could do with testing.
=> Vehicle update: Vehicle2

src/OpenLoco/Paint/Paint.cpp, src/OpenLoco/Paint/Paint.h, src/OpenLoco/Ui/ViewportInteraction.cpp
Just a small cleanup. I was going to make a bunch of ImageId changes but it ended up being pretty huge so will do that as a separate task.
=> Refactor to use types and cleanup RCT2 structs

src/OpenLoco/Map/QuarterTile.h, src/OpenLoco/Map/Track/TrackData.cpp, src/OpenLoco/Map/Track/TrackData.h
This names a few unknowns and makes things easier to understand
Needed for #1480 
I think i've done it correctly but should probably write a script to check.
=> Use quarter tile for track data

CHANGELOG.md, src/OpenLoco/Scenario.cpp
Mistake made during refactor #1487
=> Fix time limit for scenarios being set incorrectly

src/OpenLoco/Graphics/Gfx.cpp, src/OpenLoco/Graphics/Gfx.h, src/OpenLoco/Interop/Hooks.cpp
Hopefully mostly a case of lifting code from OpenRCT2.
=> Start implementing drawImage

src/OpenLoco/Entities/Misc.cpp, src/OpenLoco/Graphics/Gfx.cpp, src/OpenLoco/Graphics/Gfx.h, src/OpenLoco/Ui/Dropdown.cpp, src/OpenLoco/Ui/TextInput.cpp, src/OpenLoco/Widget.cpp, src/OpenLoco/Windows/CompanyFaceSelection.cpp, src/OpenLoco/Windows/Construction/Construction.h, src/OpenLoco/Windows/Error.cpp, src/OpenLoco/Windows/MapWindow.cpp, src/OpenLoco/Windows/News/News.h, src/OpenLoco/Windows/ObjectSelectionWindow.cpp, src/OpenLoco/Windows/TextInputWindow.cpp, src/OpenLoco/Windows/ToolTip.cpp
an existing method was already in Gfx.h/cpp to get it
=> reduce locoglobals - move 0x0112C876 (currentFontSpriteBase) into Gfx.h

src/OpenLoco/Graphics/Gfx.cpp, src/OpenLoco/Graphics/Gfx.h, src/OpenLoco/Paint/Paint.cpp, src/OpenLoco/Paint/Paint.h, src/OpenLoco/Paint/PaintMiscEntity.cpp, src/OpenLoco/Paint/PaintSignal.cpp, src/OpenLoco/Paint/PaintStation.cpp, src/OpenLoco/Paint/PaintTile.cpp, src/OpenLoco/Paint/PaintTree.cpp, src/OpenLoco/Paint/PaintVehicle.cpp
Uses the ImageId struct to enforce some safety #1496 should be merged first.
=> Paint ImageId Refactor

src/OpenLoco/Objects/BuildingObject.cpp, src/OpenLoco/Objects/BuildingObject.h, src/OpenLoco/Objects/ClimateObject.cpp, src/OpenLoco/Objects/ClimateObject.h, src/OpenLoco/Objects/CompetitorObject.cpp, src/OpenLoco/Objects/CompetitorObject.h, src/OpenLoco/Objects/HillShapesObject.cpp, src/OpenLoco/Objects/HillShapesObject.h, src/OpenLoco/Objects/IndustryObject.cpp, src/OpenLoco/Objects/IndustryObject.h, src/OpenLoco/Objects/ObjectManager.cpp, src/OpenLoco/Objects/RegionObject.cpp, src/OpenLoco/Objects/RegionObject.h, src/OpenLoco/Objects/ScaffoldingObject.cpp, src/OpenLoco/Objects/ScaffoldingObject.h, src/OpenLoco/Objects/ScenarioTextObject.cpp, src/OpenLoco/Objects/ScenarioTextObject.h, src/OpenLoco/Objects/SnowObject.cpp, src/OpenLoco/Objects/SnowObject.h, src/OpenLoco/Objects/TreeObject.cpp, src/OpenLoco/Objects/TreeObject.h, src/OpenLoco/openloco.vcxproj
Implements the remaining validate, unload object functions.
=> Object Functions 3: Last ones

src/OpenLoco/Map/Tile.h, src/OpenLoco/Map/Track/Track.cpp, src/OpenLoco/Paint/Paint.cpp, src/OpenLoco/Paint/Paint.h, src/OpenLoco/Windows/Construction/Construction.h, src/OpenLoco/Windows/Construction/ConstructionTab.cpp, src/OpenLoco/Windows/Construction/OverheadTab.cpp
I need this function implemented before the track paint function can be implemented. It is mostly the same as the OpenRCT2 equivalent. 
WiP as some of the backend hasn't been done yet.
=> Implement most of Construction draw track preview

src/OpenLoco/Map/MapGenerator.cpp, src/OpenLoco/Map/TileManager.cpp, src/OpenLoco/Map/TileManager.h, src/OpenLoco/Map/Tree.cpp, src/OpenLoco/Map/Tree.h
=> MapGen trees

src/OpenLoco/GameCommands/GameCommands.cpp, src/OpenLoco/Vehicles/CreateVehicle.cpp, src/OpenLoco/Vehicles/Vehicle.h, src/OpenLoco/Vehicles/VehicleHead.cpp, src/OpenLoco/Vehicles/VehicleManager.cpp, src/OpenLoco/Vehicles/VehicleManager.h, src/OpenLoco/Vehicles/VehicleSell.cpp, src/OpenLoco/openloco.vcxproj
=> Vehicle sell gamecommand

data/language/en-US.yml
=> Update en-US.yml with color

src/OpenLoco/Graphics/Gfx.cpp, src/OpenLoco/Graphics/Gfx.h, src/OpenLoco/Localisation/StringManager.h, src/OpenLoco/Objects/VehicleObject.cpp
Fixes https://github.com/OpenLoco/OpenLoco/issues/1557 and a few other issues.
=> Wrap string

.github/workflows/ci.yml
https://github.com/OpenLoco/openloco-docker-build/pull/8
=> Update build docker images to v3

src/OpenLoco/GameCommands/GameCommands.h, src/OpenLoco/Industry.cpp, src/OpenLoco/Industry.h, src/OpenLoco/IndustryManager.cpp, src/OpenLoco/IndustryManager.h, src/OpenLoco/Objects/IndustryObject.h, src/OpenLoco/Scenario.h, src/OpenLoco/Vehicles/VehicleHead.cpp, src/OpenLoco/Windows/IndustryList.cpp, src/OpenLoco/Windows/IndustryWindow.cpp, src/OpenLoco/Windows/LandscapeGeneration.cpp
=> Implement Industry Update Monthly

CHANGELOG.md, src/OpenLoco/Audio/Audio.cpp
=> inintialise bgm audio channel volume when playing a song (#729)

src/OpenLoco/GameCommands/GameCommands.cpp, src/OpenLoco/GameCommands/GameCommands.h, src/OpenLoco/GameCommands/RenameCompanyName.cpp, src/OpenLoco/GameCommands/RenameCompanyOwner.cpp, src/OpenLoco/openloco.vcxproj
This implements both the `changeCompanyName` and `changeCompanyOwnerName` game commands.
=> Implement the changeCompanyName game command

src/OpenLoco/GameCommands/GameCommands.h, src/OpenLoco/IndustryManager.cpp, src/OpenLoco/Objects/IndustryObject.cpp, src/OpenLoco/Objects/IndustryObject.h
=> Industry manager functions 2

src/OpenLoco/GameCommands/RemoveBuilding.cpp, src/OpenLoco/IndustryManager.cpp, src/OpenLoco/Map/BuildingTile.cpp, src/OpenLoco/Map/TileManager.cpp, src/OpenLoco/Map/TileManager.h, src/OpenLoco/Objects/IndustryObject.h, src/OpenLoco/TownManager.cpp, src/OpenLoco/TownManager.h, src/OpenLoco/Windows/IndustryList.cpp
=> Industry Manager Functions 3

.github/workflows/ci.yml, .gitignore, CMakeLists.txt, CMakeSettings.json, vcpkg.json
I dont really know what I'm doing but this look to compile on the CI. One thing to note is its not caching anything so wastes lots of time on vcpkg stuff.
=> Add Windows CMake CI

CMakeLists.txt, README.md
First of all cleaning up the compile flags and improving the ide experience.
=> Start improving CmakeLists

src/OpenLoco/Industry.cpp, src/OpenLoco/Industry.h, src/OpenLoco/Interop/Hooks.cpp, src/OpenLoco/Map/Tile.h, src/OpenLoco/Map/TileManager.cpp, src/OpenLoco/Map/TileManager.h, src/OpenLoco/Objects/IndustryObject.cpp, src/OpenLoco/Objects/IndustryObject.h
Ready for review. I hooked this function so it would be spammed a lot and i am getting no divergence on the singular industry save.
=> Implement Industry::expandGrounds

src/OpenLoco/Drawing/DrawSprite.h, src/OpenLoco/Drawing/DrawSpriteHelper.hpp, src/OpenLoco/Graphics/Colour.cpp, src/OpenLoco/Graphics/Colour.h, src/OpenLoco/Graphics/Gfx.cpp, src/OpenLoco/Graphics/Gfx.h, src/OpenLoco/Graphics/PaletteMap.cpp, src/OpenLoco/Graphics/PaletteMap.h, src/OpenLoco/Paint/Paint.cpp
PaletteMap has been a bit over-engineered, PaletteMapView is now an alias using stdx::span and PaletteMapBuffer is an alias for std::array which now clearly separates buffer and view.
=> PaletteMap cleanup

src/OpenLoco/Objects/ObjectIndex.cpp, src/OpenLoco/Objects/ObjectManager.cpp, src/OpenLoco/Objects/ObjectManager.h, src/OpenLoco/Scenario.cpp, src/OpenLoco/Windows/CompanyFaceSelection.cpp, src/OpenLoco/Windows/ObjectSelectionWindow.cpp
=> Rename free/get scenarioText

src/OpenLoco/Objects/IndustryObject.cpp, src/OpenLoco/Objects/IndustryObject.h
Found this little func hadn't been done yet.
=> IndustryObject::drawIndustry

src/OpenLoco/GameCommands/ChangeLandMaterial.cpp, src/OpenLoco/GameCommands/GameCommands.cpp, src/OpenLoco/GameCommands/GameCommands.h, src/OpenLoco/GameCommands/RemoveBuilding.cpp, src/OpenLoco/GameCommands/RemoveIndustry.cpp, src/OpenLoco/Industry.cpp, src/OpenLoco/Industry.h, src/OpenLoco/Map/MapGenerator.cpp, src/OpenLoco/Map/SurfaceTile.cpp, src/OpenLoco/Map/Tile.cpp, src/OpenLoco/Map/Tile.h, src/OpenLoco/Objects/IndustryObject.h, src/OpenLoco/Paint/Paint.cpp, src/OpenLoco/Ui/WindowManager.h, src/OpenLoco/Vehicles/VehicleHead.cpp, src/OpenLoco/Windows/IndustryList.cpp, src/OpenLoco/Windows/IndustryWindow.cpp, src/OpenLoco/openloco.vcxproj
=> RemoveIndustry Game Command

src/OpenLoco/Input/Keyboard.cpp, src/OpenLoco/Input/MouseInput.cpp, src/OpenLoco/Localisation/LanguageFiles.cpp, src/OpenLoco/Localisation/StringManager.cpp
=> Minor codestyle enforcement

src/OpenLoco/GameCommands/RemoveIndustry.cpp
Missed a check when revoke land ownership
=> Fix #1703. Remove industry accidentally removing unrelated fences

src/OpenLoco/Graphics/Colour.cpp, src/OpenLoco/Graphics/Colour.h, src/OpenLoco/Map/IndustryElement.h, src/OpenLoco/Map/Tile.cpp, src/OpenLoco/Objects/BuildingObject.h, src/OpenLoco/Objects/IndustryObject.cpp, src/OpenLoco/Objects/IndustryObject.h, src/OpenLoco/Objects/ScaffoldingObject.cpp, src/OpenLoco/Objects/ScaffoldingObject.h, src/OpenLoco/Paint/Paint.h, src/OpenLoco/Paint/PaintIndustry.cpp, src/OpenLoco/Paint/PaintIndustry.h, src/OpenLoco/Paint/PaintTile.cpp, src/OpenLoco/openloco.vcxproj
Complete.
Looks like paintBuilding is very similar to this as well so might do that one immediately afterwards.
=> Implement Paint Industry

src/OpenLoco/Graphics/Colour.cpp, src/OpenLoco/Graphics/Colour.h, src/OpenLoco/Graphics/ImageIds.h, src/OpenLoco/Input.h, src/OpenLoco/Input/MouseInput.cpp, src/OpenLoco/LabelFrame.h, src/OpenLoco/Paint/Paint.cpp, src/OpenLoco/Paint/Paint.h, src/OpenLoco/Paint/PaintSignal.cpp, src/OpenLoco/Paint/PaintTrack.cpp, src/OpenLoco/Ui/ViewportInteraction.cpp, src/OpenLoco/Vehicles/VehicleManager.cpp, src/OpenLoco/Vehicles/VehicleManager.h, src/OpenLoco/Viewport.cpp, src/OpenLoco/Widget.cpp, src/OpenLoco/Windows/Construction/ConstructionTab.cpp, src/OpenLoco/Windows/Vehicle.cpp
=> Implement Viewport Paint

CHANGELOG.md, CMakePresets.json, src/OpenLoco/src/Environment.cpp
Added intellisense hint for WSL2
=> Fix #1711. Create an initial user folder if it does not exist

src/OpenLoco/src/EditorController.cpp, src/OpenLoco/src/Localisation/StringIds.h, src/OpenLoco/src/Objects/ObjectManager.cpp, src/OpenLoco/src/Ui/WindowManager.cpp, src/OpenLoco/src/Ui/WindowManager.h, src/OpenLoco/src/Windows/ObjectSelectionWindow.cpp, src/OpenLoco/src/Windows/ToolTip.cpp, src/OpenLoco/src/Windows/ToolbarTopAlt.cpp
A selection of small functions in the end.
=> Implement WindowManager::updateDaily and ObjectManager::reloadAll

CHANGELOG.md, src/OpenLoco/src/Objects/ObjectIndex.cpp, src/OpenLoco/src/Objects/ObjectIndex.h, src/OpenLoco/src/Objects/ObjectManager.cpp, src/OpenLoco/src/Objects/ObjectManager.h, src/OpenLoco/src/OpenLoco.cpp, src/OpenLoco/src/Windows/CompanyFaceSelection.cpp, src/OpenLoco/src/Windows/ObjectSelectionWindow.cpp
Split off from #1719. Will rebase after that is merged.
=> Implement Temporary Object Loading/freeing. Cleanup/fix object loading.

src/OpenLoco/src/Graphics/Gfx.cpp, src/OpenLoco/src/Graphics/Gfx.h, src/OpenLoco/src/Paint/Paint.cpp, src/OpenLoco/src/Ui/WindowManager.cpp, src/OpenLoco/src/Ui/WindowManager.h
Very similar to the openrct2 equivalent except interestingly this handles zooms other than zero. And messes around setting colours through the window colours. https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/paint/Paint.cpp#L912
=> Implement paint string structs

src/OpenLoco/src/CommandLine.cpp, src/OpenLoco/src/EditorController.cpp, src/OpenLoco/src/Game.cpp, src/OpenLoco/src/Network/NetworkClient.cpp, src/OpenLoco/src/Network/NetworkServer.cpp, src/OpenLoco/src/OpenLoco.cpp, src/OpenLoco/src/S5/S5.cpp, src/OpenLoco/src/S5/S5.h, src/OpenLoco/src/Scenario.cpp, src/OpenLoco/src/Title.cpp, src/OpenLoco/src/Windows/PromptBrowseWindow.cpp, src/OpenLoco/src/Windows/ToolbarTop.cpp
=> Implement readSaveDetails, readScenarioOptions

thirdparty/CMakeLists.txt
Co-authored-by: duncanspumpkin <duncans_pumpkin@hotmail.co.uk>
=> CMake: split up thirdparty content fetch block

CHANGELOG.md, src/OpenLoco/src/Objects/ObjectManager.cpp
Ummm not sure when i broke this ...
=> Fix object install installing to wrong folder

src/OpenLoco/src/Windows/TownList.cpp
I don't think this is the source of #1730 but its a mistake
=> Fix misc building last game option

src/OpenLoco/src/Company.cpp, src/OpenLoco/src/Company.h, src/OpenLoco/src/ScenarioManager.cpp, src/OpenLoco/src/ScenarioManager.h
=> Implement Company::updateDailyPlayer

src/OpenLoco/src/Scenario.cpp, src/OpenLoco/src/Scenario.h, src/OpenLoco/src/ScenarioManager.cpp, src/OpenLoco/src/Windows/CompanyWindow.cpp, src/OpenLoco/src/Windows/ScenarioOptions.cpp
=> Implement loading and creating the scenario index

src/OpenLoco/src/ScenarioManager.cpp
=> Implement saveNewScore

src/OpenLoco/src/Objects/IndustryObject.cpp, src/OpenLoco/src/Objects/IndustryObject.h, src/OpenLoco/src/Objects/InterfaceSkinObject.cpp
=> Implement IndustryObject::load

src/OpenLoco/src/Objects/ScenarioTextObject.cpp, src/OpenLoco/src/Objects/SnowObject.cpp, src/OpenLoco/src/Objects/SnowObject.h
Surprisingly simple object load functions for these objects.
=> Implement SnowObject::load, ScenarioTextObject::load

src/OpenLoco/src/Audio/Audio.cpp, src/OpenLoco/src/Audio/Audio.h, src/OpenLoco/src/Objects/LandObject.cpp, src/OpenLoco/src/Objects/SoundObject.cpp, src/OpenLoco/src/Objects/SoundObject.h
Its all ready to go but i might add another few obj loads in this pr.
=> Implement Sound Object Load

CHANGELOG.md, src/OpenLoco/src/Graphics/Gfx.cpp
(Pushing this prematurely because I'm unable to build/run locally at the moment)
Fixes #528
=> Keep zoomed image relations when fixing Steam G1

src/OpenLoco/src/CompanyManager.cpp, src/OpenLoco/src/Config.h, src/OpenLoco/src/EditorController.cpp, src/OpenLoco/src/Game.cpp, src/OpenLoco/src/Localisation/StringManager.cpp, src/OpenLoco/src/Ui/WindowManager.cpp, src/OpenLoco/src/ViewportManager.cpp, src/OpenLoco/src/Windows/CompanyWindow.cpp, src/OpenLoco/src/Windows/IndustryWindow.cpp, src/OpenLoco/src/Windows/Options.cpp, src/OpenLoco/src/Windows/StationWindow.cpp, src/OpenLoco/src/Windows/ToolbarTop.cpp, src/OpenLoco/src/Windows/TownWindow.cpp, src/OpenLoco/src/Windows/Vehicle.cpp
Implemented enum flags for `Config::Flags` as part of #1757.
=> Config enum flags

src/OpenLoco/src/Windows/Options.cpp
Apologies for any protocols I am breaking here. I just learned about this game this week and I've never worked on an open source project. I realized that the edge scrolling enable/disable wasn't working and I think I fixed it with this change.
=> Fix to enable/disable edge scrolling

src/OpenLoco/src/Paint/Paint.cpp, src/OpenLoco/src/Paint/Paint.h, src/OpenLoco/src/Ui.h, src/OpenLoco/src/Ui/ViewportInteraction.cpp, src/OpenLoco/src/ViewportManager.cpp, src/OpenLoco/src/Window.cpp
Addresses #1757 
Implemented enum flags for `InteractionItemFlags`.
=> InteractionItemFlags enum flags

src/OpenLoco/src/Drawing/DrawingContext.h, src/OpenLoco/src/Drawing/SoftwareDrawingContext.cpp, src/OpenLoco/src/Drawing/SoftwareDrawingContext.h, src/OpenLoco/src/Windows/IndustryWindow.cpp, src/OpenLoco/src/Windows/MapWindow.cpp, src/OpenLoco/src/Windows/TownWindow.cpp
Heavily based off of the OpenRCT2 version
Not tested or verified yet.
=> Implement lineDraw

src/OpenLoco/src/Message.h
Addresses #1757 
Implemented enum flags for `MessageTypeFlags`.
=> Added MessageType enum flags

src/OpenLoco/src/CompanyManager.cpp, src/OpenLoco/src/EditorController.cpp, src/OpenLoco/src/GameCommands/RemoveBuilding.cpp, src/OpenLoco/src/IndustryManager.cpp, src/OpenLoco/src/Map/BuildingElement.cpp, src/OpenLoco/src/Map/TileManager.cpp, src/OpenLoco/src/Objects/BuildingObject.h, src/OpenLoco/src/Station.cpp, src/OpenLoco/src/Ui/ViewportInteraction.cpp, src/OpenLoco/src/Windows/TownList.cpp
=> Enum - BuildingObjectFlags conversion

src/OpenLoco/src/StationManager.cpp, src/OpenLoco/src/Town.h, src/OpenLoco/src/Windows/TownList.cpp
Converted `TownFlags` to enum flags for #1757
=> Added town enum flags

src/OpenLoco/src/Map/Track/TrackData.cpp, src/OpenLoco/src/Map/Track/TrackData.h, src/OpenLoco/src/Windows/Construction/ConstructionTab.cpp
=> Enum - PreviewTrackFlags conversion

src/OpenLoco/src/Industry.cpp, src/OpenLoco/src/IndustryManager.cpp, src/OpenLoco/src/IndustryManager.h, src/OpenLoco/src/Objects/IndustryObject.cpp, src/OpenLoco/src/Objects/IndustryObject.h, src/OpenLoco/src/Paint/PaintIndustry.cpp, src/OpenLoco/src/Windows/Construction/StationTab.cpp, src/OpenLoco/src/Windows/IndustryList.cpp
=> Enum - IndustryObjectFlags conversion

src/OpenLoco/src/GameCommands/CreateTree.cpp, src/OpenLoco/src/Map/TileManager.cpp, src/OpenLoco/src/Map/Tree.cpp, src/OpenLoco/src/Objects/LandObject.cpp, src/OpenLoco/src/Objects/LandObject.h
=> Enum - LandObjectFlags conversion

CHANGELOG.md, src/OpenLoco/src/Ui.cpp
=> Fix #1798: Memory leak when resizing the window

src/OpenLoco/src/Objects/RoadStationObject.cpp, src/OpenLoco/src/Objects/RoadStationObject.h, src/OpenLoco/src/Station.cpp, src/OpenLoco/src/Vehicles/VehicleHead.cpp, src/OpenLoco/src/Windows/Construction/Common.cpp, src/OpenLoco/src/Windows/Construction/StationTab.cpp
=> Enum - RoadStationFlags conversion

src/OpenLoco/src/Entities/Misc.cpp, src/OpenLoco/src/Objects/SteamObject.h, src/OpenLoco/src/Paint/PaintMiscEntity.cpp, src/OpenLoco/src/Vehicles/VehicleBody.cpp
=> Enum - SteamObjectFlags conversion

src/OpenLoco/src/Company.cpp, src/OpenLoco/src/Objects/TrackObject.cpp, src/OpenLoco/src/Objects/TrackObject.h, src/OpenLoco/src/Vehicles/Vehicle2.cpp, src/OpenLoco/src/Windows/BuildVehicle.cpp, src/OpenLoco/src/Windows/Construction/Common.cpp, src/OpenLoco/src/Windows/Construction/ConstructionTab.cpp
=> enum - TrackObject flags

src/OpenLoco/src/Company.cpp, src/OpenLoco/src/Input/MouseInput.cpp, src/OpenLoco/src/Objects/RoadObject.cpp, src/OpenLoco/src/Objects/RoadObject.h, src/OpenLoco/src/Vehicles/Vehicle2.cpp, src/OpenLoco/src/Vehicles/VehicleHead.cpp, src/OpenLoco/src/Windows/BuildVehicle.cpp, src/OpenLoco/src/Windows/Construction/Common.cpp, src/OpenLoco/src/Windows/Construction/ConstructionTab.cpp
=> Enum - RoadObject conversion

src/OpenLoco/src/Entities/Misc.cpp, src/OpenLoco/src/Objects/TrainSignalObject.h, src/OpenLoco/src/Objects/TrainStationObject.cpp, src/OpenLoco/src/Objects/TrainStationObject.h, src/OpenLoco/src/Paint/PaintSignal.cpp, src/OpenLoco/src/Paint/PaintStation.cpp, src/OpenLoco/src/Windows/Construction/Common.cpp, src/OpenLoco/src/Windows/Construction/StationTab.cpp
=> Enum - TrainStationFlags and TrainSignalFlags conversion

src/OpenLoco/src/Audio/Audio.cpp, src/OpenLoco/src/GameCommands/CreateTree.cpp, src/OpenLoco/src/Map/Tree.cpp, src/OpenLoco/src/Objects/TreeObject.cpp, src/OpenLoco/src/Objects/TreeObject.h, src/OpenLoco/src/Paint/PaintTree.cpp
=> Enum - TreeObjectFlags conversion

src/OpenLoco/src/Objects/VehicleObject.cpp, src/OpenLoco/src/Objects/VehicleObject.h, src/OpenLoco/src/Paint/PaintVehicle.cpp, src/OpenLoco/src/Vehicles/VehicleBody.cpp
=> Enum - BogieSpriteFlags and  conversion BodySpriteFlags

src/Math/CMakeLists.txt, src/Math/src/Trigonometry.cpp, src/Math/tests/TrigonometryTests.cpp, src/Math/tests/VectorTests.cpp
Fix mistake in trig function
Note: The high precision trig functions are only used for tree cluster placement so not something people will notice isn't quite right.
=> Add basic math tests

src/OpenLoco/src/Objects/VehicleObject.cpp, src/OpenLoco/src/Objects/VehicleObject.h, src/OpenLoco/src/Vehicles/CreateVehicle.cpp, src/OpenLoco/src/Vehicles/Vehicle.cpp, src/OpenLoco/src/Vehicles/Vehicle2.cpp, src/OpenLoco/src/Vehicles/VehicleHead.cpp, src/OpenLoco/src/Windows/BuildVehicle.cpp, src/OpenLoco/src/Windows/Construction/Common.cpp, src/OpenLoco/src/Windows/Vehicle.cpp
=> Enum - VehicleObjectFlags conversion

src/OpenLoco/src/Objects/CompetitorObject.cpp
Not much to say about this one. Scope for a future refactor though to avoid the globals.
=> Implement competitor object load

src/OpenLoco/src/Paint/Paint.h, src/OpenLoco/src/Paint/PaintSignal.cpp, src/OpenLoco/src/Paint/PaintTrack.cpp, src/OpenLoco/src/Ui/Screenshot.cpp, src/OpenLoco/src/Ui/ViewportInteraction.cpp, src/OpenLoco/src/Ui/WindowManager.cpp, src/OpenLoco/src/Viewport.cpp, src/OpenLoco/src/Viewport.hpp, src/OpenLoco/src/ViewportManager.cpp, src/OpenLoco/src/Window.cpp, src/OpenLoco/src/Windows/CompanyWindow.cpp, src/OpenLoco/src/Windows/Construction/Common.cpp, src/OpenLoco/src/Windows/Construction/Construction.h, src/OpenLoco/src/Windows/Construction/ConstructionTab.cpp, src/OpenLoco/src/Windows/IndustryWindow.cpp, src/OpenLoco/src/Windows/StationWindow.cpp, src/OpenLoco/src/Windows/ToolbarTopCommon.cpp, src/OpenLoco/src/Windows/TownWindow.cpp, src/OpenLoco/src/Windows/Vehicle.cpp
=> enum-ViewportFlags conversion

src/OpenLoco/src/Drawing/DrawingContext.h, src/OpenLoco/src/Drawing/SoftwareDrawingContext.cpp, src/OpenLoco/src/Drawing/SoftwareDrawingContext.h, src/OpenLoco/src/Paint/Paint.cpp, src/OpenLoco/src/Paint/Paint.h
This is the main conversion of the paint struct graph into draw calls.
=> Implement draw structs

src/OpenLoco/src/Vehicles/Orders.cpp, src/OpenLoco/src/Vehicles/Orders.h, src/OpenLoco/src/Vehicles/VehicleHead.cpp, src/OpenLoco/src/Vehicles/VehicleManager.cpp, src/OpenLoco/src/Viewport.cpp, src/OpenLoco/src/Windows/MapWindow.cpp, src/OpenLoco/src/Windows/Vehicle.cpp
=> Enum - OrderFlag conversion

src/OpenLoco/src/Windows/TerraForm.cpp
=> enum-GhostPlacedFlags conversion

src/OpenLoco/src/Input/Keyboard.cpp, src/OpenLoco/src/SceneManager.cpp, src/OpenLoco/src/SceneManager.h
=> enum-ScreenFlags conversion

src/OpenLoco/src/Vehicles/Vehicle.h, src/OpenLoco/src/Vehicles/VehicleHead.cpp
=> enum-WaterMotionFlags conversion

src/OpenLoco/src/Vehicles/CreateVehicle.cpp, src/OpenLoco/src/Vehicles/Vehicle.h, src/OpenLoco/src/Vehicles/VehicleBody.cpp, src/OpenLoco/src/Vehicles/VehicleHead.cpp
=> Enum - Flags5F conversion

src/OpenLoco/src/Ui/ScrollView.cpp, src/OpenLoco/src/Ui/ScrollView.h, src/OpenLoco/src/Ui/WindowManager.cpp, src/OpenLoco/src/Widget.cpp, src/OpenLoco/src/Window.cpp, src/OpenLoco/src/Window.h, src/OpenLoco/src/Windows/CompanyWindow.cpp
=> Enum - ScrollFlags conversion

src/OpenLoco/src/Objects/RegionObject.cpp, src/OpenLoco/src/Objects/RegionObject.h
Interesting that it has some sort of cargo header. Not sure why.
=> Implement region object load

src/OpenLoco/src/Entities/Entity.h, src/OpenLoco/src/Entities/EntityManager.cpp, src/OpenLoco/src/GameCommands/Cheat.cpp, src/OpenLoco/src/GameCommands/VehiclePickup.cpp, src/OpenLoco/src/Paint/PaintVehicle.cpp, src/OpenLoco/src/Vehicles/CreateVehicle.cpp, src/OpenLoco/src/Vehicles/Routing.cpp, src/OpenLoco/src/Vehicles/Vehicle.cpp, src/OpenLoco/src/Vehicles/Vehicle.h, src/OpenLoco/src/Vehicles/Vehicle1.cpp, src/OpenLoco/src/Vehicles/Vehicle2.cpp, src/OpenLoco/src/Vehicles/VehicleBody.cpp, src/OpenLoco/src/Vehicles/VehicleBogie.cpp, src/OpenLoco/src/Vehicles/VehicleHead.cpp, src/OpenLoco/src/Vehicles/VehiclePickupWater.cpp, src/OpenLoco/src/Windows/MapWindow.cpp, src/OpenLoco/src/Windows/ToolbarTop.cpp, src/OpenLoco/src/Windows/Vehicle.cpp, src/OpenLoco/src/Windows/VehicleList.cpp
=> Enum - Flags0C, Flags38 conversion

src/OpenLoco/src/Objects/DockObject.cpp, src/OpenLoco/src/Objects/DockObject.h
Should probably make those flags an enum...
=> Implement dock object load

src/OpenLoco/src/Objects/RoadStationObject.cpp, src/OpenLoco/src/Objects/RoadStationObject.h, src/OpenLoco/src/Station.cpp, src/OpenLoco/src/Vehicles/VehicleBody.cpp
Not much exciting, very very similar to the track equivalent station.
=> Implement road station object load

src/OpenLoco/src/Objects/ObjectManager.cpp
=> Create visitObject wrapper to prevent duplicate code

src/OpenLoco/src/Entities/Entity.cpp, src/OpenLoco/src/Entities/Entity.h, src/OpenLoco/src/Entities/EntityManager.cpp, src/OpenLoco/src/Entities/Misc.cpp, src/OpenLoco/src/Objects/CargoObject.h, src/OpenLoco/src/Objects/ObjectManager.cpp, src/OpenLoco/src/Objects/RoadObject.cpp, src/OpenLoco/src/Objects/SteamObject.cpp, src/OpenLoco/src/Objects/SteamObject.h, src/OpenLoco/src/Objects/TrackObject.cpp, src/OpenLoco/src/Objects/VehicleObject.cpp, src/OpenLoco/src/Objects/VehicleObject.h, src/OpenLoco/src/Paint/PaintVehicle.cpp, src/OpenLoco/src/Vehicles/CreateVehicle.cpp, src/OpenLoco/src/Vehicles/VehicleBody.cpp, src/OpenLoco/src/Vehicles/VehicleHead.cpp, src/OpenLoco/src/Windows/BuildVehicle.cpp, src/OpenLoco/src/Windows/Vehicle.cpp
=> Vehicle Object Load

src/OpenLoco/src/Vehicles/Vehicle.h, src/OpenLoco/src/Vehicles/VehicleHead.cpp, src/OpenLoco/src/Vehicles/VehicleManager.cpp
Just a tiny little one i saw when we were moving things about.
=> Implement VehicleMananger::updateDaily

src/OpenLoco/src/Objects/VehicleObject.cpp
Turns out official objects would occasionaly have incorrect image counts
=> Drop down to a logVerbose for vehicle images

src/OpenLoco/src/Drawing/SoftwareDrawingContext.cpp
The original didn't handle the move_x command but seemed silly not to add it. This was basically the same as wrap string but simplified.
=> Implement string width

src/OpenLoco/src/Drawing/DrawingContext.h, src/OpenLoco/src/Drawing/SoftwareDrawingContext.cpp, src/OpenLoco/src/Drawing/SoftwareDrawingContext.h, src/OpenLoco/src/Windows/Error.cpp
=> Implement Draw string centred raw

src/OpenLoco/CMakeLists.txt, src/OpenLoco/src/GameCommands/ClearLand.cpp, src/OpenLoco/src/GameCommands/GameCommands.cpp, src/OpenLoco/src/GameCommands/GameCommands.h, src/OpenLoco/src/Windows/TerraForm.cpp
Basic game command function is working. ~~In draft while I implement more of the sub functions.~~ Leaving the rest for a future PR.
=> Implement basis for clear land game command

src/OpenLoco/src/Paint/Paint.cpp, src/OpenLoco/src/Vehicles/VehicleHead.cpp, src/OpenLoco/src/Viewport.cpp, src/OpenLoco/src/Windows/StationList.cpp, src/OpenLoco/src/Windows/StationWindow.cpp, src/OpenLoco/src/Windows/Vehicle.cpp, src/OpenLoco/src/World/Industry.cpp, src/OpenLoco/src/World/Station.cpp, src/OpenLoco/src/World/Station.h, src/OpenLoco/src/World/StationManager.cpp
Addresses #1757 
Implemented enum flags for `StationFlags`. 
Created enum classes for `StationCargoStatsFlags` and `CatchmentFlags` (previously unnamed).
=> Station enum flags

src/OpenLoco/src/CommandLine.cpp, src/OpenLoco/src/EditorController.cpp, src/OpenLoco/src/Game.cpp, src/OpenLoco/src/Network/NetworkClient.cpp, src/OpenLoco/src/OpenLoco.cpp, src/OpenLoco/src/S5/S5.cpp, src/OpenLoco/src/S5/S5.h, src/OpenLoco/src/Scenario.cpp, src/OpenLoco/src/Windows/ToolbarTop.cpp
=> Enum - HeaderFlags, LoadFlags, SaveFlags, S5FixFlags

src/OpenLoco/src/Map/TileLoop.hpp, src/OpenLoco/src/Objects/AirportObject.cpp, src/OpenLoco/src/Objects/AirportObject.h, src/OpenLoco/src/Windows/Construction/Construction.h, src/OpenLoco/src/Windows/Construction/StationTab.cpp, src/OpenLoco/src/World/Station.cpp, src/OpenLoco/src/World/Station.h
=> Station Tool Update

CHANGELOG.md, src/OpenLoco/src/ScenarioManager.cpp
Woops forgot to set the pointer to nullptr after freeing it.
=> Fix 1869: Language Change Crash

src/Core/include/OpenLoco/Core/Prng.h, src/OpenLoco/src/World/Town.cpp, src/OpenLoco/src/World/Town.h, src/OpenLoco/src/World/TownManager.cpp
This still has my debug code in it but that can be deleted before merge. I can't think of a good name for these functions just yet but since that has been my excuse for not putting them up for review for 2 months might as well just leave the names as is. I verified these with the replays a bit but could probably be rechecked.
=> Town Grow Functions

src/OpenLoco/src/Objects/RoadObject.h, src/OpenLoco/src/World/Town.cpp, src/OpenLoco/src/World/Town.h, src/OpenLoco/src/World/TownManager.cpp
Implements initial town road placement.
Based off of #1740.
=> Town Grow 2

src/OpenLoco/src/CommandLine.cpp, src/OpenLoco/src/S5/S5.cpp, src/OpenLoco/src/S5/SawyerStream.cpp, src/Utility/include/OpenLoco/Utility/Stream.hpp
Converts the StreamFlags namespace for the new enum class
=> Refactor StreamFlags namespace to StreamMode enum class

src/OpenLoco/src/GameCommands/GameCommands.h, src/OpenLoco/src/Vehicles/CloneVehicle.cpp, src/OpenLoco/src/Vehicles/RenameVehicle.cpp, src/OpenLoco/src/Windows/BuildVehicle.cpp, src/OpenLoco/src/Windows/Vehicle.cpp
Switching to using game command args structs for the game commands. This will make things easier to use when implementing game commands and brings things into more standardised structure. (also will make changing the game command flags to an enum much easier)
=> Args structs for vehicle game commands

src/OpenLoco/src/Vehicles/CreateVehicle.cpp, src/OpenLoco/src/Vehicles/Vehicle.h, src/OpenLoco/src/Vehicles/Vehicle2.cpp, src/OpenLoco/src/Vehicles/VehicleHead.cpp
=> Convert vehicle flags 73

src/OpenLoco/src/Graphics/ImageId.h, src/OpenLoco/src/Windows/BuildVehicle.cpp, src/OpenLoco/src/Windows/IndustryList.cpp, src/OpenLoco/src/Windows/TerraForm.cpp, src/OpenLoco/src/Windows/TownList.cpp, src/OpenLoco/src/Windows/Vehicle.cpp
Did some manual testing to verify changes worked.
=> Replaced instances of Audio::playSound(soundId, pan) per issue #1407

src/OpenLoco/src/Objects/ObjectManager.cpp
Thanks to @duncanspumpkin to point where and what to fix
=> Fixes saving scenario issue by adding the kEmptyObjectHeader

src/OpenLoco/src/Environment.cpp, src/OpenLoco/src/Localisation/LanguageFiles.cpp, src/OpenLoco/src/OpenLoco.cpp
A tiny bit of the c++20 changes and general improvement. @ZehMatt there is still a lot of cout/printf in the command line stuff were you thinking that would call libfmt directly?
=> Use the logging library more

CHANGELOG.md, data/language/en-GB.yml, src/OpenLoco/CMakeLists.txt, src/OpenLoco/src/Localisation/StringIds.h, src/OpenLoco/src/Objects/Object.h, src/OpenLoco/src/Objects/ObjectManager.cpp, src/OpenLoco/src/Objects/ObjectManager.h, src/OpenLoco/src/OpenLoco.cpp, src/OpenLoco/src/S5/S5.cpp, src/OpenLoco/src/S5/S5.h, src/OpenLoco/src/Ui/WindowManager.h, src/OpenLoco/src/Ui/WindowType.h, src/OpenLoco/src/Windows/ObjectLoadError.cpp
This PR introduces a window listing all objects that could not be loaded, along with their expected types and checksums.
=> Introduce object load error window

src/OpenLoco/src/GameCommands/GameCommands.h, src/OpenLoco/src/GameCommands/RenameStation.cpp, src/OpenLoco/src/Windows/StationWindow.cpp
Refactored the RenameStation GameCommand to use the new Game Command args struct
=> Refactor rename station args

src/OpenLoco/src/Audio/Audio.cpp, src/OpenLoco/src/Audio/VehicleChannel.cpp, src/OpenLoco/src/Drawing/DrawSprite.cpp, src/OpenLoco/src/Drawing/DrawSprite.h, src/OpenLoco/src/Drawing/DrawSpriteBMP.hpp, src/OpenLoco/src/Drawing/DrawSpriteHelper.hpp, src/OpenLoco/src/Drawing/DrawSpriteRLE.hpp, src/OpenLoco/src/Paint/Paint.h, src/OpenLoco/src/ScenarioManager.cpp, src/OpenLoco/src/ScenarioManager.h, src/OpenLoco/src/Vehicles/CreateVehicle.cpp, src/OpenLoco/src/Vehicles/Vehicle.h, src/OpenLoco/src/Windows/Construction/Common.cpp, src/OpenLoco/src/Windows/Construction/Construction.h, src/OpenLoco/src/Windows/Construction/ConstructionTab.cpp, src/OpenLoco/src/Windows/Construction/OverheadTab.cpp, src/OpenLoco/src/Windows/Construction/SignalTab.cpp, src/OpenLoco/src/Windows/Construction/StationTab.cpp
=> Use more enum flags

src/OpenLoco/src/GameCommands/ClearLand.cpp, src/OpenLoco/src/Localisation/StringIds.h, src/OpenLoco/src/Map/TileElementBase.h, src/OpenLoco/src/Map/TileManager.cpp, src/OpenLoco/src/Map/TileManager.h, src/OpenLoco/src/World/Company.h
This is going to take a little while its a real fiddly function.
=> ConstructWithClear

src/Interop/src/Hook.cpp, src/Interop/src/Interop.cpp, src/OpenLoco/src/CommandLine.cpp, src/OpenLoco/src/Environment.cpp, src/OpenLoco/src/Localisation/LanguageFiles.cpp, src/OpenLoco/src/S5/S5.cpp
Removing any references to std::cerr (apart from the ones in Platform since logging depends on Platform)
=> Use logging lib even more

README.md
* Rephrase the situation w.r.t. OpenRCT2
* Elaborate on what recent effort has focused on
* Clarify that builds are only provided for Windows
* Explicitly refer macOS users to the wiki lemma on using Wine
* Reduce emphasis on `yaml-cpp` in the Linux section
=> Update introduction for README.md

DEVELOPMENTLOG.md
Bit tired will reread this tomorrow see if it reads...
=> Add devlog for 23.05

CHANGELOG.md, src/OpenLoco/src/Drawing/SoftwareDrawingEngine.cpp, src/OpenLoco/src/Drawing/SoftwareDrawingEngine.h, src/OpenLoco/src/Ui.h
A bit like how it works in OpenRCT2 with few minor changes
=> Implement SDL hardware rendering 

CHANGELOG.md, data/language/en-GB.yml, src/OpenLoco/src/Config.cpp, src/OpenLoco/src/Config.h, src/OpenLoco/src/Localisation/StringIds.h, src/OpenLoco/src/Windows/MessageWindow.cpp, src/OpenLoco/src/Windows/News/Common.cpp
=> Make news sound effects optional

src/Engine/include/OpenLoco/Engine/Ui/Point.hpp, src/Engine/include/OpenLoco/Engine/World.hpp, src/Math/include/OpenLoco/Math/Trigonometry.hpp, src/Math/include/OpenLoco/Math/Vector.hpp, src/Math/tests/VectorTests.cpp, src/OpenLoco/src/Audio/Audio.cpp, src/OpenLoco/src/GameCommands/ChangeLandMaterial.cpp, src/OpenLoco/src/GameCommands/ClearLand.cpp, src/OpenLoco/src/GameCommands/RemoveIndustry.cpp, src/OpenLoco/src/Map/IndustryElement.cpp, src/OpenLoco/src/Map/TileManager.cpp, src/OpenLoco/src/Map/Tree.cpp, src/OpenLoco/src/Map/WaveManager.cpp, src/OpenLoco/src/Paint/PaintIndustry.cpp, src/OpenLoco/src/Title.cpp, src/OpenLoco/src/Ui/ViewportInteraction.cpp, src/OpenLoco/src/Windows/Construction/ConstructionTab.cpp, src/OpenLoco/src/Windows/Construction/StationTab.cpp, src/OpenLoco/src/Windows/TerraForm.cpp, src/OpenLoco/src/Windows/TileInspector.cpp, src/OpenLoco/src/Windows/Vehicle.cpp, src/OpenLoco/src/World/Company.cpp, src/OpenLoco/src/World/Industry.cpp, src/OpenLoco/src/World/IndustryManager.cpp, src/OpenLoco/src/World/Station.cpp, src/OpenLoco/src/World/StationManager.cpp, src/OpenLoco/src/World/Town.cpp, src/OpenLoco/src/World/TownManager.cpp
=> Explicit position convert

src/OpenLoco/CMakeLists.txt, src/OpenLoco/src/GameCommands/GameCommands.cpp, src/OpenLoco/src/GameCommands/GameCommands.h, src/OpenLoco/src/GameCommands/VehicleOrderUp.cpp, src/OpenLoco/src/Windows/Vehicle.cpp
Borrows parts of #1961. To be rebased and merged after.
=> Implement vehicleOrderUp game command

src/OpenLoco/src/GameCommands/ClearLand.cpp, src/OpenLoco/src/GameCommands/RemoveTree.cpp, src/OpenLoco/src/Map/TileManager.cpp, src/OpenLoco/src/Map/TileManager.h
I wanted to verify that the interface for the constructwithclear was all correct and what better way than to implement one. This is quite a neat function that has a number of neat ideas. I like how CS handled the multi tile buildings to ensure they weren't counted multiple times.
=> Implement ClearTile clear function

CHANGELOG.md, src/Core/include/OpenLoco/Core/FileStream.h, src/Core/include/OpenLoco/Core/MemoryStream.h, src/Core/include/OpenLoco/Core/Stream.hpp, src/Core/src/FileStream.cpp, src/Core/src/MemoryStream.cpp, src/Core/tests/FileStreamTests.cpp, src/Core/tests/MemoryStreamTests.cpp, src/OpenLoco/src/CommandLine.cpp, src/OpenLoco/src/Objects/ObjectManager.cpp, src/OpenLoco/src/S5/S5.cpp, src/OpenLoco/src/S5/SawyerStream.cpp, src/OpenLoco/src/S5/SawyerStream.h
Results so far:
```
master:
MemoryStreamTest.testWrite100MiB (1152 ms)
PR:
MemoryStreamTest.testWrite100MiB (628 ms)
master:
FileStreamTest.testRead100MiB (5600 ms)
PR:
FileStreamTest.testRead100MiB (1915 ms)
master:
FileStreamTest.testWrite100MiB (7526 ms)
PR:
FileStreamTest.testWrite100MiB (1662 ms)
```
Might be not final, can still turn a knob here and there regarding the buffer size.
=> Stream performance improvements

src/OpenLoco/src/GameCommands/GameCommands.cpp
This was probably a mistake introduced in a rebase issue :D
=> Actually use our vehicleOrderInsert implementation

src/OpenLoco/CMakeLists.txt, src/OpenLoco/src/GameCommands/GameCommands.cpp, src/OpenLoco/src/GameCommands/GameCommands.h, src/OpenLoco/src/GameCommands/LowerWater.cpp, src/OpenLoco/src/GameCommands/RaiseWater.cpp, src/OpenLoco/src/Map/SurfaceElement.h, src/OpenLoco/src/Map/TileClearance.cpp, src/OpenLoco/src/Map/TileManager.cpp, src/OpenLoco/src/Map/TileManager.h
Currently based on top of #1998. I'll rebase and un-draft after that PR has been merged.
=> Implement the raise/lower water game commands

src/OpenLoco/src/GameCommands/GameCommands.h, src/OpenLoco/src/Vehicles/OrderManager.cpp
=> Two bugs with orders causing crashes when ai inserted orders

CHANGELOG.md, src/OpenLoco/src/Map/IndustryElement.cpp
=> Fix incorrect industry clear heights when constructing

CHANGELOG.md, src/OpenLoco/src/Windows/ObjectSelectionWindow.cpp
This conditional was back to front.
=> Fix error message for object selection failure

src/OpenLoco/CMakeLists.txt, src/OpenLoco/src/GameCommands/ClearLand.cpp, src/OpenLoco/src/GameCommands/CreateIndustry.cpp, src/OpenLoco/src/GameCommands/GameCommands.cpp, src/OpenLoco/src/GameCommands/GameCommands.h, src/OpenLoco/src/GameCommands/LowerLand.cpp, src/OpenLoco/src/GameCommands/RemoveIndustry.cpp, src/OpenLoco/src/Localisation/StringIds.h, src/OpenLoco/src/Map/IndustryElement.cpp, src/OpenLoco/src/Map/IndustryElement.h, src/OpenLoco/src/Map/StationElement.h, src/OpenLoco/src/Map/TileManager.cpp, src/OpenLoco/src/Map/TileManager.h, src/OpenLoco/src/Objects/IndustryObject.cpp, src/OpenLoco/src/Objects/IndustryObject.h, src/OpenLoco/src/World/Industry.cpp, src/OpenLoco/src/World/Industry.h, src/OpenLoco/src/World/IndustryManager.cpp, src/OpenLoco/src/World/IndustryManager.h
=> Create Industry GameCommand

src/OpenLoco/src/Input/MouseInput.cpp, src/OpenLoco/src/Map/BuildingElement.cpp, src/OpenLoco/src/Map/Tile.h, src/OpenLoco/src/Map/TileClearance.cpp, src/OpenLoco/src/Ui/ViewportInteraction.cpp, src/OpenLoco/src/Vehicles/Routing.cpp, src/OpenLoco/src/Vehicles/VehicleTail.cpp, src/OpenLoco/src/Windows/Construction/Common.cpp, src/OpenLoco/src/Windows/Construction/ConstructionTab.cpp, src/OpenLoco/src/Windows/Construction/SignalTab.cpp, src/OpenLoco/src/Windows/Vehicle.cpp, src/OpenLoco/src/World/Station.cpp
Also fixed a coding style violation.
=> Add definitions to two common items

src/OpenLoco/src/Entities/Entity.h, src/OpenLoco/src/Entities/EntityManager.cpp, src/OpenLoco/src/Entities/EntityManager.h, src/OpenLoco/src/Entities/EntityTweener.cpp, src/OpenLoco/src/GameCommands/CreateVehicle.cpp, src/OpenLoco/src/Input/MouseInput.cpp, src/OpenLoco/src/Paint/PaintVehicle.cpp, src/OpenLoco/src/Vehicles/Vehicle.cpp, src/OpenLoco/src/Vehicles/Vehicle.h, src/OpenLoco/src/ViewportManager.cpp, src/OpenLoco/src/ViewportManager.h, src/OpenLoco/src/Window.cpp, src/OpenLoco/src/Window.h, src/OpenLoco/src/Windows/BuildVehicle.cpp, src/OpenLoco/src/Windows/CompanyWindow.cpp, src/OpenLoco/src/Windows/DragVehiclePart.cpp, src/OpenLoco/src/Windows/News/News.cpp, src/OpenLoco/src/Windows/Vehicle.cpp, src/OpenLoco/src/World/Company.h
@ZehMatt pointed out we still had some thing references
=> Remove remnants of thing name

src/OpenLoco/src/Vehicles/Routing.cpp
To reduce the need for lots of duplicated code i really need the location of interest hash map to be dynamically sized. I would just replace it with an unordered_map but i think that will cause divergence issues. This change just means we can't hook half way through a routing function.
=> Routing refactor: Make HashMap dynamically sized

src/OpenLoco/src/Graphics/Colour.h, src/OpenLoco/src/Windows/MapWindow.cpp
=> Implement MapWindow::assignRouteColours

src/OpenLoco/src/Vehicles/Routing.cpp
For the create track mod game command i need to pass a bunch of variables around through globals so i thought it best we set things up from now so we don't need to do that.
This turns all of the filter and transform functions into universal references so you can do lambda capturing. I'm not 100% sure if this is a great idea. Its this or use std::function but std::function allocates and we ideally want to avoid an allocation in this code as it will be relatively hot. @ZehMatt  any suggestions?
=> Pass routing variables by ref rather than global

src/OpenLoco/src/GameCommands/Company/ChangeCompanyFace.cpp, src/OpenLoco/src/GameCommands/Company/ChangeCompanyFace.h, src/OpenLoco/src/GameCommands/Company/RenameCompanyOwner.cpp, src/OpenLoco/src/GameCommands/GameCommands.h, src/OpenLoco/src/Windows/CompanyFaceSelection.cpp, src/OpenLoco/src/World/CompanyManager.cpp, src/OpenLoco/src/World/CompanyManager.h
This was meant to fix #2103 but i accidentally merged a temp fix for that issue during making the 23.08.1 release.
=> Load Company Face From CompanyName

src/Core/include/OpenLoco/Core/EnumFlags.hpp, src/OpenLoco/src/Drawing/DrawSprite.cpp, src/OpenLoco/src/GameCommands/Company/ChangeCompanyFace.cpp, src/OpenLoco/src/GameCommands/Town/RemoveTown.cpp, src/OpenLoco/src/Graphics/Gfx.h, src/OpenLoco/src/Map/BuildingElement.cpp, src/OpenLoco/src/Objects/BuildingObject.cpp, src/OpenLoco/src/Objects/BuildingObject.h, src/OpenLoco/src/Objects/IndustryObject.h, src/OpenLoco/src/Objects/ObjectManager.cpp, src/OpenLoco/src/Objects/SoundObject.h, src/OpenLoco/src/Objects/TrainSignalObject.cpp, src/OpenLoco/src/Objects/VehicleObject.h, src/OpenLoco/src/Ui/Screenshot.cpp, src/OpenLoco/src/Vehicles/OrderManager.cpp, src/OpenLoco/src/Vehicles/Vehicle2.cpp, src/OpenLoco/src/Windows/BuildVehicle.cpp, src/OpenLoco/src/Windows/KeyboardShortcuts.cpp, src/OpenLoco/src/Windows/News/News.cpp, src/OpenLoco/src/Windows/ScenarioOptions.cpp, src/OpenLoco/src/World/Company.cpp, src/OpenLoco/src/World/TownManager.cpp
A bunch of small fixes I've found. Please let me know if I've made any erroneous changes
=> Misc static analysis fixes and typos

src/OpenLoco/src/Drawing/DrawingContext.h, src/OpenLoco/src/Drawing/SoftwareDrawingContext.cpp, src/OpenLoco/src/Drawing/SoftwareDrawingContext.h, src/OpenLoco/src/Windows/News/Ticker.cpp
Ticker is a bit annoying in that it needs special drawString code for wrapping and writing. I think this covers it all though. Its not 100% the same as vanilla codewise but i think it works the same. (Currently there is some debugging code in here that pads out news messages its useful for testing)
=> Draw String Ticker

README.md
MFC component is needed to compile the project.
=> Update Windows building prerequisites

src/Core/include/OpenLoco/Core/Exception.hpp, src/Interop/include/OpenLoco/Interop/Interop.hpp, src/Interop/src/Interop.cpp, src/OpenLoco/src/CommandLine.cpp, src/OpenLoco/src/Entities/EntityManager.h, src/OpenLoco/src/GameCommands/Vehicles/CreateVehicle.cpp, src/OpenLoco/src/Localisation/FormatArguments.hpp, src/OpenLoco/src/Localisation/Formatting.cpp, src/OpenLoco/src/Vehicles/OrderManager.cpp, src/OpenLoco/src/Vehicles/Vehicle.cpp
=> Refactor remaining exceptions to use the new custom class

src/OpenLoco/src/Objects/ObjectIndex.cpp, src/OpenLoco/src/Objects/ObjectIndex.h, src/OpenLoco/src/Windows/ObjectSelectionWindow.cpp, src/OpenLoco/src/Windows/Options.cpp
=> Use an enum for the Object Selection Flags

src/OpenLoco/src/GameState.h, src/OpenLoco/src/Map/RoadElement.cpp, src/OpenLoco/src/Vehicles/Vehicle.cpp
Was not sure which manager to use for making getGameState() visible.
=> Update 525 fbc global to use gamestate structure #1132

CMakeLists.txt, cmake/OpenLocoUtility.cmake, src/Core/CMakeLists.txt, src/Core/include/OpenLoco/Core/BitSet.hpp, src/Core/include/OpenLoco/Core/LocoFixedVector.hpp, src/Core/include/OpenLoco/Core/Span.hpp, src/Interop/include/OpenLoco/Interop/Interop.hpp, src/Interop/src/Interop.cpp, src/Math/include/OpenLoco/Math/Vector.hpp, src/OpenLoco/CMakeLists.txt, src/OpenLoco/src/Config.h, src/OpenLoco/src/Economy/Currency.h, src/OpenLoco/src/Entities/EntityManager.h, src/OpenLoco/src/Localisation/LanguageFiles.cpp, src/OpenLoco/src/Map/TileLoop.hpp, src/OpenLoco/src/Message.h, src/OpenLoco/src/Objects/Object.h, src/OpenLoco/src/Objects/ObjectIndex.cpp, src/OpenLoco/src/ScenarioManager.cpp, src/OpenLoco/src/Speed.hpp, src/OpenLoco/src/Vehicles/OrderManager.h, src/OpenLoco/src/Vehicles/Routing.cpp, src/OpenLoco/src/Vehicles/Routing.h, src/OpenLoco/src/Vehicles/RoutingManager.h, src/OpenLoco/src/Vehicles/Vehicle.h, src/OpenLoco/src/Window.h, src/OpenLoco/src/ZoomLevel.hpp, thirdparty/CMakeLists.txt
For now it is too painful to make char8_t work for us. We can look at removing the disable after the string code is refactored to be utf8. (Expecting focal builds to fail will need to merge #1843 first)
=> Enable cpp20 [disable char8_t :( ]

src/Engine/include/OpenLoco/Engine/World.hpp, src/OpenLoco/src/GameCommands/GameCommands.h, src/OpenLoco/src/Vehicles/VehicleHead.cpp, src/OpenLoco/src/World/Company.cpp, src/OpenLoco/src/World/Company.h, src/OpenLoco/src/World/CompanyAi.cpp, src/OpenLoco/src/World/CompanyAi.h, src/OpenLoco/src/World/CompanyManager.cpp, src/OpenLoco/src/World/CompanyManager.h, src/OpenLoco/src/World/Station.cpp, src/OpenLoco/src/World/Station.h
=> Various Company Ai Functions

CHANGELOG.md, data/language/en-GB.yml, src/OpenLoco/src/Config.cpp, src/OpenLoco/src/Config.h, src/OpenLoco/src/Localisation/StringIds.h, src/OpenLoco/src/Vehicles/VehicleHead.cpp, src/OpenLoco/src/Windows/Cheats.cpp
Add a cheat to disable slow loading at stations when vehicle length exceeds station length.
=> add cheat to remove station loading penalty

cmake/OpenLocoUtility.cmake, src/Core/tests/PrngTests.cpp, src/OpenLoco/src/GameCommands/GameCommands.cpp, src/OpenLoco/src/GameCommands/Vehicles/CreateVehicle.cpp, src/OpenLoco/src/Graphics/Gfx.h, src/OpenLoco/src/Input/MouseInput.cpp, src/OpenLoco/src/Input/Shortcuts.cpp, src/OpenLoco/src/Paint/Paint.cpp, src/OpenLoco/src/Paint/PaintStation.cpp, src/OpenLoco/src/Ui/Dropdown.cpp, src/OpenLoco/src/Vehicles/RoutingManager.cpp, src/OpenLoco/src/Vehicles/Vehicle.h, src/OpenLoco/src/Vehicles/VehicleHead.cpp, src/OpenLoco/src/Widget.cpp, src/OpenLoco/src/Widget.h, src/OpenLoco/src/Windows/Construction/Common.cpp, src/OpenLoco/src/Windows/IndustryList.cpp, src/OpenLoco/src/Windows/IndustryWindow.cpp, src/OpenLoco/src/Windows/News/News.cpp, src/OpenLoco/src/Windows/TerraForm.cpp, src/OpenLoco/src/Windows/ToolbarTop.cpp, src/OpenLoco/src/Windows/TownList.cpp, src/OpenLoco/src/World/Station.cpp
Since @ZehMatt keeps requesting them.
=> Enable Conversion Warnings

src/Core/include/OpenLoco/Core/BitSet.hpp, src/Core/include/OpenLoco/Core/Numerics.hpp, src/Core/src/Prng.cpp, src/Core/tests/NumericsTests.cpp, src/OpenLoco/src/Drawing/SoftwareDrawingContext.cpp, src/OpenLoco/src/Economy/Currency.h, src/OpenLoco/src/GameCommands/Industries/CreateIndustry.cpp, src/OpenLoco/src/Map/Track/TrackData.cpp, src/OpenLoco/src/Objects/ObjectIndex.cpp, src/OpenLoco/src/Objects/ObjectManager.cpp, src/OpenLoco/src/S5/SawyerStream.cpp, src/OpenLoco/src/Speed.hpp, src/OpenLoco/src/World/CompanyAi.cpp, src/OpenLoco/src/World/Town.cpp
=> Use C++20 std:: Built-ins

src/OpenLoco/src/GameCommands/Vehicles/VehiclePickupAir.cpp, src/OpenLoco/src/GameCommands/Vehicles/VehiclePickupWater.cpp, src/OpenLoco/src/Vehicles/Vehicle.cpp, src/OpenLoco/src/Vehicles/Vehicle.h, src/OpenLoco/src/Vehicles/VehicleBody.cpp, src/OpenLoco/src/Vehicles/VehicleBogie.cpp
A few more misc vehicle functions.
=> Vehicle functions: Bogie::isOnRackRail and Vehicle::removeAllCargo

src/OpenLoco/src/Localisation/LanguageFiles.cpp, src/OpenLoco/src/Localisation/StringIds.h, src/OpenLoco/src/Objects/Object.h, src/OpenLoco/src/Objects/ObjectIndex.cpp, src/OpenLoco/src/Objects/ObjectIndex.h, src/OpenLoco/src/Objects/ObjectManager.cpp, src/OpenLoco/src/Objects/ObjectManager.h, src/OpenLoco/src/Windows/ObjectSelectionWindow.cpp
~~WiP will likely have to do a few other PR's before this one as there is a bit of structural stuff i want to improve prior.~~ complete
=> Implement Object Selection

src/OpenLoco/src/S5/S5.cpp, src/OpenLoco/src/Scenario.cpp, src/OpenLoco/src/Vehicles/OrderManager.cpp, src/OpenLoco/src/Vehicles/OrderManager.h
Just a little simple one i noticed.
=> Implement OrderManager reset and zero

src/OpenLoco/src/Effects/ExplosionEffect.cpp, src/OpenLoco/src/Effects/ExplosionEffect.h, src/OpenLoco/src/Effects/VehicleCrashEffect.cpp, src/OpenLoco/src/Effects/VehicleCrashEffect.h, src/OpenLoco/src/Vehicles/Vehicle.cpp, src/OpenLoco/src/Vehicles/Vehicle.h, src/OpenLoco/src/Vehicles/VehicleBogie.cpp
Another little simple function and sub functions.
=> Implement explode component

src/OpenLoco/src/Map/Track/Track.cpp, src/OpenLoco/src/Vehicles/Vehicle.h, src/OpenLoco/src/Vehicles/VehicleHead.cpp
This looks like the base of a very important function for working out where vehicles are going to travel.
=> Vehicle functions: Sub_4ACCDC

src/OpenLoco/src/Map/RoadElement.h, src/OpenLoco/src/Objects/ObjectIndex.cpp, src/OpenLoco/src/Objects/ObjectIndex.h, src/OpenLoco/src/Title.cpp, src/OpenLoco/src/Windows/ObjectSelectionWindow.cpp
Based on #2128. This implements the functions that prepare the object selection.
=> Object selection: Part 2

CHANGELOG.md, src/OpenLoco/src/Vehicles/OrderManager.cpp, src/OpenLoco/src/Viewport.cpp
=> Fix #2111: Add nullptr check before using the order object

src/OpenLoco/src/Localisation/StringIds.h, src/OpenLoco/src/Objects/ObjectIndex.cpp, src/OpenLoco/src/Objects/ObjectIndex.h, src/OpenLoco/src/Objects/ObjectManager.cpp, src/OpenLoco/src/Objects/ObjectManager.h, src/OpenLoco/src/S5/S5.cpp, src/OpenLoco/src/Scenario.cpp, src/OpenLoco/src/Scenario.h, src/OpenLoco/src/Title.cpp, src/OpenLoco/src/Windows/ObjectSelectionWindow.cpp, src/OpenLoco/src/Windows/Options.cpp
=> Object Selection: Part 3

CHANGELOG.md, src/OpenLoco/src/Map/MapGenerator/MapGenerator.cpp
=> Fix town size limits not being taken into account

src/OpenLoco/src/Paint/Paint.cpp, src/OpenLoco/src/Paint/Paint.h, src/OpenLoco/src/Paint/PaintStation.cpp, src/OpenLoco/src/Paint/PaintTile.cpp
I know in the meeting we said paint wasn't the priority but i was wondering how something worked and ended up implementing this.
=> Implement finalise track road ordering

CHANGELOG.md, src/OpenLoco/src/Map/TileManager.cpp, src/OpenLoco/src/Ui.cpp, src/OpenLoco/src/Ui.h
=> Fix #2221: Cursor icon is reset when the game auto saves

CHANGELOG.md, src/OpenLoco/src/Input.h, src/OpenLoco/src/Input/MouseInput.cpp, src/OpenLoco/src/Ui.cpp, src/OpenLoco/src/Ui/WindowManager.cpp, src/OpenLoco/src/Ui/WindowManager.h
The goal should be following:
This PR also fixes the odd behavior that it accumulates a delta which requires to first undo the scroll before it would actually scroll.
=> Mouse wheel input refactor

src/OpenLoco/src/Widget.cpp
=> clip text inside dropdown widgets

src/OpenLoco/src/Map/MapGenerator/MapGenerator.cpp, src/OpenLoco/src/Scenario.cpp, src/OpenLoco/src/Scenario.h
Small initialisation function? Not sure what its purpose it yet.
=> Implement Scenario::sub_4969E0

src/OpenLoco/src/Paint/Paint.cpp, src/OpenLoco/src/Paint/Paint.h
This should be all that is required to make a Test Paint MkII for tracks.
=> Paint Add Track to plot list

src/Interop/include/OpenLoco/Interop/Interop.hpp, src/OpenLoco/src/Paint/Paint.cpp, src/OpenLoco/src/Paint/Paint.h, src/OpenLoco/src/Paint/PaintStation.cpp, src/OpenLoco/src/Paint/PaintTile.cpp
This reworks how bridges work labelling the offsets. It also adds helper methods for adding tunnels.
=> Add utility helper paint functions and rework some globals

src/OpenLoco/src/Paint/Paint.cpp, src/OpenLoco/src/Paint/Paint.h
Another little function that i should have done with the others.
=> Implement the add to track addition paint function

CHANGELOG.md, src/OpenLoco/src/Windows/DragVehiclePart.cpp
Whilst investigating #2265 saw this tiny issue.
=> Fix invalidation issue with vehicle drag

src/OpenLoco/CMakeLists.txt, src/OpenLoco/src/GameCommands/GameCommands.cpp, src/OpenLoco/src/GameCommands/Track/RemoveSignal.cpp, src/OpenLoco/src/GameCommands/Track/RemoveSignal.h, src/OpenLoco/src/Ui/ViewportInteraction.cpp, src/OpenLoco/src/Windows/Construction/SignalTab.cpp
Pretty simple one v. similar to create but with some easier logic.
=> Implement the remove signal game command

src/OpenLoco/src/Map/AnimationManager.cpp, src/OpenLoco/src/Map/BuildingElement.cpp, src/OpenLoco/src/Map/BuildingElement.h, src/OpenLoco/src/World/Industry.h
Ultimately a very simple function with verbose assembly due to multi tile stuff.
=> Implement update building animation

src/OpenLoco/src/Objects/BuildingObject.cpp
Another tiny function that is super easy to do now with paint buildings info
=> Implement paint building

CHANGELOG.md, src/OpenLoco/src/World/Company.h, src/OpenLoco/src/World/CompanyAi.cpp, src/OpenLoco/src/World/CompanyAi.h
Split off from #2189
Doing this standalone pointed out a bug in the ai in OpenLoco where bankrupt ai would never get removed!
=> Implement company Ai end function

CHANGELOG.md, src/OpenLoco/src/Windows/Construction/ConstructionTab.cpp
=> Fix construction arrow invalidation issue

CHANGELOG.md, src/OpenLoco/src/GameCommands/Track/CreateSignal.h
=> Fix signal placement failing on very large turns

src/OpenLoco/src/Windows/Main.cpp, src/OpenLoco/src/Windows/MapToolTip.cpp, src/OpenLoco/src/Windows/MapWindow.cpp, src/OpenLoco/src/Windows/MessageWindow.cpp, src/OpenLoco/src/Windows/MusicSelection.cpp, src/OpenLoco/src/Windows/NetworkStatus.cpp, src/OpenLoco/src/Windows/News/Common.cpp, src/OpenLoco/src/Windows/News/News.cpp, src/OpenLoco/src/Windows/News/News.h, src/OpenLoco/src/Windows/News/Ticker.cpp, src/OpenLoco/src/Windows/ObjectLoadError.cpp, src/OpenLoco/src/Windows/ObjectSelectionWindow.cpp, src/OpenLoco/src/Windows/Options.cpp, src/OpenLoco/src/Windows/PlayerInfoPanel.cpp, src/OpenLoco/src/Windows/ProgressBar.cpp, src/OpenLoco/src/Windows/PromptBrowseWindow.cpp, src/OpenLoco/src/Windows/PromptOkCancelWindow.cpp, src/OpenLoco/src/Windows/PromptSaveWindow.cpp, src/OpenLoco/src/Windows/ScenarioOptions.cpp, src/OpenLoco/src/Windows/ScenarioSelect.cpp, src/OpenLoco/src/Windows/StationList.cpp, src/OpenLoco/src/Windows/StationWindow.cpp
This tackles #646 for windows whose names start with M to S.
=> Constexpr event list refactor (windows M-S)

src/OpenLoco/src/Interop/Hooks.cpp, src/OpenLoco/src/Ui/WindowManager.h, src/OpenLoco/src/Windows/TerraForm.cpp, src/OpenLoco/src/Windows/TextInputWindow.cpp, src/OpenLoco/src/Windows/TileInspector.cpp, src/OpenLoco/src/Windows/TimePanel.cpp, src/OpenLoco/src/Windows/TitleExit.cpp, src/OpenLoco/src/Windows/TitleLogo.cpp, src/OpenLoco/src/Windows/TitleMenu.cpp, src/OpenLoco/src/Windows/TitleOptions.cpp, src/OpenLoco/src/Windows/TitleVersion.cpp, src/OpenLoco/src/Windows/ToolTip.cpp, src/OpenLoco/src/Windows/ToolbarBottomEditor.cpp, src/OpenLoco/src/Windows/ToolbarTop.cpp, src/OpenLoco/src/Windows/ToolbarTopAlt.cpp, src/OpenLoco/src/Windows/TownList.cpp, src/OpenLoco/src/Windows/TownWindow.cpp, src/OpenLoco/src/Windows/Tutorial.cpp, src/OpenLoco/src/Windows/Vehicle.cpp, src/OpenLoco/src/Windows/VehicleList.cpp
This tackles #646 for windows whose names start with T to V, i.e. the remaining ones.
=> Constexpr event list refactor (windows T-V)

src/OpenLoco/src/GameCommands/Track/CreateTrainStation.cpp, src/OpenLoco/src/World/Industry.cpp, src/OpenLoco/src/World/Station.cpp, src/OpenLoco/src/World/Station.h, src/OpenLoco/src/World/StationManager.cpp
Before doing more of the station create game commands should probably explore these functions.
=> Station Creation Functions

src/Math/include/OpenLoco/Math/Vector.hpp, src/Math/tests/VectorTests.cpp, src/OpenLoco/src/GameCommands/Industries/CreateIndustry.cpp, src/OpenLoco/src/GameCommands/Town/CreateTown.cpp, src/OpenLoco/src/Vehicles/VehicleBody.cpp, src/OpenLoco/src/Vehicles/VehicleHead.cpp, src/OpenLoco/src/Windows/Construction/Common.cpp, src/OpenLoco/src/Windows/Vehicle.cpp, src/OpenLoco/src/World/Company.h, src/OpenLoco/src/World/CompanyAi.cpp, src/OpenLoco/src/World/CompanyAi.h, src/OpenLoco/src/World/IndustryManager.cpp, src/OpenLoco/src/World/Station.cpp, src/OpenLoco/src/World/StationManager.cpp, src/OpenLoco/src/World/TownManager.cpp
As discussed in the team meeting ai is not the priority so won't take this any further for now. It looks like think state 3 is placing track and then signals and finally considers creating a station. I've only done some of the more simple functions at the start but there are some easy ones in there that could also be done for the signals in the future. I had to rename Math::Vector::distance to distanceXY as we have some users that take a Pos3 and only want the XY distance and the ai functions wants the XYZ distance. Other names could be distance2D and distance3D.
=> Company Ai Functions: ThinkState3

src/OpenLoco/src/GameCommands/Cheats/Cheat.cpp, src/OpenLoco/src/GameCommands/Vehicles/VehicleChangeRunningMode.cpp, src/OpenLoco/src/Ui/Dropdown.cpp, src/OpenLoco/src/Vehicles/VehicleHead.cpp, src/OpenLoco/src/Windows/CompanyList.cpp, src/OpenLoco/src/Windows/CompanyWindow.cpp, src/OpenLoco/src/Windows/Error.cpp, src/OpenLoco/src/Windows/MapToolTip.cpp, src/OpenLoco/src/Windows/News/News.cpp, src/OpenLoco/src/Windows/PlayerInfoPanel.cpp, src/OpenLoco/src/Windows/StationList.cpp, src/OpenLoco/src/Windows/VehicleList.cpp, src/OpenLoco/src/World/Company.cpp, src/OpenLoco/src/World/Company.h, src/OpenLoco/src/World/CompanyAi.cpp, src/OpenLoco/src/World/CompanyAi.h, src/OpenLoco/src/World/Station.cpp, src/OpenLoco/src/World/StationManager.cpp, src/OpenLoco/src/World/StationManager.h
Continue from #2286
Cleans up how company emotions work and implements the update emotion function.
=> Company Emotion Functions

src/OpenLoco/src/Config.cpp, src/OpenLoco/src/Config.h, src/OpenLoco/src/Network/NetworkClient.cpp, src/OpenLoco/src/Windows/CompanyWindow.cpp, src/OpenLoco/src/Windows/Options.cpp, src/OpenLoco/src/World/CompanyManager.cpp
=> Move preferred owner name settings to new config

src/OpenLoco/src/Config.cpp, src/OpenLoco/src/Config.h, src/OpenLoco/src/ConfigConvert.hpp, src/OpenLoco/src/Scenario.cpp, src/OpenLoco/src/Windows/Options.cpp
=> Move preferred currency settings to new config

src/OpenLoco/src/Audio/Audio.cpp, src/OpenLoco/src/GameCommands/Industries/CreateIndustry.cpp, src/OpenLoco/src/Map/MapGenerator/MapGenerator.cpp, src/OpenLoco/src/Map/SurfaceElement.h, src/OpenLoco/src/Map/TileManager.cpp, src/OpenLoco/src/Objects/ObjectIndex.cpp, src/OpenLoco/src/World/Industry.cpp
Small function that sets the upper bits of the slope byte of surface elements. Still no idea what they're for, unfortunately.
=> Implement MapGenerator::generateSurfaceVariation

src/OpenLoco/src/GameCommands/Cheats/Cheat.h
Regression from #2319. Fixes #2350.
=> Fix regression in cheat command

src/OpenLoco/src/Map/MapGenerator/MapGenerator.cpp
Result is not as smooth as vanilla yet, particularly when double height corners should be used. Not sure where it's going wrong yet. Would appreciate a second pair of eyes.
=> Implement MapGenerator::generateLand

src/OpenLoco/src/GameSaveCompare.cpp, src/OpenLoco/src/GameState.h, src/OpenLoco/src/Objects/ObjectManager.cpp, src/OpenLoco/src/Objects/ObjectManager.h, src/OpenLoco/src/OpenLoco.cpp, src/OpenLoco/src/S5/S5.h
I don't think this function should be under ObjectManager but not sure where it should go. Also the name isn't great.
=> Implement update level crossing

src/OpenLoco/src/GameCommands/Track/CreateTrainStation.cpp
Another month another issue with train stations. I think this now makes sense as it matches how the road ones work.
=> Fix train station again

src/OpenLoco/src/Objects/TrainSignalObject.h
Another one that doesn't need heap.
=> Refactor signal frames to use constexpr

src/OpenLoco/src/Windows/MapWindow.cpp, src/OpenLoco/src/Windows/ToolbarTopCommon.cpp, src/OpenLoco/src/World/Company.cpp, src/OpenLoco/src/World/Company.h
This is just a copy paste and invert of getAvailableRailTracks
=> Implement getAvailableRoads

src/OpenLoco/src/GameCommands/Industries/CreateIndustry.cpp, src/OpenLoco/src/Map/TileClearance.cpp, src/OpenLoco/src/Map/TileClearance.h
This is ultimately for #2329 as it uses the two clear function parts but none of the default collision apparatus.
=> Tidy up users of clear functions

src/OpenLoco/CMakeLists.txt, src/OpenLoco/src/GameCommands/GameCommands.cpp, src/OpenLoco/src/GameCommands/Track/CreateTrack.cpp, src/OpenLoco/src/GameCommands/Track/CreateTrack.h, src/OpenLoco/src/Localisation/StringIds.h, src/OpenLoco/src/Map/RoadElement.h, src/OpenLoco/src/Map/TileClearance.cpp, src/OpenLoco/src/Map/TileClearance.h, src/OpenLoco/src/Map/Track/TrackData.h, src/OpenLoco/src/Map/TrackElement.h, src/OpenLoco/src/Objects/BridgeObject.h, src/OpenLoco/src/Windows/Construction/ConstructionTab.cpp
Should work. Still to test with ai.
=> Create Track Game Command

src/OpenLoco/CMakeLists.txt, src/OpenLoco/src/GameCommands/Buildings/CreateBuilding.cpp, src/OpenLoco/src/GameCommands/Buildings/CreateBuilding.h, src/OpenLoco/src/GameCommands/GameCommands.cpp, src/OpenLoco/src/GameCommands/Industries/CreateIndustry.cpp, src/OpenLoco/src/Localisation/StringIds.h, src/OpenLoco/src/Map/BuildingElement.h, src/OpenLoco/src/Map/TileClearance.cpp
should work. Not fully tested.
=> Implement createBuilding game command

CHANGELOG.md, src/OpenLoco/src/Vehicles/OrderManager.cpp
Made a mistake when i tried to fix this before in that i incremented it even when it shouldn't be incremented! I've added an exception so that the game at least crashes instead of hangs if it gets into trouble.
=> Fix order display frame again

src/OpenLoco/src/Map/MapGenerator/MapGenerator.cpp
=> Change terrain ranges to be more natural

src/OpenLoco/src/EditorController.cpp, src/OpenLoco/src/Graphics/Gfx.cpp, src/OpenLoco/src/Graphics/Gfx.h, src/OpenLoco/src/Graphics/ImageIds.h, src/OpenLoco/src/Input/Keyboard.cpp, src/OpenLoco/src/Intro.cpp, src/OpenLoco/src/Intro.h, src/OpenLoco/src/Localisation/StringIds.h, src/OpenLoco/src/Scenario.cpp, src/OpenLoco/src/Title.cpp, src/OpenLoco/src/Title.h, src/OpenLoco/src/Ui.cpp, src/OpenLoco/src/Windows/ObjectSelectionWindow.cpp
I realised this was the reason i couldn't get gui to work when running without any calls.
=> Implement enough of Intro to get no loco running

src/OpenLoco/src/Map/TileElementBase.h, src/OpenLoco/src/Map/TileManager.cpp
To take NO_LOCO a bit further before crashing.
=> Implement insert element

src/OpenLoco/src/Ui/Widget.cpp, src/OpenLoco/src/Ui/Widget.h, src/OpenLoco/src/Ui/Window.cpp, src/OpenLoco/src/Ui/Window.h, src/OpenLoco/src/Windows/CompanyWindow.cpp, src/OpenLoco/src/Windows/IndustryWindow.cpp, src/OpenLoco/src/Windows/Main.cpp, src/OpenLoco/src/Windows/News/News.cpp, src/OpenLoco/src/Windows/StationWindow.cpp, src/OpenLoco/src/Windows/TownWindow.cpp, src/OpenLoco/src/Windows/Vehicle.cpp
This will be a bigger cleanup and update so I've put it into draft. I'm trying to make widgets actual widgets and not rely as much on drawing anything by hand, quite a bit is already done so its already at a good point to test the changes, we have no tests for the UI so its best to catch things early on.
=> Widget refactor

data/language/nl-NL.yml
I've ran into some non-translated strings while playing this with my daughter and also while implementing #2426, so I translated those. There are still a lot other translations left to do of course. 😄
=> Implement further Dutch localization

src/OpenLoco/src/Windows/MapWindow.cpp
Split off from #2443 for easier review.
=> Refactor MapWindow::setHoverItemTab

src/OpenLoco/src/GameCommands/Track/RemoveTrainStation.cpp
This probably won't ever be an issue for normal train stations, but perhaps for hacked diagonal ones?
=> Minor improvements to removeTrainStation with hindsight

src/OpenLoco/src/Map/SurfaceElement.cpp, src/OpenLoco/src/Map/SurfaceElement.h, src/OpenLoco/src/Map/TileManager.cpp
We have a small mistake in our code where the iterator in TileManager::update will be invalid. I'm not sure this will cause any issues but eitherway I've made it safe now. But will it desync my replays...
Update: No it doesn't desync replays :)
=> Surface update

src/OpenLoco/src/Config.cpp, src/OpenLoco/src/Environment.cpp, src/OpenLoco/src/Environment.h, src/OpenLoco/src/Localisation/Formatting.cpp, src/OpenLoco/src/OpenLoco.cpp
I'm not sure i like the locale stuff but this works.
=> Implement the remaining formatting functions with libfmt

src/OpenLoco/CMakeLists.txt, src/OpenLoco/src/GameCommands/Docks/RemovePort.cpp, src/OpenLoco/src/GameCommands/Docks/RemovePort.h, src/OpenLoco/src/GameCommands/GameCommands.cpp, src/OpenLoco/src/Localisation/StringIds.h
Based on #2422, so merge after that one.
=> Implement removePort game command

CHANGELOG.md, src/OpenLoco/src/Paint/Paint.cpp
=> Fix >1 tunnels on one tile not drawing

CHANGELOG.md, src/OpenLoco/src/OpenLoco.cpp, src/OpenLoco/src/S5/S5.cpp, src/OpenLoco/src/S5/S5.h
=> Hide progress bars for autosaves

src/OpenLoco/src/Ui/WindowManager.cpp
Backport from https://github.com/OpenRCT2/OpenRCT2/pull/22060.
Hasn't caused any issues in OpenLoco, as far as I'm aware. However, the code was clearly not using the right variable.
=> Don't confuse entryWidgetType and targetWidgetType in stepperWheelInput

src/OpenLoco/CMakeLists.txt, src/OpenLoco/src/Effects/MoneyEffect.cpp, src/OpenLoco/src/Graphics/DrawingContext.h, src/OpenLoco/src/Graphics/Font.h, src/OpenLoco/src/Graphics/Gfx.cpp, src/OpenLoco/src/Graphics/Gfx.h, src/OpenLoco/src/Graphics/SoftwareDrawingContext.cpp, src/OpenLoco/src/Graphics/SoftwareDrawingContext.h, src/OpenLoco/src/Localisation/Formatting.h, src/OpenLoco/src/Objects/CurrencyObject.cpp, src/OpenLoco/src/Paint/Paint.cpp, src/OpenLoco/src/Ui/Dropdown.cpp, src/OpenLoco/src/Ui/TextInput.cpp, src/OpenLoco/src/Ui/Widget.cpp, src/OpenLoco/src/Viewport.cpp, src/OpenLoco/src/Windows/CompanyFaceSelection.cpp, src/OpenLoco/src/Windows/Error.cpp, src/OpenLoco/src/Windows/MapWindow.cpp, src/OpenLoco/src/Windows/ObjectSelectionWindow.cpp, src/OpenLoco/src/Windows/PromptBrowseWindow.cpp, src/OpenLoco/src/Windows/TitleExit.cpp, src/OpenLoco/src/Windows/ToolTip.cpp, src/OpenLoco/src/Windows/Vehicle.cpp
I think this makes a bit more sense, I also created a few new functions to burry the implementation details and how Font is added as an offset.
=> Font refactor

src/OpenLoco/src/Localisation/StringIds.h, src/OpenLoco/src/Map/MapGenerator/MapGenerator.cpp, src/OpenLoco/src/Map/TileManager.cpp, src/OpenLoco/src/Map/TileManager.h, src/OpenLoco/src/OpenLoco.cpp, src/OpenLoco/src/S5/S5.cpp
=> Implement tile defrag function

src/OpenLoco/src/Graphics/PaletteMap.cpp, src/OpenLoco/src/Graphics/PaletteMap.h, src/OpenLoco/src/Objects/ObjectManager.cpp, src/OpenLoco/src/Objects/WaterObject.h
Based on #2518, so needs to be rebased.
=> Implement updateWaterPalette (0x004C57A6)

src/OpenLoco/src/Audio/Audio.cpp, src/OpenLoco/src/GameCommands/GameCommands.cpp, src/OpenLoco/src/Localisation/Formatting.cpp, src/OpenLoco/src/Objects/ObjectManager.h, src/OpenLoco/src/Scenario.cpp, src/OpenLoco/src/Vehicles/Vehicle.h, src/OpenLoco/src/Vehicles/VehicleBody.cpp, src/OpenLoco/src/Vehicles/VehicleHead.cpp, src/OpenLoco/src/Windows/Construction/Common.cpp, src/OpenLoco/src/Windows/TerraForm.cpp, src/OpenLoco/src/Windows/TextInputWindow.cpp, src/OpenLoco/src/Windows/TileInspector.cpp
Only the ObjectManager should be able to mutate them so lets make this more strict.
=> Return objects as const

CHANGELOG.md, src/OpenLoco/src/Windows/Vehicle.cpp
=> Fix ghost vehicles staying placed down when placement is interrupted

src/OpenLoco/src/Map/RoadElement.cpp, src/OpenLoco/src/Map/RoadElement.h, src/OpenLoco/src/Windows/Construction/ConstructionTab.cpp
This is just a copy paste modify job.
=> Implement Construct drawRoad

thirdparty/CMakeLists.txt
The author recently added a lot more of the static storage containers and also contains few improvements overall.
=> Update sfl library to 1.7.0

src/OpenLoco/CMakeLists.txt, src/OpenLoco/src/GameCommands/GameCommands.cpp, src/OpenLoco/src/GameCommands/Vehicles/VehiclePlace.cpp, src/OpenLoco/src/GameCommands/Vehicles/VehiclePlace.h, src/OpenLoco/src/Localisation/StringIds.h, src/OpenLoco/src/Vehicles/Vehicle.h, src/OpenLoco/src/Vehicles/VehicleManager.cpp, src/OpenLoco/src/Vehicles/VehicleManager.h
Seems to work. Could do with breaking up into sub functions.
=> Game Commands: Place vehicle

src/OpenLoco/src/Ui/WindowManager.h, src/OpenLoco/src/Vehicles/VehicleDraw.cpp, src/OpenLoco/src/Vehicles/VehicleDraw.h, src/OpenLoco/src/Windows/BuildVehicle.cpp, src/OpenLoco/src/Windows/DragVehiclePart.cpp, src/OpenLoco/src/Windows/Vehicle.cpp, src/OpenLoco/src/Windows/VehicleList.cpp
These haven't been implemented quite like vanilla so will need a bit of testing.
=> Implement Vehicle Inline Draw

src/OpenLoco/src/Economy/Economy.cpp, src/OpenLoco/src/Economy/Economy.h, src/OpenLoco/src/World/Company.cpp, src/OpenLoco/src/World/Company.h, src/OpenLoco/src/World/CompanyManager.cpp
~~Not tested at all~~ tested a bit
=> Company update monthly1

src/OpenLoco/src/GameSaveCompare.cpp, src/OpenLoco/src/GameState.h, src/OpenLoco/src/Map/RoadElement.cpp, src/OpenLoco/src/Map/RoadElement.h, src/OpenLoco/src/Map/TileManager.cpp, src/OpenLoco/src/Map/Track/Track.cpp, src/OpenLoco/src/S5/S5.h, src/OpenLoco/src/Vehicles/Vehicle.cpp, src/OpenLoco/src/Windows/CompanyWindow.cpp, src/OpenLoco/src/World/Company.cpp, src/OpenLoco/src/World/Company.h, src/OpenLoco/src/World/CompanyManager.cpp
Two update yearly functions. The road one is a bit odd but i think it ties in with RoadElement::update.
=> Company Update Yearly

src/OpenLoco/CMakeLists.txt, src/OpenLoco/src/GameCommands/Airports/RemoveAirport.cpp, src/OpenLoco/src/GameCommands/Road/CreateRoadStation.cpp, src/OpenLoco/src/GameCommands/Track/CreateTrainStation.cpp, src/OpenLoco/src/Map/AnimationManager.cpp, src/OpenLoco/src/Map/StationElement.cpp, src/OpenLoco/src/Map/StationElement.h, src/OpenLoco/src/Objects/AirportObject.cpp, src/OpenLoco/src/Objects/AirportObject.h, src/OpenLoco/src/Objects/DockObject.cpp, src/OpenLoco/src/Objects/DockObject.h
=> Station Animation Update

src/OpenLoco/CMakeLists.txt, src/OpenLoco/src/Map/AnimationManager.cpp, src/OpenLoco/src/Map/RoadElement.cpp, src/OpenLoco/src/Map/RoadElement.h, src/OpenLoco/src/Map/SignalElement.cpp, src/OpenLoco/src/Map/SignalElement.h, src/OpenLoco/src/Objects/LevelCrossingObject.h, src/OpenLoco/src/Objects/TrainSignalObject.h
The remaining two animation updates
=> Signal/Level Crossing Animation Update

CHANGELOG.md, CMakePresets.json, cmake/OpenLocoUtility.cmake, src/OpenLoco/CMakeLists.txt, thirdparty/CMakeLists.txt
Address's https://github.com/OpenLoco/OpenLoco/issues/2514 by not using the system runtime.
=> Switch to statically compiled dependencies

src/OpenLoco/src/GameCommands/Road/CreateRoadStation.cpp, src/OpenLoco/src/GameCommands/Track/CreateSignal.cpp, src/OpenLoco/src/Map/Track/Track.cpp, src/OpenLoco/src/Map/Track/Track.h, src/OpenLoco/src/Vehicles/Routing.cpp, src/OpenLoco/src/Vehicles/VehicleHead.cpp, src/OpenLoco/src/Windows/Construction/ConstructionTab.cpp
This changes things so we aren't using globals to pass around values.
=> Track Connections Refactor

src/OpenLoco/CMakeLists.txt, src/OpenLoco/src/GameCommands/Docks/CreatePort.cpp, src/OpenLoco/src/GameCommands/Docks/CreatePort.h, src/OpenLoco/src/GameCommands/GameCommands.cpp, src/OpenLoco/src/GameCommands/GameCommands.h, src/OpenLoco/src/GameCommands/Track/CreateTrack.cpp, src/OpenLoco/src/Localisation/StringIds.h, src/OpenLoco/src/Map/TileClearance.cpp, src/OpenLoco/src/Objects/DockObject.cpp, src/OpenLoco/src/Objects/DockObject.h
Seems to work. Haven't done replay tests on it yet.
=> Implement Create Port Game Command

src/OpenLoco/src/Paint/Paint.cpp
This is heavily inspired by @mrmbernardi 's https://github.com/OpenRCT2/OpenRCT2/pull/22239
=> Implement sprite interaction

src/Math/include/OpenLoco/Math/Vector.hpp, src/OpenLoco/src/GameCommands/Track/CreateTrainStation.cpp, src/OpenLoco/src/Map/Track/Track.cpp, src/OpenLoco/src/Map/Track/Track.h, src/OpenLoco/src/World/StationManager.cpp, src/OpenLoco/src/World/StationManager.h
~~I think i'm going to rework `getTrackConnections` first~~ Not tested yet
=> Implement find nearby station

src/OpenLoco/src/World/StationManager.cpp
=> Implement removeStationFromCargoStats

CHANGELOG.md, src/OpenLoco/src/Objects/Object.h, src/OpenLoco/src/Objects/ObjectManager.cpp, src/OpenLoco/src/Scenario.cpp, src/OpenLoco/src/World/CompanyManager.cpp
This fixes the preferred company/currency selection being safe.
=> Make preferred company face loading safe

src/OpenLoco/src/GameCommands/Vehicles/VehiclePlaceAir.cpp, src/OpenLoco/src/Objects/AirportObject.cpp, src/OpenLoco/src/Objects/AirportObject.h, src/OpenLoco/src/Objects/DockObject.cpp, src/OpenLoco/src/Objects/DockObject.h, src/OpenLoco/src/Paint/PaintAirport.cpp, src/OpenLoco/src/Paint/PaintBuilding.cpp, src/OpenLoco/src/Paint/PaintDocks.cpp, src/OpenLoco/src/Paint/PaintIndustry.cpp, src/OpenLoco/src/Vehicles/Vehicle.cpp, src/OpenLoco/src/Vehicles/Vehicle.h, src/OpenLoco/src/Vehicles/VehicleHead.cpp
Mostly a copy paste exercise and a bunch of renaming things
Found a few minor mistakes in other code when comparing the various building painters.
=> Paint docks and airports

CHANGELOG.md, src/OpenLoco/src/Windows/MessageWindow.cpp
=> Save playNewsSounds option on change

src/OpenLoco/src/GameCommands/GameCommands.cpp, src/OpenLoco/src/Localisation/StringIds.h, src/OpenLoco/src/World/Company.cpp, src/OpenLoco/src/World/CompanyManager.cpp, src/OpenLoco/src/World/CompanyManager.h
=> Implement ensureCompanyFunding

src/OpenLoco/src/GameCommands/Track/CreateTrack.cpp, src/OpenLoco/src/Map/SurfaceElement.cpp, src/OpenLoco/src/Map/TileManager.cpp, src/OpenLoco/src/Map/TileManager.h
These two functions were just specialisations of existing functions.
=> Implement two reset surface functions

src/Math/include/OpenLoco/Math/Vector.hpp, src/OpenLoco/src/World/Industry.cpp
Fixes issues after std::min/std::max no longer in cmath header.
=> Fix build on latest MSVC

src/OpenLoco/CMakeLists.txt, src/OpenLoco/src/GameCommands/GameCommands.cpp, src/OpenLoco/src/GameCommands/Track/RemoveTrack.cpp, src/OpenLoco/src/GameCommands/Track/RemoveTrack.h
~Multitile track pieces aren't removed properly yet. Needs investigating.~
=> Implement track removal game command

src/OpenLoco/src/GameCommands/GameCommands.cpp, src/OpenLoco/src/GameCommands/Track/RemoveTrack.cpp, src/OpenLoco/src/Map/TileManager.cpp
playTrackRemovalSound also had the wrong frequency range.
This is from https://github.com/OpenLoco/OpenLoco/pull/2585 but putting it separate
=> Fix for sounds using wrong prng

CHANGELOG.md, src/OpenLoco/src/World/StationManager.cpp
Found this whilst doing #2585. I don't understand how i've missed this when checking replays.
=> Fix #2372. Large square stations could not be created

src/OpenLoco/CMakeLists.txt, src/OpenLoco/src/GameCommands/Airports/CreateAirport.cpp, src/OpenLoco/src/GameCommands/Airports/CreateAirport.h, src/OpenLoco/src/GameCommands/Docks/CreatePort.cpp, src/OpenLoco/src/GameCommands/GameCommands.cpp, src/OpenLoco/src/Localisation/StringIds.h, src/OpenLoco/src/Objects/AirportObject.h, src/OpenLoco/src/World/Station.h
=> Implement Create Airport

src/OpenLoco/src/Ui/Dropdown.cpp, src/OpenLoco/src/Ui/Dropdown.h, src/OpenLoco/src/World/CompanyManager.cpp
=> Implement select new competitor

src/OpenLoco/src/Interop/Hooks.cpp, src/OpenLoco/src/Map/Track/Track.cpp, src/OpenLoco/src/Map/Track/Track.h, src/OpenLoco/src/Vehicles/Vehicle.cpp, src/OpenLoco/src/Vehicles/Vehicle.h
This is for #2568 based on #2174.
Currently matches replays but need to do the following things:
~~1. Add hooks for the function and confirm replays still match.~~
~~2. Fix function to not use globals and remove the hacks. Record new replay masters.~~
Replays still match after hooks
=> Update road motion

src/OpenLoco/src/GameCommands/Docks/CreatePort.cpp, src/OpenLoco/src/GameCommands/Road/CreateRoadStation.cpp
Mostly a copy paste job from track (Good to see CS also copy pasted it)
=> Find Nearby Station: Docks and Road

src/OpenLoco/src/Ui/WindowManager.h, src/OpenLoco/src/Windows/CompanyList.cpp, src/OpenLoco/src/World/CompanyManager.cpp, src/OpenLoco/src/World/CompanyRecords.h
=> Implement aiDestroy

src/OpenLoco/src/Input/MouseInput.cpp
=> Refactor some Ui::Point variables

src/OpenLoco/src/Windows/Construction/Common.cpp, src/OpenLoco/src/Windows/Construction/Construction.h, src/OpenLoco/src/Windows/Construction/ConstructionTab.cpp, src/OpenLoco/src/Windows/Construction/OverheadTab.cpp, src/OpenLoco/src/Windows/Construction/SignalTab.cpp, src/OpenLoco/src/Windows/Construction/StationTab.cpp
Replaces a bunch of consecutive loco_globals with one.
=> Introduce ConstructionState struct

src/OpenLoco/src/Windows/CompanyList.cpp
Replaces a bunch of consecutive loco_globals with one.
=> Introduce GraphSettings struct

src/OpenLoco/src/GameCommands/Vehicles/CreateVehicle.cpp, src/OpenLoco/src/Objects/VehicleObject.cpp, src/OpenLoco/src/Objects/VehicleObject.h, src/OpenLoco/src/Paint/PaintVehicle.cpp, src/OpenLoco/src/Vehicles/VehicleBody.cpp, src/OpenLoco/src/Vehicles/VehicleDraw.cpp
Further findings from the asset replacement project
=> Name some vehicle object unks

CHANGELOG.md, src/OpenLoco/src/Environment.cpp, src/OpenLoco/src/Environment.h, src/OpenLoco/src/GameCommands/Company/RenameCompanyOwner.cpp, src/OpenLoco/src/Objects/ObjectIndex.cpp, src/OpenLoco/src/Objects/ObjectIndex.h, src/OpenLoco/src/Objects/ObjectManager.cpp, src/OpenLoco/src/Objects/ObjectManager.h, src/OpenLoco/src/Scenario.cpp, src/OpenLoco/src/Windows/CompanyFaceSelection.cpp, src/OpenLoco/src/Windows/ObjectSelectionWindow.cpp, src/OpenLoco/src/Windows/Options.cpp, src/OpenLoco/src/World/CompanyManager.cpp
Rework to make things slightly easier to use... Oh it also handles folders.
=> Object Index Redesign

src/OpenLoco/src/Objects/ObjectIndex.cpp, src/OpenLoco/src/Ui/Windows/CompanyFaceSelection.cpp, src/OpenLoco/src/Ui/Windows/ObjectSelectionWindow.cpp
Was causing a replay desync due to the dynamically loaded ai companies.
=> Move sorting of the index back into the index

CHANGELOG.md, CMakeLists.txt, data/language/en-GB.yml, src/OpenLoco/src/Localisation/StringIds.h, src/OpenLoco/src/Objects/Object.h, src/OpenLoco/src/Ui/Windows/ObjectSelectionWindow.cpp
This adds our first release of objects to the base. ~~Should probably add a OpenLoco filter to the object selection window.~~
=> Add OpenGraphics objects

src/OpenLoco/src/GameSaveCompare.cpp
Split off from #2681
Now does tile x/y comparisons so an inserted/removed tile doesn't blow up the whole thing. Also tells you the x/y coordinates of the divergence which is very useful.
=> Improve the tile game save compare

CHANGELOG.md, src/OpenLoco/src/GameCommands/Track/RemoveTrack.cpp, src/OpenLoco/src/Ui/Windows/Construction/ConstructionTab.cpp
~~Can't quite work out where its gone wrong for #2692 though. Still looking~~
Two little mistakes that caused issues on steep curves.
=> Fix #2690. Unable to remove certain multi tile track

thirdparty/CMakeLists.txt
Now we can properly use ranges and construct span with more ease.
=> Bump sfl library to 1.8.1

CHANGELOG.md, src/OpenLoco/src/Ui/Windows/Options.cpp
Broke this when i changed the object index.
=> Fix #2725. Currency selection garbage data

CHANGELOG.md, src/OpenLoco/src/Paint/PaintBuilding.cpp, src/OpenLoco/src/Paint/PaintIndustry.cpp
Woops made this mistake whilst implementing as i didn't test with larger buildings.
=> Fix #2705. Scaffolding display fail

src/OpenLoco/src/Objects/RoadStationObject.cpp, src/OpenLoco/src/Objects/RoadStationObject.h, src/OpenLoco/src/Paint/PaintRoadStation.cpp
This is basically a big copy paste of train station with a few minor tweaks.
=> Implement paint road station

src/OpenLoco/src/Paint/PaintTile.cpp
~~Absolutely no~~ some testing has been done.
=> Implement paint supports

src/OpenLoco/src/GameCommands/Vehicles/CreateVehicle.cpp, src/OpenLoco/src/Vehicles/Vehicle.h, src/OpenLoco/src/Vehicles/VehicleHead.cpp, src/OpenLoco/src/World/Company.cpp, src/OpenLoco/src/World/Company.h, src/OpenLoco/src/World/CompanyAi.cpp, src/OpenLoco/src/World/CompanyAi.h
There a good few issues in the vanilla version of this. I'm somewhat surprised it matches the replays.
=> Company Ai: Purchase Vehicle

src/OpenLoco/src/World/Station.cpp
In #2715 I choped and changed over having the limit be 15 or 16 i.e. inclusive or exclusive seems i forgot to change one place when settling on inclusive.
=> Fix incorrect limit after adding constant

src/OpenLoco/src/Paint/Paint.cpp, src/OpenLoco/src/Paint/Paint.h
This one is a bit of special one with its bb modifications.
=> Implement final addToPlotList

src/Core/include/OpenLoco/Core/Numerics.hpp, src/OpenLoco/src/Interop/Hooks.cpp, src/OpenLoco/src/Paint/Paint.cpp, src/OpenLoco/src/Paint/Paint.h, src/OpenLoco/src/Ui/ViewportInteraction.cpp, src/OpenLoco/src/Ui/Windows/Construction/ConstructionTab.cpp, src/OpenLoco/src/Viewport.cpp
Currently in draft as I plan to refactor some things.
=> Paint interop removal

src/OpenLoco/src/GameCommands/Vehicles/CreateVehicle.cpp, src/OpenLoco/src/Vehicles/Vehicle.h, src/OpenLoco/src/World/CompanyAi.cpp, src/OpenLoco/src/World/CompanyAi.h
This is mostly to do with removing AiAllocated things (i.e. the ai ghosts). Also decided to start adding some stronger types to the ai structs.
=> Implement Company Ai: Remove AiAllocated

src/OpenLoco/src/World/CompanyAi.cpp, src/OpenLoco/src/World/CompanyAi.h
This is the auto signal placement code. @LeftofZen
=> Implement Company Ai: AiAllocated Signals

src/OpenLoco/src/Vehicles/Vehicle.cpp
Based on #2174
The original code for this was a bit inefficient so i've made a few changes.
=> Implement train collision detection

CHANGELOG.md, src/OpenLoco/src/Paint/PaintStation.cpp
=> Fix #2791. Cargo density incorrectly shown

thirdparty/CMakeLists.txt
Some new good containers.
https://github.com/slavenf/sfl-library/releases/tag/1.9.0
=> Update sfl to 1.9.0

src/Core/include/OpenLoco/Core/LocoFixedVector.hpp, src/OpenLoco/src/Map/TileLoop.hpp, src/OpenLoco/src/World/Company.h, src/OpenLoco/src/World/CompanyAi.cpp, src/OpenLoco/src/World/CompanyAi.h
=> Implement Company Ai: AiAllocated Station Stats

src/OpenLoco/src/Ui/WindowManager.cpp
Fixes issue from #2824 that is causing the replay check to fail.
=> Use global for font in hook

CHANGELOG.md, src/OpenLoco/src/Paint/PaintBridge.cpp
This is a little odd but couldn't see an easier way to pull it off.
=> Fix #2818. Incorrect bridge segment

.github/workflows/ci.yml, .github/workflows/clang-tidy.yml
Depends on https://github.com/OpenLoco/openloco-docker-build/pull/14
=> Update ci for new images

src/OpenLoco/src/GameCommands/Airports/CreateAirport.cpp, src/OpenLoco/src/GameCommands/Buildings/CreateBuilding.cpp, src/OpenLoco/src/GameCommands/Docks/CreatePort.cpp, src/OpenLoco/src/GameCommands/Terraform/ClearLand.cpp, src/OpenLoco/src/GameCommands/Terraform/LowerLand.cpp, src/OpenLoco/src/GameCommands/Terraform/LowerLand.h, src/OpenLoco/src/GameCommands/Terraform/LowerRaiseLandMountain.cpp, src/OpenLoco/src/GameCommands/Terraform/LowerWater.cpp, src/OpenLoco/src/GameCommands/Terraform/RaiseLand.cpp, src/OpenLoco/src/GameCommands/Terraform/RaiseLand.h, src/OpenLoco/src/GameCommands/Terraform/RaiseWater.cpp, src/OpenLoco/src/GameCommands/Track/CreateTrack.cpp, src/OpenLoco/src/Map/TileClearance.cpp, src/OpenLoco/src/Map/TileClearance.h, src/OpenLoco/src/Map/TileManager.cpp, src/OpenLoco/src/Map/TileManager.h, src/OpenLoco/src/Vehicles/Routing.cpp, src/OpenLoco/src/World/StationManager.cpp, src/OpenLoco/src/World/StationManager.h
Now it's actually free of any allocations, well almost, some of the string formatting sometimes requires heap but that is pretty hard to get rid of entirely as some of it comes from libfmt.
=> Eliminate most heap allocations each frame

src/OpenLoco/src/Ui/WindowManager.cpp
Same as https://github.com/OpenRCT2/OpenRCT2/pull/23702
=> Fix out of bounds access testing for stepper group

CHANGELOG.md, CONTRIBUTORS.md, data/language/sv-SE.yml
Adds Swedish as an interface language. Note, I did run the file though a prettifyer
=> Add Swedish language file

src/OpenLoco/src/GameCommands/Docks/CreatePort.cpp, src/OpenLoco/src/GameCommands/GameCommands.h, src/OpenLoco/src/Map/Track/TrackEnum.h, src/OpenLoco/src/Ui/Windows/Construction/Common.cpp, src/OpenLoco/src/Vehicles/Vehicle.h, src/OpenLoco/src/Vehicles/VehicleBody.cpp, src/OpenLoco/src/World/Company.h, src/OpenLoco/src/World/CompanyAi.cpp, src/OpenLoco/src/World/Station.cpp, src/OpenLoco/src/World/Station.h
~~WiP.~~ This is a huge function.
Continues from #2790
=> Implement Company Ai: AiAllocated Stations

src/OpenLoco/src/Audio/Audio.h, src/OpenLoco/src/Map/Tile.h, src/OpenLoco/src/Vehicles/Vehicle.h, src/OpenLoco/src/Vehicles/VehicleHead.cpp
~~Not tested.~~ Tested with replays
~~Depends on #2839~~
=> Implement Water Path Finding

src/OpenLoco/src/World/CompanyAi.cpp
=> Implement Company Ai: Sell Thought Vehicle

src/OpenLoco/src/World/Company.h, src/OpenLoco/src/World/CompanyAi.cpp
~~Depends on #2793 and #2805~~
Ready for review
=> Implement Company Ai: Thought Setup Part 1

src/OpenLoco/src/World/Company.h, src/OpenLoco/src/World/CompanyAi.cpp, src/OpenLoco/src/World/CompanyAi.h
~~WiP depends on #2807~~ Ready for review
=> Implement Company Ai: Thought Setup Part 2

src/OpenLoco/src/World/Station.cpp
TBC on the name of the function
=> Station Sequence Index / Stage / Phenotype

src/OpenLoco/src/Objects/LandObject.h, src/OpenLoco/src/Objects/WaterObject.h
Came across these two when comparing the locotool definitions.
=> Fix 2 incorrect object field sizes

src/OpenLoco/src/GameCommands/Vehicles/CreateVehicle.cpp, src/OpenLoco/src/GameCommands/Vehicles/VehiclePlaceAir.cpp, src/OpenLoco/src/Vehicles/Vehicle.h, src/OpenLoco/src/Vehicles/Vehicle2.cpp, src/OpenLoco/src/Vehicles/VehicleBody.cpp, src/OpenLoco/src/Vehicles/VehicleHead.cpp
A bit of digging around and I think this matches all the behaviors.
~~Note for review that `onRackRail` value is inverted - `onRackRail = true` is off the rack rail, and `onRackRail = false` is on the rack rail.~~ Trains cannot slip to a halt on rack rail, but they can off rack rail.
=> Enumerate Vehicle2::var_5A and rename

src/OpenLoco/src/Audio/Audio.cpp, src/OpenLoco/src/Audio/Audio.h, src/OpenLoco/src/Audio/VehicleChannel.cpp, src/OpenLoco/src/Interop/Hooks.cpp, src/OpenLoco/src/Objects/VehicleObject.cpp, src/OpenLoco/src/Objects/VehicleObject.h, src/OpenLoco/src/Vehicles/Vehicle.h, src/OpenLoco/src/Vehicles/VehicleHead.cpp
almost all renames, with one small rearrangement
=> rename variables related to vehicle sounds

CHANGELOG.md, src/OpenLoco/src/Ui/Windows/ObjectSelectionWindow.cpp
solves #2917 2917
You can play with your new trains right away :D
=> #2917: recalculate available vehicles after selecting

src/OpenLoco/src/Vehicles/Vehicle.cpp
The change of std::optional seems to have measurable impact on performance, its not a lot but its basically free. 
Example to how it impacts code gen: https://godbolt.org/z/5hqhMacvE
=> Minor code improvements

src/OpenLoco/src/Ui/Windows/Cheats.cpp
Similar issue to #2929.
Before:
After:
=> Fix cheat window's company dropdown

src/OpenLoco/src/GameCommands/Airports/CreateAirport.cpp, src/OpenLoco/src/World/StationManager.cpp, src/OpenLoco/src/World/StationManager.h
Not Tested ~~can probably be deduplciated~~
=> Implement airport find nearby station

src/OpenLoco/src/Objects/ObjectManager.cpp
=> Implement Reset Default Land Object

src/OpenLoco/CMakeLists.txt, src/OpenLoco/src/GameCommands/GameCommands.cpp, src/OpenLoco/src/GameCommands/Road/CreateRoad.cpp, src/OpenLoco/src/GameCommands/Road/CreateRoad.h, src/OpenLoco/src/Localisation/StringIds.h, src/OpenLoco/src/Map/RoadElement.h, src/OpenLoco/src/Map/TileManager.cpp, src/OpenLoco/src/Map/TileManager.h, src/OpenLoco/src/Map/Track/TrackEnum.h, src/OpenLoco/src/Ui/Windows/Construction/ConstructionTab.cpp, src/OpenLoco/src/World/CompanyAi.cpp, src/OpenLoco/src/World/Town.cpp
~~Works but its definitely got some bugs.~~
I have encountered a really odd issue with my replays where the result doesn't seem to be deterministic. All that changes is a singular ai allocated road but it seems random as to if it happens.
Other than that all appears to work replay wise up to 100000 ticks on both MixedMuscle and the Randomland save.
=> Road placement

src/OpenLoco/src/Vehicles/Vehicle.cpp
Found this when going to check a replay on 2949. Fixes mistake from #2946 (Should have really checked that PR against the randomland save)
=> Fix flipCar

CHANGELOG.md, src/OpenLoco/src/Localisation/StringIds.h, src/OpenLoco/src/Ui/ViewportInteraction.h, src/OpenLoco/src/Ui/Windows/Vehicle.cpp
Fixes https://github.com/OpenLoco/OpenLoco/issues/2895
=> Implement vehicle map route interaction

src/OpenLoco/src/GameCommands/Vehicles/VehicleRearrange.cpp, src/OpenLoco/src/Ui/Windows/VehicleList.cpp, src/OpenLoco/src/Vehicles/Vehicle.cpp, src/OpenLoco/src/Vehicles/Vehicle.h
Implements sub_4AF4D6 as insertCar
Please squash merge.
=> implement insertCar

src/OpenLoco/src/GameCommands/Town/CreateTown.cpp, src/OpenLoco/src/Interop/Hooks.cpp, src/OpenLoco/src/Map/RoadElement.h, src/OpenLoco/src/Map/Track/TrackData.cpp, src/OpenLoco/src/Map/Track/TrackData.h, src/OpenLoco/src/Objects/RoadObject.h, src/OpenLoco/src/Ui/Windows/TownWindow.cpp, src/OpenLoco/src/World/CompanyAi.cpp, src/OpenLoco/src/World/Town.cpp, src/OpenLoco/src/World/Town.h, src/OpenLoco/src/World/TownManager.cpp
=> Implement Town Growth

src/OpenLoco/src/World/CompanyAi.cpp, src/OpenLoco/src/World/CompanyAi.h
Implements a few simple company ai functions.
=> Implement Company Ai: Replace Ai Allocated Road, Refund Calc, Similar Thought Check

CHANGELOG.md, src/OpenLoco/src/MessageManager.cpp
=> Fix messages getting the wrong vehicle name set

src/OpenLoco/src/Map/TileManager.cpp, src/OpenLoco/src/OpenLoco.cpp, src/OpenLoco/src/OpenLoco.h
This implements the cleanup function that generates the exit string and then i've changed it so that it uses sdl to show a message box with the error.
=> Cleanup exit with error

src/OpenLoco/src/Objects/VehicleObject.cpp, src/OpenLoco/src/Objects/VehicleObject.h
=> remove BodySpriteFlags::UnkSprites

src/OpenLoco/src/GameCommands/Industries/CreateIndustry.cpp, src/OpenLoco/src/Map/IndustryElement.cpp, src/OpenLoco/src/Map/SurfaceElement.cpp, src/OpenLoco/src/Objects/IndustryObject.cpp, src/OpenLoco/src/Objects/IndustryObject.h, src/OpenLoco/src/Paint/PaintIndustry.cpp, src/OpenLoco/src/Paint/PaintSurface.cpp, src/OpenLoco/src/World/Industry.cpp, src/OpenLoco/src/World/Industry.h, src/OpenLoco/src/World/IndustryManager.cpp, src/OpenLoco/src/World/StationManager.cpp
~~I split one function's arguments into two, so its worth doing a replay test.~~
=> Rename flags and fields relating to industry surface tiles

src/OpenLoco/src/GameCommands/Industries/CreateIndustry.cpp, src/OpenLoco/src/Interop/Hooks.cpp, src/OpenLoco/src/World/Industry.cpp, src/OpenLoco/src/World/Industry.h
This one should get replay tested
=> Split combined dl argument into two arguments

src/OpenLoco/src/GameSaveCompare.cpp, src/OpenLoco/src/Localisation/StringIds.h, src/OpenLoco/src/Ui/Windows/ScenarioOptions.cpp, src/OpenLoco/src/World/Company.cpp, src/OpenLoco/src/World/Company.h, src/OpenLoco/src/World/CompanyManager.cpp, src/OpenLoco/src/World/CompanyManager.h
Passes replay tests (after updating replay save compare)
=> Implement Create Company

src/OpenLoco/src/World/Company.cpp
=> Implement Company::getNewChallengeProgress

src/OpenLoco/src/World/Company.cpp
Fix mistake from OpenLoco/OpenLoco#2994
=> Fix crash from get progress

.github/workflows/ci.yml, src/OpenLoco/src/World/Company.h, src/OpenLoco/src/World/CompanyAi/CompanyAi.cpp, src/OpenLoco/src/World/CompanyManager.cpp, src/OpenLoco/src/World/Industry.h, src/OpenLoco/src/World/IndustryManager.cpp, src/OpenLoco/src/World/IndustryManager.h
=> Implement Company Ai: Choosing destinations / initial thought setup

src/OpenLoco/src/GameCommands/Vehicles/CreateVehicle.cpp, src/OpenLoco/src/Objects/VehicleObject.cpp, src/OpenLoco/src/Objects/VehicleObject.h, src/OpenLoco/src/Paint/PaintVehicle.cpp, src/OpenLoco/src/Vehicles/Vehicle.h, src/OpenLoco/src/Vehicles/Vehicle2.cpp, src/OpenLoco/src/Vehicles/VehicleBody.cpp, src/OpenLoco/src/Vehicles/VehicleDraw.cpp
Ignore the branch name kthx
posting this now before it gets even more out of hand
=> Rename several unnamed vehicle properties

CHANGELOG.md, src/OpenLoco/src/World/CompanyAi/CompanyAi.cpp
Adds missing changelog for original bug fix and fixes passing by ref that i meant to remove after confirming randVal not used again.
=> #3013 Cleanup 

CHANGELOG.md, CMakeLists.txt
Adds the RE4/4 replacement, all new fences and the interface object
=> Update objects version to v0.1.3

src/OpenLoco/src/Graphics/InvalidationGrid.cpp, src/OpenLoco/src/Graphics/InvalidationGrid.h
Since people use crazy resolutions lets just make it dynamic to be safe.
=> Make blocks on InvalidationGrid dynamic size

src/OpenLoco/src/Ui/WindowManager.cpp
I was investigating something in OpenRCT2 and was wondering if this function is actually identical to the original and there were a couple mistakes. Also instead of calling it recursively it uses now a loop to obtain the first window.
Was hoping this would fix leaving stray pixels but unfortunately it doesn't, there might be some other mistakes as I believe the code was copied from OpenRCT2 and there are couple issues that aren't in the original so who knows what else I'll find.
=> Closely match the original logic of viewportRedrawAfterShift

src/OpenLoco/src/GameCommands/Road/CreateRoad.cpp, src/OpenLoco/src/Map/Track/Track.cpp, src/OpenLoco/src/Map/Track/Track.h, src/OpenLoco/src/Objects/ObjectIndex.cpp, src/OpenLoco/src/Objects/RoadObject.h, src/OpenLoco/src/Paint/PaintRoad.cpp, src/OpenLoco/src/Vehicles/Vehicle.cpp, src/OpenLoco/src/World/CompanyAi/CompanyAi.cpp, src/OpenLoco/src/World/Town.cpp
~~Will add a hook to verify~~
Ready for review
=> Implement getRoadConnectionsOneWay

src/OpenLoco/src/World/CompanyAi/CompanyAi.cpp, src/OpenLoco/src/World/CompanyAi/CompanyAi.h
=> Implement Company Ai: Choose Station Locations

src/OpenLoco/src/Vehicles/Vehicle.h, src/OpenLoco/src/Vehicles/VehicleHead.cpp, src/OpenLoco/src/World/CompanyAi/CompanyAi.cpp
Lots of loops, probably lots of chance of deduplication but so many of the loops have minor variations.
~~(Not tested)~~
Replays pass
=> Implement Company Ai: Generate Vehicle Purchase Request

src/OpenLoco/src/GameCommands/GameCommands.cpp, src/OpenLoco/src/GameCommands/GameCommands.h, src/OpenLoco/src/World/CompanyAi/CompanyAi.cpp
Replaces the ai allocated track and road assets.
~~Not tested.~~
No divergence on replays.
=> Implement Company Ai: Replace Track/Road AiAllocated assets

src/OpenLoco/src/World/CompanyAi/CompanyAi.cpp
=> Implement Company Ai: Remove all thought track / road

src/OpenLoco/src/GameState.h, src/OpenLoco/src/Input/Shortcuts.cpp, src/OpenLoco/src/Ui/Windows/BuildVehicle.cpp, src/OpenLoco/src/Ui/Windows/ToolbarTop.cpp, src/OpenLoco/src/World/CompanyManager.cpp
pretty simple little function.
=> Implement sub_4A6DA9

CHANGELOG.md, src/OpenLoco/src/Ui/WindowManager.h, src/OpenLoco/src/Ui/Windows/StationWindow.cpp, src/OpenLoco/src/Ui/Windows/VehicleList.cpp
=> List vehicles calling at station in station window

CHANGELOG.md, src/OpenLoco/src/Map/BuildingElement.cpp
=> Prevent building removal by age in scenario editor 

CHANGELOG.md, src/OpenLoco/src/Ui/Windows/ToolbarTopAlt.cpp
=> Tile Inspector in Scenario Editor

CHANGELOG.md, src/OpenLoco/src/Audio/Audio.cpp, src/OpenLoco/src/Ui/Windows/Options.cpp
=> Fix title screen music not playing after switching audio device

CHANGELOG.md, src/OpenLoco/src/Ui/Windows/Construction/Construction.h, src/OpenLoco/src/Ui/Windows/Construction/ConstructionTab.cpp
Fixes #3093 (at least partially)
=>  Fix construction window background being active

src/OpenLoco/src/World/CompanyAi/CompanyAi.cpp
AI would accidentally try build larger than expected trains for short distances
Found this whilst working out an issue in #3111
=> Fix minor divergence

CHANGELOG.md, src/OpenLoco/src/Ui/Window.cpp, src/OpenLoco/src/Ui/Window.h, src/OpenLoco/src/Ui/Windows/Vehicle.cpp, src/OpenLoco/src/Vehicles/VehicleManager.cpp
=> Fix game crash when deleting a vehicle followed on the main viewport

src/OpenLoco/src/Vehicles/Vehicle.h, src/OpenLoco/src/Vehicles/VehicleHead.cpp, src/OpenLoco/src/Vehicles/VehicleTail.cpp
=> Implement VehicleHead::liftUpVehicle

src/OpenLoco/src/World/CompanyAi/CompanyAiPathfinding.cpp
I'm not sure why CS decided to do it like this with track using a gc and road using special functions. I'm also not sure where i should place this function. Any suggestions?
All replays pass.
=> Implement Company Ai: Calculate ai Road replacement cost

src/OpenLoco/src/World/CompanyManager.cpp
Saw this whilst looking at what is left to do.
=> Add missing offset comment

src/OpenLoco/src/World/CompanyAi/CompanyAiPathfinding.cpp
Continues from #3144
~~Making this a draft until #3144 is merged.~~
=> Implement Company Ai: Some sort of compatible track check

src/OpenLoco/src/World/CompanyAi/CompanyAiPathfinding.cpp
I'm still not entirely sure what this is for but it seems to walk all of the ai allocated track for some reason and calculates some estimated costs.
~~Continues from #3145~~
=> Implement Company Ai: Finish allocated ai track walker

src/OpenLoco/src/GameCommands/Vehicles/CreateVehicle.cpp, src/OpenLoco/src/Vehicles/Vehicle.cpp, src/OpenLoco/src/Vehicles/Vehicle.h
implement sub_4AF5E1 as connectJacobsBogies
=> implement connectJacobsBogies

src/OpenLoco/src/Interop/Hooks.cpp, src/OpenLoco/src/World/CompanyAi/CompanyAi.cpp, src/OpenLoco/src/World/CompanyAi/CompanyAiPathfinding.cpp, src/OpenLoco/src/World/CompanyAi/CompanyAiPathfinding.h
This is it the last Ai function implemented!
~~Continues from #3146~~
=> Implement Company Ai: Finish Ai Pathfinding

src/OpenLoco/src/GameCommands/Vehicles/CreateVehicle.cpp, src/OpenLoco/src/Localisation/LanguageFiles.cpp, src/OpenLoco/src/Objects/ObjectIndex.cpp, src/OpenLoco/src/Objects/ObjectManager.cpp
A very small bit of the overlapping globals
=> Remove a number of duplicated globals

CHANGELOG.md, src/OpenLoco/src/Ui/Widgets/CaptionWidget.cpp, src/OpenLoco/src/World/Station.cpp
=> Fix #3171: Background of station labels are off by one pixel

CHANGELOG.md, src/OpenLoco/src/Ui/Windows/MapWindow.cpp
=> Fix minimum map window size

src/OpenLoco/src/Vehicles/Vehicle.cpp, src/OpenLoco/src/Vehicles/Vehicle.h, src/OpenLoco/src/Vehicles/VehicleBogie.cpp
Not much to say pretty simple and almost identical the first bit to OpenRCT2.
=> Implement destroyedBogieCheckForCollision

src/OpenLoco/src/Vehicles/Vehicle.h, src/OpenLoco/src/Vehicles/VehicleHead.cpp, src/OpenLoco/src/Vehicles/VehicleTail.cpp
I'm not entirely sure what this is doing but its clearly to update the train occupied states.
All replays pass.
=> Implement Sub_4AD93A: Some sort of move head function

src/OpenLoco/src/Map/SignalElement.h, src/OpenLoco/src/Vehicles/Routing.cpp, src/OpenLoco/src/Vehicles/Vehicle.cpp, src/OpenLoco/src/Vehicles/Vehicle.h, src/OpenLoco/src/Vehicles/VehicleHead.cpp
This is the main function that works out the route for a train to take to get to a destination.
=> Implement Vehicle Track Routing

src/OpenLoco/src/Vehicles/VehicleHead.cpp
Continues from #3176 (its mostly a copy paste modify with some new bits)
=> Implement Road Routing

src/OpenLoco/src/Audio/Audio.cpp, src/OpenLoco/src/GameCommands/Buildings/CreateBuilding.cpp, src/OpenLoco/src/GameCommands/Docks/CreatePort.cpp, src/OpenLoco/src/Map/BuildingElement.cpp, src/OpenLoco/src/Objects/BuildingObject.cpp, src/OpenLoco/src/Objects/BuildingObject.h, src/OpenLoco/src/Objects/DockObject.cpp, src/OpenLoco/src/Objects/DockObject.h, src/OpenLoco/src/Objects/RoadStationObject.cpp, src/OpenLoco/src/Objects/RoadStationObject.h, src/OpenLoco/src/Objects/SoundObject.cpp, src/OpenLoco/src/Objects/SoundObject.h, src/OpenLoco/src/Objects/SteamObject.cpp, src/OpenLoco/src/Objects/SteamObject.h, src/OpenLoco/src/Objects/TrainStationObject.cpp, src/OpenLoco/src/Objects/TrainStationObject.h, src/OpenLoco/src/Paint/PaintBuilding.cpp, src/OpenLoco/src/Paint/PaintDocks.cpp, src/OpenLoco/src/World/Company.cpp, src/OpenLoco/src/World/Town.cpp
Looks like that's all of them now.
=> Refactor some more objects to use offsets and not pointers

src/OpenLoco/src/Vehicles/Vehicle.h, src/OpenLoco/src/Vehicles/VehicleHead.cpp
Nothing too exciting here called quite often by all vehicle place/remove code to position a vehicle on the track.
Verified with replays and playing a tiny amount.
=> Implement position vehicle on track

src/OpenLoco/src/Vehicles/OrderManager.cpp
Not tested in anyway shape or form
=> Implement removeOrdersForStation

src/OpenLoco/src/OpenLoco.cpp, src/Platform/include/OpenLoco/Platform/Platform.h, src/Platform/src/Platform.Posix.cpp, src/Platform/src/Platform.Windows.cpp
This is a copy paste modify of the OpenRCT2 equivalent.
=> Implement lockSingleInstance

CHANGELOG.md, src/OpenLoco/src/Ui/WindowManager.cpp
Issue was discussed on Discord.
Related to #3181
=> Fix crash when moving vehicle window when a message is showing a vehicle

src/OpenLoco/src/Vehicles/Vehicle.cpp, src/OpenLoco/src/Vehicles/Vehicle.h, src/OpenLoco/src/Vehicles/VehicleHead.cpp
Continues from #3243. #3243 was checking for potential overtakes so this takes that result and then checks the tiles infront to make sure its clear. At least that is what i think its doing. No idea what the level crossing part is about.
=> Implement sub_47ceb7

.github/workflows/ci.yml, src/OpenLoco/src/Objects/ObjectManager.cpp, src/OpenLoco/src/Objects/RegionObject.h, src/OpenLoco/src/Vehicles/VehicleHead.cpp
This is it, the last (usable) function!
Note: This will cause a desync as it changes some road behaviour with overtakes. The original code for this is definitely broken though as it walks off the end of an array and starts reading some variables from the company ai. Because of this I have left it till the very end.
Close #3237
=> Update traffic handedness

CHANGELOG.md, CMakeLists.txt
=> Update objects to v0.1.4

src/OpenLoco/src/Ui/Dropdown.cpp
Fixes #3296. Regression from https://github.com/OpenLoco/OpenLoco/pull/3285.
=> Populate kAppropriateImageDropdownItemsPerRow

src/OpenLoco/src/Input.h, src/OpenLoco/src/Input/MouseInput.cpp, src/OpenLoco/src/Ui/Windows/TerraForm.cpp
Fixes issues from #3285. I've also added the offsets to the fields as it can help when looking back at the old code for bugs like this.
=> Fix terraform dragging
