OpenLoco/OpenLoco

README.md

I left non-dev as the normal non-dev channel. As it sits now, it's the defacto non-dev location, and the same people are involved in both projects, so it works for now. Plus a specific one does not exist.

Add Gitter Links to Readme

---

openloco.common.props

Every time I do a debug build, I get a warning message from the linker telling me that /LTCG is doing nothing and that removing it from the options will speed up the linking process.
```
LINK : /LTCG specified but no code generation required; remove /LTCG from the link command line to improve linker performance
```
(I believe this is due to LTCG being incompatible with incremental linking; and AFAIK incremental linking is enabled in debug builds by default.)
So, this PR simply disables the LTCG flag for the project's Debug config.

Disable link-time code generation for MSVC Debug builds

---

src/openloco/envionment.cpp
src/openloco/interop/hooks.cpp
src/openloco/utility/string.hpp
src/openloco/windows/promptbrowsewnd.cpp

Read the commit messages for more details.
Buffer overruns aren't exactly a huge concern right now, security-wise, but it's probably still a good idea to be proactive about preventing them so that we reduce the likelihood of false-positive bugs popping up.

Implement overrun-safe C-string functions and replace usages of std::strcpy with them

---

data/language/ko-KR.txt

Half translated, I think. I will improve translations continuely.
I make a translation first of all whether OpenLoco still not support UTF-8 yet or not.
And i think it will be great to implement a **gender** for nouns as OpenTTD does.
Actually korean has no genders in noun, but I use it in OpenTTD to represent  **Josa**, which is a postposition attached right after a noun in Korean grammar, differ to whether a last sound (we call it batchim, 받침) exists or not.

ko-KR: Create the first translation

---

src/openloco/graphics/gfx.cpp
src/openloco/graphics/gfx.h

~~Initial decompilation of the G1.DAT load function - doesn't work because various offset fixes are TBD. Please feel free to fix up.~~ `load_g1()` implemented.

Implement load_g1()

---

src/openloco/graphics/gfx.cpp

As things stand compilation fails on macOS as the constructor for `std::ifstream` doesn't like `boost::filesystem::path` (see exact error below).
```
/Library/Developer/CommandLineTools/usr/include/c++/v1/fstream:1016:14: note: candidate constructor not viable: no known conversion from
'boost::filesystem::path' to 'const char *' for 1st argument
explicit basic_ifstream(const char* __s, ios_base::openmode __mode = ios_base::in);
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/fstream:1018:14: note: candidate constructor not viable: no known conversion from
'boost::filesystem::path' to 'const string' (aka 'const basic_string<char, char_traits<char>, allocator<char> >') for 1st argument
explicit basic_ifstream(const string& __s, ios_base::openmode __mode = ios_base::in);
^ …
```

Fix load_g1() when using boost

---

src/openloco/config.cpp
src/openloco/envionment.cpp
src/openloco/environment.h
src/openloco/openloco.cpp

This allows the game to run without the following files pre-existing:
* game.cfg
* plugin.dat
* plugin2.dat
* scores.dat
They are also now read and written to the user directory for OpenLoco and use lower case names.
Existing players will need to copy scores.dat to `%APPDATA%\OpenLoco` if they wish to transfer their scenario progress.

Change user paths and disable file checks

---

.gitignore
docker-compose.yml

This allows you to run the CI jobs on your computer using docker.
```sh
docker-compose up openloco-gcc32
docker-compose up openloco-clang32
docker-compose up openloco-mingw32
docker-compose up
```
This should allow anyone to easily "build" openloco either on Windows (10 pro+), macOS or any Linux distro.

Add a docker-compose file for each compiler

---

src/openloco/windows/promptbrowsewnd.cpp

The original issue is that if one appends the null string, since `p.native() begins with a directory separator`, it will not append the separator. (see http://en.cppreference.com/w/cpp/experimental/fs/path/append).
The filesystem spec is rather... interesting. The preferred separator is a char, but this cannot be concatenated nor appended to a path. Fun 😬

Fix path seperator with filesystem in get_directory

---

README.md

macOS builds currently depend on Boost as a replacement for `std::filesystem`, which hasn't landed in its standard library yet. This PR adds this dependency to README.md

Include Boost dependency in README.md

---

src/openloco/environment.cpp
src/openloco/openloco.vcxproj

I really didn't want to make such a trivial PR, but this has been bugging me for a while now…

Rename envionment.cpp to environment.cpp

---

CMakeLists.txt
src/openloco/version.cpp

This adds the current git branch and short sha1 hash to the version info line on the title screen.

Add git branch and short sha1 hash to version info line

---

src/openloco/interop/hooks.cpp

Sound is not implemented yet, so just return 0.

Name fn_404e8c as get_num_dsound_devices

---

src/openloco/interop/hooks.cpp

This PR removes (no-ops) the terraforming limits outside of the scenario editor. Fixes #127.
Initially, I thought it best to leave changing these until the window was implemented, but it turned out to be fairly straightforward.
* Make in-game follow the same restrictions as the scenario editor for clear tool, water tool
* Enables use of the mountain tool outside of the scenario editor
* Enables placing forest and walls/fences outside of the scenario editor

Remove terraforming limits outside of scenario editor

---

CMakeLists.txt
appveyor.yml
src/openloco/openloco.vcxproj
src/openloco/version.cpp

This PR introduces the use of `git describe` to express the version number in terms of the last tag by appending the number of commits since the release was tagged.
Before:
After:

Use `git describe` to express version in terms of closest tag

---

src/openloco/interop/hooks.cpp
src/openloco/windowmgr.h
src/openloco/windows/promptbrowsewnd.cpp

Currently, all entries in the load/save window are taken as filenames on Linux and macOS. This PR changes things so they are recognised as directories when appropriate. It also implements simple directory browsing: navigating to a directory, and going up one level.
When we're implementing the load/save window properly, and we're no longer bound to Locomotion's internal data structures, I believe we should replace these with instances of `filesystem::path`. Until that time, I think this is a reasonable approach.
I'd like to move the functions for these hooks to `windows/promptbrowsewnd.cpp`\*, but as we currently don't have any header files I'm not sure what the best approach to that end would be.
\* Side note: I believe we should rename it to loadsavewnd.cpp or something similar.

Directory browsing on Linux and macOS

---

src/openloco/window.cpp
src/openloco/window.h
src/openloco/windowmgr.cpp

This implements the viewport zooming functions, and extends them such that mouse-wheel scrolling zooms towards the cursor, rather than the centre of the viewport.

Implement viewport zooming functions

---

src/openloco/openloco.vcxproj

Currently, the MSVC project needs to be manually updated whenever we add a file. This PR updates the MSVC project so it uses wildcards for filenames instead, like OpenRCT2 does.

Use filename wildcards in MSVC project

---

src/openloco/environment.cpp

`result` was not assigned when a `similarResult` was indeed found.

Fix config directory initialisation on non-Windows

---

CHANGELOG.md
src/openloco/config.convert.hpp
src/openloco/config.cpp
src/openloco/config.h
src/openloco/environment.cpp
src/openloco/openloco.cpp
src/openloco/ui.cpp
src/openloco/ui.h
src/openloco/utility/yaml.hpp

This also improves the configuration code:
* All properties and order are preserved when loading / saving the YAML. Unfortunately `yaml-cpp` does not support preserving comments yet.
* Parse and store enums in YAML with only a small amount of code.

Feature: Fullscreen mode

---

src/openloco/interop/hooks.cpp

An unfortunate side-effect of 5ec3aa700bebabb489ca942d951ab9d5d81f86c8 is a crash on startup on macOS. Adding `FORCE_ALIGN_ARG_POINTER` to the hooks `lib_CreateRectRgn` and `lib_WriteFile` fixes this.

Force-align arg pointers for more hooks

---

CHANGELOG.md
src/openloco/graphics/gfx.cpp

As draw sprite is not implemented yet we can't fix it within that code. Instead we require the offscreen detection within draw string to be working. This is slightly less efficient than the original but unlikely to be noticeable. Fix #257, #219.

Fix #257. Draw sprite does not like bad y coordinates.

---

data/language/en-GB.yml
src/openloco/config.h
src/openloco/localisation/string_ids.h
src/openloco/window.cpp
src/openloco/windows/options.cpp

With #226 still an issue, we should mark zooming to cursor as experimental for the upcoming release.

Make zooming to cursor position optional

---

src/openloco/ui/WindowManager.cpp
src/openloco/windows/vehicle.cpp

The bug revealed an off-by-one error in WindowManager::isInFront, which was masking a crash due to a typo.

Fix #273: Cannot issue vehicle orders

---

data/language/en-GB.yml
src/openloco/audio/audio.cpp
src/openloco/config.cpp
src/openloco/config.h
src/openloco/localisation/string_ids.h
src/openloco/windows/options.cpp

While we could disable in-game music already, the title music could not. Unfortunately, one can get enough of John Broomhall's funky beats, so this PR introduces the option.
I've filed the option under the "audio" tab, rather than the "music" tab, as the latter is not available from the title screen. Perhaps this should be changed in the future.
I also noticed two other options weren't persisting. I've added the necessary fix in a separate commit.

Option to disable title screen music

---

appveyor.yml
src/openloco/openloco.vcxproj
src/openloco/packages.config

Currently, the SDL2-mixer dependency carries with it several DLLs adding codec support. As we do not use any of these codecs, they should be disabled in vcpkg similar to how is done for macOS.
This is a companion PR to https://github.com/OpenLoco/Dependencies/pull/2, which has since been merged.
Fixes #267.

Reduce dependencies for Windows builds

---

.gitignore
.travis.yml
CMakeLists.txt
distribution/macos/AppIcon.iconset/Contents.json
distribution/macos/Info.plist.in
src/openloco/environment.cpp
src/openloco/environment.h
src/openloco/localisation/languagefiles.cpp
src/openloco/localisation/languages.cpp
src/openloco/platform/platform.h
src/openloco/platform/platform.macos.mm

Application bundles are the user-friendly way of packaging apps on macOS. This PR is working towards including such builds for OpenLoco.
To do:

Build application bundle for macOS

---

.travis.yml

By default, Travis fetches up to 50 commits. This leads to `git describe` not finding any tag to offset against. Fetching the last 1000 commits allows it to work properly on non-master builds as well.
Fixes #283.

Fetch more of the repository history for non clang-format builds

---

src/openloco/date.cpp
src/openloco/localisation/argswrapper.hpp
src/openloco/localisation/stringmgr.cpp

As [reported on Gitter](https://gitter.im/OpenLoco/OpenLoco?at=5c7c10424a65f754735a70d6):
> ![image](https://user-images.githubusercontent.com/737603/53701598-0583f680-3dff-11e9-83dc-c432665cfd16.png)
> My "Engine Flippers" used to read "-1mph Max Speed", now they read "65,535mph Max Speed". 
Might be nicer to have a syntax similar to the ObjectManager. E.g. `pop<int16_t>()`.

Fix string formatting for velocities and dates

---

src/openloco/input/mouse_input.cpp

The click sound was implemented for both mouseup and mousedown events. This removes the mouseup variant.
It still sounds as though the click sound is clipped or cut off, but that's a separate issue.

Fix #306: Click sound on both mouseup and mousedown events

---

src/openloco/config.cpp

- Processing audio node when loading config would erroneously check the display node.
- `audioNode["device"]` was being set twice.

Minor clean-up in config processing

---

src/openloco/window.cpp
src/openloco/window.h

The saved_view members of the `viewport_config` struct were typed unsigned, while it appears they should be signed.
This fixes part of #226, but it's still more jittery than I would like. I'll do some more debugging eventually, but help is also welcome.

Make zooming to cursor more reliable

---

README.md

A user on Reddit [suggested](https://www.reddit.com/r/locomotion/comments/aw889a/openloco_release_v1902/ehkwrqm/) we add a few screenshot to the GitHub page. I don't want to clutter the readme file too much, but this PR adds a simple one at least, showcasing a macOS build.
Perhaps we should link a few more further down in the file. Any suggestions?
Current screenshot:

Add a screenshot to the readme file

---

src/openloco/ui/WindowManager.cpp

This PR fixes `WindowManager::closeTopmost` closing the wrong window.

WindowManager::closeTopmost closes the wrong window

---

src/openloco/openloco.cpp

Ensure WindowManager::init() is called before ui::process_messages(), otherwise any initial window events may call resize which then attempts to use the Window Manager.

Call tick() before ui::process_messages

---

CHANGELOG.md
src/openloco/station.cpp

Work on the station list window has uncovered a bug in the cargo rating computations.

Fix: Cargo rating is calculated incorrectly in some edge cases

---

src/openloco/input.h

Caused by `mouse_button` being 32-bits rather than 16-bits. Therefore, an assignment to `_lastKnownButtonState` (`0x001136FA0`) would also overwrite `_textInputCaret` (`0x01136FA2`). See 6a73f0b2abd840e68e8a1dfae52667fc8b495acf for the offending lines.

Fix #342: Text cursor does not advance correctly.

---

CHANGELOG.md
src/openloco/graphics/gfx.cpp
src/openloco/graphics/gfx.h
src/openloco/graphics/image_ids.h
src/openloco/localisation/string_ids.h
src/openloco/openloco.cpp
src/openloco/platform/platform.h
src/openloco/platform/platform.macos.mm
src/openloco/platform/platform.posix.cpp
src/openloco/platform/platform.windows.cpp
src/openloco/window.cpp
src/openloco/windows/promptbrowsewnd.cpp
src/openloco/windows/stationwnd.cpp
src/openloco/windows/toolbar_top.cpp
src/openloco/windows/townwnd.cpp

Minor clean-ups of file browser and platform files that I didn't want to clog another PR with.
The second commit is mostly whitespace: I've moved the functions into a dedicated `namespace` rather than repeating it for every function.

Clean-ups of file browser and platform files

---

src/openloco/window.h

The game sometimes crashed when opening the terraform window. This happened due to the row_hover value not being properly initialised, thereby relying on a previous window having it set to a valid value.
As this bug was not present in the last release, no changelog entry is required.

Fix #351: Game crashes when opening terraform window

---

src/openloco/window.cpp
src/openloco/window.h

The window struct had no default values for its min/max width and height, and the window isn't setting all of these values correctly, leaving the memory in question uninitialised.
While the affected property is only min_height, I'd rather be cautious and zero-initialise the other attributes, too.

Fix #350: Map window opens with wrong dimensions

---

src/openloco/ui/WindowManager.h
src/openloco/windows/promptbrowsewnd.cpp

The 'file name' label and text box in the file browser were misaligned when the window was in save mode. The text box being aligned incorrectly was the result of #341, however the label appears to have been out of place for much longer, since #254.
As an added bonus, this rids the window of some overzealous casting around the browse types.
Before:
After:

Fix misalignment of text box and label in browse window

---

CHANGELOG.md
src/openloco/ui.cpp

Simple change to allow using the keypad enter as normal enter which currently does nothing.

Make keypad enter work the same as normal enter

---

openloco.common.props

Use C++17 for Visual Studio

---

.travis.yml

Currently, the macOS 10.13 job on the Travis roster is uploading its builds through `transfer.sh`. Unfortunately, this often results in a time-out for the job. I propose we delete it, for now, while we come up with a better solution.
This also removes the `install` definitions from both macOS jobs, as they can now be share the global ones.

Travis: stop using transfer.sh for macOS jobs

---

src/openloco/localisation/FormatArguments.hpp
src/openloco/localisation/languagefiles.cpp
src/openloco/types.hpp
src/openloco/window.cpp
src/openloco/window.h
src/openloco/windows/KeyboardShortcuts.cpp
src/openloco/windows/LandscapeGeneration.cpp
src/openloco/windows/TimePanel.cpp
src/openloco/windows/about_music.cpp
src/openloco/windows/music_selection.cpp
src/openloco/windows/promptbrowsewnd.cpp
src/openloco/windows/station_list.cpp

This introduces a basic `FormatArguments` wrapper class, which I cherry-picked from a stale branch.
I'd like to start using this more, to prevent seeing `commonFormatArgs` declared everywhere. Pretty basic in its current state, but this should be a good base to easily expand on later.

Introduce FormatArguments wrapper class

---

src/openloco/windows/options.cpp

Extended the height of the Options window Miscellaneous tab so it wouldn't cut off the last line.

Fix #264: Corrected size of Options/Miscellaneous window

---

src/openloco/windows/options.cpp

Changed various related functions to accept the `widget_index` parameter.
This new parameter is passed when the "Ok" button is pressed on the Preferred Name text input window which triggers the `text_input` function.
The `text_input` then uses a switch to check which widget sent the text input, and when it matches `widx::change_btn` it calls the `set_preferred_name` function.

Fix OpenLoco#396: Preferred owner name does not save

---

CHANGELOG.md
src/openloco/graphics/gfx.h
src/openloco/ui.cpp
src/openloco/ui.h
src/openloco/windows/options.cpp

Implemented a check when the Plus or Minus button is pressed on the Options window to change the Scale Factor to make sure that the new scale factor is actually different to the current one.
If the new scale factor has not changed (ie. it's outside the expected range) we cancel the function instead of refreshing the Screen/UI and causing a purple flash.

Disable window scale factor buttons when not applicable

---

CHANGELOG.md
src/openloco/ui.cpp
src/openloco/ui.h
src/openloco/windows/options.cpp

Fix for issue #425 
Allows full screen resolution changes to take affect immediately instead of requiring the game to be restarted.
Waiting to see if PR https://github.com/OpenLoco/OpenLoco/pull/421 is merged so I can use the `window->moveToCentre()` function to re-center the Options window after the resolution change takes affect.

Fix OpenLoco#425: Fullscreen Resolution Change doesn't work

---

CHANGELOG.md
src/openloco/platform/platform.windows.cpp

Fix for issue #430 
Removed null characters that are appended to end of the path returned by the Browse dialog in Windows.

Fix #430: Null characters added to end of Locomotion path

---

CHANGELOG.md
data/language/en-GB.yml
src/openloco/localisation/string_ids.h
src/openloco/windows/toolbar_top.cpp
src/openloco/windows/toolbar_top_alt.cpp

Issue #77 : Add "Exit OpenLoco" to game menu
- Adds "Exit OpenLoco" to the in-game Load/Save menu.
- Changes existing "Quit Game" menu item to "Quit to menu"
- Changes existing "Quit Scenario Editor" menu item to "Quit to menu"
This is all matched to what OpenRCT2 says.

Issue #77: Add "Exit OpenLoco" to game menu

---

src/openloco/graphics/colours.h
src/openloco/windows/stationwnd.cpp

When testing master after #441 had been merged, I noticed a few regressions. This PR addresses the following:
- Fix station tab widgets not activating properly.
- Fix cargo tab animation speed.
- Fix rating bar translucency.
- Minor formatting of stationwnd.cpp.

Fix minor issues with new station window

---

src/openloco/windows/options.cpp

Widget type 17 is the stepper/spinner type, while type 18 is intended for dropdowns. This meant that clicking the label with the current scale would fire the button next to it, and therefore decrease window scale.

Fix scale stepper widget type

---

CHANGELOG.md
src/openloco/window.cpp

This tiny change represents a good many hours of bug finding.

Fix #467: Incorrect scrolling thumbs on auto resize windows

---

src/openloco/localisation/string_ids.h
src/openloco/windows/CompanyWindow.cpp
src/openloco/windows/IndustryWindow.cpp
src/openloco/windows/KeyboardShortcuts.cpp
src/openloco/windows/LandscapeGeneration.cpp
src/openloco/windows/LandscapeGenerationConfirm.cpp
src/openloco/windows/ScenarioOptions.cpp
src/openloco/windows/build_vehicle.cpp
src/openloco/windows/industry_list.cpp
src/openloco/windows/music_selection.cpp
src/openloco/windows/promptbrowsewnd.cpp
src/openloco/windows/station_list.cpp
src/openloco/windows/stationwnd.cpp
src/openloco/windows/textinputwnd.cpp
src/openloco/windows/title_options.cpp

At the core of this PR is the following diff:
```diff
-    constexpr string_id outlined_wcolour2_stringid2 = 450;
+    constexpr string_id outlined_wcolour2_stringid = 450;
-    constexpr string_id white_stringid2 = 455;
+    constexpr string_id black_stringid = 455;
-    constexpr string_id wcolour2_stringid2 = 457;
+    constexpr string_id wcolour2_stringid = 457;
```
When the original dump for the en-GB strings was made, certain assumptions were made with the OpenRCT2 format codes in mind. Implementing the string formatting functions revealed some of these were incorrect.
These incorrect string names have been bothering me for a while. Hopefully there aren't any conflicts with outstanding PRs at this time.

Rename three misnamed string ids

---

CHANGELOG.md
src/openloco/GameCommands.cpp
src/openloco/interop/hooks.cpp

Fix #409. Incorrect refund cost when deleting signals.
The cost had incorrectly been marked as unsigned which caused a comparison to fail. It looks like there is an original bug that caused signal deletion to return a pointer to the stack instead of the cost which due to the incorrect cost check caused a very large number to be taken as the cost.

Fix #409. Incorrect refund cost when deleting signals.

---

src/openloco/config.h
src/openloco/ui.cpp
src/openloco/ui.h
src/openloco/windows/options.cpp

Fix Issue #429 , plus implement simple SDL Window display functions.
Implements a brand new function in the `openloco::ui` namespace.
Function name: `setDisplayMode(config::screen_mode mode, int16_t width, int16_t height)`
Function name: `setDisplayMode(config::screen_mode mode)`
This function can be called to change the main program window display type and size.
If you don't specify a width/height, it will use the size last saved to the config, and if that's not there it will fallback to the desktop resolution, or 640x480 for windowed.
Have tested very thoroughly with clear config, and existing config, switching between all different display types and sizes.
I have adjusted the code in the Options Window to use this new function to set display type when the user chooses from either the …

Fix Issue #429, plus implemented simple SDL Window display functions

---

src/openloco/environment.cpp

When launching for the first time, `game.cfg` is saved at the first opportunity. However, until then, reading this config file will fail with a console warning. There was some confusion in #299 as to whether this was cause for failing to load the game. Perhaps rephrasing the warning would solve this.
The following message on master:
> File not found: "/home/aaron/.config/OpenLoco/game.cfg"
Is changed by this PR to read:
> Warning: file "/home/aaron/.config/OpenLoco/game.cfg" could not be not found

Change phrasing for environment::get_path error

---

src/openloco/industry.cpp
src/openloco/industry.h
src/openloco/industrymgr.cpp
src/openloco/map/tile.h
src/openloco/objects/industry_object.h

* Fix industrymgr::update being called twice in a tick.
* Move some of the surface tile element operations to property methods.
* Extract code into smaller functions.

Refactor industry::update

---

src/openloco/game_commands.h
src/openloco/windows/CompanyWindow.cpp
src/openloco/windows/IndustryWindow.cpp
src/openloco/windows/townwnd.cpp

*Game commands: check do_command's return value instead of ebx.*
Errors weren't handled properly because do_command does not update regs.ebx, but instead returns its value.
*Reorder command functions to be in numerical order.*
The file should really be in numerical order at all times. Probably happened due to PRs being merged in-between each other.
*Remove bl parameter when only used as GameCommandFlag::apply.*
In some cases, the bl register is used to pass flags. Otherwise, it's just GameCommandFlag::apply. I believe we can omit it as a parameter in such (most) cases.

Clean up game commands

---

src/openloco/interop/hooks.cpp

*Remove hooks for editor toolbar purposes.*
The editor toolbar has since been implemented, so these are no longer necessary.
*Remove hook on set_window_pos_wrapper.*
WindowManager::update has since been implemented, as are its callees.

Minor hooks cleanup

---

CHANGELOG.md
src/openloco/window.h
src/openloco/windows/build_vehicle.cpp

`window::current_secondary_tab` was not initialised to zero when constructing or opening the window — only when clicking a primary tab.

Fix #498: Zero-initialise current_secondary_tab

---

CHANGELOG.md
src/openloco/things/vehicle.cpp
src/openloco/things/vehicle.h

Mistake made in implementation that caused a wrap around due to incorrect size of the variable.
I also took the opportunity to make primary animation update almost identical to secondary animation update so that a later refactor removes the duplicated function.

Fix #485. Incorrect position of exhaust smoke on vehicles

---

src/openloco/windows/IndustryWindow.cpp

Incorrect Window size was causing the saved view to be cleared and the viewport to be created twice.

Fix #519 Industry Window Viewport showing wrong location.

---

CHANGELOG.md
src/openloco/windows/construction/Common.cpp
src/openloco/windows/construction/ConstructionTab.cpp

Thanks to @Svelbeard's painstaking efforts in #493, the construction window has been fully implemented. This allows us to change its behaviour in a more fine-grained manner than before.
This PR changes the construction window's build and remove buttons such that their actions are now repeatable. In v18.02, we added behaviour where holding shift while clicking would repeat the action 10 times. This PR removes this behaviour, as it interfered with placing tracks underground.
The new 'holdable' behaviour has a threshold of 40 ticks, meaning it is delayed by one second before it takes effect. I believe this makes it work in an intuitive way.

Construction: holdable build and remove buttons

---

src/openloco/industry.cpp

Following up on #494, we received reports of tree-related industries in the game not updating properly.
Investigation revealed `industry::find_5` to be checking for industries (0x20) present. The original routine instead checks for trees (0x14) at address 0x45330C. The function name `find_5` corresponds with the `element_type` offset for trees as well.
Considering 0x14 is 20 in decimal, I am assuming the mistake was originally introduced in a refactor. The [last diff](https://github.com/OpenLoco/OpenLoco/commit/5caff164cec0938d9193df7737ff1ca312c78e39#diff-389abedf2f6cc4cfc020640a089aa355R35) changed `unk_8` into `industry`, so it must have been in for a longer time.

Fix tree industries not updating properly

---

CHANGELOG.md
src/openloco/industry.cpp

In addition to #496 and #529, we found another bug in the industry update implementation. This one is likely the cause for the livestock farms not producing anything.
This bug went unnoticed for a long time. Until #472 was merged, the original update routine was still called at the end of `industry::update`, masking the bug.
The PR is split into two commits: the first contains the bugfix, the second some address annotations for posterity.

Fix industry production not starting up under some conditions

---

src/openloco/things/CreateVehicle.cpp
src/openloco/things/vehicle.h

Fix #531: Game crash after creating vehicles
2 mistakes made in implementation. Incorrect dimensions of the vehicle order table and incorrect value for the vehicle order. This caused memory corruption and could cause a variety of different crashes
I'm not 100% sure it will fix the source of #531 as for one it will have corrupted the saves and for two I can't get the save to load as I've not got the objects.

Fix #531: Game crash after creating vehicles

---

src/openloco/tutorial.cpp
src/openloco/ui.cpp
src/openloco/ui.h

- Use current resolution rather than config resolution for check.
- Set window position to centre of desktop if resized to ensure it doesn't go off the edge of the desktop.

Fix #543: Tutorial does not resize correctly if maximised or scaled

---

src/openloco/windows/promptbrowsewnd.cpp

Fix #538. Prevent crashes when trying to access bad directories
It also prevents a crash when trying to check if a file is a directory.

Fix #538. Prevent crashes when trying to access bad directories

---

CHANGELOG.md
src/openloco/viewportmgr.cpp
src/openloco/viewportmgr.h

Mistake made in viewport create function meant that an un-implemented function would not get a pointer to the newly created viewport but a pointer to the main windows viewport. When it set the flags for the new viewport it instead set the flags for the main viewport. Fixed by passing back the viewport to the correct register.

Fix #491: Station/city names disappear on save.

---

src/openloco/windows/options.cpp

Widened the first tab of the options tab by 34 pixels. Shrunk the dropdowns by 23 pixels. This creates 57 pixels of additional space for the labels.
What follows are before/after screenshots.

Close #540: Widen options window for German, Polish strings

---

src/openloco/windows/title_exit.cpp

The 'exit' button on the title screen is not resized to accommodate the language that is being used. This leads to awkward string wrapping when the string is longer, for instance with Dutch:
This PR adds a resize step to the `prepare_draw` event, so the button is the right size, regardless of the language used:

Resize title exit button based on language

---

src/openloco/ui/dropdown.cpp

Height of separator was 0 not 1.

Fix #552: Separators in dropdown menus aren't drawn properly

---

src/openloco/window.h

When introducing the stepper widgets to OpenLoco, I decided to give both buttons an equal width of 12px. The minus glyph on the decrement button is not optically aligned in this configuration, however.
To remedy this, this PR increases the width of just the decrement button to 13px. As a result, the glyph is now aligned properly.

Fix stepper decrement button width

---

src/openloco/map/tile.h
src/openloco/map/tile_loop.hpp
src/openloco/windows/stationwnd.cpp

`_byte_F00484` was incorrectly defined as  a `uint16_t[0x24000]`  causing the `map_invalidate_tile_full` to never be called.
`events.on_close` was missing for cargo tab.
`switchTabs` was only resetting station catchment area when the window was switched to the cargo tab not from the cargo tab.

Fix #558: Station catchment area not invalidating map properly

---

src/openloco/things/vehicle.cpp
src/openloco/things/vehicle.h

Multiple train cars were placed inside a single car due to a mistake with the loop. This constructs the Vehicle in a different way to ensure that it does not have to iterate along the Vehicle list multiple times.

Actually create Vehicle super class correctly

---

src/openloco/ui/WindowManager.cpp

Due to a mistake in implementation the right click mouse scroll would always reset the view back to centre.
For some reason I couldn't seem to reproduce this on all of the releases but it is definitely an issue.

Fix right click map scroll

---

src/openloco/input/mouse_input.cpp
src/openloco/ui/scrollview.cpp
src/openloco/ui/scrollview.h

This moves the scroll_begin function to the scroll view file and also gets it ready for slotting in the scroll left and right functions.
I also split up the modal right function as it didn't make sense to call the main scroll begin function. This fixes a bug in the ui where the modal scroll button would get stuck on.
In addition there were a bunch of pointless gets of the window ptr when we already had the window ptr those have been removed. View each individual commit if you want something easier to follow for these changes.

Refactor scroll

---

src/openloco/things/CreateVehicle.cpp
src/openloco/things/vehicle.cpp
src/openloco/things/vehicle.h
src/openloco/windows/CompanyWindow.cpp
src/openloco/windows/News/News.cpp
src/openloco/windows/map.cpp

Okay so the Vehicle Superclass is super inefficient memory allocation wise and its causing noticable slowdowns already and its not even used in that many locations. I've therefore redesigned it so that it no longer allocates any memory. This means the vectors have been removed. Instead begin and end iterators have been made available. 
Previously to iterate over every car it was:
```
things::vehicle::Vehicle train(trainHeadId);
for (auto& car : train.cars)
{
// do stuff with car
}
```
This has not changed at all and still works.
Previously to iterate over every carComponent it was:
```
for (auto& carComponent : car.carComponents)
{
// do stuff with carComponent
}
```
This has now changed to:
```
for (auto& carComponent : car)
{
// do stuff with carComponent
}
```
This change was made as …

Vehicle Superclass V2

---

CHANGELOG.md
data/language/en-GB.yml
src/openloco/companymgr.cpp
src/openloco/config.cpp
src/openloco/config.h
src/openloco/localisation/string_ids.h
src/openloco/windows/options.cpp

The current, vanilla implementation of AI companies is not very good. Their railroads swirl across the landscape, potentially ruining any elegant lines the player may have created. This PR introduces an option to disable them entirely.
Much like the option to disable vehicle breakdowns, as-is, this is very much a cheat. Ultimately, I would like to see this checkbox replaced with a dropdown to select which AI to use.

Optionally disable AI companies entirely

---

src/openloco/interop/hook.cpp

This is my attempt at fixing #585, although I'm not certain this is what's really expected or running into some other bug. With this code in place #585 (null dereference) no longer happens and is instead replaced with stack overflow:
```
OpenLoco, v20.07-32 (a4e4392 on master, DEBUG)
0024:fixme:win:RegisterTouchWindow (0x10058 00000003): stub
0024:fixme:imm:ImmReleaseContext (00010058, 0169C8C8): stub
0024:fixme:msctf:ThreadMgr_ActivateEx Unimplemented flags 0x4
0024:fixme:imm:ImeSetCompositionString PROBLEM: This only sets the wine level string
0024:fixme:imm:ImeSetCompositionString Reading string unimplemented
0024:fixme:imm:NotifyIME NI_CLOSECANDIDATE
00c4:fixme:avrt:AvSetMmThreadCharacteristicsW (L"Pro Audio",020EFEE8): stub
CreateRectRgn(0, 0, 1, 1)
Create progress bar …
```

Fix #585: Properly initialise small hook memory

---

src/OpenLoco/Things/CreateVehicle.cpp
src/OpenLoco/Things/Vehicle.h

Missed setting two variables to 0 which caused a jump into unexpected code when used as part of an indirect call

Fix crash in vehicle update head caused by CreateVehicle

---

src/OpenLoco/Ui/WindowManager.cpp
src/OpenLoco/Window.cpp
src/OpenLoco/Window.h
src/OpenLoco/Windows/CompanyList.cpp
src/OpenLoco/Windows/CompanyWindow.cpp
src/OpenLoco/Windows/IndustryList.cpp
src/OpenLoco/Windows/IndustryWindow.cpp
src/OpenLoco/Windows/MessageWindow.cpp
src/OpenLoco/Windows/Options.cpp
src/OpenLoco/Windows/StationWindow.cpp
src/OpenLoco/Windows/TerraForm.cpp
src/OpenLoco/Windows/TownList.cpp
src/OpenLoco/Windows/TownWindow.cpp

Close #647. Implement viewportRemove helper member function
I didn't see much point in having the invalidate wrapped in the result on if it was removed but could change that if you think it would be more performant.

Close #647. Implement viewportRemove helper member function

---

CMakeLists.txt

The file was renamed from `version.cpp`, but `CMakeLists.txt` hadn't been adjusted accordingly.
As far as I can tell, the MSVC project hasn't been adversely affected by the renaming.

Pass version info to Version.cpp again

---

src/OpenLoco/Windows/ScenarioSelect.cpp

Fix #660. Missing += rowHeight caused drawing to perform incorrectly
This bit of code is meant to reduce the amount of drawing taking place. Without the += rowHeight the code would do its skipping of drawing but then when it was meant to draw it would be at the wrong y coordinate. This would cause a flickering when items behind the window caused redraws of parts of the screen.

Fix #660. Missing += rowHeight caused drawing to perform incorrectly

---

CHANGELOG.md
src/OpenLoco/Audio/Audio.cpp

Due to SDL not allowing population of the available devices until the audio system is loaded the audio tries to set the device to a nullptr. Instead we load the default audio device and then immediately close it. This allows SDL to load correctly

Fix #588. Crash when changing default audio device

---

src/OpenLoco/Windows/PromptBrowseWindow.cpp

Addresses two minor regressions from #666:
* We were showing the full path in confirmation windows, rather than just the filename.
* The browse window caption wasn't copied into the confirmation window.

Address regressions in PromptBrowse window

---

src/OpenLoco/Windows/PromptOkCancelWindow.cpp

This implements the events, event list, and widgets for the PromptOkCancel window.
I think the window could be refactored to take `std::string`s as parameters — it appears to only be used by the PromptBrowseWindow. But that's for a later PR.

Implement events and widgets for PromptOkCancel window

---

src/OpenLoco/Audio/VehicleChannel.cpp
src/OpenLoco/Input/MouseInput.cpp
src/OpenLoco/Things/CreateVehicle.cpp
src/OpenLoco/Things/Misc.cpp
src/OpenLoco/Things/Misc.h
src/OpenLoco/Things/Thing.cpp
src/OpenLoco/Things/Thing.h
src/OpenLoco/Things/Vehicle.cpp
src/OpenLoco/Things/Vehicle.h
src/OpenLoco/ViewportManager.cpp
src/OpenLoco/ViewportManager.h
src/OpenLoco/Window.cpp
src/OpenLoco/Windows/CompanyWindow.cpp
src/OpenLoco/Windows/Vehicle.cpp

I was having issues with Entity paint setup functions without access to all of the fields this will expose. Originally I was hoping that this sort of arrangement wouldn't be required but oh well! This is how OpenRCT2 handles its entities.

Reorg thing so that base has access to more

---

src/OpenLoco/Windows/TerraForm.cpp

Mistake made in implementation. The dropdown index is not gauranteed to be the same as the texture index therefore it would select invalid objects

Fix #679: Crash when changing ground texture

---

src/OpenLoco/Windows/Vehicle.cpp

Mistake made in implementation caused orders to be inserted in the wrong locations in the order table. This could cause unknown side effects or a crash

Fix orders related crashes and quirks

---

src/OpenLoco/Windows/Vehicle.cpp

Default selection is meant to be always the inverse of the state. i.e. start becomes stop, stop becomes start and manual becomes stop.

Fix start stop highlighted selection

---

src/OpenLoco/Config.h
src/OpenLoco/Paint/Paint.cpp
src/OpenLoco/Paint/Paint.h
src/OpenLoco/Paint/PaintEntity.cpp
src/OpenLoco/Paint/PaintEntity.h
src/OpenLoco/openloco.vcxproj

Continues from #681 and #684
Implements entityPaintSetup very similar to its OpenRCT2 equivalent.

Paintsetup 2: entityPaintSetup

---

CHANGELOG.md
src/OpenLoco/Input.cpp
src/OpenLoco/Input.h
src/OpenLoco/Input/MouseInput.cpp

Fix #151: Mouse moves out of window when looking around

---

src/OpenLoco/Paint/Paint.cpp
src/OpenLoco/Paint/Paint.h

Continues from #681. Implements arrangeStructs. Heavily based on its OpenRCT2 equivalent.

Paintsetup 3: arrangeStructs

---

CHANGELOG.md
data/language/en-GB.yml
src/OpenLoco/Config.cpp
src/OpenLoco/Config.h
src/OpenLoco/Environment.cpp
src/OpenLoco/Environment.h
src/OpenLoco/Localisation/StringIds.h
src/OpenLoco/OpenLoco.cpp
src/OpenLoco/S5/S5.cpp
src/OpenLoco/S5/S5.h
src/OpenLoco/Utility/String.hpp
src/OpenLoco/Windows/Options.cpp
src/OpenLoco/Windows/PromptBrowseWindow.cpp

Add two new configuration options to control frequency of autosaving and the number of autosaves to keep.
Autosaves are saved to `<user openloco directory>/save/autosave`.
The default saved game directory is now `<user openloco directory>/save`.
Last thing that needs doing is:

Implement #39: Auto save

---

src/OpenLoco/Graphics/Gfx.cpp
src/OpenLoco/Graphics/Gfx.h
src/OpenLoco/Paint/Paint.cpp
src/OpenLoco/Paint/Paint.h
src/OpenLoco/Ui.h
src/OpenLoco/Ui/ViewportInteraction.cpp

Continues from #686: Implements getNormalInteractionInfo. Based off of OpenRCT2 equivalent.

Paintsetup 4: spriteInteractWith

---

CHANGELOG.md
src/OpenLoco/Windows/CompanyList.cpp

The wrong data type size was being passed to the graphing routine. The value being passed was 4 bytes (32 bits) instead of 6 bytes (currency48_t).
Renaming `_dword_113DD0C` to `_graphDataTypeSize` makes it obvious what's wrong.

Fix #725: Company value graph does not display correctly

---

src/OpenLoco/Windows/Options.cpp

The value being read is 32-bits ("Every {INT32} months"). However, only 16-bits was being pushed to the dropdown arguments. Thus, this was relying on 'clean' argument memory.

Fix #727: Autosave frequency dropdown glitch

---

src/OpenLoco/Windows/CompanyList.cpp

Follow on from the other setLegendHover. Simple little function not much to say. Doesn't suffer from the bug mentioned in the previous setLegendHover as you can only have 16 companies.

Implement setLegendHover for main company list tabs

---

src/OpenLoco/Types.hpp

This fixes a potential future bug with 0.33333_mph

Change the mph literal to allow for 5 decimal places of accuracy

---

src/OpenLoco/Core/Span.hpp
src/OpenLoco/S5/SawyerStream.cpp
src/OpenLoco/S5/SawyerStream.h
src/OpenLoco/Utility/Numeric.hpp
src/OpenLoco/openloco.vcxproj
src/Thirdparty/span.hpp

* Add a polyfill for `std::span`. I have chosen `stdx::span` and we can replace it with `std::span` when we move to C++20.
* Add the SawyerEncoder and SawyerDecoder classes.
Pretty much code I wrote for OpenRCT2 refactored. All works correctly in the save and load branches I am working on.

Implement the sawyer encoder / decoder

---

src/OpenLoco/Vehicles/Orders.cpp
src/OpenLoco/Vehicles/Orders.h

This is required as vehicle functions use offsets rather than index's for storing the current order position

Add atOffset function

---

src/OpenLoco/Platform/Platform.Posix.cpp

Commit 963203743 (#711) changed `Numeric.hpp` to include `<limits>` instead of `<limits.h>`. This had the side-effect of not `PATH_MAX` no longer being defined on (Arch) Linux.
This PR addresses it by including the appropriate header in `Platform.Posix.cpp`.

Fix compilation on Arch Linux

---

src/OpenLoco/Types.hpp
src/OpenLoco/Vehicles/CreateVehicle.cpp
src/OpenLoco/Vehicles/VehicleBody.cpp

Replace numeric constants using literals with _mph defined in Types.hpp
All numeric constants are added to static_assert to check the validity of conversion.

Fix #737: Use _mph literals instead of numeric constants

---

CHANGELOG.md
src/OpenLoco/Windows/ScenarioOptions.cpp

We were just missing a multiplication factor. Verified that the original game was doing something similar in the equivalent prepareDraw event.

Fix #766: Performance index is off by a factor of 10

---

data/language/en-GB.yml
src/OpenLoco/Input/MouseInput.cpp
src/OpenLoco/Localisation/StringIds.h
src/OpenLoco/Window.cpp
src/OpenLoco/Window.h
src/OpenLoco/Windows/Vehicle.cpp

The vehicle window has long since had a button to centre the main viewport on the vehicle it represents. However, it may be nice to _follow_ a vehicle for a longer period of time. This PR makes that possible.
The centre viewport button has been changed into a dropdown, with two items. The first and default item is using the old behaviour: the main viewport is centred on the vehicle. The second item _follows_ the vehicle, until the viewport is dragged around or centred on something else.
Below is a screenshot of what it looks like right now. Feedback and testing welcome.

Feature: allow main viewport to follow an entity

---

CHANGELOG.md
src/OpenLoco/Objects/AirportObject.h
src/OpenLoco/Station.cpp

Mistake made in implementation. Min/Max are signed and are in TilePos coordinates not MapPos coordinates.

Fix #721. Incorrect catchment area for airports

---

src/OpenLoco/Vehicles/CloneVehicle.cpp

Offset for game command 35 is relative to the start of the vehicles orders not relative to the start of the order table
Fix #772

Fix clone vehicle orders.

---

CHANGELOG.md
src/OpenLoco/Windows/TownList.cpp

An int16 was being pushed to the format arguments, rather than an int32.
Bug:
Fixed:

Fix: Town list could show the wrong number of stations

---

.editorconfig

Its the same as in OpenRCT2, this enforces VS to use a specific encoding and line ending.

Add .editorconfig for VS

---

src/OpenLoco/Vehicles/CloneVehicle.cpp
src/OpenLoco/Vehicles/Orders.cpp
src/OpenLoco/Vehicles/Orders.h
src/OpenLoco/Windows/Map.cpp
src/OpenLoco/Windows/Vehicle.cpp

After playing with the vehicle update code I feel this is definitely a better way to structure the orders. You now have a ring view of the orders. It will loop around until it sees the order you started with. This allows for much simpler code to increment an order (its now just ++). To look for the first order satisfying a condition (which is used quite often) is also simplified. Empty orders always have an end order and this version will correctly know how to handle that.
If you pass an invalid current order offset then it will not operate correctly. This is not expected to happen.
This version is a slight improvement over the one in #747 and #747's version will be replaced by this one. Also no longer need the `atOffset` function.

Change OrderTableView to OrderRingView

---

src/OpenLoco/StationManager.cpp

The station manager is using 0xFFFF (`StringIds::null`) to check where to allocate the next station. However, when saving, these are set to 0x0 (`StringIds::empty`) instead.
I the intention was good, but the wrong constant was used. Obviously, we missed this in the review process as well.

Fix StationManager::zeroUnused

---

CHANGELOG.md
src/OpenLoco/Vehicles/Orders.cpp
src/OpenLoco/Windows/Vehicle.cpp

Calculation was incorrectly adding the offset to the first tile instead of removeing the offset from the current tile. This meant that it would set the waypoint at the wrong location

Fix waypoint setting function

---

CHANGELOG.md
src/OpenLoco/Environment.cpp

While #752 fixed the issue with savings game to paths that contain a period, the initial save path is still missing its trailing slash. This finally corrects that.
Should this be added to the changelog?

Append trailing slash to initial save path

---

src/OpenLoco/GameCommands.cpp
src/OpenLoco/Vehicles/OrderSkip.cpp
src/OpenLoco/Vehicles/Vehicle.h
src/OpenLoco/openloco.vcxproj

This was a very simple game command that I implemented to show all of the steps for what needs to be done. 
* Create a new file for your game command (we want exactly 1 per file as it makes it much easier when refactoring these in the future)
* Create a function that interfaces with the game command parameters. (`void xxxxx(registers& regs)`)
* Create a sensible function for the game command with named parameters (`uint32_t orderSkip(uint16_t headId, uint8_t flags)`)
* Change the respective nullptr in GameCommands.cpp.
Things to know about game commands:
* Failure is indicated by `GameCommands::Failure` returned in register `ebx`
* Cost is returned in register `ebx`
* Flags are passed into the function on `bl`. There is always an apply flag so that you can have a query run of the game …

Implement Order Skip game command

---

src/OpenLoco/Vehicles/Orders.h
src/OpenLoco/Vehicles/VehicleHead.cpp

Continuing from #738. 
See final commit I've introduced a different way of viewing orders. Could swap them all to use this version. It has a cycle in it as most uses of the orders expect it to roll over back to the start. i.e. 0 -> 1 -> 2 -> 0 (where 3 is the end).
Will rebase after #754

Vehicle update2 Part 1b: Order functions

---

CHANGELOG.md
src/OpenLoco/Vehicles/VehicleBody.cpp

When the vehicle reaches its top speed an invalid value for the animation would be set. Mistake was made during implementation

Fix speed based vehicle animations such as hydrofoils

---

src/OpenLoco/GameCommands.cpp
src/OpenLoco/OpenLoco.cpp
src/OpenLoco/OpenLoco.h
src/OpenLoco/Title.cpp
src/OpenLoco/Windows/News/Common.cpp
src/OpenLoco/Windows/News/News.h
src/OpenLoco/Windows/PlayerInfoPanel.cpp
src/OpenLoco/Windows/TimePanel.cpp

Recently, I've noticed that we're defining the same variables in several files. This PR removes several `loco_global` declarations of the game speed variable. Ownership is now centralised in `OpenLoco.cpp`
I think it's important that we think about data ownership. Ideally, only one file defines the variable, and exposes it only through accessor functions. This will help us down the line, when interop with the original routines is no longer needed.

Centralise ownership of game_speed variable in OpenLoco.cpp

---

src/OpenLoco/S5/S5.cpp

When S5::save was implemented, the original function (0x00441C26) was hooked to use our implementation. However, the hook is currently wrong: the original sets the carry flag on fail, not success.

Fix return value for S5::save hook

---

src/OpenLoco/S5/S5.cpp

For some reason there is a "landscape" S5 type and flag, but they aren't used. Landscapes just seem to be scenarios.

Fix #802: Scenario save is failing

---

src/OpenLoco/S5/S5.cpp

For our macOS builds, we use macOS 10.13. This is the last macOS to with a 32 bit compiler toolchain. On this version, using `std::string_view` on `fs::u8path` doesn't compile. Using `std::string` compiles fine.
While `string_view` seems semantically nicer, this seems like the right solution, for now.

Fix compilation on macOS 10.13

---

src/OpenLoco/Vehicles/Vehicle.h
src/OpenLoco/Vehicles/VehicleHead.cpp

I think this represents almost the last of the main functions from #136. `sub_4ACCDC` was partially implemented in `vehicle_update` but it uses a memory structure i've been avoiding so will not finish it atm.

Vehicle Update 2 Part 3e: Implement landTryBeginUnloading and landLoadingUpdate

---

src/OpenLoco/Vehicles/Vehicle.h
src/OpenLoco/Vehicles/VehicleHead.cpp

Looks like sub_4AD93A does a good bit of work here and ends up firing off a entity movement function this function though doesn't do much.

Vehicle Update 2 Part 3c: Implements sub_4A8CB6

---

CHANGELOG.md
src/OpenLoco/Town.h
src/OpenLoco/TownManager.cpp

Noticed this when creating the function that increments `monthly_cargo_delivered`.
It is not a signed value and this was causing the computations to be incorrect.

Fix monthly town update

---

src/OpenLoco/Map/TileManager.cpp

I believe this makes a bit more sense

Avoid converting map to tile pos when passing tile pos

---

src/OpenLoco/Audio/Audio.h
src/OpenLoco/Company.h
src/OpenLoco/Currency.h
src/OpenLoco/GameCommands.h
src/OpenLoco/Location.hpp
src/OpenLoco/Things/Thing.h
src/OpenLoco/Town.h
src/OpenLoco/Types.hpp
src/OpenLoco/Viewport.hpp
src/OpenLoco/Window.h
src/OpenLoco/ZoomLevel.hpp
src/OpenLoco/openloco.vcxproj

Having multiple types packed into a single header is not ideal as Types.hpp is pretty a prominent included header. I think the "include what you need" philosophy should be applied whenever possible, that also means splitting out types into separate headers, best case they come with their corresponding systems so its usually isolated within a certain section of the code base.

Refactor some includes

---

CHANGELOG.md
src/OpenLoco/Input/Keyboard.cpp
src/OpenLoco/Ui/WindowManager.h
src/OpenLoco/Windows/PromptBrowseWindow.cpp

This PR implements PromptBrowseWindow::handleInput (0x0044685C), which fixes #804. This function is analogous to sub_4CE910 in the TextInput window. Ideally, part of it would be shared at least, but I have not yet refactored the lot for this PR. Perhaps both windows should share a namespace with tools to this end.
Unlike #839 from the other day, this window still uses the VK keycodes. This is because we are still converting all SDL2 keycodes to Windows/DirectInput keycodes in `Ui.cpp`. Some happen to match, but not all. With most of the UI now implemented, I think we can drop this conversion in a future PR, and use the SDLK constants instead.

Implement PromptBrowseWindow::handleInput

---

src/OpenLoco/OpenLoco.cpp
src/OpenLoco/Title.cpp
src/OpenLoco/Title.h

This continues from #322, implementing the title update steps and integrating the title sequence script using modern C++.
Each of the command types is encoded using typed structs. A title sequence is a vector of `std::variant` of these. By using `std::visit`, we can then use the type system to run these commands using lambda functions.
Perhaps we should split Title.{cpp,h} into TitleScreen.{cpp,h} and TitleSequence.{cpp,h} (or one .hpp file?). Any thoughts on that?

Implement title sequence

---

src/OpenLoco/ZoomLevel.hpp

Just to prevent the crash in debug builds for the time being.

Remove assert from ZoomLevel, value is used for other things

---

CHANGELOG.md
src/OpenLoco/Objects/VehicleObject.cpp

If a vehicle does not carry any cargo (e.g. is a train engine) the previous items capacity string (or anything else) would be shown as the capcity. This is because a global variable is being used that has not been correctly intialised.

Fix capacity string showing incorrect data

---

src/OpenLoco/GameCommands/LoadSaveQuit.cpp
src/OpenLoco/Interop/Hooks.cpp

Sub_441FA7 in a lot of situations will cause a crash this prevents just one of them which is gauranteed to happen. It is quite likely that there are other crashes here that will still happen. Full implementation of all callers and the function will need to be done before we can be confident that there is no sources of crashes here.

Fix load save window crashing Windows builds

---

src/OpenLoco/Windows/Vehicle.cpp

Regression from #889. The condition is slightly different from an inverted isPlaced. The difference is subtle:
```cpp
// Generalised condition
isPlaced = tile_x != -1 && !(var_38 & Flags38::isGhost);
!isPlaced = tile_x == -1 ||   var_38 & Flags38::isGhost ;
// Here, though, a mix of both is correct:
tile_x == -1 || !(var_38 & Flags38::isGhost);
```

Fix vehicle pickup tool abort event

---

src/OpenLoco/Vehicles/VehicleHead.cpp

This was causing the incorrect order station to show as where a vehicle was travelling to

Stop looking for order station after finding one

---

src/OpenLoco/Math/Trigonometry.hpp

This was also causing some ship pathing issues
Note that after the trig PR distance calcs are marginally more accurate so there is a subtle difference between vanilla and OpenLoco. I've confirmed that this is the case with a few test scenarios.

Fix #931. Odd pathing at certain speeds due to variable overflow

---

CHANGELOG.md
src/OpenLoco/Vehicles/VehicleHead.cpp

Wrong size of height variable caused truncation at high water levels
which caused docks to not be marked as occupied. Which caused a crash
when trying to unoccupy the dock when removing a boat.

Fix #914. Actually fix correctly this time.

---

src/OpenLoco/Windows/Construction/Construction.h
src/OpenLoco/Windows/Map.cpp
src/OpenLoco/Windows/TileInspector.cpp

While working on #945, I noticed the panel height was off in the construction window, resulting in the bottom window border not being rendered.
I went over the other windows as well, and turns out the map window and tile inspector also suffered a similar same issue. I couldn't find any others.

Fix panel heights in several windows

---

CHANGELOG.md
src/OpenLoco/Windows/Construction/Common.cpp
src/OpenLoco/Windows/Construction/StationTab.cpp

| Before | After |
| - | - |
| ![Screenshot_20210423_191050](https://user-images.githubusercontent.com/604665/115907044-a105d480-a468-11eb-973e-02340dfe5ca5.png) | ![Screenshot_20210423_191757](https://user-images.githubusercontent.com/604665/115907049-a19e6b00-a468-11eb-802d-d93d4708a42c.png) |

Fix #945: Station construction preview image is using wrong colours

---

src/OpenLoco/Windows/PromptBrowseWindow.cpp

Fixes #955 by only saving the last used path for save games, as intended.
Perhaps at a later point this can be expanded to remember the last paths used for scenarios and landscapes as well.

Fix #955: Last landscape path is used as last save game path

---

src/OpenLoco/Map/MapGenerator.cpp
src/OpenLoco/Objects/ClimateObject.h
src/OpenLoco/Objects/ObjectManager.cpp
src/OpenLoco/Objects/ObjectManager.h
src/OpenLoco/OpenLoco.cpp
src/OpenLoco/Scenario.cpp
src/OpenLoco/Scenario.h

Two small functions to implement. Mostly because this means we finally have an idea what what's in the climate objects. They're nearly identical, so it might be good to refactor them a little after reviewing.
I could use some help in naming the fields. For reference, the Alpine Climate uses the following values:
```
climateObj->var_02 = 1
climateObj->var_03 = 57
climateObj->var_04 = 80
climateObj->var_05 = 100
climateObj->var_06 = 80
climateObj->var_07 = 48
climateObj->var_08 = 76
```

Implement updateSnowLine

---

CMakeLists.txt

This is probably a leftover from our early macOS toolchain, since replaced by vcpkg.

CMake: Remove reference to non-existing lib directory

---

src/OpenLoco/Ui/Dropdown.cpp

Opening a company selection dropdown, sets the highlighted item to -1. The `size_t` type is unsigned, so that would be interpreted as bigger than the uint8_t max.

Fix dropdown assertions

---

CHANGELOG.md
src/OpenLoco/Windows/TitleMenu.cpp

Occasionally, new players assume OpenLoco has working multiplayer functionality, while it's been broken since the first release. This hides the toggle button from the title menu, while still making it easy to re-enable.
Before:
After:

Temporarily hide multiplayer functionality

---

CONTRIBUTORS.MD
data/language/pt-BR.yml

Having been reminded of OpenLoco by PR #966, I've done some further improvements on the pt-BR translation:
- General typo fixes
- Changed some instances of 'Locomotion' to 'OpenLoco' (Matching the ones in the en-GB.yml file)
- Changed all instances of 'Empresa' to 'Companhia', which better matches it's English counterpart: 'Company'
- Added translation for 'Disable vehicle breakdowns'
I've also added my name to the contributors.md file

Update pt-BR translation

---

src/OpenLoco/Environment.cpp

This adds the default path used by the offline installer from GOG.

Add a default installation path to searchPaths

---

src/OpenLoco/Config.h
src/OpenLoco/TrackData.h

This allows compilation to finish when using gcc 11.1. Unfortunately, the resulting builds still segfault:
```
* thread #1, name = 'openloco', stop reason = signal SIGSEGV: invalid address (fault address: 0x0)
* frame #0: 0xf76fe200 libX11.so.6`_XSend + 368
frame #1: 0xf76fe68a libX11.so.6`_XFlush + 42
frame #2: 0xf76dfee1 libX11.so.6`XFlush + 49
frame #3: 0xf7ee6092 libSDL2-2.0.so.0`___lldb_unnamed_symbol2437$$libSDL2-2.0.so.0 + 178
frame #4: 0x011fd27a openloco`OpenLoco::Ui::setCursor(OpenLoco::Ui::CursorId) + 160
frame #5: 0x011acef0 openloco`OpenLoco::Input::processMouseOver(short, short) + 1101
frame #6: 0x011ff157 openloco`OpenLoco::Ui::handleInput() + 819
frame #7: 0x011d8ac0 openloco`OpenLoco::sub_431695(unsigned short) + 125
frame #8: 0x011b4e93 …
```

Add missing includes for gcc 11.1 compilation

---

src/OpenLoco/GameCommands/RenameIndustry.cpp
src/OpenLoco/GameCommands/RenameTown.cpp

This would cause reading more bytes than present in source buffer

Fix memcpy size in Rename{Town,Industry}

---

CHANGELOG.md
src/OpenLoco/Interop/Hook.cpp
src/OpenLoco/Interop/Interop.cpp

Fixes issues seen by MK Inst on his prehistoric wine

Retry hook installation

---

src/OpenLoco/TownManager.cpp

GCC11-based mingw complained about possibly writing to index -1

Only write town history when using valid index

---

src/OpenLoco/Windows/ScenarioOptions.cpp

I'm not actually sure if this is the correct solution - or if it should perhaps by changed to `tab_finances`?
https://github.com/OpenLoco/OpenLoco/blob/121d0be7b8d6263f3464e570122c0e578a59a3e6/src/OpenLoco/Windows/ScenarioOptions.cpp#L59-L62

Remove duplicated tab widget enablement

---

README.md

From time to time, we get users on Discord asking how to compile the game when they just want to play it. This PR aims to clarify that binary releases are indeed available.
I am wondering whether we should just move compilation instructions to the wiki entirely. However, I recall there was a bit of hesitance to do so in the past. I have left the instructions as-is, for now.

Clarify availability of release builds and need for compilation

---

src/OpenLoco/Widget.h

Guess it was a good sign that it took a little while to notice this glaring issue as it means that a lot of our ui code is by us.

Fix sizeof widget

---

src/OpenLoco/Objects/ObjectManager.cpp

Object name is not truly a string, but an array of 8 chars that are not expected to be null-terminated
https://github.com/OpenLoco/OpenLoco/blob/7bdc32d8b2c59fea9d9d37498752bf6144ff06f2/src/OpenLoco/Objects/ObjectManager.h#L105

Fix access to embedded object name

---

src/OpenLoco/Map/Map.hpp
src/OpenLoco/Map/TileManager.cpp

Our implementation is more sensitive with respect to memory space. This change ensures we don't trigger any alarm bells for going outside the valid coordinate space.

Close #1030: Guard exploratory tile loops

---

src/OpenLoco/Map/Map.hpp

There is no requirement for this function to take anything other than Pos2 so best make it an explicit type.

Remove template parameter and name type

---

README.md

The code style was not mentioned in the 'Contributing' section of the readme. This PR addresses this.
In addition, the TOS has been rebuilt.

Mention code style in readme

---

src/OpenLoco/Graphics/Gfx.cpp

I looked at the assembly for this one and decided it would be a pain to implement that way as it's inlining all the string width calc.
It's somewhat based on the openrct2 equivalent with some minor tweaks as we don't have the same format code handling.

Implement alternative clip string

---

src/OpenLoco/Localisation/StringManager.h

This makes it a bit easier to understand what the control codes are being used for and keeps the known gaps.

Provide further notes for string control codes

---

src/OpenLoco/CompanyManager.cpp
src/OpenLoco/Map/TileManager.cpp
src/OpenLoco/Map/TileManager.h
src/OpenLoco/S5/S5.cpp
src/OpenLoco/Ui.h
src/OpenLoco/Ui/ViewportInteraction.cpp
src/OpenLoco/Viewport.cpp
src/OpenLoco/Viewport.hpp
src/OpenLoco/Window.cpp
src/OpenLoco/Window.h
src/OpenLoco/Windows/CompanyWindow.cpp
src/OpenLoco/Windows/Construction/ConstructionTab.cpp
src/OpenLoco/Windows/IndustryList.cpp
src/OpenLoco/Windows/TileInspector.cpp
src/OpenLoco/Windows/TownList.cpp
src/OpenLoco/Windows/Vehicle.cpp

These are all really similar to OpenRCT2 functions and also really similar to ViewportInteraction functions. There is perhaps scope for trying to streamline these functions.
`getCentreScreenMapPosition()` should probably be removed and make it so it only returns the viewport position. That would make it more flexible.

Some viewport functions

---

CHANGELOG.md
src/OpenLoco/Input/ShortcutManager.cpp
src/OpenLoco/Ui/WindowManager.h
src/OpenLoco/Windows/Construction/Common.cpp
src/OpenLoco/Windows/TownList.cpp

Currently, only the track construction tool and terraform windows use the item rotation hotkey (default Z). This extends this functionality to the building tabs in the town list (editor and sandbox mode).
Part of #1075.

Allow rotating buildings in town list by keyboard shortcut

---

src/OpenLoco/Ui.cpp
src/OpenLoco/Ui/Cursor.cpp
src/OpenLoco/Ui/Cursor.h

Recently, #674 introduced support for Locomotion's custom cursors on Linux and macOS. As a result of that PR, however, the pointer and hand cursors regressed to their Windows 9x/2000 counterparts. This PR changes only these specific cursors to use the appropriate system cursors.

Use system cursors for pointer and hand cursors

---

src/OpenLoco/Map/MapGenerator.cpp
src/OpenLoco/OpenLoco.cpp
src/OpenLoco/S5/S5.cpp
src/OpenLoco/Title.cpp
src/OpenLoco/Windows/ObjectSelectionWindow.cpp
src/OpenLoco/Windows/ScenarioSelect.cpp

There are still a couple duplicates related to object loading/unloading but there wasn't a nice simple way to reduce their instances.

Cleanup duplicated call instances and add notes

---

src/OpenLoco/Input.cpp
src/OpenLoco/OpenLoco.cpp
src/OpenLoco/Ui.cpp
src/OpenLoco/Ui.h
src/OpenLoco/Viewport.cpp
src/OpenLoco/Viewport.hpp
src/OpenLoco/ViewportManager.cpp
src/OpenLoco/Window.cpp

Reworks two functions to stop using out parameters and use proper types. I know this looks a bit counter productive in one or two spots but i think its better overall. It looks like it would be useful to have both an xy32 and xy16 for use in loco globals. (Also yes I know xy32 is not the name we want)

Further coords work

---

src/OpenLoco/Window.cpp
src/OpenLoco/Window.h
src/OpenLoco/Windows/AboutMusic.cpp
src/OpenLoco/Windows/BuildVehicle.cpp
src/OpenLoco/Windows/CompanyFaceSelection.cpp
src/OpenLoco/Windows/CompanyList.cpp
src/OpenLoco/Windows/CompanyWindow.cpp
src/OpenLoco/Windows/IndustryList.cpp
src/OpenLoco/Windows/KeyboardShortcuts.cpp
src/OpenLoco/Windows/LandscapeGeneration.cpp
src/OpenLoco/Windows/MapWindow.cpp
src/OpenLoco/Windows/MessageWindow.cpp
src/OpenLoco/Windows/MusicSelection.cpp
src/OpenLoco/Windows/ObjectSelectionWindow.cpp
src/OpenLoco/Windows/PromptBrowseWindow.cpp
src/OpenLoco/Windows/ScenarioSelect.cpp
src/OpenLoco/Windows/StationList.cpp
src/OpenLoco/Windows/StationWindow.cpp
src/OpenLoco/Windows/TerraForm.cpp
src/OpenLoco/Windows/TileInspector.cpp
src/OpenLoco/Windows/TownList.cpp
src/OpenLoco/Windows/Vehicle.cpp
src/OpenLoco/Windows/VehicleList.cpp

I'd like to see almost everything pass by ref rather than by pointer. Its pretty rare that it should be passing by pointer. Passing by ref makes it clear that it cannot be null and no requirement to check if it is nullptr and prevents reassigning the variable to something else.

Modify drawScroll event to pass by reference

---

src/OpenLoco/Location.hpp
src/OpenLoco/Math/Vector.hpp

This ensures that the two types are different and prevents from being accidentally converted from one to the other.

Prevent implicit conversions from Pos2 and xy32

---

CHANGELOG.md
src/OpenLoco/Windows/TerraForm.cpp

This PR changes the cluster tool such that planting clusters of trees now costs money and influences ratings outside of editor mode.
Potential room for improvement:

Make tree clusters cost money outside editor

---

CHANGELOG.md
src/OpenLoco/Windows/CompanyWindow.cpp

In the company window's finances tab, all negative expenses were drawn in a red text colour, rather than just the sums at the bottom. This PR changes it to be in line with vanilla again, which is a little easier on the eyes and more in line with traditional book-keeping practices.
Before:
After:

Only use red text colour for expenditure sums

---

CHANGELOG.md
src/OpenLoco/Windows/PromptBrowseWindow.cpp

The file browser allowed clicking the N+1th filename, for which there is no data. This off-by-one error was not present in the mouseover event; this only affects the mousedown event.

Prevent invalid filename due to off-by-one in file browser

---

CHANGELOG.md
src/OpenLoco/Map/BuildingTile.cpp
src/OpenLoco/Station.cpp
src/OpenLoco/Station.h
src/OpenLoco/StationManager.cpp
src/OpenLoco/StationManager.h

Original game had a bug where it would write to bad memory and end up delivering cargo to stations that it shouldn't.
Note will definitely cause a desync with existing game on some maps.

Fix: #366. Implement deliver cargo to nearby stations

---

CHANGELOG.md
src/OpenLoco/Windows/ToolbarTop.cpp
src/OpenLoco/Windows/ToolbarTopCommon.cpp

Incorrectly signed type was causing comparisons of equality to fail
This has annoyed me for a while keep accidentally constructing one way road.

Fix road dropdown not remembering selection

---

src/OpenLoco/Localisation/StringManager.cpp

Use placeholder strings `(missing string id: %d)` or `(invalid string id: %d)` instead of outright throwing an exception.
Because strings may not be directly visible, such instances are logged to the console as well.

Handle missing strings more gracefully

---

src/OpenLoco/Graphics/Gfx.cpp
src/OpenLoco/Graphics/Gfx.h
src/OpenLoco/Interop/Hooks.cpp
src/OpenLoco/Ui/WindowManager.h
src/OpenLoco/Windows/PromptBrowseWindow.cpp

The PromptBrowseWindow was still relying on vanilla code for its prepare draw function, particularly the part where it truncates the current directory if the path is overly long. This also meant that it only supported `\` for this purpose. This PR uses `fs::path::preferred_separator`, so Linux and macOS are now properly supported as well.
Also implemented sub_446E87 as a bonus, which is now called `loadFileDetails`. I have not implemented the two functions it calls. Even though they are unique to the prompt browse window, I am not sure how best to tackle them. Out of scope for this PR, anyway.
Before:
After

Finish PromptBrowseWindow's prepare draw function

---

src/OpenLoco/Game.cpp
src/OpenLoco/Windows/ToolbarTop.cpp

My previous PR, #1118, removed the hooks to the prompt browse window. This was working fine for all except saving games! Turns out the toolbar menu was still calling the vanilla function, thereby relying on the hook.
Replacing this call revealed a bug in hiding with the save prompt being initialised to the wrong save path. I think this wasn't an issue for users before #1118, however, so a changelog entry won't be needed.

Fix save game open

---

CHANGELOG.md
src/OpenLoco/Widget.cpp

Before:
(Note the caption showing in the lower-right corner of the game canvas, outside the prompt window.)
After:

Fix caption 22 widget text rendering

---

src/OpenLoco/Ui.cpp

The define-guarded `LOCO_WIN32` code path has not been in use since we started OpenLoco in 2018. I propose we remove it.
Note that this does not affect the `NO_LOCO_WIN32` path, which is concerned with replacing Win32 API calls on Linux/macOS, and mostly limited to `Hooks.cpp`

Remove deprecated LOCO_WIN32 code path

---

CHANGELOG.md
src/OpenLoco/GameCommands/Cheat.cpp

Not convinced this will fix #1127 but it does at least make the code slightly cleaner.

Fix #1127: Crash during vehicle renewal cheat

---

src/OpenLoco/Config.cpp
src/OpenLoco/Config.h
src/OpenLoco/Windows/Options.cpp

Should probably add a hook so that #913 is fixed for the config file.

Implement legacy config read/write

---

CHANGELOG.md
src/OpenLoco/Windows/Options.cpp

As reported on Discord.
Before:
After:

Fix: Options window spawns behind title logo

---

CONTRIBUTORS.MD
src/OpenLoco/Speed.hpp

Changed `65535` to `65536` = 2<sup>16</sup>, should fix this in case it actually is a typo.

Fix #1188: Possible error in conversion of Speed

---

src/OpenLoco/CommandLine.cpp
src/OpenLoco/CommandLine.h
src/OpenLoco/Interop/Hooks.cpp
src/OpenLoco/OpenLoco.cpp
src/OpenLoco/OpenLoco.h
src/OpenLoco/Platform/Crash.cpp
src/OpenLoco/Platform/Platform.Posix.cpp
src/OpenLoco/S5/S5.cpp
src/OpenLoco/S5/S5.h
src/OpenLoco/S5/SawyerStream.cpp
src/OpenLoco/S5/SawyerStream.h
src/OpenLoco/Utility/Stream.hpp
src/OpenLoco/openloco.vcxproj

Add basic command line interface, with uncompress and simulate commands:
```
usage: openloco [options] [path]
uncompress [options] <path>
simulate [options] <path> <ticks>
options:
-o     Output path
--help     -h     Print help
--version         Print version
```
**Note:** about half of the changes are changing S5 code to use new Stream classes. This and a few other things in the command line code were required for the network implementation.

Implement command line options

---

src/OpenLoco/Audio/Audio.cpp
src/OpenLoco/Company.cpp
src/OpenLoco/Entities/Misc.cpp
src/OpenLoco/Entities/Misc.h
src/OpenLoco/Objects/VehicleObject.h
src/OpenLoco/Paint/PaintMiscEntity.cpp
src/OpenLoco/Paint/PaintVehicle.cpp
src/OpenLoco/Vehicles/CloneVehicle.cpp
src/OpenLoco/Vehicles/CreateVehicle.cpp
src/OpenLoco/Vehicles/Vehicle.cpp
src/OpenLoco/Vehicles/Vehicle.h
src/OpenLoco/Vehicles/VehicleBody.cpp
src/OpenLoco/Vehicles/VehicleHead.cpp
src/OpenLoco/Vehicles/VehicleTail.cpp
src/OpenLoco/Windows/BuildVehicle.cpp
src/OpenLoco/Windows/Construction/Common.cpp
src/OpenLoco/Windows/News/News.cpp
src/OpenLoco/Windows/Vehicle.cpp

This is bigger than I hoped it would be, turns out Vehicle.h has a large number of structures in it and is widely referenced throughout the code. This PR is just the rename to lower camel case, I haven't changed any c-style casts or anything else.

Apply codestyle to vehicle.h/.cpp and related code

---

src/OpenLoco/Windows/CompanyWindow.cpp

Loan stepper size doesn't scale with inflation, so in games that have high inflation (ie year is high, like 2050), trying to alter your loan takes a very long time as the stepper can only do 100k increments at max, and this takes a long time if you need to loan 30 million.
This change removes the upper limit to the stepper size increase already existing in the game, where the longer you hold the button down, the larger the step size becomes.

Increase stepper speed for loans

---

src/OpenLoco/Drawing/SoftwareDrawingEngine.cpp
src/OpenLoco/Drawing/SoftwareDrawingEngine.h
src/OpenLoco/Graphics/Gfx.cpp
src/OpenLoco/Graphics/Gfx.h
src/OpenLoco/Interop/Hooks.cpp
src/OpenLoco/Ui.cpp

Moving the SDL_Palette into the SoftwareDrawingEngine to simplify future work. This fixes a few very very minor memory leaks.

Drawing Engine Palette Refactoring

---

data/language/en-GB.yml
src/OpenLoco/Localisation/StringIds.h
src/OpenLoco/Windows/Vehicle.cpp

In the new capacity string add in #1271 there is a leading space in the 'capacity' string that shouldn't be there:
It's now fixed with a new stringid without the leading space

Fix vehicle capacity string having a leading space

---

CHANGELOG.md
src/OpenLoco/Station.cpp
src/OpenLoco/Vehicles/VehicleHead.cpp

This PR aims to deal with the cargo transfer (original) bug: https://github.com/OpenLoco/OpenLoco/issues/130
An example of how it works:
At a station there are 60 tons of coal (25 days old).
20 tons of coal (5 days old) are added.
The days for the 'enroute' age are added up: 25 + 5 = 30 days
Then, (if there was previous cargo) the result is reduced using the following formula:
`enrouteAge = enrouteAge * (1 - addedQuantity / summedQuantity)`
So the new age would be 30 * (1 - 20 / 80) = 20 days
The new 'enroute' age for the 80 tons is now 20 days.
This should make transferring cargo from, say, a ship to a train which then finishes the delivery, finally viable.

Change how the cargo enroute age is calculated

---

src/OpenLoco/Company.cpp
src/OpenLoco/Entities/Misc.cpp
src/OpenLoco/Entities/Misc.h
src/OpenLoco/Industry.cpp
src/OpenLoco/Industry.h
src/OpenLoco/IndustryManager.cpp
src/OpenLoco/Map/BuildingTile.cpp
src/OpenLoco/Map/Tile.cpp
src/OpenLoco/Map/Tile.h
src/OpenLoco/Objects/IndustryObject.cpp
src/OpenLoco/Objects/IndustryObject.h
src/OpenLoco/Paint/PaintMiscEntity.cpp
src/OpenLoco/Station.cpp
src/OpenLoco/Ui/ViewportInteraction.cpp
src/OpenLoco/Vehicles/Vehicle.h
src/OpenLoco/Vehicles/VehicleBody.cpp
src/OpenLoco/Vehicles/VehicleHead.cpp
src/OpenLoco/Windows/Construction/StationTab.cpp
src/OpenLoco/Windows/IndustryWindow.cpp

It was suggested that `object` for a function name is perhaps a bit unclear. This changes it to getObject and ensures the result is const as nothing should be using a non const object except for ObjectManager functions.

Rename object function to getObject

---

CHANGELOG.md
src/OpenLoco/Windows/News/News.cpp

This fixes the crash that happens when you remove a crashed vehicle that has a news article window open that references it.
We should probably check every single viewport init function to make sure it is correctly deleteing viewports (setting the width to 0). 
Edit. I checked all other users and they used the correct viewportRemove function so all is fine.

Fix Remove Crash Vehicle Crash

---

src/OpenLoco/Company.cpp
src/OpenLoco/CompanyManager.cpp
src/OpenLoco/CompanyManager.h
src/OpenLoco/Game.cpp
src/OpenLoco/GameCommands/Cheat.cpp
src/OpenLoco/GameCommands/GameCommands.cpp
src/OpenLoco/IndustryManager.cpp
src/OpenLoco/Map/RoadTile.cpp
src/OpenLoco/Map/TileManager.cpp
src/OpenLoco/Scenario.cpp
src/OpenLoco/Title.cpp
src/OpenLoco/TownManager.cpp
src/OpenLoco/Ui/WindowManager.cpp
src/OpenLoco/Windows/Construction/Common.cpp
src/OpenLoco/Windows/TerraForm.cpp
src/OpenLoco/Windows/ToolbarTop.cpp

When dealing with the `_updatingCompanyId` loco_global, `CompanayManager::updatingCompanyId()` is the function to both set and get the value. This PR changes it so the function isn't overloaded and has the getter/setter named appropriately

renames updatingCompanyId() into get/set variants

---

CHANGELOG.md
src/OpenLoco/Interop/Interop.cpp
src/OpenLoco/Objects/ObjectManager.cpp
src/OpenLoco/Scenario.cpp
src/OpenLoco/Vehicles/Vehicle.cpp
src/OpenLoco/Vehicles/VehicleHead.cpp
src/OpenLoco/Windows/Construction/ConstructionTab.cpp
src/OpenLoco/Windows/ObjectSelectionWindow.cpp

One bug meant that object loading would never fail causing unexpected crashes later on. The other bug was that the object count was incorrect when rebuilding an index.

Fix multiple object loading bugs

---

CHANGELOG.md
src/OpenLoco/Audio/Audio.cpp

This happens when the game tries to select a track, but none are available as the current year is out of the range of all music tracks. In this case, we simply default to playing all music tracks.

fixes divide-by-zero audio crash when really far in future

---

src/OpenLoco/GameCommands/RemoveTree.cpp
src/OpenLoco/GameCommands/RemoveWall.cpp
src/OpenLoco/Map/TileManager.cpp

I had a look and 4BB432 was tree specific and called 461760 so moved things about
Also noticed that flags was meant to be passed to removeTree.

Fix removeElement removeTree code

---

src/OpenLoco/Vehicles/VehicleHead.cpp

I found a redundant `if` statement and simplified it. I tried to find any others existing in openloco with this regex in VS
`if \((.*) != (.*)\)\r\n\s+{\r\n\s+\1 = \2;\r\n\s+}`
but this line was the only match.

Remove redundant if statement

---

src/OpenLoco/Vehicles/CreateVehicle.cpp

I somehow used the wrong variable when implementing #1371 and I really don't know how, because I absolutely tested this multiple times as a game command, so I've no idea how this has happened. *Maybe* a base rebase or merge on my part, but I don't think that's it. Oh well, this is the fix.

use correct id for vehicle unlock check

---

src/OpenLoco/Interop/Hooks.cpp
src/OpenLoco/Objects/BuildingObject.h
src/OpenLoco/Town.cpp
src/OpenLoco/Town.h
src/OpenLoco/TownManager.cpp
src/OpenLoco/TownManager.h
src/OpenLoco/Windows/TownWindow.cpp

This is an implementation of `sub_497348`.
There is a weird behavior here where `producedQuantity[0]` is being sent to `sub_497DC1` as `population` when `building->isConstructed()` is `false`. I think I understood that correctly from the assembly code, but another set of eyes on this is a good idea.
I couldn't test this code on a busy save because my game can't seem to be able to run it currently (not related to this branch. It won't open the save on `master` as well), so please test this code.
I added a hook to this function in a separate commit so that it can be easily removed if we choose to remove it.

Implement sub_497348

---

src/OpenLoco/Windows/BuildVehicle.cpp

Vaguely related to one of #1376 issues.
None rail track only has one track type.

Fix crash when opening build window on certain scenarios

---

src/OpenLoco/Audio/Audio.cpp
src/OpenLoco/Audio/Audio.h
src/OpenLoco/Interop/Hooks.cpp

This prevents the multiple reloads of music samples which was a memory leak (although very slow). Also refactored to remove some of the old code that was designed around the hooks.

Tidy up audio allow caching of music samples

---

src/OpenLoco/OpenLoco.cpp

OpenAL was crashing / hanging when an exception occurs during the game. Possibly because the sources were not deleted before the context?
This was output to the console:
```
[ALSOFT] (WW) Error generated on context 03464E40, code 0xa004, "Deleting in-use buffer 33"
```

Exit cleanly when an exception occurs

---

src/OpenLoco/Map/TileManager.cpp

Mistake in https://github.com/OpenLoco/OpenLoco/pull/1339 most obvious in the scenario editor for some reason.

Fix crash when removing an element

---

CHANGELOG.md
src/OpenLoco/Scenario.cpp

Issue was caused by the sound not being unloaded(paused) when loading a scenario from the main scenario select screen. All other ways of loading would not be affected as sound is disabled when the load save screen is visible.
#1279 is similar but would really be best to handle by implementing vehicle sell.

Fix #1424 crash when loading scenario

---

CHANGELOG.md
data/language/en-GB.yml

Autopay tooltip on finances window is not formatted correctly. I swear I fixed this a while ago, but apparently not

correctly format autopay tooltip

---

src/OpenLoco/EditorController.cpp
src/OpenLoco/Game.cpp
src/OpenLoco/Scenario.cpp
src/OpenLoco/Tutorial.cpp

Reduces `loco_global` usage by replacing with calls to `S5.getOptions()`.
Will be easiest to code-review this by commit as I've done 1 `loco_global` per commit

reduce loco_globals with S5::getOptions()

---

src/OpenLoco/Config.cpp

I noticed this a while back the previous code would never reach the `else if` as the first `if` was always taken. It seems a bit pointless to keep these checks cause i doubt people will be using a computer with <64MB or <128MB so they will never be reached.

Fix physical memory checks

---

src/OpenLoco/Vehicles/CreateVehicle.cpp
src/OpenLoco/Vehicles/Routing.cpp
src/OpenLoco/Vehicles/Vehicle.cpp
src/OpenLoco/Vehicles/Vehicle.h
src/OpenLoco/Vehicles/VehicleBody.cpp
src/OpenLoco/Vehicles/VehicleHead.cpp
src/OpenLoco/Vehicles/VehicleTail.cpp

Just a bulk rename from `Vehicle*::var_2C` to `trackAndDirection`, since that's what var_2C is.

renames var_2C to trackAndDirection where applicable

---

src/OpenLoco/GameCommands/CreateTree.cpp
src/OpenLoco/GameState.h
src/OpenLoco/Scenario.cpp
src/OpenLoco/Scenario.h
src/OpenLoco/Windows/TerraForm.cpp

removes
```
static loco_global<uint8_t, 0x00525FB4> _currentSnowLine;
static loco_global<Season, 0x00525FB5> _currentSeason;
```

Reduce locoglobals snowandseason

---

src/OpenLoco/Graphics/Gfx.cpp

Regression from #1468
Superseeds #1491

Fix #1490. drawImageSolid not setting global variables correctly

---

CHANGELOG.md
src/OpenLoco/Windows/Vehicle.cpp

As title says, this feature is simple - if you hold the shift key when placing a vehicle, when the vehicle is placed it will automatically be toggled to 'On'.

Hold shift when placing a vehicle to start it immediately

---

src/OpenLoco/EditorController.cpp
src/OpenLoco/GameState.h
src/OpenLoco/OpenLoco.cpp
src/OpenLoco/S5/S5.h
src/OpenLoco/Scenario.cpp
src/OpenLoco/ScenarioObjective.cpp
src/OpenLoco/ScenarioObjective.h
src/OpenLoco/Windows/CompanyWindow.cpp
src/OpenLoco/Windows/TimePanel.cpp

Suggested here:
_Originally posted by @duncanspumpkin in https://github.com/OpenLoco/OpenLoco/pull/1487#discussion_r861452305_

split ScenarioObjective::Objective into 2 parts, so part of it can be reused in S5::Options

---

CHANGELOG.md
src/OpenLoco/Graphics/Gfx.cpp
src/OpenLoco/Graphics/Gfx.h
src/OpenLoco/Graphics/ImageId.h
src/OpenLoco/Graphics/ImageIds.h
src/OpenLoco/OpenLoco.cpp
src/OpenLoco/Paint/PaintTree.cpp

The init function was originally in initDisplay a function we implemented very early on and replaced with an SDL2 call. I've moved the init up into the main init function. Annoyingly this breaks a few assumptions we made in the ImageId class. It turns out there are 3 states for primary colours: normal, extended (remap), translucent (remap). Extended and translucent had been rolled into one (remap) but that needs to be undone as extended can be used with tree wilt but translucent cannot be used with treewilt!

Reenable Tree wilt

---

CHANGELOG.md
src/OpenLoco/Vehicles/Vehicle2.cpp

The vanilla game had a bit of a bug in this code that caused trains to have a massive speed boost when stuck on a hill this bug wasn't in our code so it caused a different issue. This change recreates the results of the vanilla bug.

Fix #1504. Trains getting stuck on hills when at negative speed

---

src/OpenLoco/Audio/Audio.cpp
src/OpenLoco/Input/Keyboard.cpp
src/OpenLoco/Interop/Interop.hpp
src/OpenLoco/OpenLoco.cpp
src/OpenLoco/Title.cpp
src/OpenLoco/Vehicles/VehicleBogie.cpp
src/OpenLoco/Windows/Construction/ConstructionTab.cpp

This was the source of a few bugs as its not copying the value its copying the reference which is almost never what you meant

Disable copy construction of loco globals

---

src/OpenLoco/Core/BitSet.hpp
src/OpenLoco/Industry.cpp
src/OpenLoco/Industry.h
src/OpenLoco/openloco.vcxproj

I have been meaning to bring over @ZehMatt 's bitset from OpenRCT2 for a while should make navigating our various bitsets a bit easier.
I've only used it on the one structure atm but it can be rolled out onto a few others.

Add BitSet.hpp from OpenRCT2

---

src/OpenLoco/Widget.cpp
src/OpenLoco/Widget.h
src/OpenLoco/Windows/BuildVehicle.cpp
src/OpenLoco/Windows/CompanyWindow.cpp
src/OpenLoco/Windows/IndustryWindow.cpp
src/OpenLoco/Windows/MapWindow.cpp
src/OpenLoco/Windows/Options.cpp
src/OpenLoco/Windows/StationList.cpp
src/OpenLoco/Windows/StationWindow.cpp
src/OpenLoco/Windows/TerraForm.cpp
src/OpenLoco/Windows/TownList.cpp
src/OpenLoco/Windows/TownWindow.cpp
src/OpenLoco/Windows/Vehicle.cpp
src/OpenLoco/Windows/VehicleList.cpp

Changes to BuildVehicle file (or any other widget) can be omitted from merge as desired, per the notes on issue 495 suggesting BuildVehicle requires special consideration.

Refactor for window left-align tabs (issue 495)

---

src/OpenLoco/Interop/Interop.hpp

This is to overcome a bug in GCC
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90333
which means we cannot force argument alignment. Luckily, the attribute
is only required on machines with SSE2 by default (where in particular
libx11 is compiled with SSE2) such as Arch. On the other hand, platforms
that target i386 *only*, such as Ubuntu, won't hit this (#986) and the
attribute is not necessary

Disable arg alignment on platforms without SSE2 on by default

---

src/OpenLoco/S5/S5.cpp
src/OpenLoco/S5/S5.h

Moves them into the higher level part of the function. This is important for the scenario list as we need to load a save without modifying state to list its properties.

Remove game state modifications from load file

---

CHANGELOG.md
src/OpenLoco/Interop/Hooks.cpp

On Apple M1, we can run OpenLoco in Wine32on64 within Rosetta 2.  However, it
seems that for some reason, these malloc and free hooks don't seem to work.
The realloc hook does work, therefore our implementation of realloc() receives
a block of memory that was never allocated by our implementation of malloc();
this causes realloc() to return a nullptr which causes a segfault.
By hooking these malloc and free wrappers, which simply call the malloc and free
implementations we were already hooking, our implementation of malloc and free
is properly called and OpenLoco runs on M1.

Hook malloc and free a bit higher up in the call stack. Fixes running on Apple M1.

---

src/OpenLoco/Graphics/Gfx.cpp

Overgeneralisation from bba9607df2e0d11c8e5875fa56c5b387e75867e3
Before:
After:

Undo change in Gfx::drawStringLeftWrapped

---

src/OpenLoco/Graphics/Gfx.h

This PR addresses the following compiler error. Not sure why GCC 12 has decided to start complaining about this. To add to this, `<array>` doesn't seem quite right, considering we're not using `std::array` containers in this header. Other suggestions are welcome.
```
/home/aaron/Repositories/OpenLoco/OpenLoco/src/OpenLoco/Drawing/../Graphics/Gfx.h: In constructor ‘OpenLoco::Gfx::PaletteMap::PaletteMap(uint8_t (&)[TSize])’:
/home/aaron/Repositories/OpenLoco/OpenLoco/src/OpenLoco/Drawing/../Graphics/Gfx.h:137:54: error: ‘size’ is not a member of ‘std’; did you mean ‘size_t’?
137 |             , _dataLength(static_cast<uint32_t>(std::size(map)))
|                                                      ^~~~
|                                                      size_t …
```

Add <array> include for gcc 12

---

src/OpenLoco/Audio/Audio.cpp

as title says, I found this variable isn't used for anything meaningful, and removing it didn't change anything. the bgm channel will always be used for music, so there is no need to store which music channel is being used if there is only one channel

_musicCurrentChannel variable isn't used for anything meaningful

---

CHANGELOG.md
src/OpenLoco/GameCommands/VehiclePickup.cpp

Unsure why the ai is picking up a none existent vehicle but this at least stops it crashing

Fix 1614: Crash on pickup of none existent vehicles

---

CHANGELOG.md
src/OpenLoco/Audio/Audio.cpp
src/OpenLoco/Audio/Channel.h

Mistake made when refactoring to reduce global usage and didn't end up
actually setting the variable. This removes all of the loco global usage
and replaces it with a normal global. This could be further worked on in future.

Fix #1612. Ambient audio no longer playing

---

src/OpenLoco/Widget.cpp
src/OpenLoco/Window.h
src/OpenLoco/Windows/CompanyFaceSelection.cpp
src/OpenLoco/Windows/Construction/ConstructionTab.cpp
src/OpenLoco/Windows/News/News.cpp
src/OpenLoco/Windows/ObjectSelectionWindow.cpp
src/OpenLoco/Windows/Options.cpp
src/OpenLoco/Windows/Vehicle.cpp

Following up from #1610. I have changed the non-slider use of `wt_5`/`slider` to use `wt_6`, which does not change the appearance or behaviour of the widgets in question. Could do with another test, though.

Rename widget type wt_5 to slider

---

CMakeLists.txt

Bumped the cmake version to get rid of an annoying windows warning. Few little things has gone wrong since yaml-cpp changes.

Cmake was broken on windows builds

---

src/OpenLoco/Graphics/Gfx.cpp

When the string needs to be wrapped but there are no words to wrap on it would move the pointer into uninitialised memory instead of shifting the memory by 1. Note this still has issues as its not locoString argument safe

Yet another wrap string issue fixed.

---

CHANGELOG.md
src/OpenLoco/GameCommands/Cheat.cpp

This Pull Request adds a check for ownership of Road and Track elements into the acquireAssets function, this makes sure that only the assets for the target company is acquired, preventing vehicles from crashing for other companies because of being on tracks not owned by them.
this should fix #1650 
this currently is a work in progress and needs testing

Fix Vehicle Crash for Acquire Assets cheat.

---

src/OpenLoco/Math/Vector.cpp

Found this whilst trying to get industryManger3 to not diverge. I thought it would break my 1000 and 10000 tick saves but they are still fine hence why this is a standalone PR.

Use the correct cap on fast square root

---

src/OpenLoco/Windows/PromptBrowseWindow.cpp

Something I missed while reviewing #1651. I've raised the limit back to 200 chars, for now. I'd prefer to use a constant from `std::filesystem`, but I'm not aware of such a limit.

Raise filename length limit back to 200 chars

---

src/OpenLoco/Interop/Hook.cpp
src/OpenLoco/Interop/Interop.hpp

Required for my double hook.
```cpp
// Cheeky hook as this is hooking tryCreateNewIndustriesMonthly which is not used in vanilla anymore
// and then modifying callers to findRandomNewIndustryLocation allowing us to use both vanilla and new function
registerHook(
0x00459659,
[](registers& regs) FORCE_ALIGN_ARG_POINTER -> uint8_t {
registers backup = regs;
uint8_t indObjId = regs.dl;
auto res = findRandomNewIndustryLocation(indObjId);
if (res.has_value())
{
backup.ax = res->x;
backup.cx = res->y;
}
else
{
backup.ax = -1;
}
regs = backup;
return 0;
});
// Relocate calls to findRandomNewIndustryLocation to tryCreateNewIndustriesMonthly which is
// hooked to point to our findRandomNewIndustryLocation
writeLocoCall(0x0045994B, 0x00459659);
writeLocoCall(0x004597A0, 0x00459659);
```

Add writeLocoCall to interop

---

src/OpenLoco/Economy/Economy.cpp

This addresses the issue described in #1598. Going back to the disassembly it is clear 61 (ours: 122) should be used as an exclusive maximum. Note the snippet below uses `jb` and not `jbe`.
```
.text:0043762A                 cmp     edx, 61
.text:0043762D                 jb      short loc_43760B
```
I don't think this warrants a changelog entry. Even though the code ended up going over boundaries, this would only have mattered for the last cargo object, and even then, the elements directly after this array are:
```
.data:009C68F8 _deliveredCargoPayment dd 780h dup(?)   ; DATA XREF: ui__company_list__event_6_draw+74↑o
.data:009C86F8 zoom_ticks      dd ?                    ; DATA XREF: gui_init+7E↑w
.data:009C86FC _tutorialOffset dd ?                    ; DATA XREF: show_tutorial+D3↑w
``` …

Fix #1598: Cargo delivery payment calculation goes out of bounds

---

CHANGELOG.md
data/language/en-GB.yml
src/OpenLoco/Input.h
src/OpenLoco/Input/Keyboard.cpp
src/OpenLoco/Localisation/StringIds.h
src/OpenLoco/Ui/Screenshot.cpp
src/OpenLoco/Ui/Screenshot.h
src/OpenLoco/Windows/ToolbarTop.cpp
src/OpenLoco/Windows/ToolbarTopAlt.cpp

This PR introduces the ability to save the entire map as one giant screenshot. Living up to their name, these screenshots are 24,586×12,416 pixels, netting about 30MB each.

Add giant screenshots

---

src/OpenLoco/Environment.cpp
src/OpenLoco/Graphics/PaletteMap.cpp
src/OpenLoco/Interop/Interop.hpp
src/OpenLoco/Network/NetworkConnection.cpp
src/OpenLoco/Objects/ObjectIndex.cpp
src/OpenLoco/OpenLoco.cpp
src/OpenLoco/Windows/PromptBrowseWindow.cpp
src/OpenLoco/Windows/TitleMenu.cpp

They were barely used and it simplifies the header

Remove specific interop utility string functions

---

README.md

CMake 3.14.0 released in March 2019 [1] added the command line config options `-S <source-dir>` and `-B <build-dir>` and the build argument `--build <build-dir>` [2]. These options are universally valid independent of the build system used (`make`, `nmake`, `ninja`, `MSBuild`,...), making the provided CMake commands more generic.
As reference Ubuntu 20.04 ships the CMake 3.16.3 [3] version.
- [1] https://gitlab.kitware.com/cmake/cmake/-/tags/v3.14.0
- [2] https://cmake.org/cmake/help/v3.14/release/3.14.html#command-line
- [3] https://packages.ubuntu.com/focal/cmake

Update CMake usage in README build instructions

---

DEVELOPMENTLOG.md
src/OpenLoco/Graphics/Gfx.cpp
src/OpenLoco/Localisation/StringManager.cpp
src/OpenLoco/Localisation/StringManager.h
src/OpenLoco/Objects/VehicleObject.cpp
src/OpenLoco/Ui/ViewportInteraction.cpp
src/OpenLoco/Windows/CompanyWindow.cpp
src/OpenLoco/Windows/Vehicle.cpp

Lots of places are incorrectly handling inline string arguments potentially miss copying or getting the wrong length of strings.
~~There are still a few places using the stdlib ones that i need to investigate so this isn't ready just yet.~~

Introduce locoStrlen and locoStrcpy to handle args

---

src/OpenLoco/Drawing/FPSCounter.h
src/OpenLoco/GameCommands/Cheat.h
src/OpenLoco/Localisation/LanguageFiles.h
src/OpenLoco/Localisation/Languages.h
src/OpenLoco/Localisation/Unicode.h
src/OpenLoco/Map/QuarterTile.h
src/OpenLoco/Map/Track/Track.h
src/OpenLoco/Map/Tree.h
src/OpenLoco/Ui/Cursor.h
src/OpenLoco/Ui/Dropdown.h
src/OpenLoco/Ui/Screenshot.h
src/OpenLoco/Ui/ScrollView.h
src/OpenLoco/Ui/TextInput.h
src/OpenLoco/Utility/Yaml.hpp

I noticed that some of the headers are missing `#pragma once`. This PR adds it to the remaining headers

add #pragma once to header without it

---

src/OpenLoco/GameCommands/VehiclePickup.cpp
src/OpenLoco/GameState.h
src/OpenLoco/Industry.cpp
src/OpenLoco/Industry.h
src/OpenLoco/Map/WaveManager.cpp
src/OpenLoco/OpenLoco.cpp
src/OpenLoco/OpenLoco.h
src/OpenLoco/Scenario.cpp
src/OpenLoco/Town.h
src/OpenLoco/Tutorial.cpp
src/OpenLoco/Utility/Prng.hpp
src/OpenLoco/Windows/IndustryList.cpp

Really this should be in Core as well not Utility but its a pain to move with all the CMake outstanding PRs

Fix prng naming to follow coding style

---

src/OpenLoco/src/Input.h
src/OpenLoco/src/Input/MouseInput.cpp
src/OpenLoco/src/Windows/Cheats.cpp
src/OpenLoco/src/Windows/CompanyWindow.cpp
src/OpenLoco/src/Windows/Construction/ConstructionTab.cpp
src/OpenLoco/src/Windows/Options.cpp
src/OpenLoco/src/Windows/ScenarioOptions.cpp

Some minor refactor work, primarily focussed on removing globals from the scenario options window.
* Use GameState in ScenarioOptions window
* Replace _commonFormatArgs with FormatArguments in scenario options
* Remove references to clickRepeatTicks outside of MouseInput.cpp

Refactor scenario options window

---

CHANGELOG.md
src/OpenLoco/src/EditorController.cpp
src/OpenLoco/src/Windows/ScenarioSelect.cpp

Mistake made in implementation of the editorcontroller meant that invalid currency objects were set as the currency of a scenario meta details. This would cause the game to unload the currency object which would change the layout of image data set for water object which would cause invalid offsets to be set in the palette table which would cause the image draw functions to behave oddly causing crashs or infinite loops.

Fix #1676, #1702. Scenario list crash/hang on new scenarios

---

CHANGELOG.md
data/language/en-GB.yml
src/OpenLoco/src/Localisation/StringIds.h
src/OpenLoco/src/Windows/Options.cpp

This PR reorganises the miscellaneous options tab, grouping relevant options into boxes, reducing visual clutter.
Before:
After:

Revamp the miscellaneous options tab

---

CHANGELOG.md
data/language/en-GB.yml
src/OpenLoco/src/Config.cpp
src/OpenLoco/src/Config.h
src/OpenLoco/src/Localisation/StringIds.h
src/OpenLoco/src/Town.cpp
src/OpenLoco/src/Windows/Options.cpp

This adds the option to disable town renewal/expansion/growth, intended as a QoL feature for sandbox players.

Optionally disable town growth

---

src/Core/CMakeLists.txt
src/Core/include/OpenLoco/Core/EnumFlags.hpp
src/Core/tests/EnumFlagsTests.cpp
src/OpenLoco/src/Company.cpp
src/OpenLoco/src/Company.h
src/OpenLoco/src/CompanyManager.cpp
src/OpenLoco/src/S5/S5.h
src/OpenLoco/src/Windows/CompanyList.cpp
src/OpenLoco/src/Windows/CompanyWindow.cpp
src/OpenLoco/src/Windows/PlayerInfoPanel.cpp
src/OpenLoco/src/Windows/PromptBrowseWindow.cpp
src/OpenLoco/src/Windows/TimePanel.cpp

This is a proposal to use enum flags for actual flags. OPENLOCO_ENABLE_ENUM_FLAGS just implements all the operators. The main benefit is that its a strong type and can't be accidentally mixed with another flag, the other benefit is that the debugger will now correctly show all flags with a name.
I changed CompanyFlags to use this to have some example code, should probably rename challengeFlags to companyFlags or just flags for the Company struct.

Introduce enum flags

---

CHANGELOG.md
src/OpenLoco/src/Environment.cpp

This PR improves the OpenLoco 'onboarding experience' by making the Locomotion folder prompts more verbose and user-friendly. I'll let the screenshots below speak for themselves.
NB: the screenshots were taken on Linux. SDL popups do not look particularly nice on Linux; I'm sure they look nicer on Windows and macOS.
Closes #1698

Close #1698: improve Locomotion folder prompts

---

src/OpenLoco/src/Windows/TerraForm.cpp

The parser doesn't quite like this and it seems to be an accidental change, see https://github.com/OpenLoco/OpenLoco/commit/7380c4b4492ac76cd4022dba559b405962f0cc01#diff-aaae0c8d1a0b580bbfaad30e86c4c3f9d72ac4f65b93271fdfe300b7d8f9102aR1023

Fix address comment for toolDragEnd

---

src/Interop/include/OpenLoco/Interop/Interop.hpp

Since debug builds disable inlining entirely each call to addr would also lead to remapAddress calls, since the addresses are all const we can just compute the address within addr with constexpr, this makes very little difference code wise but spares us with all the pointless calls. I also added std::launder, it was sort of made for this purpose to specify the lifetime of an object that comes from some memory address, this acts as optimization barrier and avoids possible undefined behavior. Also instead of a C cast it uses reinterpret_cast which is the correct way to go about this.

Performance improvement for debug builds, fix possible UB

---

.github/workflows/ci.yml

There is currently a warning about github deprecating one of the things it uses

Use most up to date run-vcpkg

---

CMakeLists.txt
thirdparty/CMakeLists.txt

I think this makes more sense, now all thirdparty stuff is at one place we need to manage. Was trying to add spdlog to test it out and noticed it was a bit scattered.

Move thirdparty part in CMakeLists root to thirdparty CMakeLists

---

src/OpenLoco/src/Paint/Paint.cpp
src/OpenLoco/src/Paint/Paint.h

Enum PaintStruct Quadrant Flags

---

CHANGELOG.md
src/OpenLoco/src/Input/Keyboard.cpp
src/OpenLoco/src/Ui.cpp
src/OpenLoco/src/Ui.h

This annoyed me quite a bit, it should only scroll when the window has actually input focus.

Apply edge scroll only when the window has input focus

---

src/OpenLoco/src/Drawing/SoftwareDrawingEngine.cpp
src/OpenLoco/src/Drawing/SoftwareDrawingEngine.h
src/OpenLoco/src/Ui.cpp

Mostly moving code around, no actual changes.

More rendering refactoring

---

CHANGELOG.md
src/OpenLoco/src/Objects/Object.h
src/OpenLoco/src/Objects/ObjectManager.cpp
src/OpenLoco/src/Objects/ObjectManager.h
src/OpenLoco/src/Objects/TrackObject.cpp
src/OpenLoco/src/Objects/TrackObject.h
src/OpenLoco/src/Windows/Construction/Common.cpp

Getting onto the more annoying load functions. This one had a mistake in the unload! It wasn't clearing the correct values this would mean that packing track objects would mess up! Not sure if that is a known issue.

Track Object Load

---

CHANGELOG.md
src/OpenLoco/src/Objects/RoadObject.cpp
src/OpenLoco/src/Objects/RoadObject.h

Another object with bad unloads!

Road object load

---

CHANGELOG.md
data/language/en-GB.yml
src/OpenLoco/src/Input/Keyboard.cpp
src/OpenLoco/src/Localisation/StringIds.h
src/OpenLoco/src/Ui/TextInput.cpp
src/OpenLoco/src/Ui/TextInput.h
src/OpenLoco/src/Ui/WindowManager.h
src/OpenLoco/src/Windows/ObjectSelectionWindow.cpp

This PR introduces search/filter functionality to the object selection window, performing case-insensitive string matching on the visible name and object filenames.
Matches by visible name:
Or by object filename:

Add search/filter functionality to object selection window

---

CHANGELOG.md
src/OpenLoco/src/Windows/CompanyList.cpp

While tinkering with the warnings I discovered this. This would have never made it if the warnings were not disabled for unused variables.
Closes #1853

Fix company sort order by status

---

CHANGELOG.md
src/OpenLoco/src/OpenLoco.cpp

Actually my bad, sleeping for the remaining time until the next tick halted the entire game loop for that time of course.
Closes #1475

Fix #1475: Slow view panning with uncaps FPS disabled

---

src/OpenLoco/src/Windows/TitleExit.cpp

The 'Exit game' button at the bottom-right of the title screen uses `getStringWidthNewLined` to determine the width of the button. This is expected to return a width of 40px for English, but other languages may use a wider button (e.g. German, Spanish).
The width does not seem to be consistent, however, due to the tooltip window overriding the font used. Due to the string rendering functions still using globals, this triggers a race condition, which this PR addresses.

Fix #1870: 'Exit game' button glitches

---

src/OpenLoco/src/Objects/VehicleObject.cpp

Fix #1874
Silly me, reading one memory addresses twice and expecting different values.

Fix mistake in vehicle object load.

---

src/Console/CMakeLists.txt
src/Console/include/OpenLoco/Console/Console.h
src/Console/src/Console.cpp
src/Core/CMakeLists.txt
src/Interop/src/Interop.cpp
src/OpenLoco/src/Audio/Audio.cpp
src/OpenLoco/src/Drawing/SoftwareDrawingEngine.cpp
src/OpenLoco/src/Entities/EntityManager.cpp
src/OpenLoco/src/GameCommands/Cheat.cpp
src/OpenLoco/src/Graphics/Gfx.cpp
src/OpenLoco/src/Interop/Hooks.cpp
src/OpenLoco/src/Localisation/StringManager.cpp
src/OpenLoco/src/Network/Network.cpp
src/OpenLoco/src/Network/NetworkClient.cpp
src/OpenLoco/src/Network/NetworkConnection.cpp
src/OpenLoco/src/Network/NetworkServer.cpp
src/OpenLoco/src/Network/Socket.cpp
src/OpenLoco/src/Objects/ObjectManager.cpp
src/OpenLoco/src/Objects/VehicleObject.cpp
src/OpenLoco/src/OpenLoco.cpp
src/OpenLoco/src/Ui.cpp
src/OpenLoco/src/Ui/Dropdown.cpp
src/OpenLoco/src/Windows/PromptBrowseWindow.cpp
src/OpenLoco/src/Windows/ScenarioSelect.cpp
src/Platform/src/Platform.Posix.cpp
thirdparty/CMakeLists.txt

As the title suggests, its about time we ditch the old way of formatting strings. I also started to refactor the Console library a little, I think we should rename this to Logging/Diagnostics at some point. Another benefit of libfmt is its dynamic_args_store which works a little like the CS way, one can push arguments to that object and format the string later with it, might be useful to have localisation actually type safe. I haven't refactored all uses of the old logging, its quite a few and i just renamed them to deprecated, can gradually replace them. The output is also now colorized on the console for each logging level. I think this can be merged as is besides potential review comments, all of this should be a bit prettier.

Refactor Console logging and introduce fmtlib

---

src/OpenLoco/src/Windows/StationWindow.cpp
src/OpenLoco/src/World/Station.cpp
src/OpenLoco/src/World/Station.h

There are multiple users of the sub function and this splits it out for those users.
I've also removed a few functions from the members as they could be called with nullptr stations. (Although I'm pretty sure nullptr stations are impossible)

Split up station calcs

---

CHANGELOG.md
src/OpenLoco/src/Audio/OpenAL.cpp
src/OpenLoco/src/OpenLoco.cpp

If we crash uncleanly i.e. not through an exception then the audio will get stuck waiting on a lock that is never free'd. This address's the issue by removing the destructor. If we exit uncleanly the audio will not be shutdown correctly but at least we wont hang. Also added an additional catch all exception handler as its possible we might have thrown an exception that isn't derived from std::exception
Fixes #1882

Fix hang when crashing uncleanly

---

src/OpenLoco/src/Graphics/ImageId.h

The methods I did not add [[nodiscard]] to were:
```
explicit constexpr ImageId(ImageIndex index)
: _index(index == kIndexUndefined ? kImageIndexUndefined : index)
constexpr ImageId(uint32_t index, ExtColour palette)
: ImageId(ImageId(index).withRemap(palette))
constexpr ImageId(uint32_t index, Colour primaryColour)
: ImageId(ImageId(index).withPrimary(primaryColour))
constexpr ImageId(uint32_t index, Colour primaryColour, Colour secondaryColour)
: ImageId(ImageId(index).withPrimary(primaryColour).withSecondary(secondaryColour))
constexpr ImageId(uint32_t index, ColourScheme scheme)
: ImageId(index, scheme.primary, scheme.secondary)
```
happy to add [[nodiscard]] if required.

added [[nodiscard]] to returns function in ImageId, to prevent further bugs

---

src/OpenLoco/src/Config.cpp
src/OpenLoco/src/Objects/Object.h
src/OpenLoco/src/Objects/ObjectManager.cpp

This is for #1902.
Nothing at present was expecting the object header to be default constructed to an empty header (at least i don't think there is I tried deleting the constructor and seeing where all the constructor sites were)

Make ObjectHeader trvially constructable

---

CHANGELOG.md
src/Diagnostics/CMakeLists.txt
src/Diagnostics/include/OpenLoco/Diagnostics/LogLevel.h
src/Diagnostics/include/OpenLoco/Diagnostics/LogTerminal.h
src/Diagnostics/src/LogFile.cpp
src/Diagnostics/src/LogTerminal.cpp
src/Platform/CMakeLists.txt
src/Platform/include/OpenLoco/Platform/Platform.h
src/Platform/src/Platform.Macos.mm
src/Platform/src/Platform.Posix.cpp
src/Platform/src/Platform.Windows.cpp

I refactored out the platform specific code to the Platform library, I had to remove Diagnostics as the dependency as Platform should be one of the core libraries that doesn't really depend on anything. It will also now disable printing escape sequences in case stdout is redirected to a pipe/file and instead prints the level. VT100 detection is done on posix via reading the env variable TERM and check for common terminals there might be some that I missed, on Windows we have to check for the version, this is done by dynamically locating RtlGetVersion and calling it to get the window version.

Improve logging library to handle cases where VT100 is unavailable

---

src/OpenLoco/src/Graphics/Gfx.h
src/OpenLoco/src/Paint/Paint.cpp

Could someone with gcc 12 check this. Also i noticed one potential issue the way vanilla handles children with attachements is slightly different to what we are doing. We should investigate that further as potentially we aren't displaying things quite correct with attachments. Possibly missing ones which are on the last child. But thats a bit odd design so i think we are fine.

Fix #1525: Compile warning gcc 12

---

src/OpenLoco/CMakeLists.txt
src/OpenLoco/src/GameCommands/GameCommands.cpp
src/OpenLoco/src/GameCommands/GameCommands.h
src/OpenLoco/src/GameCommands/VehicleReverse.cpp
src/OpenLoco/src/Vehicles/Vehicle.h
src/OpenLoco/src/Windows/Vehicle.cpp

This implements the vehicle reverse game command. I was surprised to see the 'query' sanity checks weren't being executed when the 'apply' play is set. I've taken the liberty to change that -- better safe than sorry.
Regardless, this implementation probably means the workaround below isn't needed any more, right? Should I remove it?
https://github.com/OpenLoco/OpenLoco/blob/9e5cdcc2edac8f6c4c6761feffff7851b9438df9/src/OpenLoco/src/GameCommands/GameCommands.h#L233-L243

Implement vehicle reverse game command

---

src/OpenLoco/src/CommandLine.h
src/OpenLoco/src/Localisation/Languages.h

```
In file included from /home/aaron/Repositories/OpenLoco/OpenLoco/src/OpenLoco/src/CommandLine.cpp:1:
/home/aaron/Repositories/OpenLoco/OpenLoco/src/OpenLoco/src/CommandLine.h:28:23: error: ‘uint16_t’ was not declared in this scope
28 |         std::optional<uint16_t> port{};
|                       ^~~~~~~~
/home/aaron/Repositories/OpenLoco/OpenLoco/src/OpenLoco/src/CommandLine.h:5:1: note: ‘uint16_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
4 | #include <string>
+++ |+#include <cstdint>
5 | 
/home/aaron/Repositories/OpenLoco/OpenLoco/src/OpenLoco/src/CommandLine.h:28:31: error: template argument 1 is invalid
28 |         std::optional<uint16_t> port{};
|                               ^
/home/aaron/Repositories/OpenLoco/OpenLoco/src/OpenLoco/src/Command …
```

Add cstdint include in two more headers for gcc 13.1

---

src/OpenLoco/src/CommandLine.cpp
src/OpenLoco/src/CommandLine.h
src/OpenLoco/src/Main.cpp
src/OpenLoco/src/OpenLoco.cpp
src/OpenLoco/src/OpenLoco.h
src/Platform/include/OpenLoco/Platform/Platform.h
src/Platform/src/Platform.Posix.cpp
src/Platform/src/Platform.Windows.cpp

Slightly convoluted as i wanted all the memory allocated cleaned up automatically so i've got a std::unique_ptr of char* and a std::vector of strings.

Use a utf8 command line on windows

---

CHANGELOG.md
src/OpenLoco/src/GameCommands/GameCommands.h
src/OpenLoco/src/Vehicles/CloneVehicle.cpp
src/OpenLoco/src/Windows/Vehicle.cpp

Based on work in #1954. Split off so the bugfix may be reviewed separately.

Fix #1953: Cloning a vehicle doesn't copy cargo retrofit selection

---

src/Engine/include/OpenLoco/Engine/World.hpp

Something I noticed in another PR, we should be using the right types and not confuse tile coordinates over map coordinates. Unfortunately we can't really make them real strong types but ideally we won't be storing plain integers and rather have vectors everywhere.

Use tile_coord_t for TilePos2 and functions

---

CHANGELOG.md
src/OpenLoco/src/GameCommands/ClearLand.cpp

Fixes #1966
In #1942 the offsets for some loco_globals were corrected to the right memory address but not the right data type. This resulted in an overflow bug, overwriting the last selected land type from the paint tool.

Correct data type for clear land offsets

---

src/OpenLoco/src/Objects/ObjectManager.cpp
src/OpenLoco/src/Objects/ObjectManager.h
src/OpenLoco/src/S5/S5.cpp
src/OpenLoco/src/S5/S5.h
src/OpenLoco/src/S5/SawyerStream.cpp
src/OpenLoco/src/S5/SawyerStream.h
src/Utility/include/OpenLoco/Utility/Numeric.hpp

This is for #1982, we should generally use std::byte for all raw memory data.

Use std::byte instead of uint8_t for raw memory

---

src/OpenLoco/src/Input/MouseInput.cpp
src/OpenLoco/src/Window.cpp
src/OpenLoco/src/Window.h
src/OpenLoco/src/Windows/Vehicle.cpp

All windows have been reimplemented for a while — save for the multiplayer one, which we're going to tackle in a different way. This means that we can now remove interop support for window events.
In doing so, I have found one bug hiding in the call for `event_15`. All events defaulted to an interop event, which meant the fallback/default cursor for `event_15` was never used in the C++ side of things. This meant e.g. terraform tool cursors wouldn't be set. Easy fix, fortunately. I'm renaming this event `toolCursor` in this PR as well, to reflect its usage.
I've currently left `isInteropEvent` in for assertion purposes. In my testing, it hasn't triggered, and I indeed haven't found any place where they should trigger. Before merging, I'd like the assertions to be removed, but I'd like …

Remove window event interop

---

src/OpenLoco/src/CommandLine.cpp

Recent changes made this not possible. So this re-enables it.

Allow overwritting files with uncompress command

---

src/OpenLoco/src/Map/TileManager.cpp
src/OpenLoco/src/Objects/BridgeObject.h

A close inspection of my divergence saves identified the following issue:
As everyone knows it should be the following:
Clearly there was an issue with lowering land underneath bridges! So that was super easy to identify the issue and fix.
_Above is a fictional story on how i found this issue... what actually was involved was very long and tedious trying to work out where exactly in memory and individual tile was._

Fix bridge height issue in land lower gc

---

CHANGELOG.md
src/OpenLoco/CMakeLists.txt
src/OpenLoco/src/OpenLoco.cpp
src/Platform/CMakeLists.txt
src/Platform/include/OpenLoco/Platform/Crash.h
src/Platform/src/Crash.cpp

I also took the liberty to clean it up a bit, I also had to refactor it a bit to be independent as Platform can't have a dependency to OpenLoco so instead it passes AppInfo to the initialization. Also wrapped it in a namespace to match the current code style a bit better. Also removed the forward declaration and instead use void* as the handle, we shouldn't be forward declaring thirdparty library types.

Fix breakpad

---

CHANGELOG.md
src/OpenLoco/src/Objects/ObjectManager.cpp

Crash would happen when loading a scenario and you had your objects in a folder with a non ascii path. This is due to it failing to load a competitor object. Normal object loading happened fine just the competitor object as that happens through a different mechanism that we haven't implemented just yet. Fix was to just hook our utf8 loader.

Fix crash when loading objects from non ascii paths

---

CHANGELOG.md
src/Interop/src/Hook.cpp

Our hook table is executable code but was marked as read/write code.
~~https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-setprocessdeppolicy~~
~~On Win11 DEP is enabled by default so could see this as being an issue for a lot of folks.~~

Fix crash when DEP enabled

---

src/Interop/src/Hook.cpp
src/OpenLoco/src/Graphics/Gfx.cpp

This PR change the log level for two log messages, as they often confused players.
* The warning for G1 element count not matching is now only shown if it _isn't_ the Steam version.
* Warnings about a hook straddling the page boundary are now shown in verbose mode only.

Change two log messages to verbose log level

---

CHANGELOG.md
src/OpenLoco/src/Ui/WindowManager.cpp

OpenLoco allows the mouse scroll wheel to be used to zoom in and out of the viewport, as well as to scroll through 'scrollable' view widgets. This PR introduces one of my favourite QoL features from OpenRCT2 to OpenLoco: being able to use the wheel to manipulate stepper widgets and tool sizes.
The code proposed has been adapted from https://github.com/OpenRCT2/OpenRCT2/pull/7627, so I would like to add @Broxzier as a co-author, assuming we get his blessing.

Allow scrolling up and down on steppers to change their values

---

CHANGELOG.md
src/Engine/include/OpenLoco/Engine/World.hpp
src/OpenLoco/CMakeLists.txt
src/OpenLoco/src/Audio/Audio.cpp
src/OpenLoco/src/GameCommands/ChangeLandMaterial.cpp
src/OpenLoco/src/GameCommands/ClearLand.cpp
src/OpenLoco/src/GameCommands/LowerLand.cpp
src/OpenLoco/src/GameCommands/LowerWater.cpp
src/OpenLoco/src/GameCommands/RaiseLand.cpp
src/OpenLoco/src/GameCommands/RaiseWater.cpp
src/OpenLoco/src/GameCommands/RemoveIndustry.cpp
src/OpenLoco/src/GameCommands/RemoveTown.cpp
src/OpenLoco/src/Map/IndustryElement.cpp
src/OpenLoco/src/Map/MapGenerator.cpp
src/OpenLoco/src/Map/TileLoop.cpp
src/OpenLoco/src/Map/TileLoop.hpp
src/OpenLoco/src/Map/TileManager.cpp
src/OpenLoco/src/Windows/Construction/StationTab.cpp
src/OpenLoco/src/World/Industry.cpp
src/OpenLoco/src/World/TownManager.cpp

The assumption that lead to this bug was that TilePosRangeView would not produce invalid TilePos2 coordinates. For various reasons, it can and should. In short, we have to check that coords are valid before using them.
This PR introduces two new methods, `getClampedRange` and `getWorldRange`, as a means of obtaining a constrained `TilePosRangeView`.
Fixes #2011, a crash when using terraform tools exceeding the map edge

Introduce getClampedRange and getWorldRange

---

src/OpenLoco/src/Map/TileManager.cpp
src/OpenLoco/src/Map/TileManager.h
src/OpenLoco/src/OpenLoco.cpp

This implements TileManager::allocateMapElements using a simple malloc, like the original function, answering questions about tile element capacity.
I think we might want to switch to a std container for allocation, but the original game expects 0x005230C8 to contain a ptr instead. Should we just allocate the internal tile element pool separately (statically?), then set 0x005230C8 to point to the start of that internal tile element buffer?

Implement TileManager::allocateMapElements

---

src/OpenLoco/src/Map/TileManager.cpp

Moved the index computation into its own function, the current calculation leaves gaps in the memory but due to some interop code we can't change it to kMapColumns just yet. Also added a check to see if the index is actually within _tiles range and added an error message.

Small refactor in Tile Manager

---

src/OpenLoco/src/MessageManager.cpp

This is ugly and I purposely had written the code not to do this but now i see we have a divergence when i try use the message manager with the create industry gc so this addresses that issue.

Add in Ugly Message copying to prevent divergences

---

CHANGELOG.md
src/OpenLoco/src/GameCommands/BuildCompanyHeadquarters.cpp
src/OpenLoco/src/GameCommands/RemoveCompanyHeadquarters.cpp

Fix issues with HQ placement

---

src/OpenLoco/src/Map/Track/Track.cpp
src/OpenLoco/src/Map/Track/Track.h
src/OpenLoco/src/Vehicles/Routing.cpp
src/OpenLoco/src/Vehicles/VehicleHead.cpp
src/OpenLoco/src/Windows/Construction/ConstructionTab.cpp

I'm still trying to work out how I can add some helper classes for the TaD mess. We basically have a variety of different things that can get shoved into a uint16_t and some can be used by other functions. The road/track split is really quite annoying for this.

Add names for some of the routing flags

---

CMakeLists.txt
cmake/OpenLocoUtility.cmake
src/Core/CMakeLists.txt
src/Core/include/OpenLoco/Core/Exception.hpp
src/Core/src/BinaryStream.cpp
src/Core/src/FileStream.cpp
src/Core/src/MemoryStream.cpp
src/Core/tests/FileStreamTests.cpp
src/Core/tests/MemoryStreamTests.cpp

Instead of not knowing where exceptions come from this approach includes always the source location, most compilers already implement the functions to obtain the information only std::source_location is C++20 but we don't need it, if we ever go to C++20 we can ditch the custom thing.
This is what it looks like now:

Better exceptions

---

CHANGELOG.md
src/OpenLoco/src/GameCommands/Company/BuildCompanyHeadquarters.cpp
src/OpenLoco/src/Input/Shortcuts.cpp
src/OpenLoco/src/Ui/WindowManager.h
src/OpenLoco/src/Windows/CompanyWindow.cpp
src/OpenLoco/src/Windows/Construction/Common.cpp
src/OpenLoco/src/Windows/IndustryList.cpp
src/OpenLoco/src/Windows/TownList.cpp

* Allow modifying HQ rotation using keyboard shortcut (default Z; #61)
* Fix: HQ placement now correctly passes buildImmediately flag onto building placement command (our bug)
* Change: construction ghosts now show finished buildings instead of scaffolding
* Fix: remove HQ ghost when company window is closed with shortcut
* Fix: Orphaned arrow bug when closing construction window with shortcut (original bug; #56)

Construction related bugfixes and improvements

---

src/OpenLoco/src/Objects/ObjectIndex.cpp
src/OpenLoco/src/Objects/ObjectIndex.h
src/OpenLoco/src/Objects/ObjectManager.cpp
src/OpenLoco/src/Objects/ObjectManager.h
src/OpenLoco/src/ScenarioManager.cpp

@AaronVanGeffen this is what is needed for your PR. You would need to modify ObjectHeader3 and loadTemporaryObject to add in the specific vehicle code and then you would need to force a rebuild of the cache probably through a flag of some sort on the object count.

Pass temporary load variables by return rather than global

---

CHANGELOG.md
src/OpenLoco/src/Windows/PromptBrowseWindow.cpp

Ideally, we'd move the drawing routines to use Unicode, but in the mean time, this is such an improvement.
Before:
After:

Fix #891: Non-ASCII characters do not show up correctly

---

CHANGELOG.md
src/OpenLoco/src/Objects/ObjectIndex.cpp
src/OpenLoco/src/Objects/ObjectManager.cpp
src/OpenLoco/src/Objects/ObjectManager.h
src/OpenLoco/src/Windows/ObjectSelectionWindow.cpp

This PR introduces secondary tabs to the object selection window, grouping vehicles by type if the vehicle objects tab is active. These new secondary tabs are not shown in any of the other tabs.
NB: merge after #2085.
Before:
After:

Group vehicles by type in object selection window

---

src/OpenLoco/src/Vehicles/Routing.cpp

I'm pretty confident that this is still the same behaviour. This is so there isn't a stack overflow from complex networks.

Rework routing functions to not recurse

---

CHANGELOG.md
data/language/en-GB.yml
src/OpenLoco/src/Localisation/StringIds.h
src/OpenLoco/src/Windows/ObjectSelectionWindow.cpp

Add 'expert mode' to object selection window

---

CHANGELOG.md
src/OpenLoco/src/EditorController.cpp
src/OpenLoco/src/Windows/LandscapeGeneration.cpp

Vanilla scenario editor lets you select 0 towns and regenerate the map, and only checks you have a town when you try to advance the editor stage. OpenLoco currently doesn't allow you to step to 0, it caps it at 1. The reason to allow it to go to 0 is to produce a map with no towns and let the user place the towns themselves. They can currently generate a 1-town map and delete it, but that leaves a small terraforming mess that must be manually fixed.

Allow 0-town landscape generation as per vanilla behaviour

---

.github/workflows/ci.yml

C++20 requires at least GCC10, while focal has GCC9

Drop focal builds for C++20

---

src/OpenLoco/src/Map/TileElementBase.h
src/OpenLoco/src/Map/TileManager.h

Noticed this while toying around with messing around with tile element queries

Use uint8_t for ElementType enum class

---

CHANGELOG.md
src/OpenLoco/src/GameCommands/Company/RenameCompanyOwner.cpp

pop16 is defined as unsigned. std::string is signed. std::remove first checks if the value is within the bounds of the type :(.

Fix issue with std algos and signed/unsigned types

---

src/OpenLoco/src/Map/Track/Track.cpp
src/OpenLoco/src/Map/Track/Track.h
src/OpenLoco/src/Windows/Construction/ConstructionTab.cpp

This is needed as some functions need the next road position.
When looking at a few road functions this was needed. Makes things match the track equivalent functions as well.

Split road connections function

---

src/OpenLoco/src/Audio/OpenAL.h

Needed to successfully compile on g++ (GCC) 13.2.1

Add cstdint include to OpenAL.h

---

src/OpenLoco/src/Map/Track/SubpositionData.cpp
src/OpenLoco/src/Map/Track/SubpositionData.h

#2174 is especially slow because of the allocations. Switching to a std::span prevents all of that. I'm not 100% sure if getRoadPlacementSubPositon ends up the same though. Would be good for someone to test road placement on master and this branch and confirm there is no change.

Don't allocate when getting the subposition data

---

CMakeLists.txt
cmake/mingw32_toolchain.cmake
src/OpenLoco/CMakeLists.txt

Changing things so that the dll output is compatible with OpenLoco.exe i.e. no lib prefix and cased `openloco`.

Cmake Mingw32 Improvements

---

src/OpenLoco/src/Objects/RoadObject.h

The flag value for `intersection` in RoadObjectPieceFlags appears to be wrong via copy-paste

Wrong flag value for intersection in RoadObject.h

---

CHANGELOG.md
src/OpenLoco/src/Objects/CompetitorObject.cpp

Unified the preview image in `ObjectSelectionWindow` with what is used in `CompanyFaceSelection`.
Before:
After:

Fix #2114: Company face in object selection window is wrong size

---

CHANGELOG.md
src/OpenLoco/src/Map/Tile.cpp
src/OpenLoco/src/Map/Track/Track.cpp
src/OpenLoco/src/Vehicles/Vehicle1.cpp

There were two divergences from v23.10 that had been missed until I ran my ai test save. Annoyingly the Tile::roadStation mistake caused a mistake in a function that was implemented much older than before my ai test saves. So will need to rerecord replays and call this the base. The trackConnections is also a potentially big change this function is used in many many many places so a mistake in it might cause a lot of difference. Still need to apply the vehicle1::updateRoad CS bug reproduction as well.

Fix divergences

---

src/OpenLoco/src/Paint/Paint.cpp
src/OpenLoco/src/Paint/Paint.h

While looking at IDA I noticed a few things, the order was a bit out of place, a few fields have been missing and we accessed the bounding box offset field outside of the class.
I wanted to implement some of the paint functions and that caught my eye, some things might be not needed but we can eliminate those later on, right now its good to stay a bit closer to the binary.

PaintSession refactor

---

src/OpenLoco/src/Paint/Paint.h

Those fields were actually part of the array, in the disassembly they had references since CS just directly wrote to the address to zero them but it's better to treat this as a single array.

Correct a small mistake

---

src/OpenLoco/src/Map/TileManager.cpp

Resize of vector is not malloc so it did 8 times more than it should.

Reduce memory usage when reorganizing tiles

---

src/OpenLoco/src/Config.cpp
src/OpenLoco/src/Config.h
src/OpenLoco/src/Input/Keyboard.cpp
src/OpenLoco/src/Windows/Options.cpp

There are three ways to pan the viewport in OpenLoco: putting the cursor to the canvas/window edge, right-click dragging, and using the arrow keys. The latter has been commented to be relatively slow, which this PR addresses.
This PR changes the arrow key scroll speed to match that of the edge scroll speed, effectively changing it from 8px to 12px at a time. Inspired by OpenRCT2, I have also made the speed configurable in the config file, making the scroll speed a new 'hidden' setting.

Move edge scrolling section to NewConfig struct and reorder

---

CHANGELOG.md
data/language/en-GB.yml
src/OpenLoco/src/Graphics/ImageIds.h
src/OpenLoco/src/Localisation/StringIds.h
src/OpenLoco/src/Widget.cpp
src/OpenLoco/src/Windows/TerraForm.cpp

This PR brings various improvements to the terraform tools:
- The mountain tool is now a toggle, rather than size 0, making it possible to specify the mountain's table size.
- The landscape 'paint mode' button now uses a slightly paintbrush image.
- The landscape texture selection is now hidden until the 'paint' mode is activated.
- Increases max tool sizes from 10x10 to 64x64. Larger tool sizes will show a number instead of a grid sprite.

Terraform improvements

---

src/OpenLoco/src/Config.cpp
src/OpenLoco/src/Config.h

This PR makes the config reading and writing more resilient by explicitly defaults for the YAML reader to fall back to. Added benefit is that we can omit all the `if` blocks checking whether nodes exist in the YAML file that is being read. This drastically increases legibility.
I've also changed the order of the NewConfig struct attributes, grouping them together logically. I'd like this struct to be split into smaller structs in another PR. Doing so would ideally be compatible with existing configs, though -- at least for a while. We might opt to addressing this along with a change in config format (TOML?), but that needs discussing first.
~NB: this PR is based on the work from #2229, so I'm filing this as a draft for now.~

Refactor NewConfig struct reading and writing

---

src/OpenLoco/src/Windows/TerraForm.cpp

The changes from #2228 had an unintended consequence in that the single-tile mountain tool now allowed for corner selection. The selected corner isn't used, however, so this should be disabled. Investigating this, I found the same to be true for the land type paint tool, so it is disabled for this tool as well now.

Land tool: disable surface corner selection in mountain or paint mode

---

src/OpenLoco/src/Input/Keyboard.cpp
src/OpenLoco/src/Ui/TextInput.cpp
src/OpenLoco/src/Ui/WindowManager.cpp
src/OpenLoco/src/Ui/WindowManager.h
src/OpenLoco/src/Window.cpp
src/OpenLoco/src/Window.h
src/OpenLoco/src/Windows/BuildVehicle.cpp
src/OpenLoco/src/Windows/ObjectSelectionWindow.cpp
src/OpenLoco/src/Windows/PromptBrowseWindow.cpp
src/OpenLoco/src/Windows/PromptOkCancelWindow.cpp
src/OpenLoco/src/Windows/TextInputWindow.cpp

This adds a new event to windows, `keyUp`, allowing window text input to be handled in a uniform way with less code.
Bonus: this now allows shortcuts to be executed if input is not consumed by a window with a keyUp event. (Changelog worthy?)

Turn window-specific handleInput functions into keyUp events

---

CHANGELOG.md
src/OpenLoco/src/Input/Keyboard.cpp

Issue caused by not scaling the mouse cursor position before checking it against the UI dimensions.
We really need do a thorough check of all cursor position users, with #1839 in mind as well.

Fix #2238: Scroll on map edge doesn't work for bottom and right edges

---

src/OpenLoco/src/Input/Shortcuts.cpp
src/OpenLoco/src/Ui/WindowManager.h
src/OpenLoco/src/Windows/TimePanel.cpp
src/OpenLoco/src/Windows/TitleMenu.cpp
src/OpenLoco/src/Windows/Vehicle.cpp

This implements the three remaining shortcut functions, `makeScreenshot`, `cancelConstructionMode`, and `sendMessage`. The latter requires networking, though, and has not been tested.

Implement remaining shortcut functions

---

src/OpenLoco/src/Input.h
src/OpenLoco/src/Input/Keyboard.cpp
src/OpenLoco/src/Input/Shortcuts.cpp
src/OpenLoco/src/Ui/Screenshot.cpp
src/OpenLoco/src/Ui/Screenshot.h
src/OpenLoco/src/Windows/ToolbarTop.cpp
src/OpenLoco/src/Windows/ToolbarTopAlt.cpp

This is the start of moving things out of the Input namespace. Many functions should be moved to Ui, particularly into the ToolManager and WindowManager.

Refactor screenshot logic out of Input namespace

---

CHANGELOG.md
src/OpenLoco/src/Localisation/Languages.cpp
src/OpenLoco/src/Localisation/Languages.h
src/OpenLoco/src/Windows/Options.cpp

As language was being copied the nativeName would be allocated and free'd before drawing. Most of the time this would just mean it didn't draw correctly but it could do anything.

Fix #2210. Prevent drawing invalid pointers

---

src/OpenLoco/src/Interop/Hooks.cpp
src/OpenLoco/src/Map/AnimationManager.cpp
src/OpenLoco/src/Map/TileManager.cpp
src/OpenLoco/src/S5/S5.cpp
src/OpenLoco/src/Title.cpp
src/OpenLoco/src/Ui/WindowManager.cpp
src/OpenLoco/src/ViewportManager.cpp
src/OpenLoco/src/Windows/Error.cpp
src/OpenLoco/src/Windows/ToolTip.cpp
src/OpenLoco/src/World/StationManager.cpp
src/OpenLoco/src/World/TownManager.cpp

This adds registers backups to all hook functions (apart from one for signal removal as i can't quite work out what it should do). Might solve some mysterious bugs.

Add missing registers backups

---

src/OpenLoco/src/EditorController.cpp
src/OpenLoco/src/Game.cpp
src/OpenLoco/src/GameCommands/GameCommands.cpp
src/OpenLoco/src/Gui.cpp
src/OpenLoco/src/OpenLoco.cpp
src/OpenLoco/src/Ui/Screenshot.cpp
src/OpenLoco/src/Ui/WindowManager.cpp
src/OpenLoco/src/Ui/WindowManager.h
src/OpenLoco/src/Windows/CompanyWindow.cpp
src/OpenLoco/src/Windows/Construction/Common.cpp
src/OpenLoco/src/Windows/Construction/ConstructionTab.cpp
src/OpenLoco/src/Windows/Error.cpp
src/OpenLoco/src/Windows/IndustryList.cpp
src/OpenLoco/src/Windows/Main.cpp
src/OpenLoco/src/Windows/PromptBrowseWindow.cpp
src/OpenLoco/src/Windows/TerraForm.cpp
src/OpenLoco/src/Windows/TitleMenu.cpp
src/OpenLoco/src/Windows/TownList.cpp

Move {show,hide}{Gridlines,DirectionArrows} into Main window. These methods always apply to the main window, so best to keep them there as well.
Rewrite {show,hide}{Gridlines,DirectionArrows}. The new functions use the viewport flags, rather than rely on an additional boolean state.
~~Add resetGridlines, resetDirectionArrows methods to replace direct memory access. This allows resetting the state logic for the above without amending flags. Previously, this relied on setting vanilla memory space.~~ And removed them again.
Add terraform tool size setter methods to replace direct memory access. Similar to above, but for each of the terraform tool sizes.
Consolidate Windows::showError into Windows::Error::open. The former appears to be a duplicate of the latter, with an extra sound parameter …

Refactor various window (manager) bits

---

src/OpenLoco/src/Input/MouseInput.cpp
src/OpenLoco/src/Input/Shortcuts.cpp
src/OpenLoco/src/Ui/ViewportInteraction.cpp
src/OpenLoco/src/Ui/WindowManager.cpp
src/OpenLoco/src/Ui/WindowManager.h
src/OpenLoco/src/Windows/Construction/Common.cpp
src/OpenLoco/src/Windows/IndustryList.cpp
src/OpenLoco/src/Windows/MessageWindow.cpp
src/OpenLoco/src/Windows/TerraForm.cpp
src/OpenLoco/src/Windows/TimePanel.cpp
src/OpenLoco/src/Windows/TitleMenu.cpp
src/OpenLoco/src/Windows/TownList.cpp
src/OpenLoco/src/Windows/Vehicle.cpp

This PR refers to issue #1590.
I have changed the parameter of `WindowManager::bringToFront()` from pointer to reference. If I understand correctly this a good practice since a reference doesn't need `nullptr` check. Is this correct? Are there other reasons?

Change Window functions parameters from pointer to reference

---

.github/workflows/ci.yml

See https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/
Inspired by https://github.com/OpenRCT2/OpenRCT2/pull/21326

Update checkout version for GitHub Actions

---

README.md

Add fmt to list of build prerequisites

---

CHANGELOG.md
src/OpenLoco/src/Map/MapGenerator/MapGenerator.cpp
src/OpenLoco/src/Windows/LandscapeGeneration.cpp

#2209 had an issue when town size was 0 (1 in the ui). When it was zero the randnext function will go wrong as the min is larger than the max and will end up returning invalid numbers. #2282 also mentions that there might be a mistake in the sizes as well. Perhaps needs further investigation.
Edit. Yes the ui code also had a mistake. So its fixed twice. Once in Ui to match vanilla and again to fix the crash (that can't happen anymore unless you hex edit your saves).

Fix town size very small crash

---

CHANGELOG.md
src/OpenLoco/src/Windows/PromptBrowseWindow.cpp

In #2225, we refactored mouse input such that certain handling is split off to `Input::processMouseWheel`. This new function is called in the main event loop. However, the load/save window uses its own event loop. Ideally, we get rid of that eventually. For now, I have just added the call, fixing the issue.

Fix #2287: Scroll wheel not working in load/save window

---

CHANGELOG.md
src/OpenLoco/src/Ui/ViewportInteraction.cpp

This PR addresses two issues. First and foremost, it fixes #2293, which meant the see-through trees flag was ignored when right-clicking on a viewport.
Second, it adds ignore flags for track and road elements when either of them is made see-through.

Fix #2293: see-through trees flag is ignored when right-clicking

---

src/Core/include/OpenLoco/Core/FileStream.h
src/Core/include/OpenLoco/Core/MemoryStream.h
src/OpenLoco/src/OpenLoco.cpp
src/OpenLoco/src/Paint/Paint.cpp
src/OpenLoco/src/Windows/BuildVehicle.cpp
src/OpenLoco/src/Windows/IndustryList.cpp
src/OpenLoco/src/Windows/MapWindow.cpp
src/OpenLoco/src/Windows/MessageWindow.cpp
src/OpenLoco/src/Windows/TerraForm.cpp
src/OpenLoco/src/Windows/TownList.cpp
src/Platform/src/Platform.Windows.cpp

This apply the checks from #2296 on the codebase. (Note it doesn't do anything about macros though)

Apply initial clang tidy checks to codebase

---

data/language/en-GB.yml
src/OpenLoco/src/Localisation/StringIds.h
src/OpenLoco/src/Windows/Cheats.cpp
src/OpenLoco/src/Windows/Options.cpp

This PR adds a new 'Vehicle behaviour' group to the options window, separating some settings from the from 'Gameplay tweaks' group. It also moves the 'Disable vehicle load penalty' cheat into this new 'Vehicle behaviour' group.
I also considered introducing a new tab for both affected groups. However, I'd like to tackle #132 eventually as well, which means it might be better to move the preferred company name settings to another tab instead.
Before:
After:

Move vehicle load penalty cheat into Options window

---

src/OpenLoco/src/Windows/LandscapeGeneration.cpp

In #2288, we changed the internal value for the selected max town size to match vanilla. However, the UI wasn't changed to reflect this, leading to the displayed value to be off-by-one.

Fix wrong max town size displayed in LandscapeGeneration window

---

CHANGELOG.md
src/OpenLoco/src/Windows/News/News.cpp

Regression from #2304. Should fix #2316, #2321.

Re-add missing resize event to news window

---

src/OpenLoco/src/Localisation/FormatArguments.hpp
src/OpenLoco/src/Ui/Dropdown.cpp
src/OpenLoco/src/Vehicles/OrderManager.cpp
src/OpenLoco/src/Windows/BuildVehicle.cpp

We really need to get rid of all of the void* string functions they might be hiding more instances of this going wrong. We should also avoid using the operator& on format arguments as it converts it to a void* which means it will be used with functions taking a void* which means the function might accidentally be passed a FormatArguments*

Fix crash when using format args in dropdowns

---

src/OpenLoco/src/GameCommands/Vehicles/CreateVehicle.cpp
src/OpenLoco/src/GameCommands/Vehicles/VehicleOrderDelete.cpp
src/OpenLoco/src/GameCommands/Vehicles/VehicleOrderDown.cpp
src/OpenLoco/src/GameCommands/Vehicles/VehicleOrderInsert.cpp
src/OpenLoco/src/GameCommands/Vehicles/VehicleOrderUp.cpp
src/OpenLoco/src/Vehicles/OrderManager.cpp
src/OpenLoco/src/Vehicles/OrderManager.h
src/OpenLoco/src/Vehicles/Orders.h

This stops https://github.com/OpenLoco/OpenLoco/issues/2336 from crashing but it doesn't fix the source of the ai issuing bad game commands. I'm still unsure if that is a vanilla issue or an OpenLoco one. Eithere way the ai is not currently validating game command results so sending bad game commands could be caused by many things.

Add protection to order game commands

---

CHANGELOG.md
data/language/en-GB.yml
src/OpenLoco/src/Localisation/StringIds.h
src/OpenLoco/src/Windows/LandscapeGeneration.cpp

This PR changes the landscape generation window slightly, moving the existing water options (sea level) from the land options tab into a tab their own tab. Not particularly exciting right now, but hopefully followed by some exciting new options soon. 
Before:
After:

Give water options their own tab in the landscape generation window

---

CHANGELOG.md
src/OpenLoco/src/World/StationManager.cpp

#2315 implemented allocate station which use the correct value for z but i didn't notice we had the hook wrong all this time... This modifies replays unfortunately.

Fix hook for station name

---

src/OpenLoco/src/EditorController.cpp

In #2354, we implemented the initialisation function for the scenario editor. Confusingly, we noticed the title screen flag was retained while resetting the other screen flags.
Well, we must have skipped something, because retaining it was inhibiting the editor's viewport functionality, e.g. scrolling, rotating, panning...
The fix is simple: remove the title screen flag as well. This makes the most sense to do as well, to me.

Fix scenario editor (regression from #2354)

---

data/language/en-GB.yml
src/OpenLoco/src/EditorController.cpp
src/OpenLoco/src/Localisation/StringIds.h
src/OpenLoco/src/Map/MapGenerator/SimplexTerrainGenerator.cpp
src/OpenLoco/src/S5/S5.h
src/OpenLoco/src/Ui/WindowManager.h
src/OpenLoco/src/Windows/LandscapeGeneration.cpp
src/OpenLoco/src/Windows/ObjectSelectionWindow.cpp

This PR rework the height map generator options in the landscape generation window.
If the original generator is selected, the hill shape object in use will now be shown. Next to this, a 'change' button is shown leading back to the object selection window.
If the simplex generator is selected, the user can specify the number of terrain smoothing passes to apply instead.
This area may be reused by #1941, e.g. to allow showing what PNG file is being used for the height map, along with a browse button.
The PR currently builds on a few unrelated changes which are probably best reviewed separately. These have been spun off to #2354 and #2355.
Before:
After:

Rework generator options in landscape generation window

---

CHANGELOG.md
src/OpenLoco/src/Windows/LandscapeGeneration.cpp
src/OpenLoco/src/Windows/TileInspector.cpp

The LandscapeGeneration and TileInspector windows were using the onMouseUp event for their stepper widget functionality, instead of the onMouseDown event used elsewhere. Using the 'up' event prevents repeated ticks from having effect on the steppers, and prevents the scroll wheel functionality (cf. #2019) from firing.
Both windows have their stepper events moved to onMouseDown, ensuring the scroll wheel now works as expected.

Always use mouse down event for stepper widgets

---

CHANGELOG.md
src/OpenLoco/src/GameCommands/Road/CreateRoadStation.cpp
src/OpenLoco/src/GameCommands/Track/CreateTrainStation.cpp

I thought that this would solve #2357 but I'm not sure if it would as that save only has 64 station tiles (which is a curious number anyway)

Fix crash when creating too big a station

---

CHANGELOG.md
src/OpenLoco/src/Vehicles/VehicleManager.cpp
src/OpenLoco/src/World/Company.cpp
src/OpenLoco/src/World/Company.h

* When a vehicle is sold/deleted a company may still have its owner status pointed to the vehicle. This change makes sure that we have a valid owner status by making sure it is updated to a new sane value.
* Added changelog
This solves #2388 and implements defensive measures so something similar might not happen again.

Fix crash when owner status still points to deleted vehicle (#2388)

---

src/OpenLoco/CMakeLists.txt
src/OpenLoco/src/Map/MapGenerator/HeightMap.cpp
src/OpenLoco/src/Map/MapGenerator/HeightMap.h
src/OpenLoco/src/Map/MapGenerator/MapGenerator.cpp
src/OpenLoco/src/Map/SurfaceElement.h
src/OpenLoco/src/Map/TileManager.cpp

This implements the first four terrain generation functions, near/far water, near/far mountains, as well as the 'around cliffs' terrain. They share common patterns, which I've extracted into separate functions.
I am leaving the other two methods, small/large random areas, for a future PR, as they do not share these common patterns.

Implement terrain generation

---

.github/workflows/ci.yml
CMakeLists.txt

This bumps vcpkg from [2023.06.20](https://github.com/microsoft/vcpkg/releases/tag/2023.06.20) to [2024.03.25](https://github.com/microsoft/vcpkg/releases/tag/2024.03.25).
This includes newer versions of SDL2, which might help with #2401

Bump vcpkg to 2024.03.25

---

CHANGELOG.md
src/OpenLoco/src/Input.h
src/OpenLoco/src/Input/MouseInput.cpp
src/OpenLoco/src/Windows/BuildVehicle.cpp
src/OpenLoco/src/Windows/ObjectSelectionWindow.cpp
src/OpenLoco/src/Windows/PromptBrowseWindow.cpp
src/OpenLoco/src/Windows/TextInputWindow.cpp

Since their introduction, text input widgets have been focused while their window is open. This meant they would always override shortcut behaviour, which is not always what is expected. This PR changes this behaviour, with focus now being optional.
The new behaviour should be more straightforward. Text boxes can be focused by clicking them. Clicking anywhere else will unfocus them immediately.
Two windows set focus automatically: the main text input window, and the load/save prompt window. Other uses require clicking.
Currently, the focus properties reside in MouseInput.cpp, along with a bunch of widged-related state. Ideally, these would be moved to the WindowManager namespace, along with most of the MouseInput.cpp file. However, as overdue that is, this is matter for a future PR.
Also …

Make focus optional for text input widgets

---

CHANGELOG.md
src/OpenLoco/src/Localisation/StringIds.h
src/OpenLoco/src/S5/S5.cpp

Closes #1014.
Adding these makes it apparent that the title screen is loaded twice when opening the game, somehow? Worth looking into for a potential speed-up.

Add progress bars to gamestate import/export

---

src/OpenLoco/src/OpenLoco.cpp

This removes sub_46FFCA entirely. None of the values it was setting were being used anywhere, and there are no xrefs in IDA either. @ZehMatt suggests it might be code from the msvcrt debug runtime.

Remove sub_46FFCA

---

src/OpenLoco/src/OpenLoco.cpp

The new progress bars (#2423) revealed we were loading the title screen twice. Means a very modest speedup in starting the game.

Remove redundant calls to Title::start

---

src/OpenLoco/src/OpenLoco.cpp

This removes the old cd key check. There's little point in it, anyway, since Steam and GOG seem to be using one cd key for all installs.

Remove legacy cd key check

---

src/OpenLoco/src/OpenLoco.cpp

This removes the setjmp/longjmp interop support, which is no longer needed. All its users have since been replaced with `throw GameException`. This means we now have more freedom to refactor the tick loop.
I believe the last bit of code that still relied on this was reimplemented in #2307.

Remove setjmp/longjmp interop support

---

src/Core/CMakeLists.txt
src/OpenLoco/src/Ui/WindowManager.cpp
thirdparty/CMakeLists.txt

Puts the Windows in their own storage rather than relying on the external memory. I've kept the changes relatively simple for now to just have it in a working condition before doing further refactors.

Refactor Window storage to use sfl::static_vector

---

CHANGELOG.md
src/OpenLoco/src/Ui/WindowManager.cpp

With #2436 in, we can finally close #2.
The screenshot below uses 17 windows (13 floating windows, 3 panels, and 1 main window).

Increase window limit from 12 to 64

---

src/OpenLoco/src/S5/S5.cpp

The game refuses to render the viewport as long the progress bar is active. This bypasses the window manager entirely and works like the screenshots rather than temporarily hooking into the window manager.

Fix save previews not being rendered

---

CHANGELOG.md
src/OpenLoco/src/ScenarioManager.cpp

Changing the in-game language currently forces a rebuild of the scenario index to translate the scenario descriptions and progress strings. I noticed this progress is quite slow – much slower than the initial scenario index creation process. After some investigation, I narrowed it down to `ScenarioManager::loadScenarioProgress`.
More specifically, `loadScenarioProgress` temporarily swaps out the currency object, and then calls `ObjectManager::reloadAll()`. While likely better for completeness, it seems to me a superfluous step, what with there always being one currency object loaded anyway. Removing these calls makes the process considerably faster. (I want to say 10x faster, but I haven't actually benchmarked it.)
Hopefully, this does indeed work as I think it does. I imagine …

Speed up ScenarioManager::loadScenarioProgress

---

CHANGELOG.md
data/language/en-GB.yml
data/language/nl-NL.yml
src/OpenLoco/src/Localisation/StringIds.h
src/OpenLoco/src/Objects/IndustryObject.cpp
src/OpenLoco/src/Objects/Object.h
src/OpenLoco/src/Windows/IndustryList.cpp
src/OpenLoco/src/Windows/IndustryWindow.cpp

Implements #1652
* Add column to industry list w/ sorting support
* Industry cargo type checks: Figured it was best now to extract the 0xFF to constant for re-use - there are several other places where this magic constant is used, so let me know if you'd like to revert this or are open for a follow-up PR to replace other occurrences 
* Updated changelog

Add last month production column to the industries list (#1652)

---

CHANGELOG.md
src/OpenLoco/src/Ui/WindowManager.cpp
src/OpenLoco/src/Ui/WindowManager.h
src/OpenLoco/src/Windows/Construction/ConstructionTab.cpp

In https://github.com/OpenLoco/OpenLoco/pull/2231/commits/9d772bb8fd73cbbb75994f1950df641469ef2ada, we revealed the `height_marks_on_land` and `height_marks_on_tracks_roads` flags were swapped in our implementation. As it turns out, we forgot this has implications for what we called `ViewportVisibility::heightMarksOnLand`, which should really have been `ViewportVisibility::heightMarksOnTrack` instead.
Should fix #2374.

Correct naming and use of ViewportVisibility::heightMarksOnTrack

---

src/OpenLoco/src/Localisation/StringIds.h
src/OpenLoco/src/Windows/ObjectSelectionWindow.cpp

Not actually a buffer! The string reads `{COLOUR BLACK}{INT16} selected (maximum {INT16})`.

Rename StringIds::buffer_2038 to StringIds::num_selected_num_max

---

src/OpenLoco/src/Gui.cpp
src/OpenLoco/src/Ui.cpp

This bit of code was hacked into Ui::resize at some point (#421). Gui::resize deals with repositioning many windows already; it's the better place for it.

Move options window centring to Gui::resize

---

src/OpenLoco/CMakeLists.txt
src/OpenLoco/src/GameCommands/GameCommands.cpp
src/OpenLoco/src/GameCommands/Road/RemoveRoadStation.cpp
src/OpenLoco/src/GameCommands/Road/RemoveRoadStation.h
src/OpenLoco/src/Ui/ViewportInteraction.cpp
src/OpenLoco/src/Windows/Construction/StationTab.cpp

This implements the removeRoadStation game command. It's very similar to removeTrainStation, so let's merge this after #2410.

Implement removeRoadStation game command

---

src/OpenLoco/CMakeLists.txt
src/OpenLoco/src/GameCommands/Airports/RemoveAirport.cpp
src/OpenLoco/src/GameCommands/Airports/RemoveAirport.h
src/OpenLoco/src/GameCommands/GameCommands.cpp
src/OpenLoco/src/Localisation/StringIds.h
src/OpenLoco/src/Map/StationElement.h
src/OpenLoco/src/Objects/AirportObject.cpp
src/OpenLoco/src/Objects/AirportObject.h
src/OpenLoco/src/World/Town.h

Has a few issues to be worked out still

 Implement removeAirport game command 

---

src/OpenLoco/src/Graphics/SoftwareDrawingEngine.cpp
src/OpenLoco/src/OpenLoco.cpp

This function hasn't done anything since probably OpenLoco began. To work it needed the window size be set in a global that we weren't setting. It looks to be some sort of debug thing or maybe some sort of indication to the render engine of where has changed.

Remove unused function

---

CHANGELOG.md
src/OpenLoco/src/Game.cpp
src/OpenLoco/src/Windows/PromptSaveWindow.cpp

This fixes #2341.
However something is not clear to me:
1. Why `loadGame()` had `Title::stop();`? Maybe it was added thinking that the function was for loading the selected game and not for opening load game window.
2. It seems that the _Load saved game_ button is opening a `PromptSaveWindow` and closing it immediately. In fact the code calls `Ui::WindowManager::close(Ui::WindowType::saveGamePrompt);` and then `0x0043C577 onClose()`. Why is that?

Fix music stop when loading saved game in title screen

---

CHANGELOG.md
src/OpenLoco/src/Audio/Audio.cpp
src/OpenLoco/src/Audio/Audio.h

As reported in https://github.com/OpenLoco/OpenLoco/issues/2180, the music doesn't restart when the game is resumed from pause.
This PR fixes it by preventing _Play music_ option to be unselected by `cfg.musicPlaying = playMusic(mi.pathId, cfg.volume, false);` in `playBackgroundMusic()` when game `isPaused()`.
But there is still a problem: when resuming in Locomotion the music is actually resumed, while in OpenLoco it restarts from the beginning.
Moreover I have noticed that clicking _Load Saved Game_ in main menu also stops the music.
I don't know if we should solve everything in one PR or you can review and merge this little fix only.

Ignore music playing state when game is paused

---

src/OpenLoco/src/Graphics/SoftwareDrawingContext.cpp
src/OpenLoco/src/Graphics/TextRenderer.cpp
src/OpenLoco/src/Paint/Paint.cpp
src/OpenLoco/src/Ui/WindowManager.cpp
src/OpenLoco/src/Ui/WindowManager.h

The way this works is a bit odd, before each window is rendered it copies the colors from what the window holds into the global, ideally when rendering the text it inherits the colors from the window so we avoid the need to set it in the window manager. For now this at least removes all the interop variables.

Remove interop for window colours, refactor code

---

CHANGELOG.md
src/OpenLoco/src/OpenLoco.cpp

_monthsSinceLastAutosave was not being reset after it reached the autosave frequency so following the first time it was autosaved every subsequent autosave was done at a monthly frequency

Fix bug with autosave frequency

---

src/Diagnostics/src/LogTerminal.cpp
src/OpenLoco/src/Map/Track/SubpositionData.cpp
src/OpenLoco/src/Paint/PaintEffectEntity.cpp
src/OpenLoco/src/Title.cpp
src/OpenLoco/src/Windows/Cheats.cpp
src/OpenLoco/src/Windows/CompanyList.cpp
src/OpenLoco/src/Windows/CompanyWindow.cpp
src/OpenLoco/src/Windows/IndustryList.cpp
src/OpenLoco/src/Windows/IndustryWindow.cpp
src/OpenLoco/src/Windows/KeyboardShortcuts.cpp
src/OpenLoco/src/Windows/LandscapeGeneration.cpp
src/OpenLoco/src/Windows/MapWindow.cpp
src/OpenLoco/src/Windows/Options.cpp
src/OpenLoco/src/Windows/ScenarioOptions.cpp
src/OpenLoco/src/Windows/StationWindow.cpp
src/OpenLoco/src/Windows/TimePanel.cpp
src/OpenLoco/src/Windows/ToolbarTop.cpp
src/OpenLoco/src/Windows/TownList.cpp
src/OpenLoco/src/Windows/TownWindow.cpp
src/OpenLoco/src/Windows/Vehicle.cpp
src/OpenLoco/src/Windows/VehicleList.cpp
src/OpenLoco/src/World/StationManager.cpp

While this doesn't matter that much for release builds it has some impact for debug builds as the compiler will be forced to evaluate the expression where without constexpr we would have static initializers. Also its generally good practice to have things like in this PR being constexpr.

More constexpr

---

src/OpenLoco/src/Graphics/Gfx.cpp
src/OpenLoco/src/OpenLoco.cpp
src/OpenLoco/src/Ui/ProgressBar.cpp

A little cleanup operation.
Removes all the dead time code.
Removes the dead progress bar code.
Removes the dead noise mask map code.

Remove dead code calls

---

src/OpenLoco/src/Objects/ObjectIndex.cpp
src/OpenLoco/src/Objects/ObjectIndex.h
src/OpenLoco/src/Windows/Options.cpp

i had held off doing this function as its a bit of silly function. We should just not do things like this and use a more sensible structure but decided its best to just implement it for now and rework object selection a later day.

Implement mark only loaded

---

.github/workflows/ci.yml
CMakeLists.txt

This bumps vcpkg from [2024.03.25](https://github.com/microsoft/vcpkg/releases/tag/2024.03.25) to [2024.07.12](https://github.com/microsoft/vcpkg/releases/tag/2024.07.12).
~~Hopefully helps with #2514.~~

Bump vcpkg pin to v2024.07.12

---

CHANGELOG.md
src/OpenLoco/src/Audio/VehicleChannel.cpp
src/OpenLoco/src/S5/S5.cpp

Went for some defense in depth here. We now always stop all vehicle sounds when loading and also protected the audio code from throwing exceptions when a vehicle isn't 2or6.

Fix #2520: Crash when loading from title screen

---

CHANGELOG.md
src/OpenLoco/src/Ui/ViewportInteraction.cpp
src/OpenLoco/src/Ui/WindowManager.h
src/OpenLoco/src/Windows/Construction/Common.cpp

Following up on #2551, this changes the right-click track mod removal function to take the selected track mod section mode into account.

Take selected track mod section into account when removing mods

---

src/OpenLoco/src/Windows/AboutMusic.cpp
src/OpenLoco/src/Windows/CompanyFaceSelection.cpp
src/OpenLoco/src/Windows/Error.cpp
src/OpenLoco/src/Windows/IndustryList.cpp
src/OpenLoco/src/Windows/IndustryWindow.cpp
src/OpenLoco/src/Windows/KeyboardShortcuts.cpp
src/OpenLoco/src/Windows/LandscapeGenerationConfirm.cpp
src/OpenLoco/src/Windows/Main.cpp
src/OpenLoco/src/Windows/MapToolTip.cpp
src/OpenLoco/src/Windows/MapWindow.cpp
src/OpenLoco/src/Windows/MessageWindow.cpp
src/OpenLoco/src/Windows/MusicSelection.cpp
src/OpenLoco/src/Windows/ObjectSelectionWindow.cpp
src/OpenLoco/src/Windows/ProgressBar.cpp
src/OpenLoco/src/Windows/PromptOkCancelWindow.cpp
src/OpenLoco/src/Windows/ScenarioOptions.cpp
src/OpenLoco/src/Windows/ScenarioSelect.cpp
src/OpenLoco/src/Windows/StationList.cpp
src/OpenLoco/src/Windows/TileInspector.cpp
src/OpenLoco/src/Windows/TitleExit.cpp
src/OpenLoco/src/Windows/TitleLogo.cpp
src/OpenLoco/src/Windows/TitleMenu.cpp
src/OpenLoco/src/Windows/TitleOptions.cpp
src/OpenLoco/src/Windows/TitleVersion.cpp
src/OpenLoco/src/Windows/TownWindow.cpp
src/OpenLoco/src/Windows/VehicleList.cpp

This integrates quite a few `loco_global` properties in the `Ui::Windows` namespace, and removes `Interop.hpp` includes from many more compilations units.

Integrate window loco_globals

---

CHANGELOG.md
src/OpenLoco/src/Windows/Error.cpp

Basically the equivalent of https://github.com/OpenRCT2/OpenRCT2/pull/22357.
Before:
After:

Rework error window to improve text contrast

---

CHANGELOG.md
src/OpenLoco/src/Paint/PaintTrackData.h

I don't know why i decided to implement the tunnels different to every other property (and then mess it up :))
Found the source of this issue when implementing the road paint as it used the same style for the streetlight heights.

Fix #2574: Left turn tunnels not drawing

---

src/OpenLoco/src/GameCommands/Docks/CreatePort.cpp

Found this tiny mistake when looking at airports. Without this you will never get the special "{town} docks" station names.

Fix docks never using docks in station name

---

CHANGELOG.md
src/OpenLoco/src/Input/MouseInput.cpp
src/OpenLoco/src/Ui/ScrollView.cpp
src/OpenLoco/src/Ui/Widget.cpp

This PR changes the scrollview behaviour such that scrollbars are no longer drawn when the scrollview contents do not overflow the visible area.
Basically the same as https://github.com/OpenRCT2/OpenRCT2/pull/22491

Hide scrollbars when there is nothing to scroll

---

src/OpenLoco/src/Windows/BuildVehicle.cpp

This cleans up the Build Vehicle window's `onResize` and `onUpdate` events. Split off from #2578.

Cleanup build vehicle window

---

src/OpenLoco/src/Vehicles/RoutingManager.cpp
src/OpenLoco/src/Vehicles/RoutingManager.h
src/OpenLoco/src/Vehicles/Vehicle.cpp
src/OpenLoco/src/Vehicles/Vehicle.h

This is the main track update motion function that handles traveling along a track. ~~It is not complete and I'm not entirely sure i want to go down this route with templates. I'm leaning to not doing it like this and adding more getters/setters to the VehicleCommon. There are a few other issues that need address before this is ready like fixing subposition data.~~

Update track motion

---

src/OpenLoco/src/GameCommands/Vehicles/CreateVehicle.cpp
src/OpenLoco/src/Vehicles/Vehicle.h
src/OpenLoco/src/Vehicles/VehicleBogie.cpp
src/OpenLoco/src/Vehicles/VehicleHead.cpp
src/OpenLoco/src/World/CompanyAi.cpp
src/OpenLoco/src/World/CompanyAi.h

There is some horrible branches in this code. I can't see an easy way to rework it to not be as horrible whilst still matching vanilla logic.

Vehicle Functions: Update daily

---

src/OpenLoco/src/Map/MapGenerator/MapGenerator.cpp

With all map generator code implemented, we can finally limit the heightmap generator to the actual map size. Provides a little speedup to the simplex noise based generator.

Limit heightmap generator to map size

---

CHANGELOG.md
src/OpenLoco/src/Localisation/StringManager.cpp
src/OpenLoco/src/Windows/Construction/ConstructionTab.cpp

Bridge tooltip was just displaying any old junk from the global var.
This solves the problem two fold. Fixes the source of the issue (puts the correct values in the global). And fixes the crash (accessing the invalid string id).

Fix #2604. Bridge tooltip crash

---

CHANGELOG.md
src/OpenLoco/src/Windows/MapWindow.cpp

Fixes the selective blinking issues with the following:
- Vehicles:
- Hovering 'Trains' blinks all vehicles
- None of the other vehicle types blink
- Transport Routes:
- Railroad track doesn't blink
- Narrow gauge doesn't blink
- Underground track is not rendered
- Ownership:
- Underground track is not rendered
Regressions from #2443 (v24.06), so warrants a changelog entry.

Fix selective minimap map blinks

---

src/OpenLoco/src/EditorController.cpp
src/OpenLoco/src/Game.cpp
src/OpenLoco/src/Game.h
src/OpenLoco/src/S5/S5.cpp
src/OpenLoco/src/S5/S5.h

Implements the `S5::drawScenarioPreviewImage` function. During implementation, I ran this implementation and the vanilla function side-by-side to ensure a correct result. The code has since been cleaned up, and is now ready to be merged.

Implement S5::drawScenarioPreviewImage

---

CHANGELOG.md
data/language/en-GB.yml
src/OpenLoco/src/EditorController.cpp
src/OpenLoco/src/Localisation/StringIds.h
src/OpenLoco/src/Map/MapGenerator/MapGenerator.cpp
src/OpenLoco/src/S5/S5.h
src/OpenLoco/src/Scenario.h
src/OpenLoco/src/Windows/LandscapeGeneration.cpp

Earlier this year, we moved the sea level settings to their own tab in the landscape generation window. This PR introduces the possibility to carve out river beds throughout the terrain map.
The resulting rivers aren't always the prettiest. Indeed, the code is a bit naive in places, and perhaps not the prettiest. Perhaps we can improve it a little over the course of the review process. Either way, I think it's a good start.

Add riverbeds to map generator

---

CHANGELOG.md
src/OpenLoco/src/Map/MapGenerator/HeightMap.h
src/OpenLoco/src/Map/MapGenerator/MapGenerator.cpp
src/OpenLoco/src/Map/MapGenerator/OriginalTerrainGenerator.cpp

This PR addresses issue #2614:
* Found a bug in `generateTerrainAroundCliffs` where it would go one tile past the bounds
* `OriginalTerrainGenerator` was hardcoding `& 0x1FF` (511), which I've replaced with `% heightMap.width - 1` (or height, as appropriate)
Bonus:
* Removed the superfluous `pitch` parameter from the HeightMap class, instead using `width`

Adjust OriginalTerrainGenerator to adhere to heightMap dimensions

---

CHANGELOG.md
src/OpenLoco/src/Map/MapGenerator/MapGenerator.cpp

The `generateTerrain` function represents a big chunk of the map generation process, with the full map being iterated over for number of patterns times the number of surface styles times! Unfortunately, we were only reporting progress at the start and end of the entire function. This PR changes this such that progress is now reported for every distribution pattern involved.

Increment progress bar for generateTerrain substeps

---

src/OpenLoco/src/Graphics/Colour.h

Noticed this while refactoring some other code, when AdvancedColour was const then it was impossible to just do `auto color = colourArg.opaque()`. Given the type is only 1 byte and no code ever used the functions for in-place modifications I made it return the value and make all of the functions const, to ensure nobody gets confused that this doesn't change the data for the object I added nodiscard so it will just cause compile errors when used wrong.

Refactor AdvancedColour to be const correct, add nodiscard for safety

---

src/Interop/include/OpenLoco/Interop/Interop.hpp
src/OpenLoco/src/Graphics/Colour.h

Small mistake I made, the static_cast was used to invoke the type operator which strips the data of all flags first. Also added an assert in interop, the exception thrown doesn't typically provide a meaningful call stack.
Also there were a few missing const keywords.

Advanced color fix

---

CHANGELOG.md
src/OpenLoco/src/Ui/Window.h
src/OpenLoco/src/Windows/MapWindow.cpp
src/OpenLoco/src/Windows/ObjectSelectionWindow.cpp
src/OpenLoco/src/Windows/TimePanel.cpp

This PR groups tabs in the object selection window such that related elements appear together. This is done in a way analogous to the vehicles tab, which was already using sub-tabs for each of the vehicle types.
Grouping these items together brings the number of main tabs down from 20 (advanced) or 34 (expert) to just 12. This makes the window less cluttered, and thereby hopefully makes it easier to find the right tab.
Before:
After:
To do:

Group object selection tabs by category

---

src/OpenLoco/src/Windows/PlayerInfoPanel.cpp
src/OpenLoco/src/Windows/TimePanel.cpp

Noticed there was a 5px gap between the time panel and the game window border, leading to the news ticker being rendered incorrectly. This corrects that.
Originally, I had changed the window height from 27px to 29px as well, however the bottom border seems to have been cut off intentionally.

Change TimePanel window width to match widgets

---

src/OpenLoco/src/OpenLoco.cpp
src/OpenLoco/src/Ui.cpp
src/OpenLoco/src/Ui.h

These were initialising and disposing DirectInput, which hasn't been used in a long time.

Remove initialiseInput, disposeInput

---

CHANGELOG.md
src/OpenLoco/src/Graphics/SoftwareDrawingContext.cpp

While working on #2646, it was discovered that our `drawLine` implementation has an off by one issue in horizontal-to-vertical transitions. This affects the map window as well, specifically rendering aircraft routes. Fixing the issue finally brings these in line with vanilla again.
Before:
After:

Fix drawLine being off by one in horizontal-to-vertical transitions

---

CHANGELOG.md
src/OpenLoco/src/Ui/Windows/CompanyList.cpp
src/OpenLoco/src/Ui/Windows/MapWindow.cpp

This PR changes the company list window such that tabs with charts are now made resizeable, following up on the work in #2646.

Allow resizing company charts

---

CHANGELOG.md
src/OpenLoco/src/Ui/Windows/Vehicle.cpp

The cargo text labels are spaced too far from the vehicle sprite. This was introduced sometime between v24.06 and v24.07; I'm assuming by #2513.
v24.06:
v24.07:
This PR:

Fix cargo text alignment

---

CHANGELOG.md
src/OpenLoco/src/Map/MapGenerator/OriginalTerrainGenerator.cpp

Fixes #2680
Side note, these 4 blit functions seem a little strange - I would have expected four functions following
```
[x++, y++]
[x++, y--]
[x--, y++]
[x--, y--]
```
but instead it seems the x and y loops are switched, which is a confusing and non-standard way to do this IMO

Fix modulo operation on negatives in terrain gen

---

CHANGELOG.md
src/OpenLoco/src/Paint/PaintVehicle.cpp
src/OpenLoco/src/Ui/Windows/DragVehiclePart.cpp
src/OpenLoco/src/Ui/Windows/Vehicle.cpp
src/OpenLoco/src/Vehicles/VehicleDraw.cpp
src/OpenLoco/src/Vehicles/VehicleDraw.h

Mistake from #2513 caused the vehicle paint to have wrong bound boxes and a change from implementing the vehicle draw inline caused bogies which overlap other bodies to change ordering.
Possible source of 1st bug of #2540

Fix #2678. Train bogie body draw order and body bound box

---

cmake/OpenLocoUtility.cmake

Spotted this one because of SFL in where it doesn't check for the alternative _MSC_LANG. I have a PR for SFL where it makes up for MSVC but until then this will do plus its a good thing to do anyway.

Enable correct reporting for __cplusplus

---

CHANGELOG.md
src/OpenLoco/src/Map/MapGenerator/MapGenerator.cpp

Quick fix that prevents division by 0 when generating riverbanks. This was able to happen if the player set the river meander rate to "1 units" when generating landscape in the scenario editor with non-zero number of rivers and riverbank width.

Fix crash when river meander rate is 1 unit

---

CHANGELOG.md
src/OpenLoco/src/Input/Keyboard.cpp

The keyboard shortcut to open the Options window did not work from the title screen, despite it being possible to open it using a mouse. This fixes that by adding check for the shortcut when the game is in title mode.

Make "Show Options Window" keyboard shortcut work in title screen

---

src/OpenLoco/src/Ui/Windows/MusicSelection.cpp

- `i` → `row`
- But also added `musicTrack`, which is given the same value.
- Groundwork for if the music selection window is changed in the future to make the row number and music ID number not necessarily be the same value (though the first line of `onScrollMouseDown()` will also need to be updated).
- `text_colour_id` → `textColour`
- `music_title_id` → `musicTitle`

Rename variables in MusicSelection.cpp

---

CHANGELOG.md
src/OpenLoco/src/Ui/Windows/MapWindow.cpp

Fixes #2718.
Implementation based on existing implementations of the same feature from other windows: https://github.com/OpenLoco/OpenLoco/blob/31b6d16f985289d68434994a82d2cc2ada399f9b/src/OpenLoco/src/Ui/Windows/TimePanel.cpp#L142 and https://github.com/OpenLoco/OpenLoco/blob/31b6d16f985289d68434994a82d2cc2ada399f9b/src/OpenLoco/src/Ui/Windows/ToolbarTopCommon.cpp#L92

Fix #2718 - North arrow image not changing to reflect rotation on the Map window

---

src/OpenLoco/src/Objects/TrainStationObject.cpp
src/OpenLoco/src/Objects/TrainStationObject.h
src/OpenLoco/src/Paint/PaintStation.cpp
src/OpenLoco/src/Paint/PaintStation.h
src/OpenLoco/src/Paint/PaintTrainStation.cpp
src/OpenLoco/src/S5/Limits.h
src/OpenLoco/src/World/Station.cpp

This was actually producing a noticeable slow down in rendering due to the allocation/deallocation of the vector. The engine can't actually handle anything larger than 16 so I've switched it to a static_vector. Note: Need patch in sfl to make the span work.

Improve performance of station rendering

---

CHANGELOG.md
src/OpenLoco/src/World/Company.cpp

Mistake made whilst implementing.

Fix #2727. Bankruptcy warnings do not appear

---

CHANGELOG.md
src/OpenLoco/src/Map/MapGenerator/MapGenerator.cpp
src/OpenLoco/src/Objects/ObjectIndex.cpp
src/OpenLoco/src/Ui/Windows/Construction/StationTab.cpp
src/OpenLoco/src/Vehicles/OrderManager.cpp

Tile uses TileElement* as its iterator type so for ranged loops will dereference the pointer and when the var is not declared a ref it will naturally do a copy. I think we should use custom iterators instead of pointers, I also don't really like the fact that a call  to end() is not the complexity of O(1)

Fix map generator not updating tree seasons

---

CONTRIBUTORS.md
src/OpenLoco/src/Audio/Audio.cpp
src/OpenLoco/src/Audio/Audio.h
src/OpenLoco/src/Ui/Windows/Options.cpp

-  In Audio.cpp, removed the `excludeTrack` parameter from all functions that had it, and removed `trackToExclude` in `playBackgroundMusic()`.
- Instead of needing a track to exclude as a parameter, `chooseNextMusicTrack()` removes `_lastSong` from the playlist it creates, if it is present and not the only song in the playlist. Preventing this function from choosing _lastSong appeared to be the intention of excludeTrack, so this simplifies that.
- Decomposed parts of `chooseNextMusicTrack()`, creating `addCustomSelectionSongsToPlaylist()` and `addSelectedPlaylistToPlaylist()`.
- Removed duplicate logic by replacing the function in Options.cpp that gets the list of music for the "Currently playing" dropdown with one that re-uses Audio.cpp's logic for generating the list of music.

Simplify & modularise music playlist code

---

CHANGELOG.md
src/OpenLoco/src/Objects/ObjectImageTable.cpp
src/OpenLoco/src/Objects/ObjectManager.cpp

If an object has a malformed image table it would be dangerous to try continue loading it as it may cause all sorts of crashes.

Prevent object loading crashing on malformed imagetables

---

src/OpenLoco/src/Paint/Paint.cpp
src/OpenLoco/src/Paint/Paint.h

This much I can already refactor without breaking any existing interop code, there is mostly the bridges left but this has no effect on it.

Remove interop for _paintHead, refactor uses, isolate PaintEntry

---

.github/workflows/ci.yml

I think this is a better approach, the secret is only available when the branch comes from this repository in the PR or its an action caused by this repo and not a fork.

Run simulate test only when the secret is available

---

CHANGELOG.md
src/OpenLoco/src/Environment.cpp
src/OpenLoco/src/Environment.h
src/OpenLoco/src/Ui/Screenshot.cpp

Taking a screenshot will now save it into a folder named "screenshots" (which gets auto-created if not present).
i.e. `%appdata%\OpenLoco\screenshots\` instead of just `%appdata%\OpenLoco\`

Screenshots directory

---

CHANGELOG.md
src/OpenLoco/src/Ui/Windows/ObjectSelectionWindow.cpp

Recently, we reworked the way objects are indexed (#2650), allowing for multiple folders to be scanned for object files. As a direct result, requesting an object entry's filename now returns the full path. This PR changes the object selection window such that only the actual filename is shown again.
Before:
After:

Show object filenames without directories

---

CHANGELOG.md
src/OpenLoco/src/Audio/Audio.cpp
src/OpenLoco/src/Game.cpp
src/OpenLoco/src/Ui/Windows/PromptSaveWindow.cpp

Effects:
- Fixes #2742
- Music no longer stops when loading into a scenario (so you now have more than just the loading bar train to keep you company whilst you wait)
Both of these effects match original Locomotion behaviour.

Update sound pausing on title screen to match original behaviour

---

src/OpenLoco/src/GameCommands/Vehicles/CreateVehicle.cpp
src/OpenLoco/src/Vehicles/Vehicle.h
src/OpenLoco/src/Vehicles/Vehicle2.cpp
src/OpenLoco/src/Vehicles/VehicleBody.cpp
src/OpenLoco/src/Vehicles/VehicleBogie.cpp
src/OpenLoco/src/Vehicles/VehicleHead.cpp

As discussed in Discord, I discovered that var_5E appears to be used for wheelslipping.
Observed behaviour is that when var_5E of the front bogey != 0, the vehicle is wheel slipping. This can be seen happening in-game randomly to vanilla steam engines when they are setting off. The function `shouldSetVar5E` (renamed here to `shouldStartWheelSlipping`) seems to determine when the vehicle should start wheel slipping.
Also rename `kMaxVehicleLength` to `kMaxRoadVehicleLength`.

Rename var_5E to wheelSlipping

---

CHANGELOG.md
src/OpenLoco/src/GameCommands/Company/RenameCompanyName.cpp
src/OpenLoco/src/GameCommands/Company/RenameCompanyOwner.cpp
src/OpenLoco/src/GameCommands/General/RenameStation.cpp
src/OpenLoco/src/GameCommands/Industries/RenameIndustry.cpp
src/OpenLoco/src/GameCommands/Town/RenameTown.cpp
src/OpenLoco/src/GameCommands/Vehicles/RenameVehicle.cpp
src/OpenLoco/src/Localisation/StringManager.cpp
src/OpenLoco/src/Localisation/StringManager.h
src/OpenLoco/src/World/IndustryManager.cpp
src/OpenLoco/src/World/StationManager.cpp
src/OpenLoco/src/World/TownManager.cpp

`userStringAllocate` was implemented back to front for the unique name parameter. In addition all callers weren't passing whether it should be unique or not.

Fix #2785. Unique names for industries not respected

---

CHANGELOG.md
src/OpenLoco/src/Audio/Channel.cpp

It seems some objects e.g. `CARVWBAM` were relying on the dsound function that skipped setting frequency if the frequency value was zero.

Allow for zero frequency sound objects

---

CHANGELOG.md
src/OpenLoco/src/Objects/ObjectIndex.cpp

Fixes the crash that can happen if you move folders.
Solved by encoding the base path in the folder state. Which can later be used to perhaps not need to do a full reindexing.

Fix #2716. Plugin.dat crash

---

CHANGELOG.md
src/OpenLoco/src/Vehicles/Vehicle.cpp

~~One of the reasons this is slow is due to having to recreate the train. But we can skip that as we have already removed the ability to do this fancier check on non-selves.~~
Switch to vanilla style for this calc.

Improve performance of collision checks

---

src/OpenLoco/src/Paint/PaintRoad.cpp
src/OpenLoco/src/Paint/PaintTrack.cpp

This is for #2825
These globals were only here due to interop that isn't needed anymore.

Remove globals from paint road/track

---

CHANGELOG.md
src/OpenLoco/src/Graphics/SoftwareDrawingEngine.cpp

A small regression from #1965, when we don't use scaling we can avoid copying to the textures which are a bit slower as it uses a command queue to perform those tasks once SDL_RenderPresent is called.
PR:
master:

Avoid expensive copies to texture when scaling isn't applied

---

src/OpenLoco/src/Graphics/Gfx.cpp
src/OpenLoco/src/Graphics/Gfx.h
src/OpenLoco/src/Graphics/SoftwareDrawingEngine.cpp
src/OpenLoco/src/Graphics/SoftwareDrawingEngine.h
src/OpenLoco/src/Ui/WindowManager.cpp

This makes a bit more sense if we ever want a different rendering engine to handle those things.

Move copyRect implementation to SoftwareDrawingEngine, use better names

---

CHANGELOG.md
src/OpenLoco/src/Paint/Paint.cpp

```
// assert(childPs->attachedPS == nullptr); Children can have attachments but we are skipping them to be investigated!
```
so can confirm now that this was needed after all!

Fix station glass drawing issues

---

src/OpenLoco/src/Graphics/FPSCounter.cpp

Now with pretty big numbers I noticed its wrong.
The provided point is at the start of the string not the center also use the string width which is already obtained rather than hardcoded numbers.

Fix FPS counter not being properly invalidated

---

.github/workflows/clang-tidy.yml

This step is no longer required.

Remove install clang tidy (part of dockerimage now)

---

src/OpenLoco/src/Input/MouseInput.cpp

Discovered this while messing around with my debug window making it resizable, if the resize isn't handled correctly this would trigger this path and crash and also cause invalidation issues.

Use correct type for widget index, prevent potential out of bounds read

---

src/OpenLoco/src/Graphics/TextRenderer.cpp
src/OpenLoco/src/Graphics/TextRenderer.h

It currently defaults to medium_normal but majority of the UI uses the bold font so lets make that the default instead. Also added getters necessary to compute the layout later, we might have variable fonts at some point so can't have that static in all widgets.

Default the font to medium bold, small regression

---

src/OpenLoco/src/Input/MouseInput.cpp
src/OpenLoco/src/Ui/WindowManager.cpp
src/OpenLoco/src/Ui/WindowManager.h

Those should be safe to do, I haven't touched the others as they still share the address in other files. Most of things in MouseInput really belong in WindowManager and we should simply signal the WindowManager about input and let that deal with state.

Remove some interop variables 

---

CHANGELOG.md
src/OpenLoco/src/Environment.cpp
src/OpenLoco/src/S5/S5.cpp

Could do with a few people checking this works. I was surprised that I didn't need to adjust the progress bar in `ObjectManager::loadIndex();`. It does fix the issue though on my system.

Fix #2613. Crash when unpacking objects

---

src/OpenLoco/src/World/CompanyAi.cpp

This can happen when the ai finds a tile that isn't appropriate (wrong water height) but does have some water.
Vanilla doesn't suffer from this as it uses a global variable that is never reset to an invalid direction. That causes its own issues...

Fix crash when ai attempts dock placement

---

src/OpenLoco/src/Ui/Windows/StationWindow.cpp

Fix station window scrollview width off-by-one

---

CHANGELOG.md
src/OpenLoco/src/Graphics/TextRenderer.cpp
src/OpenLoco/src/Ui/Windows/News/News.cpp

This fixes the issue, its a bit of a work-around but we can clean up that code afterwards.

Fix #2864: News messages are drawn incorrectly

---

src/OpenLoco/src/GameCommands/Vehicles/CreateVehicle.cpp
src/OpenLoco/src/Objects/SteamObject.h
src/OpenLoco/src/Objects/VehicleObject.h
src/OpenLoco/src/Vehicles/Vehicle.h
src/OpenLoco/src/Vehicles/VehicleBody.cpp

I uncovered the meaning of some flags and some unnamed variables.
I moved the return in `steamPuffsAnimationUpdate` since both paths had the same condition and did no work.

rename some steam effect variables

---

src/OpenLoco/src/Ui/Windows/ObjectSelectionWindow.cpp

This replaces the faux-tab area in the object selection window with real tab widgets, removing the need to emulate tab behaviour. This has been feasible for a while, since we split the tab strip in a primary and secondary area in #2629.

Use real tab widgets in object selection window

---

src/OpenLoco/src/Ui/Windows/MessageWindow.cpp

Addresses a recent regression while also improving the code slightly.
Before:
After:

Use label widgets for message/news settings

---

CHANGELOG.md
src/OpenLoco/src/Input.h
src/OpenLoco/src/Input/MouseInput.cpp
src/OpenLoco/src/OpenLoco.cpp

This should make more sense now, also fixed a bug that each mouse event would overwrite the delta rather than accumulate it until its processed, multiple mouse events can occur between ticks and now it will actually go as fast as the user moves the mouse.
Close #2931

Refactor how it handles mouse movement

---

src/OpenLoco/src/Ui/Widgets/PanelWidget.cpp

The resize handle was not being drawn for windows that are only resizeable on one axis.
Fixes #2927.

Fix resize handle not being shown for some windows

---

CHANGELOG.md
src/OpenLoco/src/Graphics/SoftwareDrawingEngine.cpp

Apparently SDL doesn't like mixing the two so we have to stick to the old way.
Close #2876

Fix #2876: Screen freezes when lowering scale back to 1.0

---

CHANGELOG.md
src/OpenLoco/src/Ui/Windows/Error.cpp

Fix incorrect error window frame size when competitor image is shown

---

src/OpenLoco/src/Graphics/TextRenderer.cpp
src/OpenLoco/src/Ui/Windows/MapToolTip.cpp

Use correct position for competitor image in map tooltip

---

CHANGELOG.md
src/OpenLoco/src/World/TownManager.cpp

Not convinced this will fix #2701, but it's all I can think of.

Town names: fix valid index 0 not being considered

---

CHANGELOG.md
src/OpenLoco/src/Input/MouseInput.cpp

Fix #2764
The widget pointer will be stale after performing a bring to front which will cause unexpected behaviour. In this case it caused the scroll index to be miscalculated which then caused unitialised memory to be copied into the y coordinate of the scroll click position which then caused a miscalculation of the message that was being pressed.

Fix #2764: Don't pass around a stale widget pointer

---

CMakeLists.txt

For some saves I tested I got additional extra 30 FPS so that is pretty good, the downside is that Release builds will take a bit longer now. I think it might be an idea to consider building RelWithDebInfo rather than Release for PRs and only do Release on master/releases. But for now I suggest we just see how it goes.

Enable LTO/IPO for Release configuration

---

src/OpenLoco/src/Date.cpp
src/OpenLoco/src/Date.h
src/OpenLoco/src/OpenLoco.cpp
src/OpenLoco/src/Scenario.cpp

Old name was incorrect, as by following the logic of the code that sets its value, and by using a tracepoint, the value of dayOfOlympiad clearly only ranges from 0 to 365. It is also clearly not intended to actually store the day of the current Olympiad (4 year period), as that would in theory cause a bug where each Winter (or Summer in Australia) would last for an additional 3 years.

Rename dayOfOlympiad to dayOfYear

---

src/OpenLoco/src/Date.cpp

Remove loco_global 0x0112C810 _currentDayInYear (previously _currentDayInOlympiad (I don't know why I bothered renaming it yesterday)) as it doesn't appear to be needed for anything.

Remove loco_global _currentDayInYear

---

thirdparty/CMakeLists.txt

Just removing GIT_SHALLOW does the trick, at first I thought commits were force pushed but I was wrong.

Fix sfl not being downloaded

---

src/OpenLoco/src/Ui/Windows/LandscapeGeneration.cpp

This is mostly done, but I've noticed LandscapeGeneration::Options::draw can be simplified further. I'd like to tackle that in this PR, still.
Part of #2951

LandscapeGeneration: turn text labels into widgets

---

.github/workflows/ci.yml
CHANGELOG.md
src/OpenLoco/src/GameCommands/Vehicles/CreateVehicle.cpp

Fixes #1689. The reliability penalty on newly designed vehicles will now be removed after two years, matching vanilla behaviour.

Fix reliability penalty not being removed for newly designed vehicles

---

CMakePresets.json

This seems to cause more problems than it solves. Vcpkg will cache the files in appdata anyway so its better to just stick to the version specified by the project.

Always install vcpkg with the specified commit

---

thirdparty/CMakeLists.txt

This is the commit immediately after 0.8.0 which fixes the cmake to actually build. Unfortunately yaml-cpp doesn't appear to do releases very often at all. We should probably look at moving to something else.

Update yaml-cpp to build on cmake v4

---

CHANGELOG.md
src/OpenLoco/src/Ui/Windows/Construction/ConstructionTab.cpp

Fix missing outline for construction button

---

src/OpenLoco/src/GameCommands/Docks/RemovePort.cpp

I was very confused as to why an ai function was removing ports instead of road stations and found it was because this comment offset was wrong.

Fix comment offset on removePort

---

.github/workflows/ci.yml
CMakeLists.txt
vcpkg.json

Following up on #3048, with OpenAL having released v1.24.3.

Bump vcpkg to April 2025; remove openal-soft version override

---

src/OpenLoco/src/Input/MouseInput.cpp
src/OpenLoco/src/Ui/Window.cpp
src/OpenLoco/src/Ui/Window.h
src/OpenLoco/src/Ui/Windows/TerraForm.cpp

This PR renames the `ToolDragContinue` event to `ToolDrag`, and more importantly the `ToolDragEnd` event to `ToolUp`. Unlike what the previous name suggests, dragging is not necessary for the up event to fire. This will allow some more creative tool (map selection) usage that I hadn't thought possible yet.
For reference, the events were originally named in #635.

Rename tool drag events

---

src/OpenLoco/src/Vehicles/Vehicle.cpp
src/OpenLoco/src/Vehicles/Vehicle.h
src/OpenLoco/src/Vehicles/VehicleBody.cpp
src/OpenLoco/src/Vehicles/VehicleBogie.cpp
src/OpenLoco/src/Vehicles/VehicleHead.cpp

- VehicleHead::sub_4AA625() is implemented
- Renamed to VehicleHead::landCrashedUpdate()
- Several other subroutines used by sub_4AA625 are also implemented
- sub_4AA64B as VehicleHead::updateSegmentCrashed
- sub_4AA904 as VehicleBody::updateSegmentCrashed
- sub_4AA68E as VehicleBogie::updateSegmentCrashed
- explodeComponent() is refactored as a member function of VehicleBase

Implement sub_4AA625 as VehicleHead::landCrashedUpdate()

---

CHANGELOG.md
src/OpenLoco/src/Map/MapSelection.cpp
src/OpenLoco/src/Map/MapSelection.h
src/OpenLoco/src/Ui/Windows/Construction/Construction.h
src/OpenLoco/src/Ui/Windows/Construction/ConstructionTab.cpp
src/OpenLoco/src/Ui/Windows/Construction/OverheadTab.cpp
src/OpenLoco/src/Ui/Windows/Construction/SignalTab.cpp
src/OpenLoco/src/Ui/Windows/Construction/StationTab.cpp
src/OpenLoco/src/Ui/Windows/TerraForm.cpp

This PR introduces an alternate mode for the construction tool, allowing players to build a grid of track/road pieces at once by dragging the selection tool over the map. This is done in a way that is not intrusive to (and indeed fully compatible with) the vanilla method.
To achieve this, the selection tool is now activated using the ToolUp event instead of the ToolDown event. When ToolDown is activated, the initial tile position is stored. On ToolDrag, the current tile position is stored. If the two positions are identical, then the game takes the vanilla code path: you'll see a ghost track piece, and clicking (ToolUp) will build that piece, and activate interactive mode.
Conversely, if the two positions aren't identical, the new 'dragging' mode is activated. Instead of a ghost piece, …

Allow dragging the construction tool to build

---

src/OpenLoco/src/Ui/Windows/Construction/ConstructionTab.cpp
src/OpenLoco/src/Ui/Windows/Construction/StationTab.cpp

This PR improve invalidation for station drag selection, particularly when part of the selection fails to build.
This was not an issue for the construction tab, as the map selection flags were reset elsewhere down the code path. I've still applied the same patch to keep things consistent, though.

Improve invalidation for station drag selection

---

src/OpenLoco/src/Ui/Windows/Construction/Common.cpp

Looks like a minor copy/paste mistake. Don't think this will actually affect anything.

Check the correct tab for overhead animation

---

src/OpenLoco/src/GameCommands/Vehicles/CloneVehicle.cpp
src/OpenLoco/src/Vehicles/Vehicle.cpp
src/OpenLoco/src/Vehicles/Vehicle.h

Prerequisite of https://github.com/OpenLoco/OpenLoco/pull/2897
I still don't understand how trains are assembled. This was the easiest way I thought of to iterate over every component regardless of type.
Tested with vehicles with bogies and bodies painted different colors. Works great.

copy vehicle colours when cloning vehicle

---

CHANGELOG.md
src/OpenLoco/src/GameCommands/Road/CreateRoadStation.cpp
src/OpenLoco/src/GameCommands/Track/CreateTrainStation.cpp
src/OpenLoco/src/Ui/Windows/Construction/StationTab.cpp

This PR changes the station placement tool such that existing station elements may be replaced. Fortunately, the game commands appear to have supported this already, but errored out instead of actually replacing the element! Replacement cost is even calculated.
These changes apply to the new drag tool as well as the original single station tile placement.
https://github.com/user-attachments/assets/87b0b192-2183-428b-a883-8403cc52d20a

Allow replacing existing station elements directly

---

CHANGELOG.md
src/OpenLoco/src/Environment.cpp

I am confident that this is the most typical installation path of Chris Sawyer's Locomotion when installed with Steam on Windows.
I tested this by deleting my openloco.yml file: OpenLoco now automatically detects a Steam installation of Locomotion when run for the first time.

Automatically search for Steam installation of Locomotion

---

src/OpenLoco/src/GameCommands/Track/CreateTrainStation.h
src/OpenLoco/src/World/CompanyAi/CompanyAi.cpp
src/OpenLoco/src/World/CompanyAi/CompanyAiPathfinding.cpp

Found these whilst investigating @LeftofZen's saves. The most important one is the trackId being corrupted which causes the ai to never remove tracked hills.

Fix minor divergence issues

---

src/OpenLoco/src/Ui/Widget.cpp
src/OpenLoco/src/Ui/Widgets/ButtonWidget.cpp
src/OpenLoco/src/Ui/Widgets/CaptionWidget.cpp
src/OpenLoco/src/Ui/Widgets/CheckboxWidget.cpp
src/OpenLoco/src/Ui/Widgets/ColourButtonWidget.cpp
src/OpenLoco/src/Ui/Widgets/DropdownWidget.cpp
src/OpenLoco/src/Ui/Widgets/FrameWidget.cpp
src/OpenLoco/src/Ui/Widgets/GroupBoxWidget.cpp
src/OpenLoco/src/Ui/Widgets/ImageButtonWidget.cpp
src/OpenLoco/src/Ui/Widgets/LabelWidget.cpp
src/OpenLoco/src/Ui/Widgets/NewsPanelWidget.cpp
src/OpenLoco/src/Ui/Widgets/PanelWidget.cpp
src/OpenLoco/src/Ui/Widgets/ScrollViewWidget.cpp
src/OpenLoco/src/Ui/Widgets/TabWidget.cpp
src/OpenLoco/src/Ui/Widgets/TextBoxWidget.cpp
src/OpenLoco/src/Ui/Widgets/ViewportWidget.cpp
src/OpenLoco/src/Ui/Widgets/Wt3Widget.cpp

Now windows and widgets will always use the local coordinate space for drawing.

Clip render target for widgets, do not draw them with window relatives

---

src/OpenLoco/src/Vehicles/Vehicle.cpp
src/OpenLoco/src/Vehicles/Vehicle.h
src/OpenLoco/src/Vehicles/Vehicle2.cpp
src/OpenLoco/src/Vehicles/VehicleBogie.cpp
src/OpenLoco/src/Vehicles/VehicleHead.cpp
src/OpenLoco/src/Vehicles/VehicleTail.cpp

This function displays the "vehicle has crashed" message (if the train belongs to the player company), marks the head as "crashed", sets the refund value of the train and each vehicle to zero, and does something with var_5A that I don't fully understand the purpose of.

Implement VehicleBase::sub_4AA464, rename to destroyTrain

---

src/OpenLoco/src/Vehicles/Vehicle.cpp
src/OpenLoco/src/Vehicles/Vehicle.h
src/OpenLoco/src/Vehicles/Vehicle1.cpp
src/OpenLoco/src/Vehicles/Vehicle2.cpp
src/OpenLoco/src/Vehicles/VehicleBogie.cpp
src/OpenLoco/src/Vehicles/VehicleTail.cpp

I gave the unknown ones an m prefix to prevent name collisions, which slow down visual studios when renaming elements.
I named the ones I thought I knew the purpose of. In my opinion, better to name them on your hunch to get that self-documentation machine working.

Create flags enum for _vehicleUpdate_var_1136114

---

src/Interop/include/OpenLoco/Interop/Interop.hpp
src/Interop/src/Interop.cpp

This will be helpful to look for overlaps and deduplicate the global instances which we will need to do when we become standalone. Its disabled by default. Enable with `_LOG_GLOBAL_STORE_`.

Add logger to track globals

---

CHANGELOG.md
src/OpenLoco/src/Input/MouseInput.cpp

Mainly to change stateScrollRight() to use getNextDragOffset() (like stateViewportRight() already does) instead of the x, y from handleMouse().
- Fixes #3019
Also a couple new unrelated code comments and a minor code style change in the same file.

Fix mouse getting stuck on edges of monitor when right mouse dragging scrollviews

---

CHANGELOG.md
src/OpenLoco/src/Ui/WindowManager.cpp
src/OpenLoco/src/Viewport.hpp
src/OpenLoco/src/ViewportManager.cpp

My refactoring caused this, the issue is that viewports store their positions now relative to the parent (window) and it used that to shift the pixels which requires the absolute screen position. Viewports now store the owner so we can compute the correct position when the absolute one is needed, there was also an issue that invalidation didn't correctly work but on busy maps its hard to notice that.
Closes #3116

Fix #3116: Visual artifacts with additional viewports

---

CHANGELOG.md
src/OpenLoco/src/Ui/Windows/MapWindow.cpp

This PR is an alternative to #3191.
As mentioned in the code comments, the constraints I chose to determine the new minimum window size was to make the map be square when at minimum size, and to not allow the map to be thinner than the part of the window with the key. This means the user can now make the map window somewhat thinner, but not as short. (The initial window size when the player opens the window for the first time remains unchanged.)
**Before:** (Minimum window size in original Locomotion)
**After:**
(Dotted black square on map in both screenshots above are indicative of 1280x720 game resolution and fully zoomed in).
**Additional screenshot:** hovering over an item on the industries tab (the key having more items forces the window to be a little taller) (1080p game resolution)

Change minimum map window size to make the map square at its minimum size

---

CHANGELOG.md
src/OpenLoco/src/Ui/Windows/LandscapeGeneration.cpp

I don't know how this call got in there but it's not needed.
Closes #3195

Fix #3195: Ui state is reset each frame preventing scrolling

---

src/OpenLoco/src/Vehicles/VehicleHead.cpp

I'm not 100% sure why this is used in some places but I think its so that there is a deterministic pathing function. Its definitly used when placing road vehicles but its also used when they turn around and a few other places (look for head->var_52 = 1 which triggers this code). Needs to have the same signature as roadPathing (thats why it has the empty vars)
~~Note: Replays don't pass just yet.~~
Replays pass

Implement Road Longest Pathing

---

CHANGELOG.md
src/OpenLoco/src/Ui/ViewportInteraction.cpp
src/OpenLoco/src/Ui/Window.cpp

This is not the prettiest solution, ideally it transforms the position underneath but there is a bit of cleaning up to do, for now this will fix the issue without having major refactoring going on.
Closes #3137

Fix #3137: Viewport interaction is offset by window position

---

CHANGELOG.md
src/OpenLoco/src/Input/Keyboard.cpp
src/OpenLoco/src/Localisation/Conversion.cpp
src/OpenLoco/src/Localisation/LanguageFiles.cpp
src/OpenLoco/src/Localisation/Unicode.cpp
src/OpenLoco/src/Localisation/Unicode.h

Fixes #3198
It feels kind of stupid, both to be using a module named localization here, ~~as well as the crazy cast,~~ but it works.
Previously the behaviour was bugged such that `ä` would become `{keyCode=228 charCode=4294967235}` instead of `{keyCode=228 charCode=228}`.

Fix non-ASCII keyboard input

---

CHANGELOG.md
src/OpenLoco/src/Ui/ScrollFlags.hpp
src/OpenLoco/src/Ui/ScrollView.cpp
src/OpenLoco/src/Ui/Widgets/ScrollViewWidget.cpp
src/OpenLoco/src/Ui/Window.cpp
src/OpenLoco/src/Ui/Window.h
src/OpenLoco/src/Ui/Windows/AboutMusic.cpp
src/OpenLoco/src/Ui/Windows/BuildVehicle.cpp
src/OpenLoco/src/Ui/Windows/CompanyFaceSelection.cpp
src/OpenLoco/src/Ui/Windows/CompanyList.cpp
src/OpenLoco/src/Ui/Windows/CompanyWindow.cpp
src/OpenLoco/src/Ui/Windows/IndustryList.cpp
src/OpenLoco/src/Ui/Windows/KeyboardShortcuts.cpp
src/OpenLoco/src/Ui/Windows/LandscapeGeneration.cpp
src/OpenLoco/src/Ui/Windows/MapWindow.cpp
src/OpenLoco/src/Ui/Windows/MessageWindow.cpp
src/OpenLoco/src/Ui/Windows/MusicSelection.cpp
src/OpenLoco/src/Ui/Windows/ObjectLoadError.cpp
src/OpenLoco/src/Ui/Windows/ObjectSelectionWindow.cpp
src/OpenLoco/src/Ui/Windows/PromptBrowseWindow.cpp
src/OpenLoco/src/Ui/Windows/ScenarioSelect.cpp
src/OpenLoco/src/Ui/Windows/StationList.cpp
src/OpenLoco/src/Ui/Windows/StationWindow.cpp
src/OpenLoco/src/Ui/Windows/TerraForm.cpp
src/OpenLoco/src/Ui/Windows/TileInspector.cpp
src/OpenLoco/src/Ui/Windows/TownList.cpp
src/OpenLoco/src/Ui/Windows/Vehicle.cpp
src/OpenLoco/src/Ui/Windows/VehicleList.cpp

Changes scrollbar types to 32 bits to account for very large scroll content sizes. Changing the height is necessary, but changing the width isn't that necessary since there are no large-horizontally-scrolling windows in the game currently

Changes scrollbar types to 32 bits to account for very large scroll content sizes

---

src/OpenLoco/CMakeLists.txt
thirdparty/CMakeLists.txt
vcpkg.json

With this PR it fetches yaml-cpp and fmt over vcpkg, it's kinda annoying that yaml-cpp is always rebuilt and now its out of the VS project as well.

Vcpkg changes

---

src/OpenLoco/src/Environment.cpp
src/OpenLoco/src/Game.cpp
src/OpenLoco/src/Map/MapSelection.cpp
src/OpenLoco/src/Map/MapSelection.h
src/OpenLoco/src/Paint/PaintSurface.cpp
src/OpenLoco/src/Ui/ToolManager.cpp
src/OpenLoco/src/Ui/Windows/Construction/Common.cpp
src/OpenLoco/src/Ui/Windows/Construction/Construction.h
src/OpenLoco/src/Ui/Windows/Construction/ConstructionTab.cpp
src/OpenLoco/src/Ui/Windows/Construction/StationTab.cpp
src/OpenLoco/src/ViewportManager.cpp

The main changes are around configurable paths. These are paths that record where you last used them (such as save location) to the config file but also have a default location. We had a bunch of code for handling two player and single player save locations but both locations were always the same so I've removed that. Also we had a bunch of copy into a global only to copy out of the global so that is also removed.
Also reworked the freeform map selection tiles which was using duplicated loco globals to pass state and was a bit of a mess. Its still a mess but its a bit less now. (yeah i should have probably done these as two PRs...)

Remove and rework some loco_globals

---

src/OpenLoco/src/Scenario.cpp
src/OpenLoco/src/ScenarioConstruction.cpp
src/OpenLoco/src/ScenarioConstruction.h

Nothing too exciting it sets the default track mods for a track in the construction window. For example it makes sure that trams track by default has its catenary wire road mod.

Initialise default track road mods

---

src/OpenLoco/CMakeLists.txt
src/OpenLoco/src/GameCommands/GameCommands.cpp
src/OpenLoco/src/GameCommands/Road/CreateRoadMod.cpp
src/OpenLoco/src/GameCommands/Road/CreateRoadMod.h
src/OpenLoco/src/GameCommands/Road/RemoveRoadMod.cpp
src/OpenLoco/src/GameCommands/Road/RemoveRoadMod.h
src/OpenLoco/src/Map/Track/Track.h
src/OpenLoco/src/Vehicles/Routing.cpp
src/OpenLoco/src/Vehicles/Vehicle.h

I've hijacked this PR ~@duncanspumpkin
Implements both createRoadMod and removeRoadMod a mostly useless game command that can only be accessed from the tram building window and only after you disable road mods for the tram. I'm not sure why you would want to remove road mods for trams but it is doable.

Implement createRoadMod command

---

CHANGELOG.md
src/OpenLoco/src/Input/MouseInput.cpp
src/OpenLoco/src/Ui/Window.cpp
src/OpenLoco/src/Ui/Window.h
src/OpenLoco/src/Ui/WindowManager.h
src/OpenLoco/src/Ui/Windows/Main.cpp
src/OpenLoco/src/Ui/Windows/Vehicle.cpp
src/OpenLoco/src/Vehicles/VehicleManager.cpp

~~Removes `savedView.isEmpty()` checks from Window methods related to focusing viewports on entities, as they served no clear purpose (correct me if I'm wrong!)~~ and caused following (and unfollowing) vehicles on the main view to not work.
Fixes #3135

Fix focusing on entities on the main viewport
